### ISSUE TITLE
Audio drifting out of sync after 2-5 minutes.

### ISSUE THREAD

**Issue by dtiesling** [videojs/videojs-contrib-hls#1007]
## Description
After a video plays for 2-5 minutes the audio has drifted out of sync considerably.

## Sources
All videos on our platform. We are generating encrypted HLS using bento4.

## Steps to reproduce
Play a video for 2-5 minutes.

### Expected
Audio and video are aligned.

### Error output
No errors.

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 5.2.1

### videojs version
what version of videojs does this occur with?
video.js 5.16.0

### Browsers
* Safari
* Chrome

### Platforms
* Windows 7
* macOS 10.12

### Other Plugins
None

### Other JavaScript
* Webix

**Comment by gesinger** [comment]
Hey @dtiesling , thanks for reporting. Do you have a sample video you can drop into our [starter template](http://jsbin.com/vokipos/8/edit?html,output) to demonstrate the issue?

And when you noticed it on Safari, were you overriding native playback?

**Comment by dtiesling** [comment]
I am not setting the override option so whatever the default is. All of content is password protected so I'm working getting something hosted publicly to try in the template. 

Are there settings anywhere for the playback speed of the audio that I'm missing? It seems to get ahead of the video at a fairly constant rate.

**Comment by dtiesling** [comment]
Here's a new piece of information. When I switched to unencrypted files the audio maintains sync. Has it been confirmed that the plugin works with encrypted videos longer than a couple of minutes?

**Comment by gesinger** [comment]
Thanks for trying to make something publicly available.

As for Safari, the reason I ask is that by default on Safari videojs-contrib-hls will use Safari's native HLS player. If you're hearing the audio desyncing with both the videojs-contrib-hls player on Chrome and on Safari's player, it potentially points to a content issue.

We have tested the plugin on long encrypted videos (both VOD and LIVE), and they seem to work well, although it's always possible a bug may have appeared or the content is encoded in such a way that it leads to a new issue.

**Comment by dtiesling** [comment]
Issue has been replicated here - http://output.jsbin.com/fagituguba

I've also tested the encrypted videos using the built-in ios player and the audio stays synced.

**Comment by dtiesling** [comment]
@gesinger Were you able to view the example? Do you know yet if this is a bug in the plugin or an issue with the stream?

**Comment by gesinger** [comment]
Hey @dtiesling , it looks like it's most likely coming from the stream. When playing, I get logs in chrome://media-internals where it is dropping audio frames, e.g., `Dropping audio frame which failed decode with timestamp: 10432000 us, duration: 21333 us, packet size: 359 bytes`, and `Large timestamp gap detected; may cause AV sync to drift. time:33472000us expected:33407999us delta:64001us`. Hope this helps.

**Comment by dtiesling** [comment]
Thanks for the prompt responses @gesinger and all the help. Just a couple more questions.

Since the stream is handled without issue by the iOS player it looks like it could be played. Are you guys going to look into this further or is this going to be a "won't fix"?

If it is a "won't fix" do you have a list of specs for encrypted videos that work best with the plugin (i.e. aes-128, AAC audio, mpeg 2 chunks, etc.)?

**Comment by dtiesling** [comment]
I'm using a single .ts file for the .m3u8 playlist instead of creating a separate file for every chunk. Could that be related?

**Comment by dtiesling** [comment]
It looks like the issue is that the chunk sizes are not divisible by 16 so the decryption bombs out. @gesinger  does having the player add padding to any chunks that are not divisible by 16 seem like a viable option?

**Comment by dtiesling** [comment]
The bento4 packager has been updated to create valid streams. The new streams with valid sized chunks play flawlessly. Thanks again for the help debugging.
