### ISSUE TITLE
How support multiple *.flv?

### ISSUE THREAD

**Issue by caobug** [videojs/videojs-contrib-hls#1009]
My video files consist of many flv(name-01.flv, name-02.flv) files, how to play like m3u8 continuous?

**Comment by gesinger** [comment]
Hey @caobug , the HLS spec only allows certain formats (e.g., MPEG-2 Transport Streams and Fragmented MPEG-4). Behavior is not defined for other formats (including flv). However, a videojs playlist plugin might work in this case. Would that help your use case?

**Comment by caobug** [comment]
@gesinger Thank you. I have a full video be split to many flv files, I hope it can play like m3u8. 

A plugin ckplayer can load an XML file, It contains video clip information, I hope videojs can support:

`<?xml version="1.0" encoding="utf-8"?>
<ckplayer> 
  <video>
    <file><![CDATA[a.flv]]></file>
    <size>32594386</size>
    <seconds>204</seconds>
  </video>
  <video>
    <file><![CDATA[b.flv]]></file>
    <size>31835748</size>
    <seconds>189</seconds>
  </video>
  <video>
    <file><![CDATA[c.flv]]></file>
    <size>48219871</size>
    <seconds>189</seconds>
  </video>
  <video>
    <file><![CDATA[d.flv]]></file>
    <size>49745973</size>
    <seconds>206</seconds>
  </video>
</ckplayer>
`

**Comment by gesinger** [comment]
Hey @caobug , for that XML file to be playable, you can create a Video.js plugin (see https://github.com/videojs/video.js/wiki/Plugins for details) to parse and play that content . But since that is a different file type and spec from HLS, it'll have to be outside of the videojs-contrib-hls plugin.

**Comment by caobug** [comment]
@gesinger Can you help me?

**Comment by gesinger** [comment]
Hey @caobug , if you go to https://github.com/videojs/video.js/wiki/Plugins , you can see some documentation about how to create Video.js plugins and some example plugins on the page. If you follow those instructions and examples, you should be able to create your own plugin that can parse the example XML file you posted, then append the flv data to https://github.com/videojs/video-js-swf similar to how it is done in https://github.com/videojs/videojs-contrib-media-sources .

**Comment by caobug** [comment]
gesinger Thank your answer. I can't make the clip look like a full video, I spent a lot of time but no progress. my html:

```
<head>
  <link href="https://movie.caobug.com/assets/plugins/player/video-js.css" rel="stylesheet">
  <style type="text/css">.video-js{ display: none; }</style>
</head>
<body>
  <div id="player-container"></div>
  <script src="https://movie.caobug.com/assets/plugins/player/video.js"></script>
  <script src="https://movie.caobug.com/assets/plugins/jquery/jquery-1.12.4.min.js"></script>
  <script type="text/javascript">
      function createPlayer (resources) {
        var options = {controls: true, preload: "metadata", autoplay: false};
        var allPlayers = [];
        for (var i = 0; i < resources.length; i++) {
          $("#player-container").append('<video id="player-' + i + '" class="video-js vjs-default-skin"></video>');
          allPlayers[i] = videojs("#player-" + i, options, function onPlayerReady() {
            this.on('ended', function() {
              var order = parseInt(this.id().substring(7)) + 1;
              var nextPlayer = allPlayers[order];
              nextPlayer.play();
              $(".video-js").hide();
              $("#player-" + order).show();
            });
          });
          allPlayers[i].src(resources[i]);
          allPlayers[i].duration = function() {
            return 699;
          }
        }
      }

      var assetsPrefix = "https://movie.caobug.com/assets/plugins/player";

      $(function(){
          createPlayer(new Array(assetsPrefix + '/a.mp4', assetsPrefix + '/b.mp4'));
          $("#player-0").show();
      });
  </script>
</body>
```
