### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by FDiskas** [videojs/videojs-contrib-hls#1010]
version 4.0.3
Installed via npm - included minimized file from dist and got error
http://i.imgur.com/iGp67FR.png

**Comment by gkatsev** [comment]
Please fill out the [issue template](https://github.com/videojs/videojs-contrib-hls/blob/master/.github/ISSUE_TEMPLATE.md), without answering those questions, there is not enough information to answer your question. Some important stuff to answer is browser and OS versions as well as version of videojs. It will be best if a reduced test case can be provided as well.
