### ISSUE TITLE
the flash player can play the video ,but h5 player not play,how can i ?

### ISSUE THREAD

**Issue by y284663247** [videojs/videojs-contrib-hls#1012]
## Description
the flash player can play the video ,but h5 player not play,how can i ?

## Sources
http://hljvodqn.soocedu.com/20170206_5897e2c8ca290370654862_0.m3u8

### Error output
The media could not be loaded, either because the server or network failed or because the format is not supported.

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 1.3.7

### videojs version
what version of videojs does this occur with?
video.js 5.8.8

### Browsers
chrome
*

### Platforms
all platforms
*

### Other Plugins
videojs-resolution-switcher.js
/*! videojs-resolution-switcher - 2015-7-26
 * Copyright (c) 2016 Kasper Moskwiak
 * Modified by Pierre Kraft and Derk-Jan Hartman
 * Licensed under the Apache-2.0 license. */
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* jquery

**Comment by forbesjo** [comment]
It looks like you're using pretty old versions of contrib-hls and video.js. I can see that this source works with the latest versions when loaded into http://videojs.github.io/videojs-contrib-hls/

![feb-15-2017 09-41-27](https://cloud.githubusercontent.com/assets/7529098/22979052/0ab4309a-f363-11e6-829a-28ca2abd8e6c.gif)

**Comment by dmlap** [comment]
Closing based on @forbesjo's testing. Please reopen it if you're still having problems after updating.
