### ISSUE TITLE
Problem/Bug with m3u8 url

### ISSUE THREAD

**Issue by mikhoul** [videojs/videojs-contrib-hls#1013]
Hi'

First I'm new to "Video.js",

I've  read a lot the documentation and so far I've no problem playing MP4 movie but when I try to play m3u8 stream it did not work, it behave like if the player was "buggy" of have hard time trying to decode m3u8 stream.  :disappointed: 

I've setup a JsBin to test here: http://jsbin.com/hicijo/edit?html,output
Here's the URL of the Stream: http://www.streambox.fr/playlists/test_001/stream.m3u8

And here's a scrennshot where the player is frozen and the .TS file are "loaded" in the console.

From the console I the player "freeze"for ~15-30 seconds when loading HLS plugin, but the plug-in itself is loaded and after I can see the .ts files loading but nothing on the screen.

The player behaving is erratic... :bug: 

When I try the same stream in other players like "mediaelement" or even VLC I have no problem at all, so I know that the stream itself is not the problem.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Try to play the stream few times.
2.
3.

### Expected
Just play the stream fine at the best quality it can.

### Actual
 Erratic behavior of the player ending most of the time not playing the stream.

**N.B.:** Tried on Firefox and Chrome under Win7/64.

Let me know if you need more information.

Best Regards :octocat:

**Comment by gesinger** [comment]
Hey @mikhoul , thanks for the reporting the issue. I definitely see that the stream makes a lot of segment requests before it begins to play, and then plays without audio, whereas it's able to play with audio in Safari. We'll take a closer look to try to figure out what's going on.

**Comment by gesinger** [comment]
It seems to download the whole playlist before playing the video with no audio when using HTML. However, when using flash, it plays the audio with no video (and starts immediately).

**Comment by campones** [comment]
yea, i m testing last videojs contrib hls (5.4.0) along with videojs (v5.19.1) and it behave really badly, especially and start a long pause..  first I don't see why it needs to download all segments of the playlist to start streaming, that makes the thing very slow for people with bad internet connection.  Plus, it download segments in wrong order, or sometimes even twice.. if you check the console you know the stream is coming, but for regular users, they just think it isn't working..

https://i.gyazo.com/475828eab1aca09a00ac206b7a29c754.png

**Comment by campones** [comment]
"However, when using flash, it plays the audio with no video (and starts immediately)."

this is normal, there are parameters if you want to change that behavior in the rtmp streamer. either it plays audio immediately or you set it up in a way it sync with the video, which takes more time to play. usually the default is the best so your users know it's working
