### ISSUE TITLE
live m3u8 issue :  bufferizes, plays, stops, bufferizes....error

### ISSUE THREAD

**Issue by shaolintibo** [videojs/videojs-contrib-hls#1017]
## Description
I try to read one live hls, the manifest seems good and with all required tags

So after loading which takes time to load, but after the player plays, stops and bufferizes, plays... , even if I use a lowest quality, so it seems not linked to the chunk size.
and finally after a certain time, one error message 

## Sources
https://aefnefl-lh.akamaihd.net/i/aef_nefl3@16055/master.m3u8

## Steps to reproduce

1. load this page http://videojs.github.io/videojs-contrib-hls/#
2. enter this url https://aefnefl-lh.akamaihd.net/i/aef_nefl3@16055/master.m3u8 in video url field
3. click on load button
4. click on play video button

### Expected
the player reads video fluidely

### Error output
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. MediaErrorcode: 3message: "The media playback was aborted due to a corruption problem or because the media used features your browser did not support."__proto__: Object
logByType @ video.js:22933

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
videojs-contrib-hls 5.2.1

### videojs version
video.js 5.16.0

### Browsers
On Chrome 56
Windows 10

### Platforms
Mac/Win

**Comment by mjneil** [comment]
It looks like there is something wrong with the stream itself. Looking at things more closely, I see that the buffer is filled with 4 second gaps every 6 seconds. It appears that the last (or first) 4 seconds of every segment is not included in the ts file. You can see this if you try and play your stream in VLC or another video player. If you watch the timestamps on the bottom closely, you'll notice every 6 seconds, it freezes with potentially some visual artifacts, and then jumps ahead 4 seconds

**Comment by mikhoul** [comment]
Here's the result I have in VLC:

```
mpeg4audio info: AAC channels: 1 samplerate: 8000
direct3d9 error: SetThumbNailClip failed
adaptive info: Encountered discontinuity
core error: ES_OUT_SET_(GROUP_)PCR is called too late (pts_delay increased to 8000 ms)
mpeg4audio info: AAC channels: 1 samplerate: 8000
direct3d9 error: SetThumbNailClip failed
ts error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1) for PID 4095
ts error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1) for PID 4095
ts error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1) for PID 4095
ts error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1) for PID 4095
ts error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1) for PID 4095
ts error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1) for PID 4095
ts error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1) for PID 4095
ts error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1) for PID 4095
ts error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1) for PID 4095
direct3d9 error: SetThumbNailClip failed 


```

The stream cut lot of time... but it should at least play minus the cut but for me I'm not able to have it play with http://videojs.github.io/videojs-contrib-hls/# .

**Comment by mjneil** [comment]
I'm having no issue and seeing no errors playing the stream on http://videojs.github.io/videojs-contrib-hls/#

The repeated buffering spinner you are seeing is because of those 4 second gaps I mentioned. When a gap is detected, a timeout is set to seek over the gap after the duration of the gap has completed. So what I'm seeing is it playing those 6 seconds, watching the time on screen increase, then when it hits the gap, the spinner appears for 4 seconds, then it jumps forward and starts playing again, repeat.

**Comment by shaolintibo** [comment]
Thanks for your feedback, I'll search why the  buffer is filled with 4 second gaps every 6 seconds.

**Comment by gesinger** [comment]
Thanks @shaolintibo for reporting the issue and providing the sample (and @mikhoul and @mjneil for debugging the issue). Let us know if the player still has trouble after the gap resolution.
