### ISSUE TITLE
Some m3u8 do not work

### ISSUE THREAD

**Issue by onigetoc** [videojs/videojs-contrib-hls#1020]
Do this url do not work because it contain special characters?

It work on others players like the Hola player

http://stream-07.vty.dailymotion.com/46/dm/1/x3b68jn/live.isml/events(live-1487472885)/live-audio=128000-video=1200000.m3u8

`(live-1487472885)`

**Comment by mikhoul** [comment]
@onigetoc   It's look like you have almost the same issue I have here:  https://github.com/videojs/videojs-contrib-hls/issues/1021

I tried your URL and I can see the stream loading but nothing appear in the player sadly.


Regards. :octocat:

**Comment by onigetoc** [comment]
I found lot of list of m3u8 file that do not work with this videojs hls plugin.
I found a chrome extension to read m3u8 right in your browser to test m3u8 files. (i found dozen of m3u8 files who is working with this chrome extension who not work with videojs hls) 
https://chrome.google.com/webstore/detail/native-hls-playback/emnphkkblegpebimobpbekeedfgemhof
I think it based on hls.js (from dailymotion i think)

There's also a chrome plugin to download or view all Chrome extension files.
Chrome extension source viewer: 
https://chrome.google.com/webstore/detail/chrome-extension-source-v/jifpbeccnghkjeaalbbjmodiffmgedin

**Comment by mikhoul** [comment]
The best I found to test a stream is to use VLC **3.x beta** , this way you can see quickly if the stream is protected or not and you can see also what kind of stream it is via the Tools menu option.

I'm just beginning playing with the streams and players, I've see that some stream that DON'T work with "_**videojs-contrib-hls**_" will work with the "**_Flashls_**" plugin, to test the stream just go here:  http://www.flashls.org/videojs/flash_demo.html and copy paste the URL.

If you like it, it's not hard to install the plug-in but it is VERY hard to find clear information to do it... 
To install "Flashls" plugin: You **MUST** use this fork: https://github.com/tommyh/videojs-flashls anything else will NOT work.

Hopping it will help you to have most of your your streams to work.

You can also take a look at "_**Clappr**_" it is also a very good small video/audio player too: https://github.com/clappr/clappr


Regards ! :octocat:

**Comment by mjneil** [comment]
I think #1016 will address this issue

**Comment by onigetoc** [comment]
Do this is updated on the CDN?
some LIVE videos who work with the Chrome extension but not with videojs HLS
#EXTINF:-1,BBC Arabia **
http://bbcwshdlive01-lh.akamaihd.net/i/atv_1@61433/master.m3u8
#EXTINF:-1, MTV AM **
http://mtvam.ru/hlsam/playlist.m3u8
#EXTINF:-1, M6 Music **
http://sslhls.m6tv.cdn.sfr.net/hls-live/livepkgr/_definst_/m6_music_hits_hls_aes/m6_music_hits_hls_aes_856.m3u8
#EXTINF:-1,VOX Music TV **
http://stream.smcloud.net/live/vox2/stream1/VOX Music TV.m3u8
#EXTINF:-1,Radio Montecarlo TV **
http://fms.105.net:1935/live/rmc1/playlist.m3u8
#EXTINF:-1,Virgin Tv **
http://fms.105.net:1935/live/virgin1/playlist.m3u8
#EXTINF:-1,Radionorba Tv **
http://85.17.80.132:80/radionorbatv/norbatv_source.stream/playlist.m3u8

**Comment by onigetoc** [comment]
Ok, i did find out that most of the have this message in the inspector.
`XMLHttpRequest cannot load http://77.92.76.135:1935/tvce/livestream/playlist.m3u8. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.example.com' is therefore not allowed access.`

**Comment by onigetoc** [comment]
I did a test
this m3u8: http://live.lachainenormande.fr:80/live/lcn/livestream/playlist.m3u8
work here: https://www.hlsplayer.net/
but not with videojs HLS
http://www.scriptsmashup.com/scripts/videojs-contrib-hls-master/demo-live-tv.html

**Comment by gkatsev** [comment]
Seems like that stream doesn't have any CORS headers which are [required](https://github.com/videojs/videojs-contrib-hls#hosting-considerations). hlsplayer.net seems to be playing it back in flash, which has different different hosting considerations.

**Comment by gesinger** [comment]
Looks like the root of the problems for the available streams were lack of CORS headers. If you are encountering any other issues with the player, please let us know. Thank you.
