### ISSUE TITLE
Issue with M3U8 Url

### ISSUE THREAD

**Issue by mikhoul** [videojs/videojs-contrib-hls#1021]
I have problem with an **M3U8** url:  http://www.streambox.fr/playlists/test_001/stream.m3u8

When I try to play the stream on various browser (Firefox, Chrome, IE11 & Opera) the stream seem to load fine when I look at the browser console but the "**Video player Window**" keep showing the spinning wheel for over 1 minute before playing the stream and when the stream start there is no sound at all. :disappointed: 

I use the latest version of everything and since english is not my native language I made a short screencast to demonstrate the issue:  http://screencast-o-matic.com/watch/cbnYrO6oA0

I have also setted a JSBin to show the exact setup I use, so it should be more easy to replicate:  http://jsbin.com/suvebuk/edit?html,output

I'd really like to know what I do wrong since it play fine in other video players.

Regards !  :octocat:

**Comment by gesinger** [comment]
Hey @mikhoul , haven't gotten to look too closely at the stream yet, but I do see that it is not playing back. I think it's the same issue/stream as posted in https://github.com/videojs/videojs-contrib-hls/issues/1013 , so I'm going to close this one in favor of the other issue. If you believe they are separate issues, we can re-open this one or add a separate issue.
