### ISSUE TITLE
Can not play HLS when loading as a dependency via package.json

### ISSUE THREAD

**Issue by vpowers** [videojs/videojs-contrib-hls#1024]
The plugin does not seem to be fully registered and can not playback any HLS stream.  I don't have this issue when using the standalone script in a script tag (dist/videojs-contrib-hls.js). 

I am loading the master branch (5.3.0) as a dependency module in my project.  I have verified that v5.1.1 is the last version that will playback HLS when loaded as a dependency module.  I have compared v5.1.1 to the next version 5.2.0 and see this commit 925f14f6d8533a4ed0e434624969b00f59fe3b45 changed some dependencies.  I've narrowed it down to the change from `video.js ^5.15.1` to `^5.17.0` as the problem.  When building with `video.js ^5.17.0`, the `HlsSourceHandler.canHandleSource` is not called and defaults to `Html5.nativeSourceHandler.canHandleSource` indicating video.js is not "aware" of the HLS plugin.  

### Reduced Test Case
https://github.com/vpowers/videojs-contrib-hls-test

### Error output
VideoJS error: No compatible source was found for this media. MediaError {code: 4, message: "No compatible source was found for this media."}

### videojs-contrib-hls version
videojs-contrib-hls 5.3.0

### videojs version
video.js 5.16.0

### Browsers
Chrome Version 56.0.2924.87

**Comment by LeonidasEsteban** [comment]
Same issue here. any idea for fix it?

**Comment by vpowers** [comment]
@LeonidasEsteban Seems to be an issue with the build using ^5.17.0 of video.js.  My workaround was to fork videojs-contrib-hls and rollback to using ^5.15.1 and load from my own repo until they address the issue.

**Comment by frontMoment** [comment]
@LeonidasEsteban same issue, any solution by using dependency via package.json?

**Comment by mjneil** [comment]
Sorry this has gone unnoticed for so long. @vpowers looking at your reduced test case, it looks like 2 versions of videojs are being loaded into the page, 5.16.0 for the project's dependency, and 5.18.4 (as of today) for the ^5.17.0 dependency in contrib-hls. The project works properly for me if I update the dependency in the root project to ^5.16.0 so that npm can load just 1 version of videojs that covers both dependency requirements

**Comment by gdenisov** [comment]
@mjneil switching the dependencies to the latest video.js 5.19.0 and videojs-contrib-hls 5.3.3 loads only one version of video.js for me, but the video in the above test case or my own project still does not work

**Comment by dbryand** [comment]
Just filed an issue with that test repo, but there were two issues for me. The `.m3u8` link in the repo is broken. When I upgraded to `"video.js": "5.19.2"` and entered a link to a working `.m3u8` file and this worked for me.

https://github.com/vpowers/videojs-contrib-hls-test/issues/2

**Comment by gesinger** [comment]
@dbryand , thanks for the update.

@vpowers , are you still experiencing this issue with the latest versions of video.js and videojs-contrib-hls?

**Comment by gesinger** [comment]
Closing for now. If you are still experiencing this issue with the latest version of videojs-contrib-hls (as of this comment, v5.5.3), please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.
