### ISSUE TITLE
videojs hls unable to reopen source HLS m3u8 ||| Failed to execute 'endOfStream' on 'MediaSource'

### ISSUE THREAD

**Issue by mescalito** [videojs/videojs-contrib-hls#1034]
## Description
I constantly get the same error when reopen a live streaming m3u8 file.

The first time everything works fine but if OBS stops and restart live streaming then an error occur.

here is a 2 mins video showing exactly the problem/error (if a picture is worth a thousand words then a video is worth a million):

## VIDEO Description: 2 mins
**[http://youtu.be/tTskEdPSen8?hd=1](http://youtu.be/tTskEdPSen8?hd=1)**

### Error output

Uncaught DOMException: Failed to execute 'endOfStream' on 'MediaSource': The MediaSource's readyState is not 'open'.

    GET http://cdn-event.superfans.tv/b5XDFh3oqS/index.m3u8 404 (Not Found)

    Uncaught DOMException: Failed to execute 'endOfStream' on 'MediaSource': The MediaSource's readyState is not 'open'.
        at MasterPlaylistController.blacklistCurrentPlaylist (https://npmcdn.com/videojs-contrib-hls@5.1.0/dist/videojs-contrib-hls.js:1160:33)
        at PlaylistLoader.<anonymous> (https://npmcdn.com/videojs-contrib-hls@5.1.0/dist/videojs-contrib-hls.js:699:16)
        at PlaylistLoader.trigger (https://npmcdn.com/videojs-contrib-hls@5.1.0/dist/videojs-contrib-hls.js:4947:24)
        at https://npmcdn.com/videojs-contrib-hls@5.1.0/dist/videojs-contrib-hls.js:2273:23
        at Object.callback (https://npmcdn.com/videojs-contrib-hls@5.1.0/dist/videojs-contrib-hls.js:5461:7)
        at cbOnce (http://vjs.zencdn.net/5.15.1/video.js:24407:21)
        at loadFunc (http://vjs.zencdn.net/5.15.1/video.js:24483:16)
        at XMLHttpRequest.readystatechange (http://vjs.zencdn.net/5.15.1/video.js:24413:13)

This is the broken line FILE: https://npmcdn.com/videojs-contrib-hls@5.1.0/dist/videojs-contrib-hls.js

    ...// If there is no current playlist, then an error occurred while we were
    // trying to load the master OR while we were disposing of the tech
    if (!currentPlaylist) {
      this.error = error;
      return this.mediaSource.endOfStream('network');
    }
    ...

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls **5.1.0**

### videojs version
what version of videojs does this occur with?
video.js **5.15.1**

### Browsers
what browsers are affected? please include browser and version for each
* Chrome latest version: Version 56.0.2924.76 (64-bit)
* Chrome canary  58.0.3022.0 (64-bit)

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* Windows

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* AngularJS

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* AngularJS

**Comment by gesinger** [comment]
Hey @mescalito , thanks for the information, debugging, and the video. We really appreciate all the effort you put in into helping discover the problem.

You found the exact problem spot too, and we actually started working on a fix for it the other day, to allow for proper error events in the case where the media source's readyState is not yet open and the source stream fails.

I'm going to close this issue, just because we have https://github.com/videojs/videojs-contrib-hls/issues/575 reporting the same item, but we'll be trying to get out a fix for it soon. Keep an eye on that issue, as we'll update as we get a pull request ready.

Thanks again!
