### ISSUE TITLE
overrideNative doesnt seem to have any effect?

### ISSUE THREAD

**Issue by samueleastdev** [videojs/videojs-contrib-hls#1040]
## Description
Hi All,

I am trying to utilise the overrideNative options with the setup below.

~~~
var videoPlayer = videojs("video-player", {
    flash: {
        hls: {
            overrideNative: true
        }
    },
    html5: {
        hls: {
            nativeAudioTracks: false,
            nativeVideoTracks: false,
            overrideNative: true
        }
    }
}, function() {

});

videoPlayer.on('loadedmetadata', function() {

    var player = this;
    console.log("player.tech_.hls", player.tech_.hls);

});
~~~

Is the code above correct or am I setting it up wrong if it is correct then I will create an example

Thanks ;)

**Comment by sea-kg** [comment]
I use "videojs.options.overrideNative = true" - it worked for emulator chrome browsers (and in adnroid chrome)

**Comment by samueleastdev** [comment]
Hi @sea-kg,

Thanks for the response sorry for the basic question but where are you putting this in your code after the ready call?

~~~
var videoPlayer = videojs("video-player", {}, function() {
    var player = this;
    player.options.overrideNative = true;
});

//or just after the call

videoPlayer.options.overrideNative = true;

~~~

Thanks

**Comment by sea-kg** [comment]
It's global options of videojs. You must set this options before creation.
I m using like:

    ...
    <script src="js/videojs-contrib-hls.js?v=1"></script>
    <script>
	videojs.options.hls.overrideNative = true;
    </script>

**Comment by samueleastdev** [comment]
Ah right thanks @sea-kg felt a bit dumb fo asking but better to know ;)

**Comment by sea-kg** [comment]
You welcome )

**Comment by samueleastdev** [comment]
Working now thanks ill close ;)
