### ISSUE TITLE
Use hls with webpack and can't resolve some error

### ISSUE THREAD

**Issue by zswxp32** [videojs/videojs-contrib-hls#1041]
## Description
hello all, here is my code;

```
// videojs
import videojs from 'video.js';
window.videojs = videojs; // don't know whether it's needed
// videojs hls
import 'imports-loader?this=>window!videojs-contrib-hls/dist/videojs-contrib-hls.js';

```

```
// player had initialized with videojs
player.src([{
    src: 'https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8',
    type: 'application/x-mpegURL'
}]);
player.play();
```
I also tried import directly like this, and nothing happened
```
// like this
import 'videojs-contrib-hls';
// this will get error like "TypeError: Cannot read property 'EventTarget' of undefined"
```
```
// or like this
videojs.Hls = require('videojs-contrib-hls');
// this will get  error like "Cannot read property 'beforeRequest' of undefined"
```
then when I test in chrome 56
videojs-contrib-hls.js has this problem, allways, i checked a lot, but could't find a good way...

**Comment by gkatsev** [comment]
contrib-hls has an issue with webpack around webworkify, there's a workaround here: https://github.com/videojs/videojs-contrib-hls/issues/600#issuecomment-258400412

Hope that helps.

**Comment by zswxp32** [comment]
@gkatsev  thank you for help, it's useful.

**Comment by asokani** [comment]
FYI https://github.com/videojs/videojs-contrib-hls/issues/636#issuecomment-296364099
