### ISSUE TITLE
videojs-contrib-hls only works with videojs-flash in version 6.0.0 depending on order

### ISSUE THREAD

**Issue by johndanek** [videojs/videojs-contrib-hls#1047]
## Description
If you wish to play HLS files with the new videojs-flash for videojs 6.0.0, the order of those two includes definitely matters. I used video.js@6.0.0-RC.3.

If your <script> tags in <head> have videojs-contrib-hls BEFORE videojs-flash, it will not work. The Flash plugin is unaware of videojs-contrib-hls. If you switch the order, it works fine. I didn't notice any documentation on the matter, so if this can't be remedied in code, maybe a notice on the README.md is in order.

## Sources
https://gist.github.com/johndanek/fe2e6a4e79bcaafd57dc580cf88f9539

Copy that into a local file and load it in Chrome. It doesn't want to seem to work in JSBin. Anyways, the file will play fine. But reverse the order of the <script> tags for videojs-flash.js and videojs-contrib-hls.js and you'll get Media Unsupported errors.

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls x.y.z

### videojs version
what version of videojs does this occur with?
video.js 5.3.3

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
video.js@6.0.0-RC.3
videojs-flash@1.0.0-RC.2

**Comment by mjneil** [comment]
Thanks for bringing this to our attention. I've updated the README to include a notice.
