### ISSUE TITLE
Add videojs-flash to gh-pages for video.js 6

### ISSUE THREAD

**Issue by forbesjo** [videojs/videojs-contrib-hls#1050]
## Description
For the demo page to work on browsers with Flash playback and video.js 6 https://github.com/videojs/videojs-flash/ needs to be included

**Comment by forbesjo** [comment]
This needs to wait until https://www.npmjs.com/package/video.js latest is 6.0

**Comment by thecotne** [comment]
@forbesjo video.js@6.1.0 is latest version

**Comment by thecotne** [comment]
@forbesjo videojs-contrib-hls flash does not work for me 

in chrome 

```
VIDEOJS: Error: Error: Failed conversion between PP_Var and V8 value
```

in firefox it does not work but there is not error message

any ideas?

**Comment by pinglikethinking** [comment]
how did you resolve your problems I have the same
![image](https://user-images.githubusercontent.com/17807157/33256165-ebb94342-d38b-11e7-94c6-38acfb188785.png)
