### ISSUE TITLE
Order of playlist not respected for initial quality selection

### ISSUE THREAD

**Issue by jasonbouffard** [videojs/videojs-contrib-hls#1051]
## Description

In our playlist 720p is first in the list. I would expect the videojs-contrib-hls plugin to choose this quality initially.

```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=10525594,AVERAGE-BANDWIDTH=4587570,CODECS="avc1.64001f,mp4a.40.2",RESOLUTION=1280x720
video_clip_64885-hls_720p.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5701514,AVERAGE-BANDWIDTH=2562120,CODECS="avc1.42001f,mp4a.40.2",RESOLUTION=854x480
video_clip_64885-hls_480p.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=18724800,AVERAGE-BANDWIDTH=8268554,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1920x1080
video_clip_64885-hls_1080p.m3u8
```

I understand the size of the video player is taken into consideration as well when choosing the quality. Could the video player size not be available at the time the initialization logic is running? Maybe I'm missing something on why 480p is getting loaded first or if there is something we can do to hint to videojs-contrib-hls that we would prefer 720p load first then let the hls magic take over from there.

https://output.jsbin.com/begayatane
https://jsbin.com/begayatane/edit?html

I did see this entry in the changelog a little while ago. I thought for sure this would fix this issue: https://github.com/videojs/videojs-contrib-hls/commit/ef34bbe5e07aa4cd275ca139fed8670f6529ac62#diff-4ac32a78649ca5bdd8e0ba38b7006a1e This could be a potential regression.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Create a playlist with a 720p (medium) quality first (or use the jsbin links above)
2. Play the playlist
3. 480p (low) will play not 720p (medium) initially. It will then bump to 1080p if the player is large enough and bw is sufficient.

### Expected
Plays 720p then goes up or down from there depending on bandwidth.

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 5.3.3

### videojs version
what version of videojs does this occur with?
video.js 5.18.4

### Browsers
what browsers are affected? please include browser and version for each
* pretty sure all

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* pretty sure all

**Comment by mjneil** [comment]
The ABR algorithm doesn't take order into consideration when selecting a rendition, except in the case of redundant streams (same width/height/bitrate) in which case it will choose the redundant stream based on the order it is listed in the playlist (this was the change you saw in the changelog). What it does take into account is the player size and user's bandwidth. The player defaults an initial bandwidth of 4194304, which is below the bandwidth of your 720 rendition, which would explain why it isn't selecting that. You can change the initial bandwidth to be above the bandwidth of your 720 rendition to have it selected first by setting it through the player options during player creation. 

```
var options = {
  hls: {
    bandwidth: 10525595
  }
};

var player = videojs('myPlayer', options);
```

**Comment by jasonbouffard** [comment]
Thanks for the explanation.

**Comment by russ** [comment]
I'm having the same issue. I took at a look at the jsbin fix posted above but that is showing the same problem. It should load the 720 but if you look at your inspector, you'll see it's loading the 480 version instead.

https://www.dropbox.com/s/tyjkr39she88ynu/Screenshot%202018-09-26%2014.16.55.png?dl=0

**Comment by russ** [comment]
I noticed that Safari picks the video correctly where Firefox and Chrome do not.

**Comment by jwoertink** [comment]
Something I noticed was this depends on your screen size. When shrinking the screen size down, it drops to the lower rate, but doing full screen, it jumps up to a higher rate. Maybe there's a config option for this to say always do the higher rate? (unless on mobile)
