### ISSUE TITLE
Primary and backup stream not in sync 

### ISSUE THREAD

**Issue by amit1990sumit** [videojs/videojs-contrib-hls#1054]
Hi Team,

Could you please guide me, why my stream is not synced with the backup stream?
Also, I read many places that primary and backup stream PST timestamp should be same.
I am new for live streaming. Could please guide me how I can track timestamp from the client end.

Thanks in advance

**Comment by gesinger** [comment]
Hey @amit1990sumit , the primary and backup stream syncing is usually on the software used to generate the streams, however, if those appear to be in sync but the client (videojs-contrib-hls) is desyncing the streams, we will definitely want to look into the issue. Do you have a publicly accessible m3u8 you can throw into a [template](http://jsbin.com/vokipos/8/edit?html,output) for us to check out?

As for the timestamps, are you trying to get the PTS/DTS values of different segments of the stream? I don't believe we have a public API at the moment to get those, but is the use-case simply for debugging purposes, or something beyond?

**Comment by gesinger** [comment]
Closing for now. If you still need an API for PTS/DTS values of different segments, please let us know your use-case (for debugging, or beyond) and provide a reduced test case of your stream using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.
