### ISSUE TITLE
Better Playback Tests

### ISSUE THREAD

**Issue by mjneil** [videojs/videojs-contrib-hls#1055]
It would be good to add some more tests to https://github.com/videojs/videojs-contrib-hls/blob/master/test/playback.test.js to test common playback scenarios including seeking to the begining/middle/end as well as testing an fmp4 source https://d2zihajmogu5jn.cloudfront.net/advanced-fmp4/master.m3u8

**Comment by gesinger** [comment]
This is definitely a good idea. We should try to categorize what sorts of scenarios we want to test in this issue (maybe start with those you mentioned), so that we can check them off as we add them and ultimately resolve this issue.

**Comment by forbesjo** [comment]
Moved this to VHS
