### ISSUE TITLE
Video Player does not work on Android

### ISSUE THREAD

**Issue by selimatmaca** [videojs/videojs-contrib-hls#1058]
I stream HLS on VideoJS.  it used to work fine but I just noticed that android browser can not display my video, anymore. Windows browsers such as Chrome Firefox Edge works on PC. I suspect that android phones might have received an update and that might cause this issue.
The player shows this message "Your browser does not support the playback of this video". 

I use Video.js 5.14.0 and videojs-contrib-hls version 4.0.2.

I also tried CDN links: That did not work either
<link href="//vjs.zencdn.net/5.11/video-js.min.css" rel="stylesheet">
<script src="//vjs.zencdn.net/5.11/video.min.js"></script>

I tried this live example on Windows PC: http://jsbin.com/liwecukasi/edit?html,output
It is giving the error message "Media could not be loaded..."

Any ideas?

I tried latest version of  videojs-contrib-hls version 5.3.3. It does not work either

**Comment by forbesjo** [comment]
Have you tried using this source https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8 ? The source in the jsbin no longer exists

**Comment by selimatmaca** [comment]
I tested  https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8 on http://jsbin.com/peyikedime/edit?html,output on android devices and it works.

I am using the exact same code from http://jsbin.com/peyikedime/edit?html,output (except the source off course) and my hls stream can not be seen on videojs on only android. On other platforms such as windows PC, Mac PC, iPhone can display it.

Any idea?

**Comment by gesinger** [comment]
Hey @selimatmaca , if that stream and template works on Android, but a different stream with the same template doesn't work, it points to it most likely being an issue with that different stream. If you are able to provide that stream , it can help us debug the issue.

Also, for Android, it should be using the native player, however, you can try using [overrideNative](https://github.com/videojs/videojs-contrib-hls#overridenative) to override that native player and see if it works otherwise. If you can give that a shot and let us know if it helps, that may also help point to the source of the issue.

**Comment by selimatmaca** [comment]
Hi Gesinger,
I used override option as below and it didn't fix the issue. 
overrideNative: true
videojs.options.html5.nativeAudioTracks: false
videojs.options.html5.nativeVideoTracks: false

My stream link is: https://stream.sehir.edu.tr/mezuniyethls/sehirhlstest.m3u8

**Comment by selimatmaca** [comment]
I have been streaming for the last 3 days (24/7),did you get a chance to check my stream?

**Comment by samueleastdev** [comment]
Hi All,

I am also getting this issue on android chrome it won't work for me.

To test you can paste this url.

https://s3.amazonaws.com/Loop.Sam/alien-covenant-trailer-1_h1080p/encoded-Sun-Mar-2017-19-00-42/encoded-Sun-Mar-2017-19-00-42.m3u8

Into the demo.

https://videojs.github.io/videojs-contrib-hls/

I am testing on a Samsung Galaxy S3.

Thanks

**Comment by selimatmaca** [comment]
I tested on many other players such as viblast and bitmovin. They dont work on android, too. Yesterday we tried android nougat and it works. So, I think this is an issue with android os, not with videojs player. What do you think?

**Comment by samueleastdev** [comment]
@selimatmaca yes I think that might be the case spent the whole day trying to debug this ended up stripping everything back to just the basic HTML video tag with a mp4 and I was still getting issues I posted an issue here. https://github.com/videojs/video.js/issues/4214 then I suddenly had an update to Chrome on Android and it started working I upgraded to version 56.0.2924.87

**Comment by gesinger** [comment]
Thanks for the tips @samueleastdev , and for the issue info @selimatmaca . It looks like this was an issue with the Android OS itself. Closing for now, but if you see any info regarding the issue that could point to something else, please let us know. Thanks.
