### ISSUE TITLE
Issue with playing HLS video on Chrome

### ISSUE THREAD

**Issue by JohnnyDev0918** [videojs/videojs-contrib-hls#1066]
## Description
Briefly describe the issue.
For some reason, when the length of a HLS video is 10 seconds or less, I get the error " “VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported" on Chrome. I do not received this error on any other browsers (Firefox, Edge, Safari, etc.)

## Sources
Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. For some reason, when the length of a HLS video is 10 seconds or less, I get the error " “VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported" on Chrome. I do not received this error on any other browsers (Firefox, Edge, Safari, etc.)
2.
3.

### Expected
I should not be getting any error.

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 4.0.2

### videojs version
what version of videojs does this occur with?
video.js 5.12.1

### Browsers
what browsers are affected? please include browser and version for each
Latest version of Chrome browser

### Platforms
what platforms are affected? please include operating system and version or device and version for each
Mac OS X El Capitan

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by mjneil** [comment]
Can you provide a source that causes the problem and try loading it [here](http://jsbin.com/vokipos/8/edit?html,output). I am seeing no issues with a 6 second source.

**Comment by JohnnyDev0918** [comment]
Here's the video that I've been getting the error in Chrome only:
http://breakdownservices-dev.s3.amazonaws.com/media/ecocast/209462/videos/209462-8ecd721a-e6d6-4992-9715-db9edcb112d7/playlist.m3u8
 

    On Tuesday, March 28, 2017 7:58 AM, Matthew Neil <notifications@github.com> wrote:
 

 Can you provide a source that causes the problem and try loading it here. I am seeing no issues with a 6 second source.—

**Comment by mjneil** [comment]
Looking at the console, I am getting
```
XMLHttpRequest cannot load http://breakdownservices-dev.s3.amazonaws.com/media/ecocast/209462/videos/209462-8ecd721a-e6d6-4992-9715-db9edcb112d7/hls10.ts. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://null.jsbin.com' is therefore not allowed access. The response had HTTP status code 403.
```

Content needs to have cors headers otherwise the browser wont allow the player to load the source. See https://github.com/videojs/videojs-contrib-hls/blob/master/README.md#hosting-considerations

**Comment by JohnnyDev0918** [comment]
Here's an example (see code below). If remove the "autoplay" attribute from the video element, then you won't receive the error "VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. MediaError {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported."}", but if you leave the "autoplay" attribute there, you will receive the above error after refreshing the page a couple times.
<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8 />
<title>videojs-contrib-hls embed</title>
  
  

  <link href="https://unpkg.com/video.js/dist/video-js.css" rel="stylesheet">
  <script src="https://unpkg.com/video.js/dist/video.js"></script>
  <script src="https://unpkg.com/videojs-contrib-hls/dist/videojs-contrib-hls.js"></script>
  
</head>
<body>
  <h1>Video.js Example Embed</h1>

  <video id="my_video_1" class="video-js vjs-default-skin" controls autoplay width="640" height="268" data-setup='{}'>
    <source src="http://breakdownservices-dev.s3.amazonaws.com/media/ecocast/209462/videos/209462-8ecd721a-e6d6-4992-9715-db9edcb112d7/playlist.m3u8" type="application/x-mpegURL">
  </video>
  
  <script>
  </script>
  
</body>
</html>

Please help! Many thanks in advance.

 

    On Tuesday, March 28, 2017 11:05 AM, Peter Le <peter_le1@yahoo.com> wrote:
 

 Here's the video that I've been getting the error in Chrome only:
http://breakdownservices-dev.s3.amazonaws.com/media/ecocast/209462/videos/209462-8ecd721a-e6d6-4992-9715-db9edcb112d7/playlist.m3u8
 

    On Tuesday, March 28, 2017 7:58 AM, Matthew Neil <notifications@github.com> wrote:
 

 Can you provide a source that causes the problem and try loading it here. I am seeing no issues with a 6 second source.—

**Comment by mjneil** [comment]
The presence of the autoplay attribute does not make a difference for me. I am still seeing errors saying the content do not have CORS headers. The response MUST contain a `Access-Control-Allow-Origin` header, otherwise the player will not be able to play the video. Please refer to the section about hosting in our [README](https://github.com/videojs/videojs-contrib-hls/blob/master/README.md#hosting-considerations)

I'm closing this issue for now. If you configure your server to attach CORS headers to media responses and still have problems, please reopen the issue or create a new one.

**Comment by itspwk** [comment]
I have set on the "Cross-origin resource sharing (CORS) (for HTTP-based streams)", but still getting this error on chrome. i have latest chrome installation
Below is the code :

`<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8 />
	<link href="https://unpkg.com/video.js/dist/video-js.css" rel="stylesheet">


</head>
<body>

<div style="width:600px;">
 <video id="my_video_1" class="video-js vjs-default-skin vjs-big-play-centered" controls autoplay="true" preload="auto" width="640" height="360" data-setup='{"fluid":true}'>
    <source src="http://192.206.7.232:1935/Steelbird/myStream/playlist.m3u8" type="application/x-mpegURL">

  </video>
  </div>
	<script src="https://unpkg.com/video.js/dist/video.js"></script>
	<script src="https://unpkg.com/videojs-contrib-hls/dist/videojs-contrib-hls.js"></script>
</body>`
