### ISSUE TITLE
Unable to load a m3u8 link on google chrome by using a local html file.

### ISSUE THREAD

**Issue by hmd13** [videojs/videojs-contrib-hls#1073]
## Description
I am trying to load m3u8 media link on google chrome using videojs-contrib-hls by creating a local html file.

I copied the same html code used in the starter template (http://jsbin.com/vokipos/8/edit?html,output), it didn't work on google chrome while it worked on firefox, I tried to change the m3u8 video link, some links ( the default link) only work on firefox and not on chrome because of these errors:
1. **Not allowed to load local resource: blob:null/288470a8-ae84-4891-a545-7752a7387bc3**
2. **VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.**

Some other links (http://www.metafilegenerator.de/DWelle/tv-northamerica/ios/master.m3u8) didn't work for any browser and provided these errors for both, chrome and firefox:
1.**Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur http://www.metafilegenerator.de/DWelle/tv-northamerica/ios/master.m3u8. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant.**
2.**VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.**

I want to understand the reason behind these issues, why the first attempt worked only on firefox, and why the second one didn't work for both browsers while they worked successfully on the starter template.
Does the scripts should run on a webserver or what ?

## Sources
m3u8 link 1: http://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8
m3u8 link2: http://www.metafilegenerator.de/DWelle/tv-northamerica/ios/master.m3u8

## Steps to reproduce
1.Copy the html code of the starter template and paste it on a html locale file.
2.open the file on firefox and chrome ( it worked on firefox while it didn't on chrome)
3.Change the m3u8 link with another one and open again the file, it didn't work on both browsers.

## Results
As reported above.

### Expected
to make the m3u8 videos load.

### Error output
PS: I'm not able to put a screenshot here so the errors are reported above.

### videojs-contrib-hls version
videojs-contrib-hls 5.4.0

### videojs version
video.js 5.19.1

### Browsers
for the first attempt: only google chrome is affected v57.0.2987.133.
for the second attempt, both browsers, chrome and firefox are affected, firefox v52.0.2.

**Comment by gesinger** [comment]
Hey @hmd13 , thanks for all of the details.

The second error looks to be due to CORS, as the server doesn't allow cross-domain requests (and when your page is hosted locally, the domain doesn't match what the server expects). This must be remedied server-side (as the server must allow CORS for your/all domains).

As for the first error, is "blob:null/288470a8-ae84-4891-a545-7752a7387bc3" set as the source of the video? Do you have a copy of the page you are hosting locally?

**Comment by gkatsev** [comment]
Making XHR requests on a page opened from the file system is a recipe for failure. Running via a local static file server is highly recommended.

**Comment by hmd13** [comment]
@gesinger @gkatsev Thank you for the answers, I will try that.
@gesinger I can't attach the file here, so this is the code of the hosted locally page:

<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8 />
	<title>videojs-contrib-hls</title>
	<link href="https://unpkg.com/video.js@5.19.1/dist/video-js.css" rel="stylesheet">
	<script src="https://unpkg.com/video.js@5.19.1/dist/video.js"></script>
	<script src="https://unpkg.com/videojs-contrib-hls@5.4.0/dist/videojs-contrib-hls.js"></script>
</head>
<body>
	<h1>Video.js Example</h1>
	<video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="268" 
	data-setup='{}'>
    <source src="http://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8" type="application/x-mpegURL">
	</video> 
</body>
</html>

**Comment by hmd13** [comment]
@gesinger and @gkatsev thank you for the answers, I will try that
@gesinger , I can't attach the file, so this is the code of the local page

`<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8 />
	<title>videojs-contrib-hls</title>
	<link href="https://unpkg.com/video.js@5.19.1/dist/video-js.css" rel="stylesheet">
	<script src="https://unpkg.com/video.js@5.19.1/dist/video.js"></script>
	<script src="https://unpkg.com/videojs-contrib-hls@5.4.0/dist/videojs-contrib-hls.js"></script>
</head>
<body>
	<h1>Video.js Example</h1>
	<video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="268" 
	data-setup='{}'>
    <source src="http://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8" type="application/x-mpegURL">
	</video> 
</body>
</html>`

**Comment by gesinger** [comment]
@hmd13 , @gkatsev 's answer should be the reason you are getting the first error (don't need to send the file).

**Comment by hmd13** [comment]
@gkatsev thank you again for the answer, but do you know why it works on Firefox, and not in chrome ?

**Comment by gkatsev** [comment]
Different browsers have different restrictions. It's possible that in this case firefox is letting the requests through and chrome isn't. I would urge you to always use a static file server locally for testing these types of things as they would provide the most realistic scenario to work with.

**Comment by gesinger** [comment]
Thanks @gkatsev . @hmd13 , let us know if you experience any problems with the player when using a server. Thanks.
