### ISSUE TITLE
Trigger an event when the final playlist would've been blacklisted

### ISSUE THREAD

**Issue by gesinger** [videojs/videojs-contrib-hls#1074]
## Description
Right now, with the latest changes to the player, we don't blacklist the final rendition, meaning that the player will keep trying that stream. This is normally fine, as the stream should be able to play within a player without trouble, and normally when errors happen it is due to the server being down temporarily, rather than a complete block due to permissions (in which case the stream isn't usually meant for that domain/user to play). However, there could be various reasons for the event, and it would be nice to allow developers to react outside of the player to such an error condition.

**Comment by zhuangs** [comment]
#1080

**Comment by mjneil** [comment]
#1080 has been merged into master
