### ISSUE TITLE
Plugin failure when run the signal page app(Vue.js)

### ISSUE THREAD

**Issue by Henry-nie** [videojs/videojs-contrib-hls#1078]
## Description

I want to dynamic set up src, but it failure. 

## Sources
import videojs from 'video.js'
<template>
<video id="player"
             class="video-js vjs-default-skin vjs-big-play-centered"
             controls
             autoplay
             preload="auto">
</video>
</template>
<script>
videojs('player', {}, function () {
          this.src({
            src: 'xxx.m3u8',
            type: 'application/x-mpegURL',
            withCredentials: true
         })
          this.play()
       })
</script>
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1.
2.
3.

### Expected
Please describe what you expected to happen that did not happen in the description.

can play .m3u8 media

### Error output
No compatible source

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls x.y.z

### videojs version
what version of videojs does this occur with?
video.js x.y.z

### Browsers
what browsers are affected? please include browser and version for each
*

### Platforms
what platforms are affected? please include operating system and version or device and version for each
*

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by gesinger** [comment]
Hey @Henry-nie , I noticed that in the sample you listed, you aren't including videojs-contrib-hls. video.js by default doesn't include videojs-contrib-hls, so it won't be able to play the m3u8 without it. Would you be able to try including it and see if it helps? And if it doesn't, would you be able to put together a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thanks.

**Comment by Henry-nie** [comment]
thanks, is this reason. i solved

**Comment by gesinger** [comment]
Thanks for the update @Henry-nie .
