### ISSUE TITLE
If loadstart triggers after a player error is set, the player will clear out the error

### ISSUE THREAD

**Issue by gesinger** [videojs/videojs-contrib-hls#1079]
## Description
Discovered during research for https://github.com/videojs/videojs-contrib-hls/issues/575 . If the player encounters an error before `loadstart` fires (e.g., when the server 404s on the initial playlist request), then video.js will clear the player error on `loadstart`. The error will still trigger an `error` event, but the player will clear the error overlay, show a play button, and won't load the video once play is clicked. Optimally, `loadstart` would trigger before the loading begins.

**Comment by forbesjo** [comment]
Confirmed that this is still an issue

**Comment by forbesjo** [comment]
Moved to VHS
