### ISSUE TITLE
Chrome will not play past first HLS segment with Hardware Acceleration Enabled

### ISSUE THREAD

**Issue by pacepace** [videojs/videojs-contrib-hls#1085]
## Description
When playing back an ondemand HLS video using Chrome 57 the playback stops after the end of the first segment with MEDIA_ERR_DECODE and the message "the media was aborted due to a corruption problem...".  When hardware acceleration is disabled, the video plays past the first segment with no issues.  Video plays fine on Firefox, Safari and Edge with no configuration changes.

## Sources
I can link people to my test video on request.

## Steps to reproduce
1. Create on demand HLS video player using videojs and videojs-contrib-hls with m3u8 playlist
2. Use Chrome 57 to open this link and play the video

### Expected
Video plays to end.

### Error output
MEDIA_ERR_DECODE, message "The media playback was aborted due to a corruption problem..."
### videojs-contrib-hls version
videojs-contrib-hls 5.4.1

### videojs version
video.js 5.19.1

### Browsers
Chrome 57

### Platforms
Multiple Windows 10 (maybe more, don't have anything else around) using NVIDIA (980, 1080s) or Intel integrated graphics.

### Other Plugins
No other plugins

### Other JavaScript
No other libraries, this is a super basic test.

**Comment by gesinger** [comment]
Thanks for reporting @pacepace . I gave the HLS test page a shot on Chrome 56 and Chrome 57 with hardware acceleration enabled on both (on a Mac), and it seemed to play through the first few segments without a problem. Maybe it is a problem related to the specific source, or possibly OS related. Would you mind including a link to the m3u8 you are using?

**Comment by pacepace** [comment]
Thanks for the help!

Here's a link to my test: http://jolokia.http.internapcdn.net/jolokia/jolokia/test/ondemand.html
Here's a link to my m3u8: http://beta.plgen.jolokia.com/plgen.fcgi?bw=520381,670087,840281,1119720,1419460,2018309&bwdef=840281&w=440,548,684,840,1040,1280&base=//jolokia.ios.internapcdn.net/jolokia/jolokia_networks/demos/avatar-tlrf_adaptive__IDX__.mp4&ver=1&of=m3u8

**Comment by pacepace** [comment]
Issue remains the same with videojs 6.0.0

**Comment by pacepace** [comment]
If I use the Peer5 videojs-control-hlsjs and hls.js, my issues clear up.  Really looking like something specific to videojs-contrib-hls.  Would love to help it get fixed.  Let me know what I can provide.

Here's a link to my working player: jolokia.http.internapcdn.net/jolokia/jolokia/test/ondemandP5.html

**Comment by cedricve** [comment]
same issue when upgrading to Chrome 58, didn't experienced with Chrome 57. I get this error.
![screen shot 2017-05-01 at 21 50 20](https://cloud.githubusercontent.com/assets/1546779/25592915/e70a61da-2eba-11e7-9cfd-c8d26a851ed2.png)

**Comment by pacepace** [comment]
Just tested Chrome 58.  Same issue, unable to play past first segment...

**Comment by gesinger** [comment]
Interesting that it only happens on Chrome (works for me in Firefox too). chrome://media-internals doesn't show anything abnormal except audio splice trimming.

**Comment by forbesjo** [comment]
Is this still an issue after Chrome updates and updates to this project? If so we'll reopen and investigate
