### ISSUE TITLE
MEDIA_ERR_SRC_NOT_SUPPORTED error in browserify build

### ISSUE THREAD

**Issue by pebanfield** [videojs/videojs-contrib-hls#1086]
## Description

I am trying import the plugin into my browserify built project like so - 

var videojs = require('video.js');
require('videojs-contrib-hls');

as was recommended in this [support thread](https://github.com/videojs/videojs-contrib-hls/issues/636) 

I am using chrome to play a .m3u8 asset with type application/vnd.apple.mpegurl. This asset does play fine when I include videojs-contrib-hls with a separate script tag. 

The player is throwing an exception - 
 
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. 

Is this method of importing the plugin supported? When debugging I have noticed that in player.js a call to tech.canPlaySource is returning false (line 2451) which seems odd.  

### videojs-contrib-hls version
5.4.1

### videojs version
6.0.0

### Browsers
Chrome

### Platforms
Mac OS

**Comment by gesinger** [comment]
Hey @pebanfield , would you happen to have an example page demonstrating the error?

**Comment by pebanfield** [comment]
I've been working in my production codebase which is not practical to share. I would need to create a separate stand alone example. I was hoping this might be a known issue? I will create an example. Thanks!

**Comment by pacepace** [comment]
Might be unrelated, I've got a similar problem where Chrome gets unhappy with the same message.  This happens on initial page load and before it even tries to load the m3u8.  If you watch the network tab it just dies before it loads the m3u8, etc.  If you hit force-refresh, it will load the m3u8.  Please note that the below link is for a live player and that live stream is not currently running, but it demonstrates the problem (at least for me) as it doesn't even try to load the m3u8 before it dies on the first load:

http://jolokia.http.internapcdn.net/jolokia/jolokia/test/ondemand.html

My testing is with Chrome 57 and Windows 10.

**Comment by pebanfield** [comment]
I have created a very basic test project demonstrating this issue - 

https://github.com/pebanfield/hls-contrib-build-test

At present I am still experiencing this issue - 

https://github.com/videojs/mux.js/issues/131

It is not clear to me that the fix has made it into the build yet.

**Comment by gesinger** [comment]
@pebanfield , looks like https://github.com/videojs/mux.js/issues/131 is most likely source of the issue (the error when building possibly stops contrib-hls from being included).

 videojs/mux.js#151 was recently merged in. This is pending a release of mux.js, but should be out soon.

**Comment by pebanfield** [comment]
Ok I will check back. Thanks for the update!

**Comment by gesinger** [comment]
Hey @pebanfield , we cut v4.1.3 of mux.js with the fix for the browserify-shim error. Please give the latest version of videojs-contrib-hls (v5.5.0) a shot and if you are still experiencing the issue, please re-open the issue/let us know. Thanks for reporting the issue.

**Comment by pebanfield** [comment]
@gesinger - Thanks for the heads up. This fixed the issue. My sample is playing video now. Thanks!

**Comment by gesinger** [comment]
That's great to hear @pebanfield ! Thanks for updating.
