### ISSUE TITLE
README for vjs 6 says that videojs-flash is required

### ISSUE THREAD

**Issue by gkatsev** [videojs/videojs-contrib-hls#1088]
The way the code is, videojs-flash isn't required. It's only required if you need the flash fallback. If videojs-flash isn't included, it'll just not bind the flash source handler.
It should probably mention that instead and maybe just say it's recommended instead.

**Comment by gesinger** [comment]
Merged as part of https://github.com/videojs/videojs-contrib-hls/pull/1095 . Thanks for reporting the issue @gkatsev !

**Comment by gkatsev** [comment]
You're welcome.
