### ISSUE TITLE
Uncaught TypeError: Cannot read property 'byteLength' of undefined

### ISSUE THREAD

**Issue by zdenham** [videojs/videojs-contrib-hls#1092]
## Description
Some audio files from amazon are failing on chrome that work in safari, throwing an uncaught type error.

## Sources
Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.

## Steps to reproduce

1. Substitute the source on the JS Bin test template to 
https://radio-api-east.s3.amazonaws.com/users/2/media/2017/01/25/3601592335841/output/media_hls_master_playlist.m3u8 
2. Change the video tag to an audio one
3. Try on Safari. It works!
4. Try it on chrome...

## Results
it throws the aforementioned error in chrome
### Expected
it to work on both browsers

### Error output
<img width="1270" alt="screen shot 2017-04-19 at 8 06 27 pm" src="https://cloud.githubusercontent.com/assets/16373521/25211774/c26e5ad0-253b-11e7-9db5-0a7229ce094d.png">

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with? latest
videojs-contrib-hls 5.4.1

### videojs version
what version of videojs does this occur with? latest
video.js 5.19.1

### Browsers
what browsers are affected? please include browser and version for each
* Chrome

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* Web OSX

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* nope

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* not for the test case!

**Comment by gesinger** [comment]
Hey @zdenham , thanks for reporting the issue. Right now we don't support audio only streams. We have an enhancement issue opened to add support for it in https://github.com/videojs/videojs-contrib-hls/issues/499 . Safari uses the native player for HLS playback, and that native player does have support right now (why it works in Safari but not Chrome). Closing this ticket in favor of https://github.com/videojs/videojs-contrib-hls/issues/499
