### ISSUE TITLE
Seeking from near the end of playlist to near the end of first segment sometimes causes player freeze on Chrome

### ISSUE THREAD

**Issue by zhuangs** [videojs/videojs-contrib-hls#1093]
## Description
Seeking from near the end of playlist to near the end of first segment sometimes causes player freeze on Chrome

## Sources
http://c.brightcove.com/services/mobile/streaming/index/master.m3u8?videoId=5327995572001&pubId=3737230870001

## Steps to reproduce

1. load that source to JSBin(http://jsbin.com/vokipos/8/edit?html,output)
2. seek to near the end of the playlist(around 1:29) after playback start
3. seek to near the end of first segment(around 0:09)
4. repeat step1 & step2 for several times until see player freeze

## Additional Information
run ```player.currentTime()``` and ```player.tech_.hls.mediaSource.videoBuffer_.buffered.start(0)``` in the console and compare them, you will see ```buffered.start``` is after ```currentTime``` when player freezes

### videojs-contrib-hls version
videojs-contrib-hls 5.4.1

### videojs version
video.js 5.19.2

### Browsers
* Chrome Version 57.0.2987.133

### Platforms
* macOS Sierra vERSION 10.12.2

**Comment by cedricve** [comment]
Having similar issue when upgrading to Chrome 58, the player is stuck after loading the second segment. Following error is thrown.

![screen shot 2017-05-01 at 21 50 20](https://cloud.githubusercontent.com/assets/1546779/25592521/5fbd2ec0-2eb9-11e7-9af2-da9edf056173.png)

**Comment by SVyatoslavG** [comment]
Have same issue.
