### ISSUE TITLE
Trying to concatenate mp4 video and m3u8 video in the same video element with the videoj media player

### ISSUE THREAD

**Issue by hmd13** [videojs/videojs-contrib-hls#1094]
## Description
I am trying to load a m3u8 video after loading a mp4 video in the same video element using the videojs media player with the videojs-contrib-hls library ( for the m3u8 video type )

First, I tried to assemble two mp4 files together and it worked by Adding an event listener to the end of the video and changing the video src with the src of the next source once the video is completed. ( I used the instructions mentioned in this link to achieve that (**http://stackoverflow.com/questions/32335076/html5-video-how-to-play-two-videos-in-one-video-element**)

Then, I tried to assemble an mp4 video with m3u8 video (**http://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8**) but after the mp4 video load the m3u8 media could not  be loaded and this error occures ("**VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported**")

**PS: the m3u8 video loads successfully when it's loaded alone**.

## Sources
1. Any mp4 video
2. m3u8 video link: http://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8

## Steps to reproduce

1. Create a static html page containing two mp4 video sources on the same video element using videojs media player, loading it and it works by Adding an event listener to the end of the video and changing the video src with the src of the next source once the video is completed.

2. Create a static html page containing two videos sources, the first one is a mp4 video and the second one is m3u8 video on the same video element using videojs media player, and adding the same javascript code I mentioned above.

3. Create a local static file server and allow cross-domain request extension to make an m3u8 loads.

4. Running the page via the local server , the mp4 load but the m3u8 doesn't.

## Results
As reported above

### Error output
As reported above

### videojs-contrib-hls version
videojs-contrib-hls 5.4.0

### videojs version
video.js 5.19.1

### Browsers
google chrome v57.0.2987.133.

### Other JavaScript

Adding an event listener to the end of the video and changing the video src with the src of the next source once the video is completed: 

var myvid = document.getElementById('myvideo');

myvid.addEventListener('ended', function(e) {
  // get the active source and the next video source.
  // I set it so if there's no next, it loops to the first one
  var activesource = document.querySelector("#myvideo source.active");
  var nextsource = document.querySelector("#myvideo source.active + source") || document.querySelector("#myvideo source:first-child");
  
  // deactivate current source, and activate next one
  activesource.className = "";
  nextsource.className = "active";
  
  // update the video source and play
  myvid.src = nextsource.src;

});
        var waitTime = 150;

setTimeout(function () {      
  // Resume play if the element if is paused.
  if (myvid.paused) {
    myvid.play();
  }
}, waitTime);

**Comment by gesinger** [comment]
Hey @hmd13 , you can do this via a few methods.

One is that I noticed you're changing the src of the video element. Instead, try using the videojs src method and including the type of content. For instance:

```
var player = videojs('myvideo');

player.src({
  src: 'http://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8',
  type: 'application/x-mpegURL'
});
```

In addition, you can use a playlist plugin (e.g., https://github.com/brightcove/videojs-playlist) to play videos in sequence instead.

Hope this helps, and let us know if you're still having trouble.
