### ISSUE TITLE
Audio Playlist not working in iPhone device

### ISSUE THREAD

**Issue by samueleastdev** [videojs/videojs-contrib-hls#1101]
## Description
Hi All,
I am having an issue with an audio playlist on an actual iPhone device, works fine in desktop browsers and in the developer tools for iPhone in Chrome and Safari, but it does not work on my iPhone 6 it just stalls.
http://output.jsbin.com/tepahoviru/

## Sources
https://d1icx9xml4fjhv.cloudfront.net/audio/encoded-s3a-21-06-04-tue-may-2017/encoded-s3a-21-06-04-tue-may-2017.m3u8

## Steps to reproduce
Open the jsbin link above on an iPhone device and it doesn't play.

## Results
Playback the same as in the desktop browser

### Error output
This is from the player
~~~
"(CODE:3 MEDIA_ERR_DECODE)"
"The media playback was aborted due to a corruption problem or because the media used features your browser did not support."
~~~
This is from the direct link.
~~~
Failed to load resource: Plug-in handled load
~~~

### videojs-contrib-hls version
@version 5.5.1
### videojs version
Video.js 5.19.2

### Browsers
Works in all desktop browsers

### Platforms
Does not work on an actual iPhone tested on an iPhone 6

**Comment by samueleastdev** [comment]
Hi All,

After finding out it wasn't working in the desktop browsers either and debugging this some more, the link plays fine in VLC player and pasted directly into Safari.

I rolled back the release one by one and it turns out everything worked up until version 5.5.1 in the browser so the issue seems to have been introduced in this version, taking a look at the logs to see if I can find out what changed just to note this is only an audio m3u8.

Version 5.5.0 works in the browser haven't tested on mobile Safari running some more tests today.

Thanks

**Comment by gesinger** [comment]
@samueleastdev , when I pasted the m3u8 directly into Safari I got the same message of "Missing Plug-in." Did you manage to get around that error?

**Comment by Sathishchary** [comment]
@gesinger , @samueleastdev, I am following the same videojs versions but i am not able to play the m3u8 files in the iOS devices and safari browsers, can you please help me how you played m3u8 files in iOS devices.

**Comment by gesinger** [comment]
Sorry this issue has gone a while without much attention. I see that the stream is down now. Closing for now, but if this is still an issue with an active stream please let us know. Thank you.
