### ISSUE TITLE
Seeking within a multi-day live stream using player.currentTime(...) sometimes results in endless loop of loading the same segment

### ISSUE THREAD

**Issue by petergeneric** [videojs/videojs-contrib-hls#1103]
## Description
I'm seeking to a particular point in an m3u8 (30 second .ts files) using currentTime(desiredTime). Most of the time this works, however occasionally contrib-hls will get itself into an endless loop of loading the same file, looks to be caused by a call to resetEverything() after the file is loaded

## Steps to reproduce
I don't have a public m3u8, unfortunately, however I don't think this is a playlist issue

1. Create a long (multi-hour, in my case multi-day) m3u8 event with a single bitrate and 30 second chunks. Created with FFmpeg, using -hls muxer and a simple h.264 video track and stereo AAC audio track.
2. Have the m3u8 still be live
3. Seek using currentTime to various points (seems to happen more reliably in the middle of the stream)

### Expected
Expecting video playback to start at the desired point

### Error output
No error output, however network inspector shows the same .ts file being loaded again and again.

## Additional Information
Following the XHR callbacks, it appears that the following code in handleUpdateEnd_ is triggering:
```
// If we previously appended a segment that ends more than 3 targetDurations before
      // the currentTime_ that means that our conservative guess was too conservative.
      // In that case, reset the loader state so that we try to use any information gained
      // from the previous request to create a new, more accurate, sync-point.
      if (segment.end && this.currentTime_() - segment.end > segmentInfo.playlist.targetDuration * 3) {
        this.resetEverything();
        return;
      }
```

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 5.5.1

### videojs version
what version of videojs does this occur with?
video.js 5.19.2

### Browsers
* Chrome Version 59.0.3071.36 (Official Build) beta (64-bit)

### Platforms
* macOS 10.12.4

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* jquery 3.1.1

**Comment by gesinger** [comment]
Hey @petergeneric , thanks for reporting. We definitely want to find a case where this is happening, however, we've haven't been able to replicate this behavior with any of our streams. Would you be able to provide a sample m3u8? Thanks.

**Comment by petergeneric** [comment]
I've included a snippet of the m3u8 below - I'm not currently able to release the source material, however this command (run against the most recent FFmpeg to allow -video_size to work) should create the same sample media and m3u8:

```
ffmpeg -y -f lavfi -i smptebars -s 1920x1080 -re -f lavfi -i "aevalsrc=sin(400*2*PI*t)|sin(410*2*PI*t)|sin(420*2*PI*t)|sin(430*2*PI*t):s=2000" -vf format=yuv420p,yadif -nr 600 -map 0:v -map 0:d -map 0:a -vcodec libx264 -preset veryfast -qp 23 -pix_fmt yuv420p -acodec aac -b:a 128k -f hls -hls_time 30 -hls_list_size 0 -hls_segment_filename essence/%05d.ts example.m3u8
```




My m3u8:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:40
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:30.000000,
00000.ts
#EXTINF:30.000000,
00001.ts
#EXTINF:30.000000,
00002.ts
#EXTINF:30.000000,
00003.ts
#EXTINF:30.000000,
00004.ts
#EXTINF:30.000000,
00005.ts
#EXTINF:30.000000,
00006.ts
#EXTINF:30.000000,
00007.ts
...continues on like this for 46,000 lines...
```


Here are the JS includes I'm using:
```
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/semantic-ui/2.2.10/semantic.min.css"
	      integrity="sha256-5+W3JHnvGYIJkVxUBsw+jBi9+pOlu9enPX3vZapXj5M=" crossorigin="anonymous" />
	<link rel="stylesheet" href="/css/main.css"/>
<script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"
        integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/semantic-ui/2.2.10/semantic.min.js"
        integrity="sha256-97Q90i72uoJfYtVnO2lQcLjbjBySZjLHx50DYhCBuJo=" crossorigin="anonymous"></script>
<script src="//unpkg.com/moment@2.14.1"></script>
<link href="//unpkg.com/video.js@6.0.1/dist/video-js.css" rel="stylesheet" />
<script src="//unpkg.com/video.js@6.0.1/dist/video.js"></script>
<script src="/vendor/videojs-contrib-hls-5.5.1/videojs-contrib-hls.js"></script>
<script src="/vendor/videojs-dvrseekbar/videojs-dvrseekbar.js"></script>
```

I'm using a custom videojs-dvrseekbar.js to work around an issue, however I was experiencing the issue before using dvrseekbar. I've attached it [videojs-dvrseekbar.js.txt](https://github.com/videojs/videojs-contrib-hls/files/1010870/videojs-dvrseekbar.js.txt)

Here's my modified version of videojs-contrib-hls 5.5.1 to work around this issue: 
[videojs-contrib-hls.js.txt](https://github.com/videojs/videojs-contrib-hls/files/1010876/videojs-contrib-hls.js.txt)


My movie HTML is very simple:
```
			<video id="main-movie" class="video-js vjs-default-skin" controls="controls" preload="auto" width="480" height="270">
				<source src="playlist.m3u8" type="application/x-mpegURL"/>
			</video>
```

And I'm initialising videojs with:
```
	// Initialise the main movie
	player = videojs('main-movie', {
		startTime: desiredStartOffset,
		controlBar: {
			volumePanel: {
				inline: false
			}
		}
	});

```

**Comment by mjneil** [comment]
I believe this issue is because of the multi-day long m3u8. Timestamps in MPEG2TS streams are 33 bits, with a max value around ~26.5 hours, so there will be multiple segments with the same exact timestamp.  Currently, we don't have a great way of dealing with seeks that span very large time ranges. During the transmuxing stage, we try and account for this rollover by comparing and adjusting the timestamps when a rollover is detected. https://github.com/videojs/mux.js/blob/master/lib/m2ts/timestamp-rollover-stream.js#L34
The `SyncController` is also probably experiencing issues since we inspect each segment before transmuxing for timing information https://github.com/videojs/videojs-contrib-hls/blob/master/src/sync-controller.js#L409

**Comment by gesinger** [comment]
Nice catch @mjneil . @petergeneric , while we should consider approaches to finding a fix for this, is there any way you could use shorter playlists, or does your use case require multi-day m3u8s?

**Comment by petergeneric** [comment]
Ah, excellent @mjneil thanks! Hadn't thought about pts rollover.

In my use case recordings should all be ~20 hours long (my playlists in this case being so long is a result of using the system in test mode) so it shouldn't be an problem going forward.

**Comment by gesinger** [comment]
Thanks for following up @petergeneric . Since your real world use cases are a shorter duration, I'm going to close this issue for now, as we don't often see people using multi day windows for their production playlists.

If you are still having any trouble, please let us know. Thanks again for posting.
