### ISSUE TITLE
Import not working for video-record.js

### ISSUE THREAD

**Issue by manishchauhanquovantis** [videojs/videojs-contrib-hls#1104]
unable to import video from 'videorecord';

` resolve: {
    extensions: ['', '.js', '.jsx'],
    alias: {
      actions: `${defaultSettings.srcPath}/actions/`,
      components: `${defaultSettings.srcPath}/components/`,
      sources: `${defaultSettings.srcPath}/sources/`,
      stores: `${defaultSettings.srcPath}/stores/`,
      styles: `${defaultSettings.srcPath}/styles/`,
      config: `${defaultSettings.srcPath}/config/` + process.env.REACT_WEBPACK_ENV,
      'react/lib/ReactMount': 'react-dom/lib/ReactMount',
      videorecord:path.resolve(__dirname, "../node_modules/videojs-record/src/videojs.record")
    }`

**Comment by gkatsev** [comment]
I'm guessing that the problem is that webpack needs to be configured as outlines in #600.

**Comment by manishchauhanquovantis** [comment]
Getting error

`Module not found: Error: Cannot resolve 'file' or 'directory' /home/manish/Documents/OPENSOURCE/videoRecordingReact/cfg/node_modules/videojs-record/dist/videojs.record.js in /home/manish/Documents/OPENSOURCE/videoRecordingReact/src/components
 @ ./src/components/Main.js 15:25-55
`


WEBPACK configuration

` resolve: {
    extensions: ['', '.js', '.jsx'],
    alias: {
      actions: `${defaultSettings.srcPath}/actions/`,
      components: `${defaultSettings.srcPath}/components/`,
      sources: `${defaultSettings.srcPath}/sources/`,
      stores: `${defaultSettings.srcPath}/stores/`,
      styles: `${defaultSettings.srcPath}/styles/`,
      config: `${defaultSettings.srcPath}/config/` + process.env.REACT_WEBPACK_ENV,
      'react/lib/ReactMount': 'react-dom/lib/ReactMount',
      'videojs-contrib-hls': path.join(
        __dirname,
        'node_modules',
        'videojs-record',
        'dist',
        // You can use the unminified version and let the minifier minify!
        'videojs.record.js'
      ),
    }
  },`

**Comment by gesinger** [comment]
Hey @manishchauhanquovantis , this looks like it might be an error with either video-record, or the webpack configuration. If it is the former, it might be better to open an issue in the video-record repo. If it is the latter, as @gkatsev mentioned, we have https://github.com/videojs/videojs-contrib-hls/issues/600 for webpack configuration. Hope this helps.
