### ISSUE TITLE
Test MSE HLS with IE11 on Windows 8.1+

### ISSUE THREAD

**Issue by imbcmdth** [videojs/videojs-contrib-hls#1107]
## Acceptance Criteria
1. MAAT Switching
1. Fullscreen Switching
1. Aggressive Seeking
1. Seeking near the end
1. Replaying
1. Manual Rendition Selection
1. IMA3
1. Does Adv. BipBop blow you away?
1. Live Stuff
   1. Large Windows
   1. Seek to live when we fall off the window
   1. Live DVR

## Notes
1. REALLY LOOK AT THE MANAGED RELEASE U GUYS -- Joe

**Comment by forbesjo** [comment]
Done, closing
