### ISSUE TITLE
Increase GOAL_BUFFER_LENGTH

### ISSUE THREAD

**Issue by imbcmdth** [videojs/videojs-contrib-hls#1109]
## Acceptance
* Make GOAL_BUFFER_LENGTH larger (double it)
* Do managed releases to see the impact on rebuffering and COGS
* For each test, a report should be created with:
   *  Chosen size of GBL
   * Growth algorithm (if applicable)
   * The COGS impact (% change)
   * Rebuffering impact (change in count and duration)

## Notes
* Try a growth algorithm:
   * Idea: 30 seconds for the first minute then 60 thereafter
   * Idea: Add 1 second to the GBL for each second viewed up to the max

**Comment by imbcmdth** [comment]
@imbcmdth Find out why this didn't seem to help much!

**Comment by mjneil** [comment]
this was added in #1176
