### ISSUE TITLE
HLS video doesn't fire 'ended' event

### ISSUE THREAD

**Issue by saverchenkov** [videojs/videojs-contrib-hls#111]
Hi Guys,
I have a playlist with variable durations of each segment. Each segment's duration is reported in seconds to a 10th decimal point precision, but there is obviously a rounding error. When HLS plugin plays this movie it is not able to detect the end of the movie. Safari and iOS are both able to correctly play this playlist.

```
#EXTM3U
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-TARGETDURATION:11
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:10.9,
video-hls-3500-0.ts
#EXTINF:9.9,
video-hls-3500-1.ts
#EXTINF:9.9,
video-hls-3500-2.ts
#EXTINF:9.9,
video-hls-3500-3.ts
#EXTINF:9.6,
video-hls-3500-4.ts
#EXTINF:9.7,
video-hls-3500-5.ts
#EXTINF:9.9,
video-hls-3500-6.ts
#EXTINF:9.8,
video-hls-3500-7.ts
#EXTINF:9.9,
video-hls-3500-8.ts
#EXTINF:7.7,
video-hls-3500-9.ts
#EXT-X-ENDLIST
```

https://s3-us-west-2.amazonaws.com/udropr-content-dev/user-0Sergey/test13/video-hls-3500/playlist-3500.m3u8

Thank you!

**Comment by cdhowie** [comment]
This problem seems to have recurred in 1.3.5 (possibly prior versions) and still remains in 1.3.7.
