### ISSUE TITLE
Start using Bandwidth Simulator in tests

### ISSUE THREAD

**Issue by imbcmdth** [videojs/videojs-contrib-hls#1115]
## Acceptance Criteria
* [ ] Use the bandwidth simulator in tests to verify ABR performance
* [x] Use a sub-set of the bandwidth traces from the commute path 3G dataset
* [ ] Generate a baseline set of numbers for each bandwidth trace
* [ ] Tests run in a new command (not with all other tests)
* [ ] Tests should compare against that baseline and report variances
  * [ ] We should update the baseline when we create results that are markedly and demonstrably better

## Notes
* Things bandwidth simulator tracks:
   * Number segments downloaded for a video
   * Renditions of all of those segments
   * Calculated bandwidth
   * Buffer state
       * Rebuffering counts and duration
   * Number of aborts
* Things bandwidth simulator COULD track:
   * Time to start playback

**Comment by forbesjo** [comment]
cc @zhuangs

**Comment by gesinger** [comment]
## Done
* [X] We can run simulation with multiple files
* [X] We get an output of relevant numbers (and in JSON format)
* [X] We have some real results we can use to verify the simulator (with GOAL_BUFFER_LENGTH of 60)

## Next Steps
* [ ] Create scripts to summarize numbers
* [ ] Verify results
* [ ] Gather more files to do simulations
* [ ] Create ability for simulator to dynamically change configuration (e.g., automatically test GOAL_BUFFER_LENGTH values from 30 => 60 incrementing by 1 each time)
