### ISSUE TITLE
troubling with HLS live stream

### ISSUE THREAD

**Issue by adel1ne** [videojs/videojs-contrib-hls#1121]
## Description
Hi, can you help me plz?
I install videojs and videojs-contrib-hls through npm.
Code uses from example, only src changed.

### Expected
This is not real url "http://example.com/test/playlist.m3u8", but i have a working url, that show me HLS stream in VLC or other players.

The problem is that i get chunks, using my code, but player don't want to show the video.
Only once i've got a video in player. I don't now how it is happen :) 
But all other time, player shows nothing. 

My network Tab in Inspector (F12):
First, i get playlist.m3u8 with Content-type: application/vnd.apple.mpegurl
Then, i get chunks.m3u8?nimblesessionid=314853 (yes, i use nimble)
And after that, l_7_36384020_3983.ts?nimblesessionid=314853

So i get chunks and ts periodically, status is ok (200), but player not working :(

### Error output
There are some errors in console wich shows periodically:
InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable (videojs-contrib-hls.js:17064)

### videojs-contrib-hls version
last

### videojs version
last

### Browsers
Firefox 53.0.2 (x64)

### Platforms
Ubuntu 14.04

### Other Plugins
no

### Other JavaScript
no

**Comment by gesinger** [comment]
Hey @adel1ne , it's hard to debug what's happening without the stream and the page you are using it in. Would you be able to put together a reduced test case of what you are doing (and the stream you are using) using [this template](http://jsbin.com/vokipos/8/edit?html,output)? Thanks.

**Comment by gesinger** [comment]
Closing for now. If you are still experiencing this issue, please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.
