### ISSUE TITLE
Too frequent stream quality switching from SD to HD dynamically.

### ISSUE THREAD

**Issue by rishigohil** [videojs/videojs-contrib-hls#1127]
## Description
The original recordings are in WEBM container (VP9 video Codec and AAC audio Codec). The issue we are facing is our streams are bouncing back and forth between HD and SD without any network fluctuations.

![image](https://cloud.githubusercontent.com/assets/5967748/26323531/33a9f76a-3efd-11e7-8a55-52458d9c4632.png)

Is there any way I can fix this or can log when the player changes the source quality?

**Comment by gesinger** [comment]
Hey @rishigohil , how are you playing the webm files? Would you be able to put together a reduced test case using our [starter template](http://jsbin.com/vokipos/8/edit?html,output)? Thanks.

**Comment by rishigohil** [comment]
Yes. I can do that. Brb.

**Comment by rishigohil** [comment]
http://jsbin.com/zidelo/edit?html,js,output

Here you go. You can also check here. 

https://cobweb1.fau.edu/Demos/VideoJs.html

**Comment by rishigohil** [comment]
@gesinger Any luck?

**Comment by mjneil** [comment]
Issue moved to [videojs/videojs-contrib-dash #186](https://github.com/videojs/videojs-contrib-dash/issues/186) via [**ZenHub**](https://www.zenhub.com/)
