### ISSUE TITLE
it's don't support the h265 tsfile only audio can play

### ISSUE THREAD

**Issue by yuetianle** [videojs/videojs-contrib-hls#1130]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/vokipos/8/edit?html,output) on JSBin you can use.

you-get -i --json http://www.iqiyi.com/dianying/20120226/09b943a240cb37be.html#vfrm=2-4-0-1

you-get: vd: 14 is not handled
you-get: info is {'vd': 14, 'vid': '3d809c87af6b462778558b0c12095976', 'm3utx': 'http://cache.m.iqiyi.com/mus/text/107002400/3d809c87af6b462778558b0c12095976/afbe8fd3d73448c9//20161213/0c/1f/333193ee3ad79f932bd71747ea7b518e.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=107002400&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1495620389312&qypid=107002400_04022000001000000000_14&qd_k=6106164ec2bd468e93936a1d0b95130a&qd_hip=2f5d1720&qd_nsc=14548199003f5609b193d371775fb3fe&other=', 'm3u': 'http://cache.m.iqiyi.com/mus/107002400/3d809c87af6b462778558b0c12095976/afbe8fd3d73448c9//20161213/0c/1f/333193ee3ad79f932bd71747ea7b518e.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=107002400&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1495620389312&qypid=107002400_04022000001000000000_14&qd_k=6106164ec2bd468e93936a1d0b95130a&qd_hip=2f5d1720&qd_nsc=14548199003f5609b193d371775fb3fe&other='}
{
    "site": "爱奇艺 (Iqiyi)",
    "streams": {
        "HD": {
            "container": "m3u8",
            "size": 0,
            "src": [
                "http://cache.m.iqiyi.com/mus/107002400/0f4c0612db94473c9d9779a302cabf0b/afbe8fd3d73448c9//20151116/18/c9/3fb70e8493b1973699575d98c6b0806e.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=107002400&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1495620389312&qypid=107002400_04022000001000000000_2&qd_k=6106164ec2bd468e93936a1d0b95130a&qd_hip=2f5d1720&qd_nsc=f9836aec24348691421d34b116f9c685&other="
            ],
            "video_profile": "540p"
        },
        "LD": {
            "container": "m3u8",
            "size": 0,
            "src": [
                "http://cache.m.iqiyi.com/mus/107002400/adddbe59636d4d0a877d0779530fae50/afbe8fd3d73448c9//20151116/21/d0/afe977e87b71f1418055da92f022370d.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=107002400&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1495620389312&qypid=107002400_04022000001000000000_96&qd_k=6106164ec2bd468e93936a1d0b95130a&qd_hip=2f5d1720&qd_nsc=b24c58b68d22a6b000785bb2b688a427&other="
            ],
            "video_profile": "210p"
        },
        "SD": {
            "container": "m3u8",
            "size": 0,
            "src": [
                "http://cache.m.iqiyi.com/mus/107002400/a67a33737bbf42068c736a29f7bfea6d/afbe8fd3d73448c9//20151116/13/0f/8bd93eef2c8d83ee9bd75f1a167f25e2.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=107002400&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1495620389312&qypid=107002400_04022000001000000000_1&qd_k=6106164ec2bd468e93936a1d0b95130a&qd_hip=2f5d1720&qd_nsc=f1801ed2f66f27195187fbb2ea8e9def&other="
            ],
            "video_profile": "360p"
        },
        "TD": {
            "container": "m3u8",
            "size": 0,
            "src": [
                "http://cache.m.iqiyi.com/mus/107002400/13c6c2199fc36b293f6edb7a81481c93/afbe8fd3d73448c9//20151116/2e/c7/8e442449b0d13a3000111a06047c4c95.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=107002400&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1495620389312&qypid=107002400_04022000001000000000_4&qd_k=6106164ec2bd468e93936a1d0b95130a&qd_hip=2f5d1720&qd_nsc=b0d92c59db416fb857eedc1c748c84cb&other="
            ],
            "video_profile": "720p"
        }
    },
    "title": "胡桃夹子",
    "url": "http://www.iqiyi.com/dianying/20120226/09b943a240cb37be.html#vfrm=2-4-0-1"

play m3u8
http://cache.m.iqiyi.com/mus/107002400/3d809c87af6b462778558b0c12095976/afbe8fd3d73448c9//20161213/0c/1f/333193ee3ad79f932bd71747ea7b518e.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=107002400&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1495620389312&qypid=107002400_04022000001000000000_14&qd_k=6106164ec2bd468e93936a1d0b95130a&qd_hip=2f5d1720&qd_nsc=14548199003f5609b193d371775fb3fe&other=

but only auido can play
## Sources
Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1.
2.
3.

### Expected
Please describe what you expected to happen that did not happen in the description.

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls x.y.z

### videojs version
what version of videojs does this occur with?
video.js x.y.z

### Browsers
what browsers are affected? please include browser and version for each
*

### Platforms
what platforms are affected? please include operating system and version or device and version for each
*

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by gesinger** [comment]
Hey @yuetianle , thanks for reporting, but right now there isn't much browser support for h265 ( https://caniuse.com/#feat=hevc ), and due to that we have no current plans for adding h265 support.
