### ISSUE TITLE
Audio fetch error causing the browser to request the same file infinitely

### ISSUE THREAD

**Issue by tommobicast** [videojs/videojs-contrib-hls#1139]
## Description
When the player unable to fetch audio segment, the player makes infinite loop requesting the same audio segment. This can happen when the audio file is missing or the audio file got trapped with CORS header error (m3u8 file and audio file could be in different folder)
This code (https://github.com/videojs/videojs-contrib-hls/blob/master/src/master-playlist-controller.js#L575) makes the player requesting the same file again.

## Steps to reproduce
http://jsbin.com/jibomusoku/edit?html,output
1. Open the url above (audio file deliberately renamed to something else)
2. Open browser console and monitor the network tab
3. The browser keeps requesting the same resource infinitely

### Expected
Either the player should stop with error message or video can play without sound (no infinite request)

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:

### videojs-contrib-hls version
videojs-contrib-hls 5.5.3

### videojs version
video.js 5.20.1

### Browsers
* Chrome, Safari, etc

**Comment by gesinger** [comment]
Confirmed the behavior on Chrome. Thank you for reporting the issue and providing the sample source @tommobicast !
