### ISSUE TITLE
VLC HLS stream not work

### ISSUE THREAD

**Issue by poda5d2** [videojs/videojs-contrib-hls#1140]
## Description
I tried to create a hls player but it doesn't work. Is the problem with the streaming or the player configuration? It didn't work when i set playlist file in the source and didn't work when i set the stream in the video source.

## Sources
http://82.141.138.201/livevideo

Content of the playlist file:
#EXTM3U
#EXTINF:0,Channel 1
http://82.141.138.201/livevideo

### Error output
video.js:22963 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 

### videojs-contrib-hls version
5.5.3

### videojs version
5.19.2

### Browsers
Chrome 58.0.3029.110

### Platforms
Windows

**Comment by gesinger** [comment]
Hey @poda5d2 , MEDIA_ERR_SRC_NOT_SUPPORTED usually indicates that either videojs-contrib-hls is not being included and there is an m3u8 provided as the source, or that the content is not playable by any of the available technologies (e.g., the source's content type is mislabeled).

I think there may be a few issues going on here though. From your source of http://82.141.138.201/livevideo it doesn't look like that leads to a playlist, and is not segmented. Judging by the playlist you posted, there's only one link (that provided source), where in HLS the content should be segmented, and for live HLS streams there should be a minimum of 3 segments in the playlist at any given time.

**Comment by poda5d2** [comment]
I forgot to write that this source works older version of videojs without videojs-contrib-hls with flash fallback. Does it mean anything? Thanks

**Comment by gesinger** [comment]
Interesting. Would you be able to put together an example of each (working with older version, not working with newer version) using our [start template](http://jsbin.com/vokipos/8/edit?html,output)? Thanks.

**Comment by poda5d2** [comment]
Working example: development.terpola.hu/hls/older.html
Starttemplate: development.terpola.hu/hls/starttemplate.html

**Comment by gesinger** [comment]
Hey @poda5d2 , I looked at the examples. As you said, the old example doesn't seem to use HLS, and is instead using `video/x-flv`. It also didn't seem to play for me.

The HLS manifest that you have as playlist.m3u8 in the new example isn't a valid HLS playlist, and HLS also doesn't support streaming FLV.

**Comment by gesinger** [comment]
Closing for now. Please try setting up your HLS playlist with valid ts or fmp4 segments and give it another shot. If you're still having trouble with that, let us know. Thanks.
