### ISSUE TITLE
Ranges + AES - Firefox short playback glitches

### ISSUE THREAD

**Issue by d3im** [videojs/videojs-contrib-hls#1143]
## Description
When there are used ranges in combination with AES encryption in .m3u8 files playback is not smooth in Firefox 53.0.2 (x64) - there are short glitches even if the playback buffer is fully loaded. Tested on Win 10, Linux and Android 6.0.1 - all positive. Have somebody met similar problems?
```

#EXTM3U
#EXT-X-VERSION:4
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-TARGETDURATION:6
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="key.bin"
#EXTINF:6.000000,
#EXT-X-BYTERANGE:432588@0
media.ts
#EXTINF:6.000000,
#EXT-X-BYTERANGE:387280@432592
media.ts
...
#EXT-X-ENDLIST
```

### Expected
smooth play as if there is no encryption or file segments are used instead of ranges.

### Error output
no

### videojs-contrib-hls version
videojs-contrib-hls 5.5.3

### videojs version
what version of videojs does this occur with?
video.js 6.2.0

### Browsers
* Linux Firefox 53 (x64)
* Windows 10 Firefox 53.0.2 (x64)
* Android 6.0.1 Firefox 53.0.2 ARMv7l

### Platforms
* Linux
* Windows 10
* Android 6.0.1

### Other JavaScript

**Comment by gesinger** [comment]
Hey @d3im , thanks for reporting. We haven't experienced this issue before. Would you be able to provide a sample m3u8 you used that demonstrates this issue? Thanks.

**Comment by d3im** [comment]
Please look at:
AES one file XHR (glitches):
http://testeria.xf.cz/5C.html
AES separate files (OK):
http://testeria.xf.cz/6C.html

Thanks :-)

**Comment by d3im** [comment]
seems hls.js have this problems too. (This particular server doesn't serve right mimetypes)
http://testeria.xf.cz/5C1.html
http://testeria.xf.cz/6C1.html

**Comment by d3im** [comment]
Seems the problem is not in hls.js itself, but in tools writing ranges to .m3u8 file (Bento4, FFmpeg).

**Comment by cpeterso** [comment]
The http://testeria.xf.cz/5C1.html video does not play for me in Firefox 54, Chrome 60, or Edge on Windows 10. The http://testeria.xf.cz/5C.html video seems to play fine for me in Firefox 54.
