### ISSUE TITLE
Check out our live example if you're having trouble.

### ISSUE THREAD

**Issue by HankBrown** [videojs/videojs-contrib-hls#1146]
## Description

Link to fiddle may be outdated.

Click the link  on the readme at "Check out our live example if you're having trouble."

## Results

Video.js Example Embed

### Expected

Some clue about how to use this in combination with with videojs-quality-picker.
In particular, setting up the HLS variable/object so I can try the sample supplied in the README at https://github.com/streamroot/videojs-quality-picker

**Comment by gesinger** [comment]
Hey @HankBrown , the JS Bin referenced in the "Check out our live example if you're having trouble." part of our README is actually up-to-date. We don't usually include references to other plugins (and we don't actually manage https://github.com/streamroot/videojs-quality-picker ). We recommend that you ask there for an example on how to use it.
