### ISSUE TITLE
Start using the options passed to the sourceHandler functions

### ISSUE THREAD

**Issue by imbcmdth** [videojs/videojs-contrib-hls#1149]
## Description
Right now we only check `videojs.options` for several important properties - notably `hls.overrideNative`. This means that in order to set them, the options must be defined globally and impact all players. 

The source handler functions all receive a second argument that is the tech-level options object. We do properly use this in the constructor of the `HlsHandler` here: https://github.com/videojs/videojs-contrib-hls/blob/master/src/videojs-contrib-hls.js#L231 but we **don't** use it in any of the `HlsSourceHandler` functions defined here https://github.com/videojs/videojs-contrib-hls/blob/master/src/videojs-contrib-hls.js#L570-L606 !!

**Comment by gesinger** [comment]
https://github.com/videojs/videojs-contrib-hls/pull/1156
