### ISSUE TITLE
HLS Streams not Working on Windows Desktop Browsers

### ISSUE THREAD

**Issue by WaluTechnician** [videojs/videojs-contrib-hls#1154]
## Description
I'm trying to use Videojs-hls to deliver video from our site to all platforms. Here is a test page walukungfu.org/test2.html . I just get black screens on Windows desktop and on my new LG stylo 2. On my cell it only affects videos I'm trying to autoplay. I've been trying to use an MP4 fallback, but I'm having problems seeking through longer videos when i use MP4. Also, my data setup is including speed controls but none are showing up when the player uses M3U8.

## Sources
im using Video JS 1.17 
and Videojs-contrib-hls of course

## Steps to reproduce

I segmented my video with the following ffmpeg line:
ffmpeg -i 360p.mov -codec copy -vbsf h264_mp4toannexb -map 0 -f segment -segment_time 10 -segment_format mpegts -segment_list 360p/playlist.m3u8 -segment_list_type m3u8 360p/fileSequence%d.ts

I output it from Adobe Premiere with the standard H264/AAC encoding with a bitrate of 1.3 Mb/s

Here's my Video Setup:

                <script src="js/jquery-3.1.1.min.js"></script>
		<script src="js/video.js"></script>
		<script src="js/dash.all.min.js"></script>
		<script src="js/videojs-dash.js"></script>
		<script src="js/videojs-contrib-hls.js"></script>
		<script src="js/responsiveslides.js"></script>

                <div class="onehalf">
	          <video id="test" class="video-js vjs-default-skin vjs-16-9" data-setup='{ "playbackRates": [0.5, 1, 2, 4] }' poster="images/indexvidposter.png" controls>
	             <source src="images/indexvid/playlist.m3u8" type="application/x-mpegURL"/>
				
                      </video>
				<script>
                                var player = videojs('test');
                                    player.play();
                               </script>

                                  </div>

## Results

it works on mobile (except for my new LG stylo 2 when I try to use Autoplay) But not any Windows Desktop Browsers

### Error output
I get the "No Compatible Source Was Found For this Media" Error

**Comment by gesinger** [comment]
Hey @WaluTechnician , thanks for providing a sample page. I took a look and noticed that your `js/videojs-contrib-hls.js` just references the main file of the project, not the actual built project. Would you be able to update that reference and give it a shot again? Thanks.

**Comment by WaluTechnician** [comment]
Thank you for your prompt response, @gesinger 

I"m afraid I'm still quite novice, I loaded the VideoJS and HLS contrib with CDN and I'm not having issues with Playback anymore. I feel a bit silly...

I did run into something else though.

walukungfu.org/test3.html

I'm trying to use 
        data-setup='{ "playbackRates": [0.5, 1, 2, 3] }'

But it's only working on desktop. When I open it with Android Chrome I'm not getting the speed option on the controls. Is this something I'll have to go to the VideoJS git about?

Thank you for any help you can offer.

**Comment by gesinger** [comment]
No problem @WaluTechnician , glad to hear it helped. As for the playbackRates, yeah, that would be something outside of contrib-hls.

Going to close this issue for now. If you're still having trouble with any HLS features, please let us know. Thanks.

**Comment by WaluTechnician** [comment]
Hello again, @gesinger 

I eliminated a few variables and wanted to come back to you about the playbackRate issue for a moment.

I'm now running VJS 6.2.0 hosting it off my server, and still loading the HLS-contrib via CDN.

The playbackRate functions properly with MP4 sources on desktop and mobile, but when I try to use an M3U8 source it only works on Desktop. 

On Android Chrome v58 I'll see the option appear, but it does nothing when I select a different rate. 

I've brought this up over at the main Video JS git as well after gkatsev helped me get the playRate option to appear by reminding me to update my browser. 

I thought I would mention it to you here instead of opening another issue, since MP4 sources are working I thought it might have something to do with the HLS-contrib.

Thank you for your time.

**Comment by WaluTechnician** [comment]
Oh, here:

Walukungfu.org/test2.html
