### ISSUE TITLE
playbackRate option not working on mobile with .M3U8 Playlist

### ISSUE THREAD

**Issue by WaluTechnician** [videojs/videojs-contrib-hls#1157]
## Description
The option "playbackRate" isn't working properly on my Android Chrome Browser using an .M3U8 source. It will display the option and you can select a different rate, but it has no effect on the actual playback. It functions as intended on desktop browsers. 

This doesn't happen when using an MP4 source, though naturally because of how MP4 loads on mobile it doesn't last long till it has to buffer, but because it does function as intended with an MP4 source I thought it may be an issue with the Contrib-HLS 

## Sources

walukungfu.org/test2.html

I'm using h264 video and AAC audio in an Mpegts wrapper with an M3U8 playlist as created by this line with ffmpeg:

ffmpeg -i 360p.mov -codec copy -vbsf h264_mp4toannexb -map 0 -f segment -segment_time 10 -segment_format mpegts -segment_list 360p/playlist.m3u8 -segment_list_type m3u8 360p/fileSequence%d.ts

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

        <script src="js/jquery-3.1.1.min.js"></script>
		<script src="js/video.min.js"></script>
		<script src="https://unpkg.com/videojs-flash/dist/videojs-flash.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/5.5.3/videojs-contrib-hls.min.js"></script>

        <video id="test" class="video-js vjs-default-skin vjs-16-9" data-setup='{ "playbackRates": [0.5, 1, 2, 4] }' poster="images/indexvidposter.png" controls>
	
	<source src="images/indexvid/playlist.m3u8" type="application/x-mpegURL"/>
				
                </video>
	<script>
        var player = videojs('test');
        </script>

## Results

I see the option to change the playrate on mobile but it has no effect on the actual playback when I change it.

### Error output
No Error output, just no function

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
                <script src="https://unpkg.com/videojs-flash/dist/videojs-flash.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/5.5.3/videojs-contrib-hls.min.js"></script>

### videojs version
VideoJS version 6.2.0

### Browsers
Android Chrome v58

### Platforms
Lg Stylo 2 Android 6.0.1

### Other JavaScript

        <script src="js/responsiveslides.js"></script>

**Comment by gesinger** [comment]
Hey @WaluTechnician , Android Chrome should be using native playback for HLS, unless overrideNative is used (https://github.com/videojs/videojs-contrib-hls#overridenative). This means that if you're using native playback, the issue has to do with the Android Chrome browser, rather than videojs-contrib-hls.

If you can, try using overrideNative and see if playback rate changes as expected. Let us know if that helps.

**Comment by WaluTechnician** [comment]
I'm afraid I'm still quite novice at coding.

so my intitialization code will go from this:

        <script>
var player = videojs('test');
        </script>

to this:

        <script>
var player = videojs('test');
var options = {hls: {
  overrideNative: true;
videojs.options.html5.nativeAudioTracks: false;
videojs.options.html5.nativeVideoTracks: false;
}};
        </script>

yes?

Thanks, I'll try it now.

**Comment by WaluTechnician** [comment]
Thank you for being so prompt with your response, @gesinger 

I tried the initialization options I asked about in my previous comment and I'm getting no change in behavior.

walukungfu.org/test2.html

here's my code:

        `<video id="test" class="video-js vjs-default-skin vjs-16-9" data-setup='{ "playbackRates": [0.5, 1, 2, 4] }' poster="images/indexvidposter.png" controls>
	
	<source src="images/indexvid/playlist.m3u8" type="application/x-mpegURL"/>
				
                </video>
				<script>
    var player = videojs('test');
    var options = {hls: {
    videojs.options.hls.overrideNative = true;
    videojs.options.html5.nativeAudioTracks = false;
    videojs.options.html5.nativeVideoTracks = false;
    }};
    </script>`

Am I doing this wrong?

does it have anything to do with this:

https://github.com/videojs/videojs-contrib-hls/issues/403

?

Thanks for your help.

**Comment by mjneil** [comment]
@WaluTechnician You've got the right idea.

```
<script>
  // Set the HLS overrideNative option globally
  videojs.options.hls.overrideNative = true;
  // Player instance options
  var options = {
    html5: {
      nativeAudioTracks: false,
      nativeVideoTracks: false
    }
  };
  var player = videojs('test', options);
</script>
```

**Comment by gesinger** [comment]
Hey @WaluTechnician , have you had any luck with overrideNative?

**Comment by WaluTechnician** [comment]
Hey, @gesinger

Sorry, that got reprioritized and I forgot about it. Thank you for reminding me. 

Ill test it and let you know this evening so we can get to closing this.

**Comment by WaluTechnician** [comment]
@gesinger 

That did it!

Thank you @gesinger and @mjneil for your help. 

If you're ever in South Florida you've got a Kung Fu Class waiting for you.

**Comment by gesinger** [comment]
Thanks for the update @WaluTechnician , and we'll definitely have to take you up on that!
