### ISSUE TITLE
Open .m3u8 file as URL with user agent

### ISSUE THREAD

**Issue by Esteban555** [videojs/videojs-contrib-hls#1158]
On this player using Contrib HLS for my app is there a way to open a .m3u8 file just by doing the URL?
Or is there a way to open the file it self on the player?

Example:

I have this file:
#EXTINF:0,Canal America
#EXTVLCOPT:http-user-agent=iPhone
http://prepublish.f.qaotic.net/epa/ngrp:americatvlive-100056_all/Playlist.m3u8

If u copy paste the URL will not open unless you do the whole file with user agent.

Im all ears for the better way to open this file on the video.js player of my app.

Thank you

**Comment by gesinger** [comment]
Hey @Esteban555 , it looks like there's a special VLC related tag that mentions the user agent option in that playlist. Is this m3u8 meant only for playback on iPhones? We don't really look to override the user agent string on the player. Is that what you're looking for?

**Comment by Esteban555** [comment]
Hi there! Thank you for the reply. Im running a streaming app and only have the option to input a URL to play the .m3u8 in my app, so with that info on the .m3u8 file, how would i open it by just the URL, not just for iphones but it was a way to bypass that security. Any ideas im all ears.

**Comment by gesinger** [comment]
Hey @Esteban555 , trying to bypass the security via the client is generally something we want to avoid. Instead, it would be preferable to set up the server in such a way as to allow clients that need to be supported. If the security from the server says that the specific client shouldn't play it, we probably shouldn't play it.

**Comment by gesinger** [comment]
Closing. Please try modifying the server to allow the devices from which you are trying to play back your content. Thank you.

**Comment by Esteban555** [comment]
Thank you sir.

Any ideas wich method wll be better for the procedure you suggest
