### ISSUE TITLE
overrideNative doesn't affect iphone 7 chrome and safari

### ISSUE THREAD

**Issue by klimentLambevski** [videojs/videojs-contrib-hls#1159]
overrideNative doesn't affect iphone 7 chrome and safari. The option seems to have no effect on this browsers.

### videojs-contrib-hls version
I'm using the 5.5.3 version of videojs-contrib-hls

### videojs version
version 6.2.0

### Browsers
IOS safari latest, IOS chrome latest

### Platforms
IOS

**Comment by gesinger** [comment]
Hey @klimentLambevski , thanks for reporting. Right now iOS doesn't support media source extensions ( http://caniuse.com/#feat=mediasource ) which is required for us to override native functionality ( https://github.com/videojs/videojs-contrib-hls#overridenative ). Without MSE support, videojs-contrib-hls can't play HLS, so we continue to use native support. Once iOS supports MSE, we'll be able to override the native functionality.

**Comment by klimentLambevski** [comment]
@gesinger thanks for the quick answer. Can I control hls stream resolutions when hls tech es not available (trough html5 tech)? sorry for unrelated question to issue

**Comment by gesinger** [comment]
No problem @klimentLambevski .

As for HLS stream resolutions, we haven't found a way yet to manually change renditions in browsers with native playback, as the W3C spec doesn't yet define an API for it, and we haven't seen the native players providing separate APIs either.

There might be a way to get around that by having controls which set different sources on the player (and then tries to seek to the previous time), and I'm not positive but there might be plugins for videojs out there that do that already.

**Comment by klimentLambevski** [comment]
@gesinger thanks i will try that
