### ISSUE TITLE
AV drift after "Large timestamp gap detected" 

### ISSUE THREAD

**Issue by Tanyavdc** [videojs/videojs-contrib-hls#1163]
## Description

- Wowza encoded livestream experiences audio drift after watching for over 5 minutes when on Chrome or Firefox 
- Have tried increasing ```GOAL_BUFFER_LENGTH``` from 30 to 60 and noticed improvements in time before AV drift becomes noticeable 

### Error output

_media internals log :_

```Debug: Dropping audio frame which failed decode with timestamp: 604799666 us, duration: 21333 us, packet size: 235 bytes```

```Error: Large timestamp gap detected; may cause AV sync to drift. time:604821000us expected:604589666us delta:231334us```

```Debug: Detected an append sequence with keyframe following a non-keyframe, both with the same decode timestamp of 608.96```

``` VIDEOJS: ERROR: TypeError: Failed to execute 'remove' on 'SourceBuffer': The start provided (831.317) is outside the range (0, 830.523).```

```Debug: Detected an append sequence with keyframe following a non-keyframe, both with the same decode timestamp of 656.473```

```Debug: Audio buffer splice at PTS=662846000us. Trimmed tail of overlapped buffer (PTS=662826333us) by 1666us.```

### videojs-contrib-hls version
videojs-contrib-hls 5.5.3 

### videojs version
video.js 5.20.1

### Browsers
Chrome 58.0.3029.110 (64-bit)

Any guidance is appreciated

**Comment by mjneil** [comment]
Hi @Tanyavdc Thanks for reporting the issue. Would you be able to provide a reduced test case http://jsbin.com/vokipos/8/edit?html,output or provide a link to your stream?

**Comment by Tanyavdc** [comment]
Thanks for responding @mjneil 

In the process of putting up a test link, the issue went away, which makes me suspect that it is a WOWZA streamlocking issue. Any idea why the WOWZA token would cause AV drift?

**Comment by gesinger** [comment]
Not sure why it would cause that (not too experience with WOWZA), but we're happy to hear the issue went away. If it returns, please let us know, and thank you.
