### ISSUE TITLE
InvalidStateError calling endOfStream for broken source urls in Chrome

### ISSUE THREAD

**Issue by rishigohil** [videojs/videojs-contrib-hls#1164]
https://github.com/videojs/videojs-contrib-hls/issues/575

I am having the same issue. The video keeps on loading and does anyone know if we can handle this error from our end until we get support from the plugin? Or am I missing something?

![image](https://user-images.githubusercontent.com/5967748/27187507-637fbca8-51b9-11e7-83ae-705e50c64db6.png)

**Comment by gesinger** [comment]
Hey @rishigohil , I created a jsbin with that source here http://jsbin.com/nuqehab/1/edit?html,output and I don't see the error you are seeing. Would you be able to put together a jsbin based on that template that exhibits the error? Thanks.

**Comment by rishigohil** [comment]
Alright so turns out that it's the issue of videojs-contrib-hls.js version 5.3.3. It works fine with the CDN version of 5.5.3. I've updated the bin with my version of videojs-contrib-hls.js and it gives the error. Thanks. for the help though. 

http://jsbin.com/miguyaq/1/edit?html,js,output

**Comment by gesinger** [comment]
Thanks for the update @rishigohil , and glad to hear it's working.
