### ISSUE TITLE
Getting VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) on the example code when trying to init the player in js code.

### ISSUE THREAD

**Issue by sbalay** [videojs/videojs-contrib-hls#1169]
## Description
I'm having problems when trying to init my player in js code with the following method.
```js
    const player = videojs('my_video_1');
    player.src({
      src: 'http://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8',
      type: 'application/x-mpegURL'
    });
```
The link to the video is the same as in the example page, but I'm getting the error code 4, media not supported.

As you can see in [this](https://gist.github.com/sbalay/e080f885d2089be402221d092bd0685b) gist, I only changed two things:
- Removed the source from inside the `video` element
- Initialized the player in the `script` tag as described above.

Am I missing something? or is there anything wrong?
Thanks

<b>EDIT:</b>
The problem described above is only reproduced when using the chrome device simulator with nexus 5X.

## Sources
-----

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Copy and paste the example page from http://jsbin.com/vokipos/8/edit?html,console,output
2. Apply the changes described above in the issue description
3. See that the player is not loading and an error is thrown in the console

### Expected
The video to start after calling to `player.src( ... )`

### Error output
```
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 
```

## Additional Information
----

### videojs-contrib-hls version
v5.5.3

### videojs version
v6.2.0

### Browsers
* Chrome 58.0.3029.110 (64-bit)

### Platforms
* MacOS Sierra 10.12

### Other Plugins
No

### Other JavaScript
No

**Comment by sbalay** [comment]
I've found something a little strange.
If I took the code in the example page, and only add this:
```
  <script>
    const a = videojs('my_video_1');
  </script>
```
The example will still work, unless the chrome dev tools are open.
If the dev tools are closed, the example works. If the dev tools are open the following error will appear:
```
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 
```

**Comment by gesinger** [comment]
Thanks for updating @sbalay , as you noticed, the simulator is the cause of the problem. This is because the Chrome device simulator does not simulate all aspects of the device needed for playback (see https://developers.google.com/web/tools/chrome-devtools/device-mode/emulate-mobile-viewports#limitations for reference).

Please give it a shot with a real device, and if you are still seeing problems there (or with any desktop browsers), please let us know. Thanks.

**Comment by jinagko** [comment]
I'd the same problems

**Comment by camille666** [comment]
me too.
