### ISSUE TITLE
This m3u8 link only work in apple devices

### ISSUE THREAD

**Issue by beautylix** [videojs/videojs-contrib-hls#1170]
## Description
Briefly describe the issue.
Some links work well, but some do not work, for example: http://hls.playlive.360.v.btime.com/live_btime/btv_sn_20170208_s6/index.m3u8 , this link only works on apple devices, I tested it on iphone, it works well, but it does not work on windows

## Sources
http://hls.playlive.360.v.btime.com/live_btime/btv_sn_20170208_s6/index.m3u8

## Steps to reproduce
1. put this link in your videojs player
2. Play in browsers such as firefox, chrome on windows, it does not work, 
3. Go go iphone or other apple devices, play it, it works well

### Error output
HLS playlist request error at URL: http://hls.playlive.360.v.btime.com/live_btime/btv_sn_20170208_s6/index.m3u8 shows on chrome
Only a cross symbol on firefox

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
The lastest version, I just downloaded today

### videojs version
what version of videojs does this occur with?
video.js 5.11.0

### Browsers
what browsers are affected? please include browser and version for each
Firefox, chrome

### Platforms
what platforms are affected? please include operating system and version or device and version for each
Windows

**Comment by mister-ben** [comment]
You're missing CORS headers. iOS has native HLS support so does not need CORS headers.

https://github.com/videojs/videojs-contrib-hls#hosting-considerations

**Comment by gesinger** [comment]
Thanks for answering @mister-ben . @beautylix , please try adding CORS headers to your stream and give it another shot. If you notice any problems after that, please let us know with a new issue. Thank you.
