### ISSUE TITLE
In your own demo, captions do not work in Microsoft Edge

### ISSUE THREAD

**Issue by mattbrundage** [videojs/videojs-contrib-hls#1177]
## Description
In your own demo (https://videojs.github.io/videojs-contrib-hls/), captions do not work in Microsoft Edge.

## Steps to reproduce

1. Go to the demo page in Microsoft Edge: https://videojs.github.io/videojs-contrib-hls/
2. Hit play

### Expected
The caption icon/menu should appear when the stream starts. The user should be able to select a caption.

### Error output
There are no console errors relevant to this issue.

## Additional Information
I figured that this should work in your demo before I try to diagnose the same issue in my own project.

### videojs-contrib-hls version
videojs-contrib-hls 5.6.0

### videojs version
video.js 6.1.0

### Browsers
* Microsoft Edge

### Platforms
* Windows 10

### Other Plugins
* videoJS Flash

### Other JavaScript
* jQuery 1.11.2

**Comment by treyhoover** [comment]
We're experiencing the same thing and were able to re-produce the issue in your demo on MS Edge 16.

Any idea what the issue may be? I'd be happy to help track this down.

**Comment by mattbrundage** [comment]
I'm not sure what's happening. I do know that Edge supports these features natively, so perhaps there's some buggy feature-detection going on.

**Comment by triwav** [comment]
In case nobody's tried it, I tried forcing Flash on Edge and that doesn't appear to be working either. The only solution I have currently is telling Edge users to use IE11 as captions do work correctly there if you force Flash. Might be worth noting this is for Webvtt captions. It's possible CEA608 captions would work correctly.

**Comment by squarebracket** [comment]
The native HLS playback in Edge doesn't support captions. I use these configurations settings for Edge and Android, to ensure feature parity across all browsers:
```
var config = {};
if (videojs.browser.IS_EDGE || videojs.browser.IS_ANDROID) {
  config = {
    html5: {
      hls: {
        overrideNative: true
      },
      nativeAudioTracks: false,
      nativeVideoTracks: false,
      nativeCaptions: false
    }
  }
}
```

Try it out here: http://jsbin.com/juvixaf/edit?html,output

The demo page does not include this config stanza.

**Comment by triwav** [comment]
Thank you @squarebracket! I had a feeling that was what was going on. @mattbrundage comment made it seem like this feature was built in and was about to test that out when you replied. Really appreciate your help.

**Comment by squarebracket** [comment]
No problem, glad to help.

**Comment by mattbrundage** [comment]
@squarebracket, based on my tests, the native HLS playback in Edge **does** support captions.

Attached image: Edge handling captions in its native video player. **(No JavaScript.)** I'm almost certain that this HLS stream is using 608 over 708, rather than WebVTT.

![edge-native-hls](https://user-images.githubusercontent.com/1263178/33078939-35ae8a14-cea2-11e7-9df1-4f3f25d742a5.png)

**Comment by squarebracket** [comment]
Hmm. You're right; playing the BipBop feed in Edge does show all captions. I'll have to take a look into this when I get a moment.
