### ISSUE TITLE
Bug with audio in live stream

### ISSUE THREAD

**Issue by bklava** [videojs/videojs-contrib-hls#1181]
## Description

We are experiencing problems with the audio of an HLS live stream. In desktop browsers we cannot hear any audio. In Android Chrome  the audio does not play unless setting `videojs.options.hls.overrideNative = true`

Reduced test case: http://jsbin.com/fifuco/

## Sources

http://138.121.70.32/vod/ocp(t(FMwMt1lOK5c.)r(uOajMg..)a(s3HiUQ..)p(d(tD4.)k(RBE.)m(16V4KGwW3Gdwh0XictReXw..)n(a(vDQv7A..)s(eIE.)'a(lkhQiQ..)s(0hQ.)))s(s(rd4.)b(Xb93y-0ddqQ6IjAwP6AB9AIfAvjpCr54n7Z__SDcUoyNm8V7mqHKxmYJ)'s(N1I.)b(R65Ir1qQsJqGSM2gj9W5eV6wUkWuMkHiQgOlJkr4DSIQ)'s(ZkQ.)b(1kHiLBIxdQ..))m(0))/prog_index.m3u8

## Steps to reproduce
Just use the reduced test case: http://jsbin.com/fifuco/

### Expected
To hear the audio in desktop browsers 

## Additional Information
I'll keep the live stream up as long as necessary. A source of sound or noise will always be available, even when there is nobody in the office ;)

### videojs-contrib-hls version
videojs-contrib-hls 5.7.0

### videojs version
video.js 5.20.1

### Browsers
* Chrome / Firefox

### Platforms
* Windows 10 / Ubuntu 17.04

**Comment by bklava** [comment]
Ooops, my bad. Fixed. Can you try it again?

**Comment by mjneil** [comment]
It looks like your audio stream is [stream type 3](https://en.wikipedia.org/wiki/Program-specific_information#Elementary_stream_types), the mp3 audio layer, which we don't support. If you can encode your stream using the stream type 15 for ADTS AAC, the audio should work

**Comment by bklava** [comment]
Yep, that solved our issue. Thanks @mjneil for the quick feedback ;)
