### ISSUE TITLE
how can I do video snapshot in js

### ISSUE THREAD

**Issue by cppbitman** [videojs/videojs-contrib-hls#1182]
Hi,
recently, I have a job to do video snapshot streaming by HLS using video tag of videojs-contrib-hls. The key code is as follows:

`var canvas=document.getElementById('canvas');
var context=canvas.getContext('2d');
var video=document.getElementById('videoPlayer');
alert(video);
context.drawImage(video,0,0,video.clientWidth, video.clientHeight);`
 
It has failed. I find that element type of video is HTMLDivElement, but not HTMLVideoElement.

Then for comparison, I use video tag of HTML5 to do snapshot of a local .mp4 file. 
It succeeds. The element type of video is HTMLVideoElement.

So I guess that video in videojs-contrib-hls has been encapsulated.  
I have tried a lot but failed to get HTMLVideoElement in videojs-contrib-hls.

So how can I do snapshot with videojs-contrib-hls in a similar way as pure html5? 
Can anybody help me !
Thanks a lot.

**Comment by mlumbroso** [comment]
Hi,

you have to get the video element inside, since that's how video.js transforms it :
`var video=document.querySelector('#videoPlayer video');`

You should be fine with this :)

**Comment by cppbitman** [comment]
It works. Thanks a lot.
