### ISSUE TITLE
Loop enabled videos don't seem to cache first segments when reaching end of video

### ISSUE THREAD

**Issue by pandaiolo** [videojs/videojs-contrib-hls#1183]
## Description

With loop enabled, the first segments of the video don't seem to get reloaded before the first play ends. Not sure if this is the reason, but the video stalls a few moments before playing again.

## Steps to reproduce

    <video loop ... />

### Expected

When looping, the video should play again without stalling.

### Version 
videojs-contrib-hls 5.5.3
video.js 5.20.1

### Browsers
Chrome OSX Version 58.0.3029.110 (64-bit)

### Platforms
OSX 10.12.5

### Other Plugins
none

### Other JavaScript
react and tons of deps

**Comment by forbesjo** [comment]
Moving this enhancement to VHS
