### ISSUE TITLE
How to work with webpack and video.js v6.2.0 ?

### ISSUE THREAD

**Issue by zcoding** [videojs/videojs-contrib-hls#1188]
## Description
I tried to play a m3u8 video, but failed.
```
CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED
```
I don't know why

## Sources
my webpack configuration:
```json
{
  ...
  "resolve": {
    "alias": {
      "webworkify": "webworkify-webpack-dropin"
    }
  }
}
```
```html
<div data-vjs-player>
  <video id="player-wrapper"></video>
</div>
```
```javascript
import VideoJS from 'video.js'
require('videojs-flash')
import * as HLS from 'videojs-contrib-hls'

const options = {
  sourceOrder: true,
  techOrder: ['html5', 'flash'],
  html5: {
    hls: {
      withCredentials: true
    }
  },
  flash: {
    hls: {
      withCredentials: true
    }
  }
}

VideoJS('player-wrapper',  options, function ready() {
  this.src({
    src: 'myM3U8file',
    type: 'application/x-mpegURL',
    withCredentials: true
  })
  this.play()
})
```

## Steps to reproduce

1. install video.js, videojs-contrib-hls, videojs-flash and webworkify-webpack-dropin from npm
2. see sources above
3. build with webpack and run
4. not working...

### Expected
Have fun!

### Error output
```
CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED
```

### videojs-contrib-hls version

videojs-contrib-hls 5.7.0

### videojs version

video.js 6.2.0

### Browsers
Chrome latest

### Platforms
macOS Sierra

### Other Plugins
no...

### Other JavaScript
no...

**Comment by zcoding** [comment]
ok, i give up. i think it still has a long long long way to be compatible with webpack...

**Comment by h94** [comment]
Have the same problem

**Comment by gesinger** [comment]
Hey guys, sorry you are having trouble with webpack and videojs-contrib-hls. Some people have found success with webpack in https://github.com/videojs/videojs-contrib-hls/issues/600 . Please give some of those strategies a shot. I'm going to close this issue in favor of the other.
