### ISSUE TITLE
Cannot read property 'xhr' of undefined

### ISSUE THREAD

**Issue by nhatdev1193** [videojs/videojs-contrib-hls#1192]
Hello everyone and thanks for you offering help.  I tried to send Headers into the videojs.Hls.xhr.beforeRequest function, so I implement:
`<script src="http://vjs.zencdn.net/6.2.0/video.js"></script>`
`<script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/5.8.0/videojs-contrib-hls.min.js"></script>`

`var player = videojs('my-video')`
 ```
player.hls.xhr.beforeRequest = function(options) {
        options.headers['X-User-Id'] = 'nhat';
        console.log(options);
        return options;
      };
```
```
 player.src({
        src: 'http://localhost:3000/video',
        type: 'video/mp4',
        withCredentials: true
      });
```
But it seen, player.hls is underfined :cry: Plese help me fix this error,
Regards.

**Comment by mjneil** [comment]
`player.hls` is setup after the source selection process and the hls source handler is created. Since setting the source is asynchronous in videojs 6, I think the best way to do this is to set the global override for `beforeRequest`. Note that this will affect all videojs players on the page, so if you have multiple players on one page that need different `beforeRequest` you'll have to go with another approach

```
videojs.Hls.xhr.beforeRequest = function(options) {
  options.headers['X-User-Id'] = 'nhat';
  console.log(options);
  return options;
};
var player = videojs('my-video')
player.src({
  src: 'http://localhost:3000/video',
  type: 'video/mp4',
  withCredentials: true
});
```

**Comment by m2008m1033m** [comment]
@mjneil What if I wanted to have different headers for different player instances? A global beforeRequest function will force me to have the same header for all players, which is not always the case.

**Comment by mjneil** [comment]
@m2008m1033m You can still set `beforeRequest` on a per-player basis, it just needs to be set after calling `player.src`. One downside to that is if you require changing the headers for the initial manifest request, it may already be too late to set the function after calling `src`. One idea for a workaround for that would be define all your unique `beforeRequest` functions, then set a global `beforeRequest` that will attach the custom player specific `beforeRequest` functions to each player on the page. Outside of that, changes to the source code would have to be made to allow passing in a `beforeRequest` as a player or source option, or some other way to set the function before the first request is made
