### ISSUE TITLE
Update documentation and demo page to always override native functionality

### ISSUE THREAD

**Issue by forbesjo** [videojs/videojs-contrib-hls#1193]
We have had many reported issues with IE11 Windows 10/8.1, Edge and Mobile Chrome. Most of these can be resolved by adding it to the getting started documentation.

Something like:
```js
videojs.options.hls.overrideNative = true;
videojs.options.html5.nativeAudioTracks = false;
videojs.options.html5.nativeTextTracks = false;

var player = videojs('playerId');
player.src(source);
```

Ideally videojs-contrib-hls should do this automatically and not require user set up.

**Comment by samueleastdev** [comment]
We have had issues when setting overrideNative from Safari users.

I am not sure it is the best option for every situation just from our experience leaving native take over has resolved problems. I agree it would be great to have it set as default but is it granted to work in every scenario?

**Comment by forbesjo** [comment]
Yes we would continue to defer to native playback on Safari. We have not seen problems with this setup on other browsers.

**Comment by samueleastdev** [comment]
ok, thanks @forbesjo good to know ;)

**Comment by samueleastdev** [comment]
Hi @forbesjo,

So would you suggest doing this until it has been imlemented?

```
if (!navigator.userAgent.match(/iPhone|iPad|iPod/i)) {
    videojs.options.hls.overrideNative = true;
    videojs.options.html5.nativeAudioTracks = false;
    videojs.options.html5.nativeTextTracks = false;
}

```

**Comment by forbesjo** [comment]
I would suggest using `!videojs.browser.IS_ANY_SAFARI` but yes I suggest that for now
