### ISSUE TITLE
Reloading fmp4 segments after playlist update

### ISSUE THREAD

**Issue by Okapist** [videojs/videojs-contrib-hls#1200]
## Description
VideoJS-HLS reloading fmp4 segments after updating m3u8 playlist on live translation.

Old playlist:
```
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-TARGETDURATION:3
#EXT-X-MAP:URI="M1.mp4"
#EXT-X-MEDIA-SEQUENCE:581
#EXTINF:3.0000
M1-581.fmp4
#EXTINF:3.0000
M1-582.fmp4
#EXTINF:3.0000
M1-583.fmp4
#EXTINF:3.0000
M1-584.fmp4
#EXTINF:3.0000
M1-585.fmp4
```

New playlist:
```
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-TARGETDURATION:3
#EXT-X-MAP:URI="M1.mp4"
#EXT-X-MEDIA-SEQUENCE:582
#EXTINF:3.0000
M1-582.fmp4
#EXTINF:3.0000
M1-583.fmp4
#EXTINF:3.0000
M1-584.fmp4
#EXTINF:3.0000
M1-585.fmp4
#EXTINF:3.0000
M1-586.fmp4
```

Reloaded segments:
![reload](https://user-images.githubusercontent.com/14182163/28280682-2e69c986-6b2d-11e7-8f90-fbf25d0c8a2e.png)

**Comment by mjneil** [comment]
Thanks for reporting this @Okapist Could you provide some more info like Videojs version, videojs-contrib-hls version, browser, os? If its possible for you to provide a source or a reduced test case in jsbin, that would be very helpful

**Comment by Okapist** [comment]
Yes. 

I'm using VideoJS-HLS from [demo](http://videojs.github.io/videojs-contrib-hls/) page.
Browser: Firefox 54.0.1 64 bit
OS: Windows 10

Make test page is difficult. It's live stream from web camera with video server made by me (video server based on [this](https://github.com/sannies/mp4parser) project. I may attach init.mp4 and some fmp4 parts if needed.

**Comment by gesinger** [comment]
Hey @Okapist , are you still experiencing this issue? And is the player re-requesting some fmp4 segments, or you're just seeing the live playlist updating?

**Comment by gesinger** [comment]
Closing for now. If you are still experiencing this issue with the latest version of videojs-contrib-hls, please let us know (and provide a test stream if possible). Thank you.
