### ISSUE TITLE
Aspect ratio changing after first chunk playback

### ISSUE THREAD

**Issue by ChoOo7** [videojs/videojs-contrib-hls#1202]
## Description
My source video is square
MP4 : 
https://damdy-dam-videos-pad.brainsonic.com/dam/20170718-144907-5638b245/output_1.mp4
HLS : 
https://damdy-dam-videos-pad.brainsonic.com/dam/20170718-144907-5638b245/hls_1/main_stream_multistream.m3u8

When I play HLS with videoJS, after the first chunk (in the middle of this short video), the video ratio change
http://jsbin.com/cebocaqapo/1/edit?html,output
OK : 
![image](https://user-images.githubusercontent.com/4919397/28406006-0173c4be-6d2f-11e7-8f7f-e185709aeab7.png)

Not OK : 
![image](https://user-images.githubusercontent.com/4919397/28406024-12105260-6d2f-11e7-8cd2-430072e43fc4.png)

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
Bug reproduced with videojs-contrib-hls-5.2.0 & 5.8.2

### videojs version
videojs 5.15

### Browsers
Google Chrome | 59.0.3071.115 (Build officiel) (64 bits) under linux, but on other tbrower too

### Other JavaScript
Cf http://jsbin.com/cebocaqapo/1/edit?html,output
minimal example is bugged !

**Comment by gesinger** [comment]
Hey @ChoOo7 , thanks for providing the sample source. I believe this is an issue with the source itself, as if you play it in Safari (just copying and pasting the URL into the address bar) it will behave the same (changing aspect ratio). If you open the m3u8 and look at the segments from different renditions, you can also see this. For instance:

https://damdy-dam-videos-pad.brainsonic.com/dam/20170718-144907-5638b245/hls_1/main_stream_610k-00000.ts

from the 610k rendition behaves as you expect (expected aspect ratio). However,

https://damdy-dam-videos-pad.brainsonic.com/dam/20170718-144907-5638b245/hls_1/main_stream_4550k-00000.ts

from the 4550k rendition (same segment) has the stretched aspect ratio.

Hope this helps!

**Comment by ChoOo7** [comment]
Thanks  !
In vlc no issue, but definitivly the issue seems to be on source !
