### ISSUE TITLE
How is always in live mode

### ISSUE THREAD

**Issue by eightHundreds** [videojs/videojs-contrib-hls#1204]
I use ffmpeg to encode multiple files(the file will continue to increase)to generate * .m3u8, so my m3u8 will always be updated. According to my observation, if m3u8 does not end with `# EXT-X-ENDLIST`, it will be in live mode, but this Case `# EXT-X-ENDLIST` will always exist.
Is there any way to make the player always live mode?

**Comment by tchakabam** [comment]
@eightHundreds i don't think so. that would be against the standard. the player is supposed to behave depending on what the playlist advertises.

you should figure out how to generate a proper live playlist if your content is live. so it will also work with any player without any special settings :)

**Comment by gesinger** [comment]
@tchakabam is right. In order to follow the spec, we only want to allow a playlist to be LIVE if there is no `EXT-X-ENDLIST` present. Closing since this follows the spec, but definitely check your encoder, as there should be a way for it to not include an `EXT-X-ENDLIST` until the stream is over.
