### ISSUE TITLE
i want to log which hls profile/chunk is playing right now

### ISSUE THREAD

**Issue by rahulsingh9096806080** [videojs/videojs-contrib-hls#1208]
Actually i need to log the video hls profile current playing.I have p1 to p5 profile which depends on quality.
Want to log these details along with chunk

**Comment by mjneil** [comment]
You can use the [Segment Metadata text track](https://github.com/videojs/videojs-contrib-hls#segment-metadata) to get information about the segment currently being displayed. The active cue will contain the playlist uri which you can use with the [representations or qualityLevels api](https://github.com/videojs/videojs-contrib-hls#hlsrepresentations) to get additional information about the playlist

**Comment by rahulsingh9096806080** [comment]
@mjneil..i am having single hls video. from that i want to extract the chunks which we can see in network tab of devloper tool.can you help me out

**Comment by mjneil** [comment]
Yes the [Segment Metadata track](https://github.com/videojs/videojs-contrib-hls#segment-metadata) will give you this information. The track is populated with cues where each cue represents the segment loaded into the buffer at the time of the cue. So while playing the video, the active cue in this track will have information about the segment currently being played on screen.

**Comment by mjneil** [comment]
Here is an example of using the segment metadata track to log info about the current playing segment
http://jsbin.com/fuqelosavi/edit?html,output

**Comment by rahulsingh9096806080** [comment]
@mjneil can you give youe email id show that i can contact you.code snippet is as follows
'onVideoPlay': function (scope) {
      scope.player.on('play', function (e) {
        var textTracks = scope.textTracks();
        console.log(textTracks) ;// its working upto here.
          textTracks.on('addtrack', function (event) {
          var track = event.track;
          if (track.label === 'segment-metadata') {
            track.on('cuechange', function () {
              var activeCues = track.activeCues;
              for (var i = 0; i < activeCues.length; i++) {
                console.log(activeCues[i].value);
              }
            });
          }
        });

        console.log('video is playing' + scope.durationPlayed());
       

      });
    }

**Comment by mjneil** [comment]
It's possible the track is already created and added at this point. You could try searching for it first and if it's not there, add the listener. Try something like this

```
'onVideoPlay': function (scope) {
  scope.player.on('play', function (e) {
    var textTracks = scope.player.textTracks();
    console.log(textTracks) ;// its working upto here.
    var i, metadaTrack;

    for (i = 0; i < textTracks.length; i++) {
      if (textTracks[i].label === 'segment-metadata') {
        metadataTrack = textTracks[i];
        break;
      }
    }

    if (metadataTrack) {
      metadataTrack.on('cuechange', function () {
        var activeCues = metadataTrack.activeCues;
        for (i = 0; i < activeCues.length; i++) {
          console.log(activeCues[i].value);
        }
      });
    } else {
      textTracks.on('addtrack', function (event) {
        if (event.track.label === 'segment-metadata') {
          metadataTrack = event.track;
          metadataTrack.on('cuechange', function () {
            var activeCues = track.activeCues;
            for (i = 0; i < activeCues.length; i++) {
             console.log(activeCues[i].value);
            }
          });
        }
      });
    }
  });
}
```

**Comment by rahulsingh9096806080** [comment]
if (textTracks[i].label === 'segment-metadata') 
here it is the issue. always false

**Comment by mjneil** [comment]
Are you able to setup a code example with our starter template http://jsbin.com/vokipos/8/edit?html,output that shows the behavior you are seeing?

**Comment by rahulsingh9096806080** [comment]
Hi,
on mobile devices i am not gettig details..

**Comment by mjneil** [comment]
Both Android and iOS support native HLS playback, so this track will be unavailable in native playback as there is no API currently to get this type of information natively. 

You can override the native HLS playback with videojs-contrib-hls in Android by following the instructions [here](https://github.com/videojs/videojs-contrib-hls#overridenative). MSE is not supported in iOS however, so this information is unavailable in iOS

**Comment by rahulsingh9096806080** [comment]
can you make changes for that...in the demo

**Comment by gesinger** [comment]
Hey @rahulsingh9096806080 , you can see details on usage at https://github.com/videojs/videojs-contrib-hls#initialization . 

If you are still having issues with the latest version of videojs-contrib-hls and using https://github.com/videojs/videojs-contrib-hls#overridenative please let us know.

Thank you.
