### ISSUE TITLE
How to use adaptive playback of hls?

### ISSUE THREAD

**Issue by KingHorse2015** [videojs/videojs-contrib-hls#1215]
How do I use adaptive streaming? Just adding multiple video source in between the video tags?

Thanks in advance

Greetz,
King Horse

**Comment by gesinger** [comment]
Hey @KingHorse2015 , this is a longer question that is better served by the HLS specification at https://tools.ietf.org/html/draft-pantos-http-live-streaming-23 , specifically, section 4.3.4.2 https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.4.2 , however, the short version is that HLS uses a manifest file called an m3u8 that points at different variants (renditions) of the content, which themselves are m3u8 manifests that point to the segments. The m3u8 files are provided as the source of the video tags.

It is useful to look at some example m3u8 files, e.g., http://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8 to see their structure. There are also probably some shorter tutorials online describing how to create HLS content, however, the spec itself is quite descriptive.

Hope this helps!
