### ISSUE TITLE
Support mp3 audio 

### ISSUE THREAD

**Issue by Okapist** [videojs/videojs-contrib-hls#1218]
## Description
2 years ago there was pull request to support mp3 audio.
mp3 audio is still not working and pull request is closed.
May be reopen and merge?

## Sources
[https://github.com/videojs/videojs-contrib-hls/pull/214](https://github.com/videojs/videojs-contrib-hls/pull/214)

**Comment by DullSky** [comment]
i want this too

**Comment by GerardVirga** [comment]
Echoing more support a resolution to this issue - see my comments on #214

**Comment by mjneil** [comment]
We don't currently have any plans to support mp3 audio and I don't see that changing anytime in the near future. #214 is a very old PR, and the code that it changes now lives in https://github.com/videojs/mux.js 

If anyone is interested in updating #214  to be compatible with latest and opening a new pr to mux.js, we can consider pulling in mp3 support
