### ISSUE TITLE
Problems with Vue.JS

### ISSUE THREAD

**Issue by manuliner** [videojs/videojs-contrib-hls#1222]
## Description
Hello,  
i have issue to get videojs-contrib-hls running with Vue.js
here is my code example:
```
<template>
  <div class="video-player">
    <video id=example-video class="video-js vjs-default-skin" controls/>
  </div>
</template>

<script>
  import videojs from'video.js'
  import videojsHLS from 'videojs-contrib-hls'

  export default {
    name: 'video-player',
    props: {
      options: {
        type: Object,
        required: true
      }
    }, components: {},
    mounted() {
      var player = videojs('example-video')

      player.ready(function () {
          player.src({
              src: "http://10.42.0.12/postprotool.next/1_encoder_out/saal_11/un/METAENC02_2017-04-29-07-08-33.m3u8",
              type: "application/x-mpegURL",
              withCredentials: true
            }
          )
        }
      )
    }
</script>
```

## Sources
vue 2.3.3
videojs 5.19.2
videojs-contrib-hls 5.8.2

## Steps to reproduce

1.
2.
3.

### Results
results should be a running HLS Stream

### Error output
```
VIDEOJS: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at module.exports (index.js?3063:10)
    at new MasterPlaylistController (master-playlist-controller.js?f4bf:363)
    at HlsHandler.src (videojs-contrib-hls.js?0a95:363)
    at Object.handleSource (videojs-contrib-hls.js?0a95:675)
    at Html5._Tech.setSource (tech.js?d5ea:1354)
    at Player.techCall_ (player.js?bc10:1690)
    at Player.eval (player.js?bc10:2424)
    at Player.ready (component.js?5748:841)
    at Player.src (player.js?bc10:2417)
player.js?bc10:1694 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at module.exports (index.js?3063:10)
    at new MasterPlaylistController (master-playlist-controller.js?f4bf:363)
    at HlsHandler.src (videojs-contrib-hls.js?0a95:363)
    at Object.handleSource (videojs-contrib-hls.js?0a95:675)
    at Html5._Tech.setSource (tech.js?d5ea:1354)
    at Player.techCall_ (player.js?bc10:1690)
    at Player.eval (player.js?bc10:2424)
    at Player.ready (component.js?5748:841)
    at Player.src (player.js?bc10:2417)
```
### Browsers
Chrome  59.0.3071.115
*

### Platforms
Win 10
*

*

**Comment by gesinger** [comment]
Hey @manuliner , I haven't used Vue.js myself, but is `id=example-video` proper syntax for an ID?

**Comment by YGLau** [comment]
the same as you @manuliner  :(

**Comment by GitZy1821411611** [comment]
hey，friend，Has the problem been solved?

**Comment by manuliner** [comment]
yes i did


`<template>
  <div>
    <video-player
      id="myPlayer"
      class='video-player-box'
      :options='playerOptions'
      customEventName='customstatechangedeventname'
      @play='onPlayerPlay($event)'
      @pause='onPlayerPause($event)'
      @statechanged='playerStateChanged($event)'
      @ready='playerReadied'>
    </video-player>
  </div>
</template>

<script>
  import { videoPlayer } from 'vue-video-player'

  require('video.js/dist/video-js.css')
  require('vue-video-player/src/custom-theme.css')
  require('videojs-contrib-hls/dist/videojs-contrib-hls')

  export default {
    components: {
      videoPlayer
    },
    data () {
      return {}
    },
    methods: {
      onPlayerPlay (player) {
        // console.log('player play!', player)
      },
      onPlayerPause (player) {
        // console.log('player pause!', player)
      },
      playerStateChanged (playerCurrentState) {
        log.debug('player current update state', playerCurrentState)
      },
      playerReadied (player) {
        this.player = player
        if (this.player.readyState() < 1) {
          this.player.one('loadedmetadata', function () {
            let hls = player.tech({IWillNotUseThisInPlugins: true}).hls
        })
      }
    }
  }
</script>
`

and this are my player options

playerOptions: {
        muted: false,
        controls: false,
        controlBar: false,
        language: 'en',
        fluid: true,
        preload: 'auto',
        playbackRates: [0.7, 1.0, 1.5, 2.0],
        sources: [ {
            src: 'pathTom3u8',
            type: 'application/x-mpegURL'
        }],
        flash: {
          hls: {
            withCredentials: false
          }
        },
        html5: {
          hls: {
            withCredentials: false
          }
        }
}

**Comment by GitZy1821411611** [comment]
@manuliner  thanks very much

**Comment by YGLau** [comment]
@GitZy1821411611 I have been changed for using hls.js.

**Comment by jonasgroendahl** [comment]
I'm also having trouble getting this to work with VueJS using webpack. What did you exactly @manuliner to get it working?

It will work if I put the cdn of .js files in the html index file but will stop working when i leave the page and go back so I have to get the setup right with webpack.

Code:

import videojs from 'video.js'
import *  as HLS from 'videojs-contrib-hls'


error:
index.js?f68e:10 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at module.exports (index.js?f68e:10)
    at new MasterPlaylistController (master-playlist-controller.js?b41a:314)
    at HlsHandler.src (videojs-contrib-hls.js?260d:335)
    at Object.handleSource (videojs-contrib-hls.js?260d:623)
    at Html5._Tech.setSource (video.cjs.js?0e26:9000)
    at new Html5 (video.cjs.js?0e26:16502)
    at Player.loadTech_ (video.cjs.js?0e26:19215)
    at Player.src_ (video.cjs.js?0e26:20828)
    at eval (video.cjs.js?0e26:20775)

**Comment by ddereszewski** [comment]
Take a look at solution provided by @lionxcr. It helped me 
https://github.com/videojs/videojs-contrib-hls/issues/600#issuecomment-273289790

**Comment by manuliner** [comment]
@jonasgroendahl 
please check my comment above.  There i posted my code which solved that issue for me

**Comment by Jayant-Purohit** [comment]
@manuliner is it working in production too? 
- I'm using ".m3u8" it works fine in dev mode but it throws an error in production 
error in production :
 `video.cjs.js:450 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. lt {code: 4, message: "No compatible source was found for this media.`

options for the player it looks like this : 
`            playerOptions: {
              height: '360',
            //  autoplay: true,
            //  muted: true,
            //  language: 'en',
            //  playbackRates: [0.7, 1.0, 1.5, 2.0],
              sources: [{
                type: "application/x-mpegURL",
                src: "",
              }],
              controlBar:{
                timeDivider: false,
                durationDisplay: false
              },
              html5: {hls:{withCredentials: false},
              hlsjsConfig: {
                debug: true
              },
              },
              poster:''
            },`
