### ISSUE TITLE
Chrome for iOS and playsinline: frame freezes

### ISSUE THREAD

**Issue by denisvlr** [videojs/videojs-contrib-hls#1224]
## Description
On Chrome for iOS, when playsinline is set, the video freezes. The sound runs correctly but the image stays stuck on the first frame. If you tap on play/pause, the frame refreshes, but you don't get a fluid playback. If you go fullscreen, the video plays correctly.
See sample here:
https://codepen.io/anon/pen/zdZawr

This is a big problem for us since the whole point of our app is to play videos inline. Any idea why this happens or how can we fix it? 
Thanks.

## Sources
Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.

## Steps to reproduce
Open the following link on the chrome app on a iOS >= 10 device: https://codepen.io/anon/pen/zdZawr

### Expected
Please describe what you expected to happen that did not happen in the description.

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
tested on videojs-contrib-hls 5.8.3 (but I think it happens on any version)

### videojs version
tested on video.js 6.2.4 (but I think it happens on any version)

### Browsers
chrome for iOS tested on:
* 58.03029.83
* 59.0.3071.102

### Platforms
iOS, tested on 10.3.2

### Other Plugins
None

### Other JavaScript
None

**Comment by gesinger** [comment]
Hey @denisvlr , is this something you see with just HLS sources, or is it replicable with an MP4 source as well?

**Comment by denisvlr** [comment]
So it looks like the bug doesn't appear anymore on Chrome 60.
I guess it was a browser bug, we can close until someone manages to reproduce.
