### ISSUE TITLE
Video Events aren't firing on Android. What am I doing wrong?

### ISSUE THREAD

**Issue by jeffmikels** [videojs/videojs-contrib-hls#1229]
Simple question...

After creating the videojs player with a stream src set to a m3u8 file, the video plays correctly, but I get no events to fire.

	var player = videojs('#player');
	player.play();
	player.on('playing', function() {stop_slideshow(); $el.fadeIn();});
	player.on('ended', function() {console.log('ended')});

Neither of the events are firing in my Android WebView. Can someone point me in the right direction?

**Comment by gesinger** [comment]
It's possible you are running into native playback on Android (where Android has support for HLS and we relinquish control of playback over to the native player). Check out https://github.com/videojs/videojs-contrib-hls#overridenative if you'd like to override this functionality, and let us know if this helps.

**Comment by jeffmikels** [comment]
I've given up on WebView video and HLS. I am now using LibVLC in my app to
launch a dedicated RTMP player window.

*Jeff Mikels*
Pastor, Lafayette Community Church
helping people find full life in Christ
http://jeff.mikels.cc
http://lafayettecc.org
765-404-0807

Jesus: "I have come that they may have life, and have it to the full."
-- John 10:10 --

**Comment by gesinger** [comment]
Thanks for letting us know @jeffmikels . If you do decide to use videojs-contrib-hls again, let us know if you run into anything else.
