### ISSUE TITLE
Custom url loader

### ISSUE THREAD

**Issue by greenya** [videojs/videojs-contrib-hls#1231]
Hello.

**Is there a way to replace an url loader of a particular player?** So it will ask me (my function/object) to load a resource (m3u8 or ts). So i can load the content from different sources depending on internal logic, and after content loaded i can callback player with the content.

Thank you for any help.

**Comment by mjneil** [comment]
`xhr.beforeRequest` sounds like what you are looking for https://github.com/videojs/videojs-contrib-hls#hlsxhr

**Comment by hei-yu-fa** [comment]
p2p need,the same question for me

**Comment by gesinger** [comment]
Closing for now. If https://github.com/videojs/videojs-contrib-hls#hlsxhr doesn't match your use cases, please let us know. Thank you.
