### ISSUE TITLE
Problem with the Akamai CDN

### ISSUE THREAD

**Issue by charlesfonlupt** [videojs/videojs-contrib-hls#1232]
## Description
We are reproducing Videos from Vimeo through Video.js. The player is working fine in the US (Fastly), but we have some problem with the reproduction of the Video in Latam (Akamai). 

## Error Message

Error: "VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported."

## Details 
Explain in detail the exact steps necessary to reproduce the issue.

In the US, the video is accessible without any problem.

In that case the requests from vimeo are:

https://player.vimeo.com/external/208886351.hd.mp4?s=9ba688c9d5dd715ba92fa3975d6057dafc25f291&profile_id=119&oauth2_token_id=909251516
https://fpdl.vimeocdn.com/vimeo-prod-skyfire-std-us/01/1777/8/208886351/714366355.mp4?token=1502406525-0x3c9db3f693e922c6b77ce22cc2a0589b794934f4
 Headers from https://player.vimeo.com are:
Location:https://fpdl.vimeocdn.com/vimeo-prod-skyfire-std-us/01/1777/8/208886351/714366355.mp4?token=1502406525-0x3c9db3f693e922c6b77ce22cc2a0589b794934f4

In Latam, with Akamai we found that error : 

Error: "VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported."

The Requests from Vimeo are:

https://player.vimeo.com/external/208886351.hd.mp4?s=9ba688c9d5dd715ba92fa3975d6057dafc25f291&profile_id=119&oauth2_token_id=909251516
https://gcs-vimeo.akamaized.net/exp=1502406925~acl=%2A%2F714366355.mp4%2A~hmac=d6f8d6f8159a27cf4932e92fd0e8f1ee4f5afe8beaea824cbfc1ed68786103c8/vimeo-prod-skyfire-std-us/01/1777/8/208886351/714366355.mp4
Headers from https://player.vimeo.com are:
Location:https://gcs-vimeo.akamaized.net/exp=1502406925~acl=%2A%2F714366355.mp4%2A~hmac=d6f8d6f8159a27cf4932e92fd0e8f1ee4f5afe8beaea824cbfc1ed68786103c8/vimeo-prod-skyfire-std-us/01/1777/8/208886351/714366355.mp4

Headers in the US : https://fpdl.vimeocdn.com/:

accept-ranges:bytes
accept-ranges:bytes
access-control-allow-credentials:true
access-control-allow-headers:Content-Type, Accept-Encoding, Range
access-control-allow-origin:null
age:237
content-length:187688366
content-range:bytes 2883584-190571949/190571950
content-type:video/mp4
date:Thu, 10 Aug 2017 19:08:49 GMT
etag:"40bc793ed999395a97339e17e985f23f"
expires:Thu, 10 Aug 2017 19:04:52 GMT
fastly-debug-digest:a5d40422010376fed073309834d959f320a8d7ee9d51bef15d3d5a31c7a0c10b
last-modified:Fri, 17 Mar 2017 22:38:10 GMT
server:UploadServer
status:206
timing-allow-origin:*
via:1.1 varnish
via:1.1 varnish
x-cache:MISS, HIT
x-cache-hits:0, 0
x-served-by:cache-iad2150-IAD, cache-sea1038-SEA
x-timer:S1502392130.914428,VS0,VE0

Headers in Latam https://gcs-vimeo.akamaized.net/:

accept-ranges:bytes
access-control-allow-credentials:true
access-control-allow-headers:X-Requested-With
access-control-allow-headers:X-Requested-With
access-control-allow-methods:GET
access-control-allow-origin:*
access-control-allow-origin:null
access-control-expose-headers:quic-version
access-control-expose-headers:Akamai-Edge-IP, X-VIM-CACHEBC
aka-c-hit:cache-hit
akamai-edge-ip:190.98.167.238
alt-svc:quic=":443"; v="38,37,36,35"; ma=3600
cache-control:private, max-age=0
content-length:190571950
content-range:bytes 0-190571949/190571950
content-type:video/mp4
date:Thu, 10 Aug 2017 19:15:25 GMT
etag:"40bc793ed999395a97339e17e985f23f"
expires:Thu, 10 Aug 2017 19:15:25 GMT
last-modified:Fri, 17 Mar 2017 22:38:10 GMT
quic-version:Q037
server:UploadServer
set-cookie:aka_debug=cpcode:428620~clientip:181.118.102.101~ghostip:190.98.167.238~requestid:cdee6db~time:1502392525~ghostforwardip:~edgecache:cache-hit~rtt:46~region:AR-; path=/; domain=.akamaized.net;
status:206
timing-allow-origin:*
x-goog-hash:md5=QLx5PtmZOVqXM54X6YXyPw==
x-goog-hash:crc32c=fSfysQ==
x-goog-storage-class:STANDARD
x-guploader-uploadid:AEnB2Ur7drix2v504IKtDNUX9uFUnz4gTOVx5Gwo5j34WoJAOzoU2woO8d3Q5bPZecXbc2jOQ1aVc4EqYCe54hOZYvqPULWRdw
x-vim-cachebc:EP:Q,E:h
Imagen con VPN: http://imgur.com/a/fqpis
Imagen sin VPN: http://imgur.com/a/XgdXA

**Comment by remy** [comment]
Found this issue with a google search unrelated to video.js, but I can chime in to say that I'm seeing the **exact same thing** when I request a vimeo.mp4 from Chile (failure) and from the US & Europe (success).

This issue isn't videojs specific, it's to do with vimeo's CDN configuration, and somehow Amakia setup stripping headers (or even query strings I've noticed…but I'm not 100% sure if that has an impact). 

In Safari I've seen the error reporting that CORS is not enabled for the video file, and in Firefox I've seen the same error mentioned here that the mime type is not supported.

I'm raising a ticket with Vimeo and pointing them to this issue as it has solid information on the requests and response.

**Comment by charlesfonlupt** [comment]
Hi Remy : We openned a ticket with Vimeo last week. 

Here is the answer they give us : 

I just heard back from our developers on this issue. They've done some testing, and they can suspect this is likely a videojs bug.

To confirm, we played your video using the Akamai redirect link in a plain HTML5 tag, and the video played without error. There seems to be a compatibility issue on the videojs side of things. We recommend submitting an issue in their tracker here: https://github.com/videojs/videojs-contrib-hls/issues/. If you can acquire additional information from the developers of the videojs framework, I'm happy to pass this along to our engineering team. At this time, it's still unclear why your player is not accepting the Akamai URLs, so it's difficult for us to make modifications to accomodate this.

**Comment by remy** [comment]
@charlesfonlupt I was just able to work around the issue by removing the `crossOrigin` attribute on the video element.

I'm certain that Vimeo are wrong as I'm able to replicate with a plain `video` tag, and I'm 100% certain that with cross origin enabled on the request, their Akamai CDN is somehow chewing up the headers and corrupting them (one big difference I noticed on my requests that the final URL was missing a `token` query string - but I'm unsure if that's the final issue).

**Comment by Born2BCoder** [comment]
We were able to reproduce the plain video as well removing the cross-origin attribute, but the main issue now is that its required so the videojs-panorama can bend it to a 360 view mode. without it it throws an DomException bug  failing to excecute the texImage2D on  the WebGLRendering Context

> DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The video element contains cross-origin data, and may not be loaded.

This causes the video sound to be heard but not the image.

So we are left trying to figure out a way to pass through the cross-domain issue.

**Comment by charlesfonlupt** [comment]
@remy : thanks for the work-around, but as @Born2BCoder is mentioning, we need the `cross-origin` element to be able to reproduce the video correctly, using other libraries as videos-panorama.

**Comment by remy** [comment]
Got a reply _and a fix_ from Vimeo yesterday:

> I truly appreciate you sending over such an in depth analysis of the issue. Using this information (and that of others on the github thread), our engineering team was able to work with Akamai to resolve this issue. Your video should now play within error in your videojs player.
>
> The cause for this issue was two CORS headers. Akamai was not obeying the normal CORs workflow and unconditionally appending two headers:
> 
> `Access-Control-Allow-Headers: X-Requested-With`
> `Access-Control-Allow-Origin:`
>
> This created two sets of headers when a CORS request was made (a request with an 'Origin' header).  The two headers being returned to the client broke CORS, and stopped the download of segment/file in it's tracks. As a solution Akamai is now doing the appropriate behavior when a CORS response is received and echoing the requesting origin in the allowed response CORS headers. 

I was able to work around my own problem, but I think this change now means that your videojs player should work with the `crossOrigin` attribute attached.

Hope that helps!

**Comment by charlesfonlupt** [comment]
Hi @remy : Thanks a lot for you help. 

The change allow us to resolve our issue.  The "crossOrigin" problem we had is resolved.
