### ISSUE TITLE
HLS Player skipping frames on android during quality change

### ISSUE THREAD

**Issue by SVyatoslavG** [videojs/videojs-contrib-hls#1236]
## Description
Android chrome doesn't have a good native support of HLS. So if you go to https://videojs.github.io/videojs-contrib-hls/ with android device (tested with GALAXY S7, LAGAXY TAB S2). When quality changes (usually for me on 10s) frames are being skipped and image gets unpleasant. Then it gets fine again.
On IOS it plays very smooth and my MAC too.
In my dev environment I tried to use overrideNative but it did not help. 

## Sources
Bip-bop video on https://videojs.github.io/videojs-contrib-hls/
Also any other source

## Steps to reproduce
Just to go https://videojs.github.io/videojs-contrib-hls/ with an android device. Pay attention on segments changes (10s, 20s, 30s). When new segment has different quality then previous frames are being skipped.

## Results
Skipped frames

### Expected
Smooth and nice playing of the video on Android Chrome.

### Error output
No erros

## Additional Information
Bitmovin https://bitmovin.com/hls-mpeg-dash-test-player/ doesn't have this issue so I believe problem with HLS playback

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 5.9.0

### videojs version
what version of videojs does this occur with?
video.js 5.2.0

### Browsers
what browsers are affected? please include browser and version for each
Android Chrome

### Platforms
what platforms are affected? please include operating system and version or device and version for each
Andoid

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
NO

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
NO

**Comment by japettyjohn** [comment]
@SVyatoslavG I have the same problem - have you found anything on this?

It's playing fine for a single quality, but when switching from a low quality to the next quality the picture pauses, audios continues, then the picture catches up.

**Comment by forbesjo** [comment]
This plugin defers to native HLS playback if it's available, if you would like smoother playback please override the native functionality https://github.com/videojs/videojs-contrib-hls
