### ISSUE TITLE
Problems scrubbing for long audio streams

### ISSUE THREAD

**Issue by mayank-gupta** [videojs/videojs-contrib-hls#1237]
## Description
When we use the videojs-contrib-hls library to go from one point to another in long audio streams say more than 30 hours, player behaves weirdly. It goes to random locations and doesn't give any error.

[Here](https://audiblecdn-vh.akamaihd.net/i/295896/audiblewords/content/bk/haki/001303/V$403391$V/aax/bk_haki_001303_22_32.mp4/master.m3u8?hdnea=st=1503005705~exp=1503610505~acl=/*~hmac=b8fdd7d71b80fb07d2e50bb33e06055e61f7fbdbf8889c854157c81e27168277) is an HLS stream which can be used to reproduce the bug. Try playing it in the player [here](https://videojs.github.io/videojs-contrib-hls/) and try to skip to a position that is more than half of the stream. It will jump to some random location in the stream.

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 5.8.3

### videojs version
what version of videojs does this occur with?
video.js 6.2.4

### Browsers
what browsers are affected? please include browser and version for each
* Chrome Version 59.0.3071.115

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* Mac/Windows

**Comment by mjneil** [comment]
Timestamps in MPEG2TS streams are 33 bits, with a max value around ~26.5 hours, so there will be multiple segments with the same exact timestamp. Currently, we don't have a great way of dealing with seeks that span very large time ranges. During the transmuxing stage, we try and account for this rollover by comparing and adjusting the timestamps when a rollover is detected. https://github.com/videojs/mux.js/blob/master/lib/m2ts/timestamp-rollover-stream.js#L34

**Comment by forbesjo** [comment]
Putting this in the VHS backlog

/move to http-streaming
