### ISSUE TITLE
Headers not being sent specifically for Android Google Chrome

### ISSUE THREAD

**Issue by samueleastdev** [videojs/videojs-contrib-hls#1246]
## Description
We are having issues with playback on Android Chrome only. It works in every other browser and setup but not Google Chrome on Android.

We have been on support with AWS and they state the following.

> I do not have expertise with troubleshooting players so this is something you would have to do on your end. But from what I can see it looks to be that referrer header is not being sent to s3 when the video is played on Android

I have setup an example here.
http://jsbin.com/xosefiyijo/edit?html,output

You should notice it plays on Firefox on Android but not Chrome.

Thanks

**Comment by mjneil** [comment]
It appears to also not work in the ouput page  for the jsbin http://output.jsbin.com/xosefiyijo , but does work in their embedded runner

**Comment by samueleastdev** [comment]
@mjneil updated to also work in output

**Comment by mjneil** [comment]
You should also be [overriding native playback](https://github.com/videojs/videojs-contrib-hls#overridenative) for android, otherwise Android will use its own native hls playback and not contrib-hls

**Comment by samueleastdev** [comment]
Hi @mjneil 

I tried that, I have updated the jsbin links with the new setup.

http://jsbin.com/gofibonahe/1/edit?html,output
http://output.jsbin.com/gofibonahe

Here is also a full screengrab of the output of the chrome inspection tools with the Samsung Galaxy plugged in.

<img width="1671" alt="screen shot 2017-08-29 at 10 01 44" src="https://user-images.githubusercontent.com/1894778/29813208-4bfcb1a8-8ca1-11e7-9260-a16734274b9d.png">

I initially didn't think it was an issue but I can definitely recreate it on my Samsung Galaxy.

The issue is only related to Android Chrome if I open up the jsbin output in Firefox on the same Android phone it will work without and issues.

Let me know what other information could be provided to try to find the issue, spent a long time with AWS support and they seem to think it's a player issue?

They mentioned something about the content range

Content-Length:705
Content-Range:bytes 0-704/705

Thanks

**Comment by samueleastdev** [comment]
So debugging a little further.

On Android the Response Headers are as follows.
~~~
Accept-Ranges:bytes
Content-Length:705
Content-Range:bytes 0-704/705
Content-Type:application/x-mpegURL
~~~

And on iPhone Chrome, desktop Chrome they are.
~~~
Accept-Ranges:bytes
Access-Control-Allow-Methods:GET
Access-Control-Allow-Origin:*
Access-Control-Max-Age:3000
Content-Length:705
Content-Type:application/x-mpegURL
~~~

**Comment by samueleastdev** [comment]
This post is also related https://github.com/bentasker/HLS-Stream-Creator/issues/16

**Comment by samueleastdev** [comment]
Going to close this issue the HTTP referrer lockdown seems unreliable and not all browsers send the referrer, going to look into signed cookies.
