### ISSUE TITLE
Quality Level doesn't populate on edge and chrome on mobile

### ISSUE THREAD

**Issue by ahmadawada11** [videojs/videojs-contrib-hls#1248]
i am using the following plugin  videojs-contrib-hls,  videojs-contrib-quality-levels and videojs-hls-source-selector the quality level populate on chrome and firefox but it is not working on edge and chrome on mobile. i tried to debug the issue on edge it seems the event that add the quality level not fired i am using videojs 6.2.6

please note i added the following option before the player declaration

```
videojs.options.hls.overrideNative = true;
videojs.options.html5.nativeAudioTracks = false;
videojs.options.html5.nativeVideoTracks = false;  

```
thank you

**Comment by mjneil** [comment]
Please refrain from creating duplicate issues in the future, one is enough. I am closing your other [issue](https://github.com/videojs/videojs-contrib-quality-levels/issues/22) in favor of this one.

It's hard to saw what is going wrong without a full example. Could you provide a reduced test case (http://jsbin.com/vokipos/8/edit?html,output) that shows the behavior you are seeing?

**Comment by ahmadawada11** [comment]
HI, 
i modified the code in [http://jsbin.com/futexiboci/1/edit?html,js,output](http://jsbin.com/futexiboci/1/edit?html,js,output)

thanks in advance.

**Comment by mjneil** [comment]
I'm not seeing any issues on edge myself. Does `player.qualityLevels()` return an empty list on edge for you? It's possible that the levels are getting added to the list before the `hlsSourceSelector` plugin can setup its event listeners. I would try initializing the plugin through videojs options.

```
var player = videojs('my-video', {                                                                                                           
  fluid: false,
  poster: "https://static.vod-platform.net/VideosThumbsImages/admin/200000/Poster-277470-1-6771897-1.jpg",
  preload: "auto",
  controlBar: {
    volumePanel: { inline: false }
  },
  plugins: { hlsSourceSelector: {} }
});                     
```

**Comment by ahmadawada11** [comment]
Hi the above solution worked on edge.

also after i changed my code to set the player src using code not in video tag the list now appear on chrome on android mobile also.

**Comment by mjneil** [comment]
Great glad that worked for you! Closing this issue, if you run into more problems please re-open or submit a new issue
