### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by hefeng1208** [videojs/videojs-contrib-hls#1250]
I tried to use videojs-contrib-hls, but I ran into this problem

XMLHttpRequest cannot load http://live-play-hls.jcloudcs.com/live/30905e998377b5dad9.m3u8. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3333' is therefore not allowed access.

----------------------------------------------------
I need help thx

**Comment by gkatsev** [comment]
This means that the server isn't set up with the correct headers to be playable via contrib-hls. Please refer to the [hosting considerations](https://github.com/videojs/videojs-contrib-hls#hosting-considerations) in the README for modifying the server.
Hope that helps.

**Comment by hefeng1208** [comment]
thanks @gkatsev
