### ISSUE TITLE
draw AudioWaveform of HLS Stream

### ISSUE THREAD

**Issue by manuliner** [videojs/videojs-contrib-hls#1253]
Hi everyone,
i am looking for an possibility to get an arrayBuffer from the audiotrack of my TS Files. I am loading the TS files via videojs-contrib-hls.js Does anyone got an Idea how to handle this?

to be more general: i want to draw an audioWaveForm of my m3u8 playlist
my general idea is to generate my waveform data for each TS file separate and the draw them all in one canvas. For generating a waveform i need an audiotrack as .ogg or .mp3 or as an arrayBuffer

thank you very much

**Comment by gesinger** [comment]
Hey @manuliner , right now we only support AAC, and don't provide an API for exposing the bytes themselves. If browsers provide a way to access the buffered data of a video element, it may be possible, however, we aren't looking to add the feature at this point in time. Hope this helps.
