### ISSUE TITLE
ffmpeg command to convert .mp4 to .ts 

### ISSUE THREAD

**Issue by ronlinet** [videojs/videojs-contrib-hls#1261]
I am converting existing .mp4 files to .ts format but the player is shows that the format is not supported. Can you please provide a general fffmpeg command that generate .ts files for this player?
My ffmpeg command : 
```
$ ffmpeg -y \
-i sample.mp4 \
-codec copy \
-bsf h264_mp4toannexb \
-map 0 \
-f segment \
-segment_time 10 \
-segment_format mpegts \
-segment_list "playlist.m3u8" \
-segment_list_type m3u8 \
"fileSequence%d.ts"
```

**Comment by mjneil** [comment]
`ffmpeg -i input.mp4 -bsf:v h264_mp4toannexb -codec copy -hls_list_size 0 output.m3u8` this works for me, maybe try starting with this and add/edit options to get your desired output

**Comment by ronlinet** [comment]
@mjneil it does the trick ! 
I just had to add and additional scaling coz I am resizing the medias per per client's bandwidth. 
`ffmpeg -i ../tmp/short.mp4 -vf scale=320:184 -bsf:v h264_mp4toannexb -hls_list_size 0 playlist.m3u8` 
Cheers !

**Comment by ronlinet** [comment]
I have just found out that files generated with the above ffmpeg snippet works everywhere except the Android. The Android Chrome browsers abort the streaming with ‘Media could not be loaded’ error. I don’t get the error with your .ts files served by bipbop_16x9_variant.m3u8 . 
Would you mind to stick here the ffmpeg command used for your demo ts files?

**Comment by ronlinet** [comment]
Missing dollar sign field delimiter at file header #EXTM3U in main-manifest.m3u8 is enough to corrupt streaming to android devices. 
This char is invisible in Netbeens or any other IDE. File has to be edited with command line vimdiff to spot the absence of the delimiter.

**Comment by alviscure** [comment]
@mjneil thanks for the shared instruction, how can I modify the bitrate of the ouput? Thank you again, it has helped me a lot.
