### ISSUE TITLE
VIDEOJS: ERROR: TypeError: Cannot read property 'playlist' of undefined

### ISSUE THREAD

**Issue by ahmadawada11** [videojs/videojs-contrib-hls#1267]
I got a exception when I am changing the resolution several time. For example, if my list has 2 resolutions which are A and B. If I selected A and then B, and then selected A the exception will be thrown as the following:

VIDEOJS: ERROR: TypeError: Cannot read property 'playlist' of undefined

I am using videojs version 6.2.7, contrib-quality-level, hls-source-selector and hls version 5.11.0 plugins.

 this error doesn't happen with hls version 5.7.0

**Comment by ahmadawada11** [comment]
the changes solved the issue did this fix included in v5.11.1?

**Comment by mjneil** [comment]
No sorry, the fix is still being reviewed/tested

**Comment by mjneil** [comment]
The fix has been released in v5.12.0. Closing this issue for now, please re-open or submit a new one if you continue to experience issues.
