### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'new o.EventTarget')

### ISSUE THREAD

**Issue by clayjh** [videojs/videojs-contrib-hls#1268]
## Description
I started to get this error seemingly out of nowhere, it has caused all my tests to fail as soon as I visit the URL.

My quick fix was to set `page.driver.browser.js_errors = false` in each test setup

Output:
TypeError: undefined is not an object (evaluating 'new o.EventTarget')
TypeError: undefined is not an object (evaluating 'new o.EventTarget')
    at https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/5.11.0/videojs-contrib-hls.min.js:2
    at https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/5.11.0/videojs-contrib-hls.min.js:2
    at https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/5.11.0/videojs-contrib-hls.min.js:1 in r
    at https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/5.11.0/videojs-contrib-hls.min.js:1
    at https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/5.11.0/videojs-contrib-hls.min.js:7
    at https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/5.11.0/videojs-contrib-hls.min.js:7
    at https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/5.11.0/videojs-contrib-hls.min.js:1 in r
    at https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/5.11.0/videojs-contrib-hls.min.js:1 in e

videojs-contrib-hls 5.11.0, testing in Chrome

**Comment by mjneil** [comment]
Can you provide the error output using the un-minified script or create a reduced code example with our [starter template](http://jsbin.com/vokipos/8/edit?html,output)?

**Comment by gesinger** [comment]
Closing for now. If you are still experiencing this issue with the latest version of videojs-contrib-hls, please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.
