### ISSUE TITLE
Video not able to play on chrome and firefox

### ISSUE THREAD

**Issue by gskalyan90** [videojs/videojs-contrib-hls#1275]
## Description
I am not able to  play hls video, but when I seek to 6th second then it is playing, because the initial chunk may be corrupt, in safari its playing from 6th second directly, can we do the same as in safari, I am using latest version videojs @6.2.7 and videojs-contrib-hls@5.11.0

## Sources
https://vhoichoi.viewlift.com/encodes/originals/3/hls/master.m3u8

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. you can put the above src in https://videojs.github.io/videojs-contrib-hls/ and test it

**Comment by ccrsky** [comment]
I got the similar issue,but video not  able to play on Safari, videojs @6.2.7 videojs-contrib-hl@5.11.0

**Comment by dannyxu2015** [comment]
found same issue on chrome(v61.0.3163.100), videojs@6.2.8, videojs-contrib-hls@5.12.2

**Comment by gesinger** [comment]
Sorry this issue has gone a while without much attention. It looks like that stream may be down (or behind protection). Are you still experiencing this issue with the latest version of videojs-contrib-hls, and if so, would you be able to bring the stream back up (slash make it accessible)? Thank you.

**Comment by gesinger** [comment]
Closing. If you are still having issues with the latest release of videojs-contrib-hls, please let us know (and provide a new stream/open the posted stream if possible). Thank you.
