### ISSUE TITLE
videojs.Hls.xhr.beforeRequest not work on safari  but chrome is ok

### ISSUE THREAD

**Issue by ccrsky** [videojs/videojs-contrib-hls#1280]
videojs.Hls.xhr.beforeRequest not work on safari or mobile device ,but it works on chrome

beforeRequest don't work,so the .ts filePath is incorrect

error:"The media could not be loaded, either because the server or network failed or because the format is not supported."

videojs-contrib-hls @5.11.1
videojs @6.2.8

**Comment by ccrsky** [comment]
i need use beforeRequest to transform ts filePath,but mobile device  has  only one soucehandler (native soucehandler), beforeRequest not work,how to fix it ?

**Comment by gesinger** [comment]
Hey @ccrsky , Safari uses native playback for HLS, and doesn't provide us APIs for transforming requests. Native playback can be overridden by https://github.com/videojs/videojs-contrib-hls#overridenative , however, as a warning we have seen some other issues with non native Safari playback. In addition, iOS Safari doesn't provide MSE, so we are not able to use non native playback there. Sorry about the trouble, but hope this explanation helps.
