### ISSUE TITLE
The HLS + AES encryption video play ploblem

### ISSUE THREAD

**Issue by redbox-cdn** [videojs/videojs-contrib-hls#1281]
## Description
The HLS+AES video only play  first segment. second segment does not play.

I checked following demo site and both my web site. this problem is same.
https://videojs.github.io/videojs-contrib-hls/

## Sources
Here is the Video source
https://www.redbox.ne.jp/sample-movie/mobile/mid.mp4.m3u8

I don't know if this problem related to encoding or M3U8 file.
Please advice me if there are restrictions or caveats.

Best regards.

**Comment by zhuyeqing5828** [comment]
I tried with the live demo (address is http://jsbin.com/vokipos/8/edit?html,output ) ,but no issue.

**Comment by forbesjo** [comment]
I do not see an issue in the latest version of the project, please let us know if this is still an issue
