### ISSUE TITLE
Cannot access player.hls.representations(); on mobile.

### ISSUE THREAD

**Issue by samueleastdev** [videojs/videojs-contrib-hls#1283]
## Description

https://github.com/videojs/videojs-contrib-hls#hlsrepresentations

Cannot access player.hls.representations(); on mobile.

I have build a quality level switcher but I cannot seem to get it to work on mobile (Maybe it shouldn't work on mobile not sure).

I have setup a simple example here: http://output.jsbin.com/pacicob/8

This will output the reps on desktop but I just get undefined on mobile again not sure if this is correct.

I am using overrideNative for everything except Safari.
~~~
if (!videojs.browser.IS_ANY_SAFARI) {


    videojs.options.hls.overrideNative = true;
    // This crashes the player in internet explorer
    //videojs.options.html5.nativeAudioTracks = false;
    //videojs.options.html5.nativeTextTracks = false;


}
var player = videojs('my_video_1', {
    html5: {
        nativeAudioTracks: false,
        nativeVideoTracks: false
    }
}, function() {

    this.on('loadedmetadata', function(evt) {

        var reps = this.tech_.hls.representations(); // the reps returns undefined on mobile
        var rep = document.getElementById('reps');
        rep.innerHTML = JSON.stringify(reps);

    });

});
~~~

### Expected
Reps for every mobile browser except Safari.

### Error output
On mobile only undefined

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 5.12.0

### videojs version
what version of videojs does this occur with?
video.js 5.19.1

### Browsers
Tested on Chrome, Firefox Android
Chrome, Firefox IOS

**Comment by mjneil** [comment]
It doesn't look like your example is actually using the `overrideNative` options. I added the options to the jsbin http://output.jsbin.com/dubiqucimi and it is working for me on mobile

**Comment by samueleastdev** [comment]
Hi @mjneil,

Thanks for the quick response ;) but if you test on a iPhone with Chrome Browser or Android with Chrome it doesnt work for me. Work through the dev tools but not a real device?

**Comment by mjneil** [comment]
I tested in Chrome on my android device and the jsbin I linked works just like desktop. I did not test on an ios device though

**Comment by samueleastdev** [comment]
Strange it's definitely not working for me I am running on quite an old Samsung S3, and it's not working on my iPhone 6.

**Comment by samueleastdev** [comment]
I just fired up a Samsung S7 with Genymotion and it appears to be working on that, I guess its old Androids (maybe a specific operating system) and IOS.

![screen shot 2017-10-24 at 22 53 12](https://user-images.githubusercontent.com/1894778/31969942-54619e3c-b90e-11e7-95ce-cdcc1667cd82.png)

**Comment by forbesjo** [comment]
videojs-contrib-hls requires MSE in order to work and Android 4.4 is the earliest version with MSE support. Is your Samsung S3 on 4.4? Also Safari on iOS does not support MSE. Chrome for iOS uses WKWebView so it's basically Safari.

**Comment by samueleastdev** [comment]
Hi, @forbesjo thanks for the info pretty sure my Samsung S3 Android is running lower than 4.4. 

So we can only expect to get the representations on Android 4.4 that's fine at least I can relay the info to my users ;)
