### ISSUE TITLE
Catch 403

### ISSUE THREAD

**Issue by morangil** [videojs/videojs-contrib-hls#1287]
I'm using tokens on my site to play mp4. 
Is there a way to catch 403 incase of expired token?

**Comment by barhom** [comment]
+1

**Comment by squarebracket** [comment]
I'm not sure what you're asking for here. Does the token expire while the stream is playing?

**Comment by barhom** [comment]
Lets assume the following;

1. You are playing a live stream
2. Whilst fetching the playlist after playback time of X minutes you suddenly get a 40x/50x.
3. We want to catch that 40x/50x and then do whatever we want. For example, reload the video, maybe play another video, or simply outputting to console.log("40x/50x happened")

**Comment by morangil** [comment]
@squarebracket,

correct. let's say the token is set to 10 minutes but someone clicked on pause for 12 minutes and try to watch the movie.

**Comment by nicolaslevy** [comment]
I need this feature too.

Maybe i'm looking at the wrong place but the only thing that worked for me was listen to 'retryplayist' events. Something like this:
```
  player.tech_.on('retryplaylist', () => {
      do_something()
  })
```

Does anyone has a better solution?
