### ISSUE TITLE
Video stalls when changing to a higher resolution

### ISSUE THREAD

**Issue by d3x7r0** [videojs/videojs-contrib-hls#1288]
## Description
When playing an HLS live stream the player triggers a "waiting" event and the stream visually stalls. Meanwhile requests are still being made to the correct playlist and chunks despite the video not playing.

After waiting enough (several minutes), sometimes the player will switch back to the lower resolution and recover with an `hls-reset` event.

## Sources
Here's a reduced test case: http://jsbin.com/sonuleniwi/edit?html,output

## Steps to reproduce
1. Point the player to an HLS stream
2. Trigger a change of resolution due to bandwidth/size (one way to do this is using the property `enableLowInitialPlaylist`)

### Expected
The video should correctly switch to the higher resolution playlist.

### Error output
There are no errors or output in the console.

### videojs-contrib-hls version
videojs-contrib-hls 5.12.1

### videojs version
video.js 6.3.3

### Browsers
Chrome Version 63.0.3239.30 (Official Build) beta (64-bit) [OS X - Sierra]
Chrome Version 61.0.3163.100 (Official Build) (64-bit) [OS X - Sierra]
Chrome Version 61.0.3163.100 (Official Build) (64-bit) [Windows 8.1]
Firefox 57.0b10 (64-bit) [OS-X - Sierra]
Firefox 56.0.2 (64-bit) [Windows 8.1]

**Comment by mjneil** [comment]
I am getting a 403 Forbidden and No 'Access-Control-Allow-Origin' header errors for https://live.impresa.pt/live/sic/sic.m3u8

**Comment by d3x7r0** [comment]
Sorry, I've changed the stream to one that's available outside the country but apparently restarting out stream actually made the problem go away.

Sorry. I guess I'll close this one then. I'm guessing there is some sort of issue with out software when running for a large enough period of time that breaks something but its a bit hard to reproduce.
