### ISSUE TITLE
Unable to start on IE11.

### ISSUE THREAD

**Issue by auditoryhallucination88** [videojs/videojs-contrib-hls#1290]
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. [object Object]

No issue on chrome & firefox.

**Comment by mjneil** [comment]
What OS are you using?
Versions of contrib-hls and videojs?
Can you provide a source or reduced test case?

**Comment by auditoryhallucination88** [comment]
It's working now. Found out that i have no flash installed on ie.
