### ISSUE TITLE
v5.10.1 - Cookies are not sent with manifest file requests

### ISSUE THREAD

**Issue by stoicbuddha** [videojs/videojs-contrib-hls#1294]
## Description
We use Akamai for video encryption, and as such, the main manifest pulls fine because it passes the auth token.  However, the other manifest files below it all 403 because it's not passing a cookie with the requests. This is related to [#607](https://github.com/videojs/videojs-contrib-hls/issues/607).  I commented on that but figured it would be good to make a new one since it's a year old and a different version.
[Reduced Test Case](http://jsbin.com/rojibogahu/edit?html,console,output) 

## Sources
The video in the reduced test case is only good for 3 hours, so if you need to "re-up" so to speak, go [here](http://dev.player.dotstudiopro.com/share/58a5dc71d66da8d25a7b23c6?targetelm=.player&companykey=57bdf792d66da8b744a33855&skin=228b22#) and type `player.currentSrc()` in the JS console to get a current one.

## Other Javascript
We use a whole slew of other plugins, but this issue exists independently.

**Comment by mjneil** [comment]
It looks like you just have some syntax issues with your example. Specifically missing a comma after `loop: false` and `opts` being undefined

fixing your setup to be 
```
videojs('my_video_1', {
      "controls": true,
      "autoplay": false,
      "preload": true,
      "poster": '',
      "loop": false,
      "html5": {
        hls: {
          withCredentials: true
        }
      }
  });
```
with the above snippet it is working fine for me with cookies being sent

**Comment by matt-iakhno** [comment]
I updated the JSbin with proper syntax - when running in Safari 11 the player throws error, but Chrome and FF play fine

http://jsbin.com/yizuyenulu/edit?html,console,output

**Comment by stoicbuddha** [comment]
Is there any update on this?

**Comment by stoicbuddha** [comment]
Is there any news on this?  I know it's the holidays and it might be harder to get to.

**Comment by stoicbuddha** [comment]
Do you have a fix for the Safari issue?

**Comment by gesinger** [comment]
Safari uses native playback for HLS, and we don't have access to the requests to modify them. This may be overridden by https://github.com/videojs/videojs-contrib-hls#overridenative , however, as a warning, we have seen some issues with overrideNative on Safari that we have other open issues for.

**Comment by adityaj221** [comment]
@stoicbuddha Was this fixed for you.?
How did you address this. I'm facing the same issues with cookies not being sent on player calls on iOS  Safari.
It works on desktop clients.
