### ISSUE TITLE
Can you show the connection speed

### ISSUE THREAD

**Issue by pxss** [videojs/videojs-contrib-hls#1295]
Just like the youtube video right - detailed statistics.

![123](https://user-images.githubusercontent.com/9522862/32710140-e00ee2de-c870-11e7-8629-9b27fb337852.png)

**Comment by barhom** [comment]
+1

**Comment by skzap** [comment]
I'm pretty sure this relies on them knowing the filesize / bitrate of videos playing

**Comment by squarebracket** [comment]
By show, do you mean via UI? The bandwidth measured from the last segment request is accessible via the tech.

**Comment by gesinger** [comment]
As @squarebracket mentioned, we do have https://github.com/videojs/videojs-contrib-hls#hlsbandwidth for determining the bandwidth from the last segment request. We don't currently have any plans for a UI built into contrib-hls, however, we always welcome others to create such a plugin.
