### ISSUE TITLE
Question: Load m3u8 and segments in buffer before player.play();

### ISSUE THREAD

**Issue by barhom** [videojs/videojs-contrib-hls#1297]
Hey,

I would like to intstruct videojs and videojs-contrib-hls to 

1. player.src(".....");
2. "Start preloading m3u8 AND segments"
3. player.play() once buffer is > seconds or buffer is > N segments

Anyway to do this with videojs?

I havent figured out how to get videojs to preload m3u8 and segments and I havent figured out the command to ask how much buffer there currently is before the player stalls.

Appreciate the help, thanks.

**Comment by forbesjo** [comment]
You can let the player preload segments by using the `auto` preload setting and you should be able to see the buffered time range with `player.buffered()`

**Comment by sdahdaah** [comment]
Hello,

auto in preload is limited to 1 TS file in case of VOD and to no TS file in case of live. What he is referring to is similar to the behavior of hls.js that keeps preloading segments with no limit.

i have suggested a method for that i am not sure if feasible:

to have 3 different preload features currently 2 are supported correctly:
1- none does nothing (already supported)
2- metadata has similar behavior to the current auto
3- auto preload for both live and vod unlimited number of chunk and ts similar to the behavior of hls.js
