### ISSUE TITLE
Chasing a work around- Flash Fallback when Audio and video are not muxed

### ISSUE THREAD

**Issue by ebraan** [videojs/videojs-contrib-hls#1298]
Hello,

I am facing the same problem as described in #1221 (closed 3 months ago). I have noted the only solution (3 month ago) was to move to maximum hls V4. Unfortunately my packager (Shaka-packager)  formats the output following HLS V6 standard. The version could not be changed.

I Could use an other packager (ffmpeg for instance) for people wanting their contents playable on win7 ie 11, and keep Shaka Packager for people do not care about win7 ei11 (it is the only OS+brower which has audio issue). This solution implies more technical complexity....I am trying to avoid it.

Does someone find a work around to play hls V6 when flash fallback is used (Win 7 IE 11 playback)?

Many thanks for your help and idea.
 Regards
 Eric

**Comment by gesinger** [comment]
Hey @ebraan , if you are still looking for a flash fallback with support for demuxed audio and video, there is now https://github.com/brightcove/videojs-flashls-source-handler that can be used alongside videojs-contrib-hls. Hope this helps.
