### ISSUE TITLE
VM223994:1 Uncaught Error: TypeError: Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by pinglikethinking** [videojs/videojs-contrib-hls#1300]
how  to resolve this? 

"video.js": "^6.2.8",
    "videojs-contrib-hls": "^5.12.0",
    "videojs-flash": "^2.0.1",

**Comment by pinglikethinking** [comment]
I have solved this.
just delete original [video-js.swf
](https://github.com/mangui/video-js-swf/blob/master/dist/video-js.swf)and
import a new video-js.swf ,put it into static , and use it by
 `Object.assign({
       flash: {hls: { withCredentials: false }, swf: '/static/video-js.swf'}}, this.options)`

source style is this,when play hls
```
videojs.options.sources=[{
            withCredentials: false,
            src: links,
            type: 'application/x-mpegURL'
          }]
```

**Comment by vercha** [comment]
hello , I encountered same question. where to put the object.assign() code?

**Comment by cadalt** [comment]
i am also getting this error, but only on windows 7 ie 11

**Comment by gesinger** [comment]
If anyone is still encountering this issue, would someone be able to create a [reduced test case](https://css-tricks.com/reduced-test-cases/) using our [starter template](http://jsbin.com/vokipos/8/edit?html,output) on JSBin? Thank you.

**Comment by gesinger** [comment]
Closing. If anyone is still having issues with the latest release of videojs-contrib-hls, please let us know (and provide a reduced test case if possible). Thank you.
