### ISSUE TITLE
Playing a static url alongside streaming url

### ISSUE THREAD

**Issue by kshitij0392** [videojs/videojs-contrib-hls#1301]
## Description
I am currently working on a Video application which uses Videojs and Videojs-contrib-hls
 and my video tag looks like this 
```
<video  data-bind="attr:{id:playerId}"class="video-js vjs-default-skin media-player"  controls>
             <source  data-bind="attr:{src:URLToPlay}" id="video-source" type='application/x-mpegURL'>
        </video>

```
Now this URLToPlay can contain a streaming url or it can contain a static url like this 
http://techslides.com/demos/sample-videos/small.mp4

When I have a streaming url the video loads up fine and works great, but when a url like above mentioned comes in, the video breaks. However when I change the `type= "video/mp4"` it works fine, but streaming url breaks obviously. 

So my question is what is the correct MIME to play both streaming and static urls inside one video tag. 

I tried using 
application/x-mpegURL  .M3U8 - HTTP Streaming
vnd.apple.mpegURL  .M3U8 - HTTP Streaming

both these types do not work for me. 

## Steps to reproduce
To reproduce the issue, 

1. Go here http://videojs.github.io/videojs-contrib-hls/
2. Inside load video box put this url http://techslides.com/demos/sample-videos/small.mp4

## Results
Video load fails

### Expected
Expecting that static and streaming url both to play

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
@version 5.10.1

### videojs version
what version of videojs does this occur with?
video.js 6.0.2

### Browsers
what browsers are affected? please include browser and version for each
 All of the major browsers

**Comment by squarebracket** [comment]
Is there a reason you can't use the API, i.e. calling `player.src` and providing the `type`?

**Comment by mjneil** [comment]
You can't support both static a static mp4 and a streaming m3u8 with a single MIME. You'll have to dynamically set the MIME like you do with the source. Probably something along the lines of 
`<source  data-bind="attr:{src:URLToPlay, type:MIMEToPlay}" id="video-source">` where `MIMEToPlay` is the correct MIME for `URLToPlay`

**Comment by kshitij0392** [comment]
@mjneil That's exactly what I am doing now, just curious whether we could support different formats in one type. 
` <div id="videojs-container"  class="video-js-responsive-container vjs-hd">
        <video  data-bind="attr:{id:playerId}"class="video-js vjs-default-skin media-player"  controls>
           
             <source  data-bind="attr:{src:URLToPlay, type: isAkamaiUrl() ? 'application/vnd.apple.mpegURL' : 'video/mp4'}" id="video-source" >
        </video>`

Here's what I am doing !

**Comment by gesinger** [comment]
As @mjneil mentioned, the mime type specifies a specific format. Since HLS and MP4 are different formats, a single mime type will not cover both. Using a conditional based on the source type is the route to go (as you're doing). Hope this helps.
