### ISSUE TITLE
 the loading spinner is frequently displayed

### ISSUE THREAD

**Issue by lixiaochun** [videojs/videojs-contrib-hls#1302]
video.js is very powerful and easy to use, now  I'm using video.js to show hls live steam,  I have loading issues related to video caching. the loading spinner is frequently displayed expacially in case of multiple hls live streams show at the same time.  to avoid this. if I can increase buffer on video-js HTML5 player? and how can I do this?
 thank you very much:)

**Comment by gesinger** [comment]
Hey @lixiaochun , if you're watching multiple live streams, your bandwidth may not be able to keep up with the streams themselves. This is usually on an individual basis (per computer's bandwidth and processing power when appending segments). Increasing the buffer may not help (unless you are pausing to allow it to buffer larger amounts of video).

However, while it isn't recommended, you can change buffering amounts via the properties defined here: https://github.com/videojs/videojs-contrib-hls/blob/master/src/videojs-contrib-hls.js#L48 

Hope this helps.
