### ISSUE TITLE
Remove Buffer Management from Player API Methods

### ISSUE THREAD

**Issue by heff** [videojs/videojs-contrib-hls#131]
I'm wondering if it could be possible to disentangle buffer management from player API methods like [setCurretTime()](https://github.com/videojs/videojs-contrib-hls/blob/v0.8.3/src/videojs-hls.js#L161) and [play()](https://github.com/videojs/videojs-contrib-hls/blob/v0.8.3/src/videojs-hls.js#L130).  

For instance, we're currently using setCurrentTime to empty and refill the buffer on a seek. It seems like instead we could have something external monitoring events, like seeking, and updating the buffer independently.

Are there any specific blockers/challenges we might run into if we purse that direction, including for other API methods?

Part of the thought here is a deeper integration of Video.js with media source extensions, but either way I think this could help modularize some things. 

My current thought is introducing something like a "source handler" into video.js, that could register itself with the existing html5 or Flash tech. If the source handler's specific format was provided, the tech would pass it the source and a reference to the playback element/object. From there the tech would continue to operate with the playback object as usual, and the source handler would interact directly with the playback object, not the tech, filling its buffer as needed.

That seems like the ideal scenario at least, and removes the need for HLS to subclass a tech.

Any thoughts on that specifically? @dmlap

**Comment by dmlap** [comment]
This was completed in 1.0.
