### ISSUE TITLE
hls undefined

### ISSUE THREAD

**Issue by Mg-Yaya** [videojs/videojs-contrib-hls#1310]
HLS is working but I can't access to the hls object.

![image](https://user-images.githubusercontent.com/14295330/34364915-ee822de4-ea8a-11e7-8aae-dae6dfa9b930.png)

**Comment by mister-ben** [comment]
If it's a browser with native HLS support there would be no hls object.

**Comment by eklimas** [comment]
Do you need to wait till after the `loadstart` event before accessing?  I've been noticing with some issues I've been having that hls isn't initialized (it seems) till you hit that point.

**Comment by gesinger** [comment]
As @mister-ben said, if you are on a browser with native HLS support, there won't be an object. If you are on a browser without native HLS support, you may have to wait for the player to be ready/a `loadstart` event (as @eklimas mentioned) before accessing the object, as until the source is setup by video.js, the `hls` object won't be configured.
