### ISSUE TITLE
Problem with Chrome and large m3u8 manifests

### ISSUE THREAD

**Issue by Jrubensson** [videojs/videojs-contrib-hls#1311]
## Description
When trying to play a really long HLS manifest (roughly 13-14 hours long) the seek gets inaccurate/doesn't work. Not sure if this is a problem in the manifest itself, or a problem with videojs-contrib-hls. When using Safari and native HLS, everything works fine. Has it got something do to with Byte ranges or something on the server? Since it plays well in Safari without videojs-contrib-hls, but not in Chrome with the plugin, I guess the problem is with videojs-contrib-hls itself.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Generate a long HLS manifest
2. Try to play it with video.js + videojs-contrib-hls in Chrome.
3. Try to seek to somewhere at 9 hours into the clip.
4. The video seeks to 03:49.xx and sometimes changes the duration of the whole clip.

### Expected
Expected to be able to seek and playback the video in Chrome.

### Error output
> VIDEOJS: WARN: Problem encountered with the current HLS playlist. Aborted early because there isn't enough bandwidth to complete the request without rebuffering. Switching to another playlist.

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
videojs-contrib-hls 5.12.2
*and*
@videojs/http-streaming@0.3.0

### videojs version
what version of videojs does this occur with?
video.js 6.6.0

### Browsers
* Google Chrome

### Platforms
* Windows
* MacOS

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by vkulov** [comment]
How did you solve the issue?

**Comment by juninhocruzg3** [comment]
How did you solve the issue?
