### ISSUE TITLE
Works in Firefox and fails in Chrome

### ISSUE THREAD

**Issue by dimitrove** [videojs/videojs-contrib-hls#1312]
## Description
I have all files (.m3u8 .ts test.html etc) in the file system. I open test.html in the browser:
file:///D:/VideoStreaming/test.html

The video plays in Firefox. Chrome says "The media could not be loaded, either because the server or network failed or because the format is not supported."

videojs-contrib-hls - 5.12.2
video.js - 6.4.0
Firefox - 57.0.2 (64-bit)
Google Chrome - 63.0.3239.108
Windows 7

## Sources - test.html
`<!DOCTYPE html>`
`<html>`
`<head>`
	`<meta charset="utf-8">`
	`<link href="videojs/dist/video-js.css" rel="stylesheet">`
	
	<style>
		html, body {
			margin:0;
			padding:0;
			height:100%;
			background-color:#888888;
		}
	</style>
`</head>`

`<body>`

	<video id=videoid width=600 height=300 class="video-js vjs-default-skin" controls="controls">
		<source src="sp2017jmcshowcase_500_h264_240p.m3u8" type="application/x-mpegURL">
	</video>
			
	<script src="videojs/dist/video.js"></script>
	<script src="videojscontrib/dist/videojs-contrib-hls.min.js"></script>

	<script>
		var player = videojs('videoid');
	</script>
			
`</body>`
`</html>`

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1.
2.
3.

### Expected
Expected the video to play in Chrome but it did not.

### Error output
Chrome says "The media could not be loaded, either because the server or network failed or because the format is not supported."

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 5.12.2

### videojs version
what version of videojs does this occur with?
video.js 6.4.0

### Browsers
Firefox - 57.0.2 (64-bit)
Google Chrome - 63.0.3239.108
*

### Platforms
Windows 7
*

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by raditya-ab** [comment]
I experienced the same issue, chrome version 63.0.3239.84 (Official Build) (64-bit) on Mac High Sierra

**Comment by mjneil** [comment]
It sounds like you are just loading the page and media via the file protocol and not hosting it on a web server.  Chrome will not allow this so you will have to run a web server to serve the content over http. I'm surprised Firefox actually allows this. More Info: https://github.com/videojs/videojs-contrib-hls#hosting-considerations

**Comment by dimitrove** [comment]
Yes, it works when on a web server (Tomcat). When on the file system Chrome says something like "crossdomain access not allowed for file:". I don't understand what is "crossdomain" if everything is on the file system...

**Comment by mjneil** [comment]
>For file: URLs, each distinct file pathname is a distinct origin, but we report the problem as if it were a regular (scheme, host, port) origin.

Looks like when the file protocol is in use, chrome treats each path as its own origin even if they have the same base path. Your only options to work around this are to run a local server (recommended) or [disable browser security features](https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome) (NOT recommended)

Found from this chromium ticket https://bugs.chromium.org/p/chromium/issues/detail?id=512542

**Comment by dimitrove** [comment]
Thank you for the explanation. At least it is clear this is not a videojs problem. I will close this issue.
