### ISSUE TITLE
Unable to play a stream when the segment type is "combined"

### ISSUE THREAD

**Issue by jamesjieye** [videojs/videojs-contrib-hls#1313]
## Description

When the stream contains only audio and the segment type is "combined", a TypeError is thrown when sorting pending segments.

## Sources

Reproducible source: http://54.241.156.36/havana/playlist.m3u8

## Steps to reproduce

1. Open http://videojs.github.io/videojs-contrib-hls/
2. Change Video URL to http://54.241.156.36/havana/playlist.m3u8
3. Open the Console
4. Click [Load] button
5. You can see the error similar to the one in the following screenshot.

<img width="1279" alt="screen shot 2018-01-04 at 10 34 04 pm" src="https://user-images.githubusercontent.com/25553/34568156-e45d5110-f19f-11e7-8202-585b0cec9ae3.png">

### Expected
The video should play and you should see the black screen and hear the song Havana.

### Error output
```
Uncaught TypeError: Cannot read property 'segments' of undefined
    at videojs-contrib-hls.js:20417
    at Array.reduce (<anonymous>)
    at VirtualSourceBuffer.processPendingSegments_ (videojs-contrib-hls.js:20412)
    at VirtualSourceBuffer.done_ (videojs-contrib-hls.js:20202)
    at Worker.VirtualSourceBuffer.transmuxer_.onmessage (videojs-contrib-hls.js:20013)
```    

### videojs-contrib-hls version

`@version 5.12.2`

### videojs version

`Video.js 6.4.0`

### Browsers

* Chrome 63.0.3239.108 (64-bit)
* Firefox 57.0.3 (64-bit)

### Platforms

* macOS High Sierra 10.13.2

**Comment by jamesjieye** [comment]
It looks like the code is from `videojs-contrib-media-sources` here https://github.com/videojs/videojs-contrib-media-sources/blob/637ecf0a6d19b590f20b16eefd23b4dac1cebf7b/src/virtual-source-buffer.js#L609

**Comment by mjneil** [comment]
It looks like your audio is encoded in a format that isn't supported by the transmuxer. Right now the transmuxer can only detect audio streams of stream type 15 `ISO/IEC 13818-7 ADTS AAC (MPEG-2 lower bit-rate audio) in a packetized stream`, however your audio is stream type 4 `SO/IEC 13818-3 (MPEG-2 halved sample rate audio) in a packetized stream`. Re-encoding your audio to be ADTS AAC should correct the issue

**Comment by jamesjieye** [comment]
@mjneil, re-encoding the audio to AAC fixes my issue. Thank you!

**Comment by dainiusgliebus** [comment]
Is there a way to handle combined? like splitting or something?
