### ISSUE TITLE
Example hls encrypted

### ISSUE THREAD

**Issue by robov** [videojs/videojs-contrib-hls#1314]
Do you have an example somewhere to use videojs to playback an hls 128aes encrypted stream ?

**Comment by mjneil** [comment]
videojs-contrib-hls supports encrypted playback, all you need to do is provide your source to the player. You should be able to test it out by replacing in your source here http://jsbin.com/vokipos/8/edit?html,output

**Comment by robov** [comment]
Thanks.. I am new on encrypted hls, and have a hard time finding working examples

**Comment by robov** [comment]
Especially with providing the descryption keys to the player

**Comment by mjneil** [comment]
The decryption keys are specified within the m3u8 playlist as a media segment tag

e.g.
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:6
#EXT-X-KEY:METHOD=AES-128,URI="https://priv.example.com/key.php"
#EXTINF:6,
http://media.example.com/fileSequence0.ts
#EXTINF:6,
http://media.example.com/fileSequence1.ts
#EXTINF:6,
http://media.example.com/fileSequence2.ts
#EXT-X-ENDLIST
```

If you need help on how to generate playlists with the decryption key, this looks like it will be helpful http://hlsbook.net/how-to-encrypt-hls-video-with-ffmpeg/

**Comment by robov** [comment]
Thanks. that article indeed gave some valuable insights

**Comment by robov** [comment]
So the player requests the key by calling the supplied URI in the manifest. Is there a description of what is in that call ?
Meaning how can I protect that key calling url from being called by unauthorized people

**Comment by robov** [comment]
it looks like I need to send a session/encryption/auth stuff with the request for the key so the key software knows if this is a valid request or not. I am searching for what information I can pass with videojs and how I pass that to the site that hosts the key

**Comment by campones** [comment]
kinda make laugh to see that this and that is supported but when I m doing some test, only some streams are actually working with videojs-contrib, while they are all working with hls.js, even with a 2 years old library.

**Comment by gesinger** [comment]
Hey @robov , if you want to add session information for the requests, you can either use https://github.com/videojs/videojs-contrib-hls#withcredentials or you can modify the requests using https://github.com/videojs/videojs-contrib-hls#hlsxhr .
