### ISSUE TITLE
Android will not stream from current position on play

### ISSUE THREAD

**Issue by vespoli** [videojs/videojs-contrib-hls#1315]
## Description
In all tested android devices , in Chrome, when clicking play on a streaming source the video plays from the beginning of the source rather than the current position. Other environments including multiple desktop browsers and iOs devices behave as expected and play from the current segment.

## Sources
A paired down example here: https://davidvespoli.com/video_test/ (whose source may no longer be valid when this is reviewed so I'll post the contents of the m3u8 below)

## Steps to reproduce
1. Create a stripped down player with a valid streaming source
2. Play in Chrome on Android

### Expected
Plays from beginning segment and not the most current one

### videojs-contrib-hls and video-js versions tested
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 5.12.0 + video.js 5.20.1
videojs-contrib-hls 5.12.2 + video.js 6.6.2

**Comment by mjneil** [comment]
I believe this is a [bug](https://issuetracker.google.com/issues/36954991) with Android's native HLS implementation, which will be used by default. If you use the `overrideNative` [option](https://github.com/videojs/videojs-contrib-hls#overridenative) for Android devices, videojs-contrib-hls will be used for playback instead of Android native.

**Comment by vespoli** [comment]
Updated example with no success

**Comment by vespoli** [comment]
Added a clickable button to try to "jump" to the end:
`      player.currentTime(player.seekable().end(0));
        player.play();`

Again, works in other browsers but Android starts from the beginning.

**Comment by mjneil** [comment]
Your stream is not a live stream and contains an `EXT-X-ENDLIST` which gets interpreted as a VOD. Even desktop chrome is playing this from the start

**Comment by vespoli** [comment]
I apologize. As the live streams end I have to update the video or it will attempt to load the VOD version. Please take a look now

**Comment by mjneil** [comment]
The `overrideNative` options should go under the `html5` property e.g.
`player = videojs('example-video', { html5: config })`

**Comment by vespoli** [comment]
That worked! Came down to a misconfiguration. Thanks so much @mjneil ! Please point me in the direction of your tip jar.

**Comment by mjneil** [comment]
No problem, glad I could help! Go ahead and star the project if you feel so inclined :) Closing this issue, feel free to open a new one if you encounter more issues
