### ISSUE TITLE
Customizing

### ISSUE THREAD

**Issue by fyahb** [videojs/videojs-contrib-hls#1316]
## Description
How do I customize the player.
Ive used Video.js Skin Designer.

After I customize where do i put the info.
There is no help when customizing

Also videos is only showing on Safari no other browser. Can you tell me why.
Im trying to play a m3u8 stream
Here is my index

<html>
<head>
    <link href="http://vjs.zencdn.net/6.2.8/video-js.css" rel="stylesheet">
    <script src="hls.min.js"></script>
</head>
<body>
  <video id=example-video class"video-js vjs-default-skin" width=960 height=540 class="video-js vjs-default-skin" controls preload="auto">
  <source
     src="http://p12n-lh.akamaihd.net/i/network_delivery@428818/master.m3u8"
     type="application/x-mpegURL">
</video>
<script src="video.js"></script>
<script src="videojs.hls.min.js"></script>
<script>
var player = videojs('example-video');
player.play();
</script>
</body>
</html>

**Comment by gesinger** [comment]
Hey @fyahb , sorry this has gone for a while without much attention. If you are still experiencing the issue, would you be able to provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output)? Thanks.

**Comment by gesinger** [comment]
Closing for now. If you are still experiencing this issue with the latest version of videojs-contrib-hls, please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.
