### ISSUE TITLE
playback stucked when still downloading ts file, with hls live stream

### ISSUE THREAD

**Issue by lgyytm** [videojs/videojs-contrib-hls#1318]
video.js : https://unpkg.com/video.js/dist/video.js;
videojs-contrib-hls.js: https://unpkg.com/videojs-contrib-hls/dist/videojs-contrib-hls.js
script: 
`
window.onload = function () {
            var player = window.player = videojs('video', {
                html5: {
                    hls: {
                        // withCredentials: true
                    }
                }
            });
            player.ready(function () {
                var hls = window.hls = player
                    .tech({ IWillNotUseThisInPlugins: true })
                    .hls;
            })
        }
`
src: '//120.55.85.1:8001/proxy_ip120.55.85.1:5112/33T1HZ/KX9001201706.m3u8'

**Comment by gesinger** [comment]
Hey @lgyytm , I noticed that the stream only has 2 segments in it. The HLS specification requires at least enough segments to cover 3 target durations worth of time: https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-6.2.2

```
The server MUST NOT remove a Media Segment from a Playlist file
   without an EXT-X-ENDLIST tag if that would produce a Playlist whose
   duration is less than three times the target duration.  Doing so can
   trigger playback stalls.
```

**Comment by lgyytm** [comment]
thank you
