### ISSUE TITLE
Encryption Key Example 

### ISSUE THREAD

**Issue by robov** [videojs/videojs-contrib-hls#1320]
I understand that the manifest requests the key file somehwere... but how is the keyfile organized

This is my complete key information I get from cloudfront
But what do I put in the actual ekey.php ?

`
HLS AES
Method
aes-128
Key Storage Policy
NoStore
License Acquisition URL
https://tests1.mydemosite.com/ekey.php
Encryption Key
AQIXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0MtVHSK
Encryption Key MD5
xCYYYYYYYYYYYYYYY==
Encryption Initialization Vector
VQMZZZZZZZZZZZZZZZZZuQQ==

`

**Comment by gesinger** [comment]
Hey @robov , details for setup of EXT-X-KEY and the structure of the key file can be seen in the latest HLS specification at https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.2.4 and https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-5

Hope this helps.
