### ISSUE TITLE
This M3U8 movie is cut to the right

### ISSUE THREAD

**Issue by satanupup** [videojs/videojs-contrib-hls#1321]
## Description
use
http://jsbin.com/vokipos/8/edit?html,output
Play this video
http://productvideo-tss.study-king.com.tw:8080/hls/video_cc/video/stma1u010103/stma1u010103.m3u8?time=0&uid=1110&sid=1bfca901c54ee8102da3afcb241a835f
The film is cut to the right

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. http://epb1.ddns.me/show/egg.html
2. For Chrome ，stma1u0101030.ts ~ stma1u0101035.ts  (first fifty seconds) did not see the right side of the eraser
3. 

## Results
The film is cut to the right
### Expected
Please describe what you expected to happen that did not happen in the description.

1.No problem in Firefox，stma1u0101030.ts ~ stma1u0101035.ts ，on the right with eraser
2.No problem in win10 edge，stma1u0101030.ts ~ stma1u0101035.ts ，on the right with eraser

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:
front.js:7 Uncaught ReferenceError: browser is not defined
    at HTMLDocument.<anonymous> (front.js:7)

## Additional Information
Please include any additional information necessary here. Including the following:
Original video location
http://epb1.ddns.me/show/stma1u010103.mp4

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
https://unpkg.com/videojs-contrib-hls/dist/videojs-contrib-hls.js
videojs-contrib-hls 5.12.2
 
### videojs version
what version of videojs does this occur with?
https://unpkg.com/video.js/dist/video.js
video.js  6.6.0

### Browsers
what browsers are affected? please include browser and version for each
* Chrome  Version 63.0.3239.132 (official version) (64-bit)

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* In win7 、win10 test

**Comment by vitalimold** [comment]
As a workaround - turn off Hardware acceleration.

**Comment by satanupup** [comment]
Summary – How to disable hardware acceleration in Google Chrome
Open Google Chrome.
Click the menu button (It says Customize and control Google Chrome when you hover over it) at the top-right corner of the window.
Click Settings.
Scroll down and click the Show advanced settings link at the bottom of the window.
Scroll down to the System section and uncheck the box to the left of Use hardware acceleration when available.

**Comment by satanupup** [comment]
vitalimold 
https://www.bountysource.com/teams/videojs has paid 5 US

**Comment by satanupup** [comment]
mp4 original video is 640 * 480
But converted m3u8 video is 854 * 480
So the right side of the image is cut off
Turned out to 640 * 480 on the right will not be cut off
