### ISSUE TITLE
ABR HLS based on multiple playlists given as sources instead of single playlist file

### ISSUE THREAD

**Issue by marcusfrenkel** [videojs/videojs-contrib-hls#1326]
Hi,

For Adaptive bit rate HLS normally the player reads a single file (HLS master playlist) that points to multiple renditions of the video. In my case however, every playlist points to a single video file at different bit rate. Is it possible to achieve ABR HLS by setting up videojs with multiple sources, wherein each source is different rendition?

I setup sources in this fashion:
player.src([
{ type: 'application/x-mpegURL', src: 'http://streamer.tld:8081/vod/180p_file/playlist.m3u8' },
{ type: 'application/x-mpegURL', src: 'http://streamer.tld:8081/vod/360p_file/playlist.m3u8' }
]);

**Comment by squarebracket** [comment]
Are those playlists using byte-range requests like https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/gear1/prog_index.m3u8?

**Comment by marcusfrenkel** [comment]
Not really, here is contents from sample playlist:

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=604892,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=854x480
chunk.m3u8?nimblesessionid=5399956

**Comment by mjneil** [comment]
It looks like you are generating a Master `playlist.m3u8` file for each of your renditions that contain a single `chink.m3u8` stream file within each, is that correct? Sorry, but it is not possible to set up the player in this way. You will have to host a single Master manifest file that references each `chunk.m3u8` as a separate `EXT-X-STREAM-INF` to make use of ABR.

**Comment by marcusfrenkel** [comment]
OK, thanks a lot for letting me know.
