### ISSUE TITLE
The media playback was aborted due to a corruption problem on Chrome

### ISSUE THREAD

**Issue by chianhsieh** [videojs/videojs-contrib-hls#1329]
## Description

I got this problem after I upgraded to Chrome 64.0.3282.119. ( before this version of Chrome, there is no problem on it). Not all videos occur this errors but only few videos. 

## Sources
a multiple bitrates source on HLS format ( .m3u8 )

### Error output

I used the uncompressed videojs and videojs-contrib-hls js files. 
Here are the errors output from Chrome developer console: 

**1st Error:**
`VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. MediaError {code: 3, message: "The media playback was aborted due to a corruption…media used features your browser did not support."}`

**2nd Error:**

`VIDEOJS: ERROR: (CODE:-3 undefined) Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null. `

And more details about the 2nd errors:

```
MediaError {code: -3, type: "APPEND_BUFFER_ERR", message: "Failed to execute 'appendBuffer' on 'SourceBuffer'…The HTMLMediaElement.error attribute is not null.", originalError: DOMException: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribu…}code: -3message: "Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null."originalError: DOMException: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.
    at Object.wrapper.(anonymous function) [as appendBuffer] (/js/videojs-contrib-hls.js.2:19810:34)
    at VirtualSourceBuffer.concatAndAppendSegments_ (/js/videojs-contrib-hls.js.2:20527:29)
    at VirtualSourceBuffer.processPendingSegments_ (/js/videojs-contrib-hls.js.2:20475:14)
    at VirtualSourceBuffer.done_ (/js/videojs-contrib-hls.js.2:20202:12)
    at Worker.VirtualSourceBuffer.transmuxer_.onmessage (/js/videojs-contrib-hls.js.2:20013:22)code: 11message: "Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null."name: "InvalidStateError"stack: (...)get stack: ƒ nativeGetter()set stack: ƒ nativeSetter()__proto__: DOMExceptiontype: "APPEND_BUFFER_ERR"__proto__: Object
logByType @ videojs.6.6.3.js:498
log.error @ videojs.6.6.3.js:620
error @ videojs.6.6.3.js:23525
concatAndAppendSegments_ @ videojs-contrib-hls.js.2:20530
processPendingSegments_ @ videojs-contrib-hls.js.2:20475
done_ @ videojs-contrib-hls.js.2:20202
VirtualSourceBuffer.transmuxer_.onmessage @ videojs-contrib-hls.js.2:20013
```

**3rd Error:**

```
VIDEOJS: ERROR: (CODE:-3 undefined) Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null. 
```

more details about the 3rd error:

```
MediaError {code: -3, type: "APPEND_BUFFER_ERR", message: "Failed to execute 'appendBuffer' on 'SourceBuffer'…The HTMLMediaElement.error attribute is not null.", originalError: DOMException: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribu…}
logByType @ videojs.6.6.3.min.js:498
log.error @ videojs.6.6.3.min.js:620
error @ videojs.6.6.3.min.js:23525
concatAndAppendSegments_ @ videojs-contrib-hls.js.2:20530
processPendingSegments_ @ videojs-contrib-hls.js.2:20489
done_ @ videojs-contrib-hls.js.2:20202
VirtualSourceBuffer.transmuxer_.onmessage @ videojs-contrib-hls.js.2:20013
```

Could any one have any ideas on this? 

Many Thanks.

### videojs-contrib-hls version
videojs-contrib-hls 5.12.2

### videojs version
Videojs 6.6.3 

### Browsers
Chrome 64.0.3282.119

**Comment by chianhsieh** [comment]
debug from Chrome chrome://media-internals/


render_id: 324
player_id: 33
info: Effective playback rate changed from 0 to 1
pipeline_state: kStopped
found_video_stream: true
video_codec_name: h264
found_audio_stream: true
audio_codec_name: aac
audio_dds: false
audio_decoder: FFmpegAudioDecoder
**debug: Skipping audio splice trimming at PTS=5013291us. Found only 42us of overlap, need at least 1000us. Multiple occurrences may result in loss of A/V sync.**
video_dds: false
video_decoder: GpuVideoDecoder
audio_buffering_state: BUFFERING_HAVE_ENOUGH
video_buffering_state: BUFFERING_HAVE_ENOUGH
height: 720
width: 1280
pipeline_buffering_state: BUFFERING_HAVE_ENOUGH
duration: 6257.991317
event: PAUSE
seek_target: 5943.519392
error: audio error during playing, status: PIPELINE_ERROR_DECODE
pipeline_error: PIPELINE_ERROR_DECODE

I think the main cause is the bold line above. Is there anybody can help me to solve this issue?
Thank you.

**Comment by chianhsieh** [comment]
I uploaded a demo page to here.

http://106.186.118.214/mmm/videojshls.html

The old versions of Chrome or Safari, Firefox, IE do not have this issue. 

Please help me check the root cause.
Many thanks.

**Comment by SolmazKh** [comment]
I am having the same problem. Any news?

**Comment by avenchen** [comment]
We have the same problem, even "Version 66.0.3346.9 (Official Build) dev (64-bit)" show the same error "audio error during playing, status: PIPELINE_ERROR_DECODE"

**Comment by chanwaiyu** [comment]
We have to same problem

**Comment by gesinger** [comment]
Hey @chianhsieh , sorry this ticket has gone a while without much attention. I see that the stream is now down. Do you have any live examples we can take a look at?

**Comment by gesinger** [comment]
Appreciate the update and the details @chianhsieh ! Interesting problem and solution. It looks like that's a good solution. Closing this ticket then, and thank you.

**Comment by OlegBose** [comment]
I have the same problem STILL with just only audio .mp3 stream playback:
03-28 13:25:36.070: E/chromium(17073): [ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"Failed to send audio packet for decoding: timestamp=253805714 duration=26122 size=340 side_data_size=0 is_key_frame=1 encrypted=0 discard_padding (ms)=(0, 0)"}
03-28 13:25:36.073: E/chromium(17073): [ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"audio decode error"}
03-28 13:25:36.073: E/chromium(17073): [ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"audio error during playing, status: PIPELINE_ERROR_DECODE"}
03-28 13:25:36.074: E/chromium(17073): [ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"audio error during playing, status: PIPELINE_ERROR_DECODE"}
03-28 13:25:36.076: E/chromium(17073): [ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR PIPELINE_ERROR_DECODE

**Comment by liamtarpey** [comment]
Unrelated to this library but I have the same error playing an mp3 on Chrome occasionally using Media API > 
```
PIPELINE_ERROR_DECODE: Failed to send audio packet for decoding: timestamp=2114640 duration=36000 size=106 side_data_size=0 is_key_frame=1 encrypted=0 discard_padding (ms)=(0, 0)
```

**Comment by kieferaguilar** [comment]
I encountered this issue on Chrome 67 on a Mac. The issue was that Chrome was attempting to autoupdate, but needed to relaunch.

Go to **Chrome** -> **About Google Chrome**, and see if Chrome is trying to update. A "Relaunch" button appeared for me, which resolved the problem.

I suppose end users could run into the same issue. I have no idea how they would know how to fix the issue, and it's not exactly clear to me whether this poor experience is something videojs or users thereof can resolve or whether it is an issue with Chrome itself.
