### ISSUE TITLE
aes 128 bit stream not woring in videojs

### ISSUE THREAD

**Issue by Rushijain** [videojs/videojs-contrib-hls#1333]
## Description
I created an aes-128 bit encrypted stream using ffmpeg with '-hls_key_info_file' and playes it in videojs but only the time occurs and the loader spins but the video doesn't play. I can play the video in vlc but not in videojs

**Comment by gesinger** [comment]
Hey @Rushijain , would you be able to create a [reduced test case](https://css-tricks.com/reduced-test-cases/) using our [starter template](http://jsbin.com/vokipos/8/edit?html,output)? Thank you.

**Comment by gesinger** [comment]
Closing. If you are still having issues with the latest release of videojs-contrib-hls, please let us know (and provide a reduced test case if possible). Thank you.
