### ISSUE TITLE
the m3u8 url not play on this

### ISSUE THREAD

**Issue by keeleys** [videojs/videojs-contrib-hls#1334]
I test on https://videojs.github.io/videojs-contrib-hls/
use this url http://cdn.zhixueyun.com/lhc/index.m3u8
but is not working ...

but i can work it on  this way
```
ffplay http://cdn.zhixueyun.com/lhc/index.m3u8
```

can i help me. online and so on.

**Comment by gesinger** [comment]
Hey @keeleys , I think you might have an issue with your content. I was not able to play it in Safari (which uses native HLS playback) or Quicktime player, and while VLC loaded it (though rather slowly), it ended up freezing after a seek.

**Comment by gesinger** [comment]
Closing for now. While some players are able to work around content issues, others may not. If you're able to get the content playing in Safari (where they have relatively robust native playback, and I currently get a corruption issue when trying the stream), please let us know. Thank you.
