### ISSUE TITLE
VOD hls stream getting croped and squeezed on windows 10

### ISSUE THREAD

**Issue by Awais-cb** [videojs/videojs-contrib-hls#1335]
Hi guys i hope that you guys are doing well 

i was facing an issue while playing HLS playlist of some HLS converted videos,video is getting cropped on latest chrome while running it on windows 10 

for example this url mentioned here :
http://5.254.96.179/vjs_hls_test/player.html

if you play this video any else OS video works fine and goes well but if you run it on chrome with windows 10 OS video gets cropped without any reason i tested this HLS playlist on various other online HLS player works fine but why this happens with videojs this leaves me pretty confused.

here is the playlist url :
http://5.254.96.179/vjs_hls_test/151739507770a0d/151739507770a0d.m3u8

Thanks any help regarding this issue would be really appreciated.

**Comment by Awais-cb** [comment]
@heff @ronhopper @makotokw @dmlap @t2y is there anyone who could respond about this issue?

**Comment by forbesjo** [comment]
<img width="686" alt="screen shot 2018-03-16 at 2 27 43 pm" src="https://user-images.githubusercontent.com/7529098/37538201-40e7bfac-2926-11e8-9f97-ce2b92bf9979.png">

Is the square ratio what you're referring to as cropping? If you load the source in QuickTime you'll see that the source itself is square

**Comment by Awais-cb** [comment]
@forbesjo  sir can i please ask you one thing on which OS and browser you are testing this video?
issue commes on Windows 10 with chrome as browser
