### ISSUE TITLE
Event on video pausing to buffer

### ISSUE THREAD

**Issue by edoudou** [videojs/videojs-contrib-hls#1336]
## Description
I need to fire an event when the video is pausing to load. I can't find which one to use. Looking for the equivalent of BUFFER_EMPTY on Dash.js. Any idea ?

I also tried to watch readyState changes but it does not change at all.
It would be even better if the event is triggered when I seek to an unload position.

Thanks for the help.

**Comment by mjneil** [comment]
You should be able to use the `waiting` event on the player

**Comment by edoudou** [comment]
It seems to be doing the job, thanks you I will try it and close the issue if it's okay.

**Comment by edoudou** [comment]
Exactly what I was looking for, thanks you for the help.

**Comment by halm0291** [comment]
How do you know when the video resumes the playback?
