### ISSUE TITLE
Create React App and Hls

### ISSUE THREAD

**Issue by alexchern** [videojs/videojs-contrib-hls#1342]
Hi all,

Is there any way to play hls files with videojs in a react application created with "Create react app" (without ejecting)?

Thanks,

Alex

**Comment by Nickman87** [comment]
It's pretty straightforward.

You need to install two dependencies:
`npm install --save video.js videojs-contrib-hls`

And then you can use it as follows:

```
import React, { Component } from 'react';
import PropTypes from 'prop-types';

import videojs from 'video.js';
import 'video.js/dist/video-js.css';

//import 'videojs-contrib-hls/dist/videojs-contrib-hls.js';
// Workaround for webworkify not working with webpack
window.videojs = videojs;
require('videojs-contrib-hls/dist/videojs-contrib-hls.js');

class VideoPlayer extends Component {
    startVideo(video) {
        videojs(video);
    }
    
    render() {
        return (
                <video ref={this.startVideo} width={this.props.width} height={this.props.height} className="video-js vjs-default-skin" controls>
                    <source src={this.props.source} type="application/x-mpegURL" />
                </video>
        );
    }
}

VideoPlayer.propTypes = {
    width: PropTypes.string.isRequired,
    height: PropTypes.string.isRequired,
    source: PropTypes.string.isRequired,
};

export default VideoPlayer;
```

**Comment by alexchern** [comment]
Hi there,

Thanks for your answer. 
I ended up putting both video.min.js and videojs-contrib-hls.min.js into index.html (it works). Will try the above as it is a cleaner solution.

Thanks again,

Alex

**Comment by Nickman87** [comment]
Both should give you the same result :)

**Comment by alexchern** [comment]
Yep. But your approach should nicely package videojs libraries :-)

**Comment by gesinger** [comment]
Thanks @Nickman87 ! Closing for now, as it looks like @Nickman87 answered the question. @alexchern , please let us know if you encounter any other issues.
