### ISSUE TITLE
Event to look for when CueTracks in m3u8 gets loaded into TextTrack

### ISSUE THREAD

**Issue by varadarajana** [videojs/videojs-contrib-hls#1345]
## Description
I am trying to play an m3u8 file that has #EXT-X-CUE-OUT and #EXT-X-CUE-IN defined along with regular playlist. I have set the useCueTags to true in the player. What event do I need to listen to in order to get the textTracks. I tried using the #328 solution, but addtrack event is not getting triggered.

Here is my HTML file, removed all references to sources and other sections.

 <video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="268" 
  data-setup='{}'>
  </video>
    <script>
	var player = videojs('my_video_1', {html5: {
		hls: {
			useCueTags: true
		}
	}});

	//var player = videojs('my_video_1');
	try{
	
		player.src({
			src: 'file:///.../sampleoutput0302_modified_1.m3u8',
			type: 'application/x-mpegURL',
			useCueTags: true
		});
		player.play();

		player.textTracks().on('addtrack', function(e){
			console.log('on Add Track');
		// find out if the new track is metadata
			var track = e.track;
			if (track.kind === 'metadata') {

			// a cuechange event fires when the player crosses over an ID3 tag
			track.on('cuechange', function() {

			// in reality, there may be more than one cue active at a time
			// we'll ignore that for simplicity in this example
			console.log('found an ID3 tag!', track.activeCues[0]);
			});
		}
		});
		
		videojs('my_video_1').modechange (function(){
			let textTracks = player.textTracks();
			let cuesTrack;
			console.log('hello data loaded ');
			for(let i=0; i < textTracks.length; i++){
				if(textTracks[i].label === 'ad-cues'){
					cuesTrack = textTracks[i];
				}
			}

			cuesTrack.addEventListener('cuechange', function() {
				let activeCues = cuesTrack.activeCues;
			
				for (let i = 0; i < activeCues.length; i++) {
					let activeCue = activeCues[i];

					console.log('Cue runs from ' + activeCue.startTime +
							' to ' + activeCue.endTime);
				}
			});
		});

**Comment by gesinger** [comment]
Hey @varadarajana , you may have to wait for player.ready before listening for addtrack. But would you be able to create a [reduced test case](https://css-tricks.com/reduced-test-cases/), using our [starter template](http://jsbin.com/vokipos/8/edit?html,output) on JSBin? Thanks.

**Comment by gesinger** [comment]
Closing. If you are still having issues with the latest release of videojs-contrib-hls (after waiting for player.ready), please let us know (and provide a reduced test case if possible). Thank you.

**Comment by varadarajana** [comment]
Thank you @gesinger. I have been to get the cue loaded from the player.ads.cueTextTracks.processMetadataTracks(player, processMetadataTrack);
