### ISSUE TITLE
Help doc with Angular 5

### ISSUE THREAD

**Issue by CalibanAngel** [videojs/videojs-contrib-hls#1346]
Hi

I was trying to use videojs and video-contrib-hls with Angular 5 and it didn't work at all. So after trying few things I finally succeed to use it. So this is what I did to fix my problems.

I use in my **package.json** :
 ```
"devDependencies": { 
        "video.js": "^6.6.3" 
}
"dependencies": { 
        "videojs-contrib-hls": "^5.12.2" 
} 
```
Actually i don't know for others version but it works with these one.

You should add in **angular-cli.json** :
```
"script": [
        "../node_modules/video.js/dist/video.min.js",
        "../node_modules/videojs-contrib-hls/dist/videojs-contrib-hls.min.js"
]
```
And in your **my-component.component.ts** :
```
import ...
declare var videojs: any;
````

I hope it will help someone.

**Comment by gaglage** [comment]
Thanks a lot.  I'll chek it because I'll need it soon. Only a consideration the property in angular-cli.json  "**scripts**" .

**Comment by gesinger** [comment]
Thanks for sharing @CalibanAngel . Going to close this ticket though as it isn't a current issue.

**Comment by juninhocruzg3** [comment]
I have same problem. I can play MP4 with video.js, but I can't import the videojs-contrib-hls and video.js together in typescript to play M3U8.

Info:
- Angular CLI: 1.7.3
- Node: 8.4.0
- OS: linux x64
- Angular: 5.2.9
- video.js: 6.8.0
- Videojs-contrib-hls: 5.14.1

I use in **`.angular-cli.json`**
```
"styles": [
        "styles.sass",
        "app/akiryplayer/libs/video-js/dist/video-js.css"
      ],
      "scripts": [
        "../node_modules/mux.js/dist/mux.js",
        "app/akiryplayer/libs/video-js/dist/video.min.js",
        "app/akiryplayer/libs/video-js/dist-hls/videojs-contrib-hls.min.js"
      ],
```

I use in **`typings.d.ts`**
```
declare var videojs: any;
```

I use in **`player.component.ts`**
```
import * as videojs from '../libs/video-js/dist/video.min.js';
import * as videojsHls from '../libs/video-js/dist-hls/videojs-contrib-hls.js';

videojs['Hls'] = videojsHls.Hls;
videojs['HlsHandler'] = videojsHls.HlsHandler;
videojs['HlsSourceHandler'] = videojsHls.HlsSourceHandler;
```
```
play(video) { 
 this.videojs = videojs(this.player);
    this.videojs.src({
      src: video.src,      // Source url .m3u8
      type: 'application/x-mpegURL',
      withCredentials: false
    });
}
```

I'm getting this error:
```
video.min.js:1 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. 
MEDIA_ERR_ABORTED:1
MEDIA_ERR_CUSTOM:0
MEDIA_ERR_DECODE:3
MEDIA_ERR_ENCRYPTED:5
MEDIA_ERR_NETWORK:2
MEDIA_ERR_SRC_NOT_SUPPORTED:4
```

How can I import these two video-js libraries in the same `videojs` variable?

**Comment by vakuzmin** [comment]
please don't forget to include as well

"../node_modules/video.js/dist/video-js.min.css",

moreover here is the link to the custom component guide 

https://www.arroyolabs.com/2017/03/angular-2-videojs-component/

**Comment by lahbib** [comment]
import { videojs } from "video.js"; 

is the simplest way  :)
