### ISSUE TITLE
Allow m3u8 refresh for live streams to be paused (when player is paused)

### ISSUE THREAD

**Issue by cAstraea** [videojs/videojs-contrib-hls#1351]
## Description
I think this is the default behaviour ? 
Currently playing video will download the TS segments while paused other videos just update the m3u8 in the background. I'm asking because I have a video wall with several videos and thought could save some bandwith or it's not something to be concerned about.

**Comment by marsalRBX** [comment]
I have same issue, any thought?

**Comment by forbesjo** [comment]
We are currently thinking of ways to stop the m3u8 refresh when it is unnecessary so this at the moment is a known issue

**Comment by gesinger** [comment]
This is intended behavior for live videos, as it allows us to keep in sync with the stream, and is not usually an issue as m3u8 manifests should be relatively small. However, as @forbesjo mentioned, we are looking to add a feature that allows people to pause such an update. Going to change this issue to an enhancement pending such an addition.
