### ISSUE TITLE
Changing hls substream from script

### ISSUE THREAD

**Issue by gregfr** [videojs/videojs-contrib-hls#1352]
Greetings
I'm looking for a way to switch substream, in the same way the selector does, but but from JS.
I tried to use `videojs.Hls.xhr.beforeRequest` and change `options.uri`, but it says on the same substream for a while before switching (I guess there's some kind of caching involved).
What is the proper way to make the player switch substream from a script?

Thanks in advance

greg

**Comment by gesinger** [comment]
Hey @gregfr , if you want to try writing a custom ABR function for selecting playlists, you can do so using https://github.com/videojs/videojs-contrib-hls#hlsselectplaylist . Please let us know if that helps.

**Comment by gesinger** [comment]
Closing for now. If this doesn't help your use case, please let us know. Thank you.
