### ISSUE TITLE
Error: i is not defined after build

### ISSUE THREAD

**Issue by iseed12** [videojs/videojs-contrib-hls#1359]
Hello.

## Description
I connected the video and video modules.
`
  import videojs from 'video.js/dist/video.min.js'
  window.videojs = videojs;
  require('videojs-contrib-hls/dist/videojs-contrib-hls.min.js');
`
I configured the container to get HLS with an accessible server.
On dev machine everything works.
After creating the build and launching it on the apache2 web server, I get an error: ReferenceError: i is not defined. That's the stack http://joxi.ru/DrlNvxgFvXvnV2
debugger http://joxi.ru/p27OWpatoXo8a2
Tell me in which direction to look to isolate the error?

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 5.12.2

### videojs version
what version of videojs does this occur with?
video.js 6.6.3

### Browsers
Chrome 64, Firefox 58
*

### Platforms
Windows, Linux
*

### Other
webpack  3.11.0  
webpack-dev-server                   2.11.2

**Comment by iseed12** [comment]
In addition:
By an experienced test, I found out that the UglifyJsPlugin shutdown is working on the production server.
http://joxi.ru/L21v9g6f8Q8x5A

**Comment by mjneil** [comment]
We have had issues with webpack in the past (you can see its long history in #600) We recently released v5.13.0 of videojs-contrib-hls that is supposed to fix support for webpack. I suggest updating to 5.13.0 and see if that fixes your issue

**Comment by gesinger** [comment]
Closing. If you are still having issues with the latest release of videojs-contrib-hls, please let us know. Thank you.
