### ISSUE TITLE
Error with minified build file

### ISSUE THREAD

**Issue by sdahdaah** [videojs/videojs-contrib-hls#1365]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/vokipos/8/edit?html,output) on JSBin you can use.

After upgrading to the latest version of HLS contrib we started experiencing this issue. The problem is with the min file the non min is working with no issue. i have minified the non min and solved the issue

## Sources
Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.

link: http://rs.vod-platform.net/Embed/uwPUXEHxeBRpHcpRmaronw?responsive=1

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. download the files of contrib-hls from the https://github.com/videojs/videojs-contrib-hls/releases
2. update the files on your platform
3. click start for the player the error with show up

### Expected
Please describe what you expected to happen that did not happen in the description.

i expected a correct playback

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:

Error: Cannot find module '32' ->> ac593d6a-a963-174b-a4ca-5e7d055ef6ff:1:148
Error: Cannot find module '32'

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls x.y.z

latest online

### videojs version
what version of videojs does this occur with?
video.js x.y.z

videojs 6.6

### Browsers
what browsers are affected? please include browser and version for each
*

### Platforms
what platforms are affected? please include operating system and version or device and version for each
*

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by gesinger** [comment]
@sdahdaah thanks for reporting. We'll take a look into it.

**Comment by ecraven** [comment]
Same problem with v5.14.0, this prevents me from upgrading :-/

**Comment by sdahdaah** [comment]
We also have another issue happening on iOS devices, while watching a VOD sometimes the video goes backward in time and the playback continue to work. This is persisting with the latest version of the player.
