### ISSUE TITLE
Audio issue

### ISSUE THREAD

**Issue by Rushijain** [videojs/videojs-contrib-hls#1367]
I am using videojs to view live videofeed
i am using ffmpeg to create the video from webcam with audio encoding  'aac'
The problem is that it is player is loading only one chunk of the live feed and stops
If i don't encode the audio and giver the player a video without audio it plays correctly

**Comment by gesinger** [comment]
Hey @Rushijain , would you be able to provide a [reduced test case](https://css-tricks.com/reduced-test-cases/), using our [starter template](http://jsbin.com/vokipos/8/edit?html,output) on JSBin and provide your source so we can see what's happening? And what browser/OS are you using? Thanks.

**Comment by gesinger** [comment]
Closing for now. If you're still having trouble with the latest version of videojs-contrib-hls, please let us know (and provide a reduced test case with your source and platform details). Thank you.
