### ISSUE TITLE
Why videojs-contrib-hls does not walk Hls.xhr.beforeRequest under IOS

### ISSUE THREAD

**Issue by huanghanzhilian** [videojs/videojs-contrib-hls#1384]
Why videojs-contrib-hls does not walk Hls.xhr.beforeRequest under IOS

I now bring token on the encrypted key, and all the devices are so good. Only IOS will be wrong, it should be key to check the non - parameters. In the case of IOS, the m3u8 is played directly, and the hls.xhr code is not taken.

**Comment by gkatsev** [comment]
[iOS does not support MSE](https://caniuse.com/#feat=mediasource) and videojs-contrib-hls will defer to native implementations when available (at least on Safari on desktop).
Also answered in https://github.com/videojs/videojs-contrib-hls/issues/1216#issuecomment-319209490 and https://github.com/videojs/videojs-contrib-hls/issues/1280#issuecomment-372819768

**Comment by huanghanzhilian** [comment]
Thank you, let me unlock the doubt.
