### ISSUE TITLE
how can i event error and end at ios and android?

### ISSUE THREAD

**Issue by ZhangDewei** [videojs/videojs-contrib-hls#1388]
hello , I use videojs-contrib-hls at ios and android. when i use it at pc,  it has tech_.hls.masterPlaylistController_.tech_. but it not none at ios and android. i want to event error at ios and android. so how can i event error and end at ios and android? thank you

**Comment by Hirbod** [comment]
I would also appreciate a clean communication on this. Catching Errorevents on HLS its a pain..

**Comment by gkatsev** [comment]
by default, contrib-hls only runs on browsers that don't support HLS natively. Also, it cannot run on browsers that do not support MSE which will be iOS.
For other browsers like Android or desktop safari (which we don't officially support yet) you'd want to set the [overrideNative](https://github.com/videojs/videojs-contrib-hls#overridenative) option.

**Comment by Hirbod** [comment]
@gkatsev thanks for your answer. Do I have to set this option inside `{ html: hls{} }` ?

**Comment by forbesjo** [comment]
Here's a snippet for setting up `overrideNative` https://github.com/videojs/http-streaming#overridenative
