### ISSUE TITLE
Streams sometime get "stuck" on a segment

### ISSUE THREAD

**Issue by miyakoj** [videojs/videojs-contrib-hls#1394]
## Description
We're using Video.js and Video.js HLS to create a video wall with a page usually containing 4 or more players. All of our streams come from DVRs external to the network and VLC is used on our server for transcoding. A Node.js script restarts the transcoding process for a stream when there's a problem (which restarts the segment numbering over at 1), but that sometimes causes the player to get stuck in a loop trying to download the last segment it was downloading when the process restarted, which keeps 404ing. Reload source on error doesn't trigger. I added a double click handler on the player to trigger an error to force it to reload, but that doesn't help.

Sorry, I can't include a reduced test case because the streams are private.

## Sources
Can't provide.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Load multiple players with working live streams.
2. Temporarily kill the web server process.

## Results
Sometimes the stream doesn't resume, the current segment 404s repeatedly instead.

### Expected
The stream will resume playing when the web server comes back up.

### Error output
GET XHR http://[...]/video/3/fileSequence000085.ts [HTTP/1.1 404 Not Found 54ms]

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
5.14.1

### videojs version
6.8.0

### Browsers
what browsers are affected? please include browser and version for each
* Waterfox 56.0.4.1
* Chrome 65.0.3325.181

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* Windows 7
* Windows 10

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* videojs-errors 3.1.0

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* jQuery 3.3.1
* Angular 1.6.2

**Comment by forbesjo** [comment]
We've recently made a fix for live stream disconnects, is this still an issue for you in the latest version of video.js? Video.js 7 now includes HLS playback by default and includes https://github.com/videojs/http-streaming which is the next version of this project.

**Comment by miyakoj** [comment]
We decided to create a native desktop solution (using C# and Vlc.DotNet) because both Chrome and Firefox continuously crashed when playing multiple videos simultaneously. Thank you for following up anyway.
