### ISSUE TITLE
live streaming pre-load not working on Firefox and Chrome

### ISSUE THREAD

**Issue by sdahdaah** [videojs/videojs-contrib-hls#1396]
Hello,

when using preload auto .ts files are not being retrieved on Chrome and Firefox however it is working on Safari as it has built-in support for HLS.

The issue is related to live streaming, with VOD hls there is not issue in that.

Using latest version 5.14.1

Link to test: http://rs.vod-platform.net/kwikmotiontests/preload.html

**Comment by forbesjo** [comment]
It looks like your test page uses the hls.js library for HLS support via videojs-contrib-hlsjs, is this correct?

**Comment by sdahdaah** [comment]
Yes, i am moving to hlsjs as it could succeed the preload of live streaming. By the way it doesn’t need a test file i checked the .js file of contrib-hls and you are limiting preload to video on demand stream.

I will keep you this link for testing: http://player.l1vetv.com/videojs626a/sd2.php

**Comment by forbesjo** [comment]
I believe this project specifically won't preload live content so that the initial play always starts at the live edge and to reduce bandwidth from segments that may not be used.

**Comment by sdahdaah** [comment]
Hello,

You can let it start at the edge if we keep loading the segments and chunklist similar to JWPlayer and hls.js.

i think it is a good idea to create 3 types of preload:

none does nothing (already supported)
metadata (supported but same as auto) here we use the current preload method
auto we define a new state similar to JWPlayer preload and hlsjs have a look at the preload in this example (http://player.l1vetv.com/ktv1/) it keeps retrieving the m3u8 and ts

it will be really appreciated if we can reach this point with live and vod, for live metada won't do any effect.

Regards,

**Comment by forbesjo** [comment]
We'll consider providing a way to preload live streams in the next major version of this project at VHS (https://github.com/videojs/http-streaming), closing this and opening an enhancement there
