### ISSUE TITLE
Demo with Firefox: Specified “type” attribute of “application/x-mpegURL” is not supported.

### ISSUE THREAD

**Issue by wowcut** [videojs/videojs-contrib-hls#1401]
Hi, 

the [demo page](https://videojs.github.io/videojs-contrib-hls/) makes Firefox (v 59) throw this in console:

``
Specified “type” attribute of “application/x-mpegURL” is not supported. Load of media resource //d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8 failed.
All candidate resources failed to load. Media load paused.
All candidate resources failed to load. Media load paused.
``

Why? 

This is on Ubuntu, but I have seen this on OSX, too.  How to avoid that?

Ah, yes, sorry, i should add that the video plays, but the console message is annoying. Also I just do not understand why that happens, I would like to learn about that. Thanks!

**Comment by magikstm** [comment]
The suggested change in the referenced issue does make that message disappear.

I think this issue can be closed.

**Comment by gesinger** [comment]
Closing as per other issue. Thanks for posting!
