### ISSUE TITLE
Only audio with multiple renditions / tracks

### ISSUE THREAD

**Issue by hector** [videojs/videojs-contrib-hls#1405]
## Description
I am trying to play an audio with multiple renditions, e.g. I attach an example were the main audio is in French and I have an alternate audio in English. videojs-contrib-hls is playing the main audio (French) correctly, it is also reading correctly that there are two languages (showing them in the control bar) but when selecting the alternate rendition (English) the audio will not change.
I don't know if this is a feature that is lacking or I should write a different M3U8 file.

Test case:
http://jsbin.com/yijitogoji/1/edit?html,output

The same M3U8 is working in this other player:
https://bitmovin.com/hls-mpeg-dash-test-player/

M3U8 link:
https://s3-eu-west-1.amazonaws.com/media.voctrolabs/development/voiceful_studio/rice/audio.m3u8

M3U8 is like this:
```
#EXTM3U
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",NAME="French",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="fr"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",NAME="English",DEFAULT=NO,AUTOSELECT=NO,LANGUAGE="en",URI="video_audio_track_english.m3u8"
#EXT-X-STREAM-INF:AUDIO="audio"
video_audio_track_french.m3u8
```

### Expected
I should be able to change the audio.

### Error output
No errors thrown.

## Additional Information
I tried to follow this words from the HLS specification:
https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.4.2.1

> The URI attribute of the EXT-X-MEDIA tag is REQUIRED if the media
   type is SUBTITLES, but OPTIONAL if the media type is VIDEO or AUDIO.
   If the media type is VIDEO or AUDIO, a missing URI attribute
   indicates that the media data for this Rendition is included in the
   Media Playlist of any EXT-X-STREAM-INF tag referencing this
   EXT-X-MEDIA tag.  If the media TYPE is AUDIO and the URI attribute is
   missing, clients MUST assume that the audio data for this Rendition
   is present in every video Rendition specified by the EXT-X-STREAM-INF
   tag.

The same audio files but including a video work fine; example:
http://jsbin.com/jovoralubu/1/edit?html,output

### videojs-contrib-hls version
videojs-contrib-hls 5.12.2

### videojs version
video.js 6.4.0

### Browsers
* Chrome 65
* Firefox 59

### Platforms
* OSX 10.13

### Other Plugins
No

**Comment by namor** [comment]
Try setting AUTOSELECT to YES

Surprisingly you got the DEFAULT option to work (on bitmovin)  they renamed the option in production to is_default last tuesday

`#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",NAME="English",DEFAULT=NO,AUTOSELECT=YES,LANGUAGE="en",URI="video_audio_track_english.m3u8"`

**Comment by hector** [comment]
Thanks for the suggestion!

Still, it does not make it work :(

http://jsbin.com/rijezonira/1/edit?html,output

**Comment by hector** [comment]
Could someone at least tell me if this is a problem of my m3u8 or videojs-contrib-hls behaviour? If it is the latter I can try to dig into the code.

**Comment by hector** [comment]
I have been able to make this work with the new version 7 of video.js which uses https://github.com/videojs/http-streaming instead of videojs-contrib-hls.

**Comment by hector** [comment]
I do it like this:

```javascript
// Change audio track
const audioTrack = this.player.audioTracks().tracks_.find(track => track.language === language);
if (audioTrack) audioTrack.enabled = true;
```

I suggest you first pause the video in case it is playing, then play it again.

**Comment by murtaz53** [comment]
@hector : I am asking about audio quality not audio track. I have 2 audio quality/group i.e stereo and surround. how to switch quality stereo/surround. I have already handled audio track switch i.e english and dubbing.
![pasted_image_at_2018-09-05__11_56_am](https://user-images.githubusercontent.com/42437702/45074914-e54ed580-b102-11e8-918d-b766f94b646d.png)
see in the above image there is audio quality.

**Comment by murtaz53** [comment]
ok thanks hector

**Comment by murtaz53** [comment]
@heff : can you help?

**Comment by gkatsev** [comment]
@murtaz53 can you open a *new* detailed issue about the problem? What you're doing, what you're expecting, what's happening etc.

**Comment by murtaz53** [comment]
I have open a new detailed issue about the problem #1450
