### ISSUE TITLE
Problem with HLS and Apple Device

### ISSUE THREAD

**Issue by federicopuntoni** [videojs/videojs-contrib-hls#1413]
The first video of this website:
http://test-player-ads.s3-website-eu-west-1.amazonaws.com/

is failing both on Safari and Apple device but work well on chrome and other desktop browsers.
It's an HLS video transcoded with AWS (hlsv3).

I can't understand why this first video does not play.

The second video plays incorrectly on Chrome due to cross origin (that is not a problem) but plays well on Safari and Apple device.

### videojs-contrib-hls version
videojs-contrib-hls 5.14.1

### videojs version
video.js 6.9.0

### Other Plugins
videojs-contrib-ads 5.1.6

**Comment by forbesjo** [comment]
Hey sorry we haven't looked at this issue for a while, is this still an issue for you? If so you'll have to update your test page for debugging
