### ISSUE TITLE
Possible issue with file format selection based on browser support

### ISSUE THREAD

**Issue by mrosellini** [videojs/videojs-contrib-hls#1420]
## Description
We're seeing an intermittent issue reported by users where video playback fails. In digging into QoS logs it appears like the logic in the HLS lib that decides when to use HLS vs. an mp4 will select and try to deliver HLS to an incompatible browser like IE11 on Windows7. Or vice versa select the mp4 instead of HLS for a user on Chrome. 

## Sources
This video specifically errors out on IE11, Windows 7:
http://www.wyff4.com/article/video-kayakers-take-on-downtown-greenville-falls-2/6818390

## Steps to reproduce
1. Open link http://www.wyff4.com/article/video-kayakers-take-on-downtown-greenville-falls-2/6818390 in IE11, Windows7.
2. Video tries to play and fails.

### Expected
The video should work since a valid mp4 is available. 

### Error output
See screen shot
<img width="1440" alt="captura de tela 2018-05-09 as 15 54 35" src="https://user-images.githubusercontent.com/6998733/39839068-0895bd7c-53a9-11e8-84d4-06ff13455cc9.png">

### videojs-contrib-hls version
videojs-contrib-hls 5.14.1

### videojs version
video.js 6.8.0

### Browsers
Issue appears most often in IE11
*

### Platforms
Windows 7*

**Comment by crf19920623** [comment]
我也遇到了这个问题，在win7的ie11上无法播放，在win10的ie11上可以播放，项目急着，有没有什么解决办法

**Comment by crf19920623** [comment]
我也遇到了这个问题，在win7的ie11上无法播放，在win10的ie11上可以播放，项目急着上线，有没有什么解决办法

**Comment by crf19920623** [comment]
我也遇到了这个问题，m3u8格式的视频在WIN7的IE11上无法播放，在win10的IE11上可以播放，项目急着上线，有没有什么解决办法

**Comment by forbesjo** [comment]
There is a lot going on in your web page and it will be difficult to debug your issue. Could you include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/vokipos/8/edit?html,output) on JSBin.
