### ISSUE TITLE
videojs warning - A plugin named "reloadSourceOnError" already exists

### ISSUE THREAD

**Issue by magikstm** [videojs/videojs-contrib-hls#1427]
## Description
I see this warning in Chrome and Firefox consoles:
`VIDEOJS: WARN: A plugin named "reloadSourceOnError" already exists. You may want to avoid re-registering plugins!`

## Sources
http://jsbin.com/vokipos/8/edit?html,output
(*) I also see it locally with my own streams.

## Steps to reproduce
The warning is there before video is started.

### videojs-contrib-hls version
videojs-contrib-hls 5.14.1

### videojs version
video.js 7.0.2

### Browsers
Firefox 60.0.1
Chrome 66.0.3359.181 (Official Build) (64-bit)

### Platforms
Windows 7 x64

**Comment by diegoje** [comment]
I get the same warning here. Appeared after videoJS updated to 7.

**Comment by ChaplinWang** [comment]
Same issue here:

"dependencies": {
    "requirejs": "^2.3.5",
    "videojs": "^1.0.0",
    "videojs-contrib-ads": "^6.3.0",
    "videojs-contrib-hls": "^5.14.1",
    "videojs-flash": "^2.1.0",
    "videojs-ima": "^1.3.0",
    "webpack": "^4.8.3",
    "video.js": "^7.0.2"
  },

**Comment by femtasy** [comment]
+1 on Chrome 66 MacOS 10.13.4

**Comment by plainheart** [comment]
Yes, I have the same problem with you.

**Comment by saPhil** [comment]
Same issue here.

**Comment by giantninja** [comment]
I've been seeing the same warning after updating Videojs and videojs-contrib-hls to their latest:

```
VIDEOJS: WARN: A plugin named "reloadSourceOnError" already exists. You may want to avoid re-registering plugins!
```

and just in case it's relevant, here's the scripts I'm using:

```
<script src="https://vjs.zencdn.net/7.0.3/video.js"></script>
<script src="/js/videochat/videojs-contrib-hls.min.js"></script>
```

and screenshot of the warning:
https://imgur.com/CHk8IYQ

**Comment by gkatsev** [comment]
Video.js 7 comes with Video.js HTTP Streaming by default, which is the next generation version of videojs-contrib-hls. If you're using vjs 7 you don't need to include contrib-hls manually anymore.

**Comment by gkatsev** [comment]
Looks like that's the resolution for everyone's problem. Sorry I didn't realize earlier and thanks for everyone's patience on this.

If you're using the main Video.js script, you do not need to include videojs-contrib-hls manually as VHS is included by default and has the same functionality.

**Comment by yoko10000** [comment]
use the main Video.js 7.0.3, don't play m3u8

**Comment by yoko10000** [comment]
use the main Video.js 7.0.3, IOS11.4 ,don't play m3u8

**Comment by gkatsev** [comment]
@yoko10000 that sounds like a separate issue. Can you open a new issue and fill out the issue template?
