### ISSUE TITLE
Autoplay freeze and seek pixalate

### ISSUE THREAD

**Issue by damianxd** [videojs/videojs-contrib-hls#1429]
## Description
On Safari, autoplay works for a few seconds and then it stop and waits for the user to click on play. I know Safari and Chrome blocks the autoplay, but the player works when I don't use contrib-hls and just go with a regular mp4 file. I think it could be related to the change of the video for the next chunk. It happens too on Chrome for me, but many of my colleges couldn't reproduce the problem since autoplay didn't even start.

Another problem is the seek pixalation, it happens when we use hls contrib, but using native Safari HLS support, the video looks fine.

https://ibb.co/dm5G2d
https://ibb.co/ikTEoJ

http://jsbin.com/pojaruzama/edit?html,output

I think this is not a bug, but just a problem on my configuration. Can you help me?

## Sources
http://developer.skoletube.dk/video/3928186/97147684412242c5df0a

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Use the code on jsbin or open up the source link

### Expected
Autoplay working and seek without pixalation

## Additional Information
I'm using VOD-Nginx to deliver the ts and m3u8 content.

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 5.14.1

### videojs version
what version of videojs does this occur with?
video.js 6.9.0

### Browsers
what browsers are affected? please include browser and version for each
Safari 11.1
Chrome 66

### Platforms
what platforms are affected? please include operating system and version or device and version for each
MacOS
Windows

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
videojs-hls-quality-selector 0.0.4
videojs-contrib-quality-levels 2.0.4

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
jQuery 3.2.1

**Comment by forbesjo** [comment]
I'm not able to reproduce the autoplay then stop behavior in Chrome 67, it just completely blocks autoplay for me (as expected)

**Comment by damianxd** [comment]
Yeah, that's because I gave up on videojs-contrib-hls, I'm not using it anymore, so it works without it.
