### ISSUE TITLE
Problem with load balancer

### ISSUE THREAD

**Issue by svrakata** [videojs/videojs-contrib-hls#1431]
## Description
Hello,
I have this live stream.On every play the player is making requests to the load balancer instead to the assigned url. Any idea how to fix this? The hls settings are: 

`
                hls: {
                    withCredentials: false,
                    handleManifestRedirects: true,
                }
`

## Results
![result](https://image.ibb.co/d1BQoT/result.png)

### Expected
![expected](https://image.ibb.co/ebN4ho/expected.png)

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:
 no errors

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 5.14.1

### videojs version
what version of videojs does this occur with?
video.js 6.7.3

### Browsers
what browsers are affected? please include browser and version for each
Chrome 67.0.3396.79

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
videojs-contrib-ads

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
webpack

**Comment by forbesjo** [comment]
Would you be able to provide us a sample stream to debug?

**Comment by svrakata** [comment]
Hello, 
Thank you for your reply. 
Unfortunately the stream no longer exist and I can't provide sample for debugging.
Cheers
