### ISSUE TITLE
Incorrect Zoom for videojs player on Chrome

### ISSUE THREAD

**Issue by swaraasolutions** [videojs/videojs-contrib-hls#1443]
## Description
The player has been generated using videojs-contrib-hls plugin however when viewing on chrome the player seems to be zoomed and the portion on right is not visible. But with the same code it is visible with IE Edge, Firefox and Safari correctly

## Sources
Not Sure

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Create a basic videojs player and check the view in chrome, firefox and Safari. Chrome will display it differently.
![chrome](https://user-images.githubusercontent.com/12116208/43915890-b36a8cb4-9c29-11e8-9d90-c64c2ccbac95.png)
![firefox](https://user-images.githubusercontent.com/12116208/43915896-b75338c6-9c29-11e8-9db7-1824628e52bd.png)
![ie](https://user-images.githubusercontent.com/12116208/43915903-bae9976e-9c29-11e8-9059-4c1e6acc6442.png)

### Expected
It should show the full video instead of zoomed version
![firefox](https://user-images.githubusercontent.com/12116208/43916001-f76c24cc-9c29-11e8-8c03-bba41c8dd83e.png)

### Error output
No Errors available

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
    "videojs-contrib-hls": "^5.14.1",

### videojs version
what version of videojs does this occur with?
"video.js": "7.2.0",

### Browsers
what browsers are affected? please include browser and version for each
Chrome

### Platforms
what platforms are affected? please include operating system and version or device and version for each
Desktop + Mobile Windows 10

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
"videojs-contrib-ads": "^6.4.3",
"videojs-ima": "^1.5.1"

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
jQuery

**Comment by gesinger** [comment]
Hey @swaraasolutions , would you be able to include a [reduced test case](https://css-tricks.com/reduced-test-cases/), using our [starter template](http://jsbin.com/vokipos/8/edit?html,output) on JSBin and include the source you are using? Thank you.

**Comment by swaraasolutions** [comment]
Hi @gesinger below links for v6 and v7

V6 = http://jsbin.com/lirogavoni/edit?html,output

V7 = http://jsbin.com/qihojaluho/edit?html,output

We have identified that when we disable hardware acceleration from google chrome it seems to be working correctly.

**Comment by gkatsev** [comment]
Given that there's a lot more discussion in the other issue (https://github.com/videojs/video.js/issues/5366), I'll close this one and have us continue over there.
