### ISSUE TITLE
How to switch audio group or audio quality to auto or other in hls?

### ISSUE THREAD

**Issue by murtaz53** [videojs/videojs-contrib-hls#1445]
I am using this plugin in video js. I have added audio quality list using dropdown. how can I change current audio quality group through code?

**Comment by gesinger** [comment]
Hey @murtaz53 , you can use the video.js audio tracks API: https://docs.videojs.com/tutorial-audio-tracks.html . Hope this helps.

**Comment by gesinger** [comment]
@murtaz53 , it should be accessible through the same API. If you're still having trouble, would you be able to post an example using our [starter template](http://jsbin.com/vokipos/8/edit?html,output) on JSBin? Thanks.
