### ISSUE TITLE
Sometimes seek fails throwing error tags[i] is undefined

### ISSUE THREAD

**Issue by dananichev** [videojs/videojs-contrib-hls#145]
Due to #144 i decided to seek to the end of playlist before playback actually starts. But, sometimes tags[i] is undefined and player crashes (for example, i tried to set currentTime to 260 and all went fine, but 240 failed).

**Comment by dmlap** [comment]
This issue was filed quite awhile ago and is probably out of date. Please re-open if it's still occurring in the latest builds.
