### ISSUE TITLE
How to switch audio quality (for ex.. stereo/surround)?

### ISSUE THREAD

**Issue by murtaz53** [videojs/videojs-contrib-hls#1450]
## Description
I want to switch audio quality programmatically in video js for hls. I am using this plugin to play hls video.
In my there is 2 audio tracks (english,dubbing) and 2 audio quality (stereo,surround). I have successfully switch audio tracks programmatically. Now I have to switch audio quality programmatically.

## Sources
https://bitmovin.com/demos/stream-test?format=hls&manifest=https%3A%2F%2Fbitdash-a.akamaihd.net%2Fcontent%2Fsintel%2Fhls%2Fplaylist.m3u8

## Steps to reproduce
open the above link and load. You can see audio quality(stereo/surround) option in settings. I want to switch this quality programmatically using this plugin.

### Expected
I want to able switch audio quality through code.

### Error output
I am unable to find any solution from many days.

## Additional Information
see the audio quality option in below image. I am talking about it.

![ss](https://user-images.githubusercontent.com/42437702/45135129-6e294800-b1bb-11e8-96ee-770b85b1a7b1.PNG)

### videojs-contrib-hls version
I am using 5.14.1 version. 

### videojs version
video js version is 6.2.8

**Comment by murtaz53** [comment]
@gkatsev : can you help please?

**Comment by forbesjo** [comment]
As @gkatsev noted the `stereo` and `surround` audio groups are associated with specific rendition playlists so there isn't a way to switch between the two. Each group has an alternate track so you will see a choice of `en` or `dubbing`

**Comment by murtaz53** [comment]
ok thanks for reply.
