### ISSUE TITLE
HLS will not respond to IE11 browser for a period of time using 'videojs-contrib-hls'

### ISSUE THREAD

**Issue by Mr-zhangx** [videojs/videojs-contrib-hls#1452]
## Description
As the title suggests, I encountered this very difficult problem.I even use the demo website.(https://videojs.github.io/videojs-contrib-hls/)
Unfortunately, IE11 played for some time, and IE also did not respond.But chrome will not have the same problem.

## Sources
http://videojs.github.io/videojs-contrib-hls/

## Steps to reproduce
1. Go to the project test page: http://videojs.github.io/videojs-contrib-hls/ Using IE
2. Start the video
3. Wait for 10~30 minutes.Sometimes IE will do not respond.

### Expected
Video should keep playing

### Error output
IE did not respond.

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
videojs-contrib-hls v5.14.1

### videojs version
what version of videojs does this occur with?
video.js 6.4.0

### Browsers
IE11 11.228.17134.0

### Platforms
win10

**Comment by forbesjo** [comment]
Do you see this issue in http://videojs.github.io/http-streaming/ ? Could you provide clarification for what you're seeing in IE11? Is the program freezing or not responding?
