### ISSUE TITLE
a long m3u8 video problem

### ISSUE THREAD

**Issue by mzxjhx** [videojs/videojs-contrib-hls#1453]
## Description
where i use video.js and videojs-contrib-hls in my project to play a m3u8 media which time is long than 5hours,it cannot play with them.I get error like this:
* video.js error CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED.
* video-contrib-hls.js   Uncaught DOMException: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.

src of media:http://p2dpjkn9w.bkt.clouddn.com/recordings/z1.qingk.ceshizu0213/1539049680_1539100740.m3u8

### and i test other medias that less than 1 hour are ok, just long media get error

i would appreciate it if you can fix the problem,thanks.

**Comment by gesinger** [comment]
Hey @mzxjhx , I noticed when trying to play the m3u8 playlist via Safari alone (by pasting it into the address bar), Safari doesn't recognize the content. I think there may be an issue with the content itself.

**Comment by mzxjhx** [comment]
> Hey @mzxjhx , I noticed when trying to play the m3u8 playlist via Safari alone (by pasting it into the address bar), Safari doesn't recognize the content. I think there may be an issue with the content itself.
thanks for your replay,
my project is only in chrome. I just find that VLC media player can play it ,no other video player can no it
