### ISSUE TITLE
Videojs-contrib-hls still fetching the stream when video player has paused

### ISSUE THREAD

**Issue by tonyjhang** [videojs/videojs-contrib-hls#1459]
## Description
In order to reduce browser loading, I do a function when the hls live stream has retried playlist too many times it will pause. But it seems videojs still retry the hls source when I paused the player.

Issue like these link below:
https://jsfiddle.net/1nsmptfc/
https://imgur.com/a/yxcxLZD

If there's any information I must provide, please let me know.Thanks!

### videojs-contrib-hls version
videojs-contrib-hls 5.15.0

### videojs version
video.js 7.3.0

### Browsers
Chrome

### Platforms
Windows, MAC

### JavaScript
1. videojs-flvjs.min.js version:0.2.0

**Comment by forbesjo** [comment]
That's expected behavior, please see https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md#network-requests-are-still-being-made-while-paused
