### ISSUE TITLE
Desktop Chrome 37 "maybe" supports HLS

### ISSUE THREAD

**Issue by dmlap** [videojs/videojs-contrib-hls#148]
On a Mac running Chrome 37, `video.canPlayType('application/x-mpegURL')` is now returning "maybe". This causes the HLS tech to bow out of tech selection and the HTML tech proceeds to fail spectacularly.

**Comment by shanepoints** [comment]
@dmlap, do you know why emulation causes failure?  I was a bit worried earlier when all (emulated)android devices were failing when attempting to load hls.  Testing on the real devices revealed that the stream was loading perfectly, and playing as expected.  So why does the Chrome Android emulator cause this to fail?  I was able to reproduce this issue with the live example, http://videojs.github.io/videojs-contrib-hls/ , also. 

OS 10.11.3 
Chrome 48
