### ISSUE TITLE
Autoplay from the middle of the video inaccurate [question]

### ISSUE THREAD

**Issue by jtennen** [videojs/videojs-contrib-hls#154]
Scenario:  Upon loading the page, if the user has watched part of a video (determined by internal API call), the video automatically seeks to the saved position and begins playback.

Issue 1:  The initial seek jumps to the start of the segment immediately following the saved position, not the position itself.  Seeks performed after the video is playing are accurate.

Issue 2: Attempting the correct Issue 1 using the fixes proposed in #141 and #127 (independently of course) result in no sound.  In some test pages the 'Error no ATDS header found' assertion fails (side note, is it meant to be ADTS?), but undoing these changes will enable the sound.

To my knowledge, the videos are H.264/AAC.  Currently using the latest build as of two days ago.  Example code is below.
```javascript
videojs.options.flash.swf = 'node_modules/video.js/dist/video-js/video-js.swf';
    videojs.options.autoplay = true;
    
    // initialize the player
    var player = videojs('video');
    player.ready(function() {
    	this.volume(0.5);
    	this.one('loadedmetadata', function() {
	    	setTime(player, 12);
    	});
    });
    function setTime(player, offset) {
    	if(videojs.Hls.isSupported()) {
    		player.hls.setCurrentTime(offset);
    	} else {
    		player.one('loadeddata', function() {player.currentTime(offset);});
    	}
    }
```

The setTime() function is used to account for Safari.  Please advise if my code is incorrect, if there is a better method of handling this scenario, or if this is a known behavior that requires a workaround.

EDIT:  The above code is incorrect, due to listening for the wrong information.  The correct way to do this is as follows, after pulling 89601c9cee47405a43b9d735e380e98ada7572f4:

```javascript
// Enable autoplay
videojs.options.autoplay = true;
// initialize the player
    var player = videojs('video');
    player.ready(function() {
    	this.one('loadeddata', function() {
	    	this.currentTime(64);
    	});
    });
```
This appears to be working in Firefox, Chrome, Safari, and IE11; I'll have to check older versions of IE, and no guarantees on mobile browsers.

**Comment by q2apro** [comment]
> c) seeking during this load often (not always) results in no audio.

I stumbled over the same problem with the latest videojs. When jumping through the video, suddenly the audio stops. I have a pseudo-streaming php script (that reads byte ranges). 

Does somebody know a fix?

**Comment by forbesjo** [comment]
This is probably fixed with all the MSE changes and other changes over the years.
