### ISSUE TITLE
timeupdate event is not triggered while a video is paused

### ISSUE THREAD

**Issue by chikathreesix** [videojs/videojs-contrib-hls#160]
Because the current time is set in `drainBuffer` and it doesn't trigger `timeupdate` event, this event is not triggered when a video is paused. If the video is playing, the callback of setInterval triggers `timeupdate` every 250 millisecond so it won't be a big problem.
```js
  if (segment.discontinuity) {
    if (event.type !== 'waiting') {
      return;
    }
    this.sourceBuffer.abort();
    // tell the SWF where playback is continuing in the stitched timeline
    this.el().vjs_setProperty('currentTime', segmentOffset * 0.001);
  }
```

Therefore I would like to trigger `timeupdate` right after `vjs_setProperty` is called, however, it will be an infinite loop because `drainBuffer` is one of a callback for `timeupdate`.

So I came up with an idea below.
Like `manualTimeupdatesOn` in the original `video.js`, implement `setInterval` to trigger `timeupdate` in `videojs-hls` and call all callbacks including `drainBuffer` in the interval. And also set `featuresTimeupdateEvents` to false to avoid original `manualTimeupdatesOn` from being called.
```js
videojs.Hls.prototype.trackCurrentTime = function(){
  if (this.currentTimeInterval) { this.stopTrackingCurrentTime(); }
  this.currentTimeInterval = setInterval(vjs.bind(this, function(){
    this.player().trigger('timeupdate');
    this.fillBuffer();
    this.drainBuffer();
  }), 250);
};
```
Then `timeupdate` can be triggered right after `vjs_setProperty` is called in `drainBuffer`.
But I feel this solution is a bit redundant...

Could you tell me your opinion?

**Comment by dmlap** [comment]
False alarm on this one. fillBuffer() should now get called when the player is paused but we still should fire `timeupdate`s when we cross a discontinuity.

**Comment by dmlap** [comment]
I think we're all set with this one in 1.x. Thanks for the report!
