### ISSUE TITLE
Seek some video appear this error

### ISSUE THREAD

**Issue by diogopms** [videojs/videojs-contrib-hls#163]
I generate hls chunks using ffmpeg.

If i see the video from the begining i don't have any issues.

When i try to seek to specific part of the video appear this error.

Why?
 "Uncaught TypeError: Cannot read property 'pts' of undefined "

**Comment by Llorx** [comment]
Reopening. I'm getting this error. You can check it here: http://direct.airtek.es/#id=retransmision&event=27
