### ISSUE TITLE
Combine the flash tech and HLS tech's currentTime methods

### ISSUE THREAD

**Issue by heff** [videojs/videojs-contrib-hls#170]
As part of scoping out the [source handler interface](https://github.com/videojs/video.js/pull/1560) I'm trying to reduce the need to override existing tech methods.

The HLS tech's currentTime and Flash's currentTime are pretty similar, and it's not clear what the need for the differences is. Does anyone know the background? Could features in the HLS version be added to the Flash version?

#### [HLS](https://github.com/videojs/videojs-contrib-hls/blob/d738136511e8ef4d59dc6fa704b41cfe491f8e64/src/videojs-hls.js#L170)

```
videojs.Hls.prototype.currentTime = function() {
  if (this.lastSeekedTime_) {
    return this.lastSeekedTime_;
  }
  // currentTime is zero while the tech is initializing
  if (!this.el() || !this.el().vjs_getProperty) {
    return 0;
  }
  return this.el().vjs_getProperty('currentTime');
};
```

#### [Flash](https://github.com/videojs/video.js/blob/375cc1ecf93dbd386ef714034ff877486e8a3180/src/js/media/flash.js#L151)
```
vjs.Flash.prototype['currentTime'] = function(time){
  // when seeking make the reported time keep up with the requested time
  // by reading the time we're seeking to
  if (this.seeking()) {
    return this.lastSeekTarget_ || 0;
  }
  return this.el_.vjs_getProperty('currentTime');
};
```

**Comment by dmlap** [comment]
Fixed in the video.js 5.0 / development branch.
