### ISSUE TITLE
Seeking event never fires

### ISSUE THREAD

**Issue by heff** [videojs/videojs-contrib-hls#175]
For some reason with the interaction between the HLS plugin and the swf, the `seeking` event never fires. [It looks like it should, or at least we think it should](https://github.com/videojs/video-js-swf/blob/a41493bd27d8e9d4bcbba829848da39abb334114/src/com/videojs/providers/HTTPVideoProvider.as#L517).

I'm wondering if it has something to do with the source buffer calling abort() before updating the time. Or if `NetStream.SeekStart.Notify` just never fires in appendBytes mode. Anyone have any ideas?

The current workflow after HLS.setCurrentTime is called appears to be:

1. intercept the new time
1. tell the swf to abort the current playback (via sourceBuffer.abort())
1. buffer the new data
1. tell the swf the new currentTime
1. append the new data (sourceBuffer.appendBuffer())

The ideal workflow I'm trying to work towards (to mimic the video element) I believe would be more like:

1. tell the swf the new currentTime (immediately -- without intercepting)
1. the swf fires a seeking event (and probably aborts playback internally)
1. the HLS plugin picks up the seeking event
1. checks the currentTime (which should be reporting the target time, and currently appears to) 
1. buffers and appends the new data

Are there any other challenges in getting there that anyone can see?

**Comment by forbesjo** [comment]
I think it fires now.
