### ISSUE TITLE
Seeking issue for relatively large GOP (keyframe interval)

### ISSUE THREAD

**Issue by sevteen** [videojs/videojs-contrib-hls#186]
Steps to reproduce:
* checkout development branch
*  cd into videojs-contrib-hls and run  <b>_npm install_</b>
* open _example.html_ in browser and make sure it has no issues on seeking <br />
* Now re-encode HLS stream provided in _example.html_ to increase keyframe interval <br />
<pre>ffmpeg -i http://solutions.brightcove.com/jwhisenant/hls/apple/bipbop/gear4/prog_index.m3u8 -c:v libx264 -c:a copy <b>-g 250</b> -vprofile baseline -vlevel 2.1 -coder 0 -t 120 -f mpegts bipbop.ts</pre>
and create new playlist <br />
<pre>ffmpeg -i bipbop.ts -c:v copy -c:a copy -f segment -segment_time 10 -segment_list bipbop.m3u8 -segment_format mpegts bipbop%03d.ts</pre>
<br />
<br />
* If you change the URL to _bipbop.m3u8_ in _example.html_ and try to seek, you'll notice that video will freeze until sound "overtakes"  the frame

My guess is that hls tech sticks on a keyframe correctly, but incorrectly for audio and playback itself

<b>NOTE:</b> This is not the case for regular (non HLS) mp4 video.

Thanks

**Comment by dmlap** [comment]
This level of decoding is now handled by the browser's media playback engine. I believe the experience is improved a bunch on most platforms. If it's still lacking though, it would be an issue with the underlying browser, not something we could change in this project.
