### ISSUE TITLE
Bower does not provide dist version

### ISSUE THREAD

**Issue by eseceve** [videojs/videojs-contrib-hls#191]
Why bower does not provide dist version?

**Comment by hanfeisun** [comment]
+1

**Comment by dmlap** [comment]
The primary reason is it's a pain to manage the dist version through git (but that's not a good excuse!). @heff has spent a lot of time automating this process for the main video.js project. I'll look into how tough it would be to pull in some of that for contrib-hls.

**Comment by thais-molica** [comment]
+1

**Comment by DJLebedev** [comment]
+1

**Comment by kiaplayer** [comment]
+1

**Comment by forbesjo** [comment]
We plan on only supporting npm for our plugin projects, we don't plan on supporting bower specifically.
