### ISSUE TITLE
Player error in #4.10.2  hls#0.10.1 media-sources#0.3.0

### ISSUE THREAD

**Issue by eseceve** [videojs/videojs-contrib-hls#192]
I use videojs v4.10.2 and the last releases of videojs-hls (v0.10.1) and videojs-media-sources (v0.3.0) I have this error:

```
TypeError: undefined is not a function
    at videojs.Hls.src (.../videojs-hls.js:77:25
```

videojs-hls.js:77
```javascript
this.segmentParser_ = new videojs.Hls.SegmentParser();
```

But if I use the videojs-hls (v0.10.0) the player works but I cant destroyed it
```
TypeError: undefined is not a function
    at videojs.SourceBuffer.abort (.../videojs-media-sources.js:215:26)
```

videojs-media-sources.js

```javascript
this.abort = function() {
  buffer = [];
  bufferSize = 0;
  this.source.swfObj.vjs_abort(); // Line 215
};
```

Also, bower version of videojs-contrib-hls and videojs-media-sources does not provide dist versions.

**Comment by dmlap** [comment]
Closing since we haven't heard back. Please re-open if you're still experiencing the issue.

**Comment by TylerGarlick** [comment]
I'm seeing the exact same behavior on video.js#4.11.4, media-sources#0.3.1, hls#0.10.4

**Comment by gkatsev** [comment]
@TylerGarlick can you provide more information? Even better if you can provide a working example on jsbin or jsfiddle. Thanks.

**Comment by TylerGarlick** [comment]
Here is an example.  http://jsbin.com/repara/2/edit?html,js,console,output

Thanks!

**Comment by gkatsev** [comment]
I've updated the example to include the extra necessary files and I don't see the error in the first comment.
http://jsbin.com/jasujijazu

**Comment by vladutzik** [comment]
Hey guys, i'm trying to fix HLS video in Chrome, and it's a hell. I can't get it why it doesn't work. It works perfectly in safari and it works on mobile version on Android, but it won't start in Chrome.

My console is screaming like: "Uncaught TypeError: videojs.Hls.SegmentParser is not a function" 
or when i try to press play button it throws "Uncaught TypeError: Cannot read property 'media' of undefined".

Anybody can give me some clues how to fix this?

Thanks in advance.

**Comment by dmlap** [comment]
@vladutzik have you followed the steps from our [example page](http://videojs.github.io/videojs-contrib-hls/)?
