### ISSUE TITLE
player halts when tab loses focus

### ISSUE THREAD

**Issue by orcaman** [videojs/videojs-contrib-hls#196]
I have noticed that if I play a video and switch to a different tab on Chrome, after a certain amount of time (running the example on the dev env - http://127.0.0.1:9999/example.html - it happens after about 40 seconds of me browsing around in other tabs), the video pauses. I guess this might be intentional (to save bandwidth or for some other reason) but in my use case I would like to disable this, so that the video keeps on playing regardless if the user has switched to another tab. 

Any pointers on how I can change this? 

Cheers

**Comment by dmlap** [comment]
contrib-media-sources has a fix for this in version 0.3.1. If you use the latest in that project, you should not see this issue any longer.

**Comment by colt082295** [comment]
This issue is still happening for me. All packages at their latest versions, etc.
