### ISSUE TITLE
Errors + Livestream Update method

### ISSUE THREAD

**Issue by needo2** [videojs/videojs-contrib-hls#197]
1) I'm getting a waterfall off
video.dev.js:317 Uncaught TypeError: Cannot read property 'handlers' of undefined
videojs.hls.js:793 Uncaught TypeError: Cannot read property 'uri' of undefined
videojs.hls.js:641 Uncaught TypeError: Cannot read property 'key' of undefined
Errors, constantly never ending

    <script>
        $("video").each(function () {
            var instance = this;
            $(instance).parent().mouseover(function () {
                player.play();
            });
            $(instance).parent().mouseout(function () {
                player.pause();
            });
            var player = videojs(instance.id);
            player.muted(true);
        });
     </script>

2) I have small preview videos that I play on mouseover, they sometimes stuck forever in loading
Quite frankly if loading spinner ever pops up, it never loads

3) I also want to make them abandon the current track and go live when I hover them

4) Why does it have access origin problem even that it's flash player?
Nevermind apparently Flash blocks cross-origin .ts files as well

Great project by the way, made my dreams come true

**Comment by dmlap** [comment]
Do you have a publicly available example anywhere we could use to debug?

**Comment by needo2** [comment]
I will in a few hours

**Comment by dmlap** [comment]
Haven't heard back on this one for awhile so I'm going to close it. Feel free to re-open it if you're still running into issues with the latest version.
