### ISSUE TITLE
Distribute videojs-contrib-hls.js under an open source license

### ISSUE THREAD

**Issue by berndfo** [videojs/videojs-contrib-hls#200]
Currently, "videojs-hls.js" (see https://github.com/videojs/videojs-contrib-hls/blob/master/src/videojs-hls.js ) is not available under an open source license. The header reads

```
/*
* videojs-hls
*
* Copyright (c) 2014 Brightcove
* All rights reserved.
*/
```
which basically means it cannot be redistributed at all.

When will it be freely distributable for example under ASL 2.0 as video.js currently is?

Thanks!

**Comment by gkatsev** [comment]
The license is Apache 2. The file header is wrong. See the license file in the repo: https://github.com/videojs/videojs-contrib-hls/blob/master/LICENSE

**Comment by berndfo** [comment]
Indeed, it looks like you say. However, as far as I know, the current file header is overriding what's in the LICENSE file, especially if videojs-hls.js is distributed without the license and without the rest of the files, which seem likely to me. So unless the header is changed, JS code cannot be used legally without prior permission from Brightcove.

Thanks again for all the great work on video.js.

**Comment by gkatsev** [comment]
Given that we're shipping this project as a whole, the main license is the one that matters. It's mostly pointless to just use the `videojs-hls.js` file by itself. However, yes, we definitely should fix that.
