### ISSUE TITLE
EXT-X-KEY URI processing not to spec.

### ISSUE THREAD

**Issue by stevemayhew** [videojs/videojs-contrib-hls#202]
The spec ([HTTP Live Streaming - Section  3.1](https://tools.ietf.org/html/draft-pantos-http-live-streaming-13#section-3.1) says URI should be relative to the playlist:

>  "A URI in a Playlist, whether it is a URI line or part of a tag, MAY
>   be relative.  Relative URIs MUST be resolved against the URI of the
>   Playlist file that contains it."

Here is a very short sample m3u8 that demos the issue: http://flashls-test.s3.amazonaws.com/7_copy.m3u8

And here is a branch with a proposed fix:  https://github.com/stevemayhew/videojs-contrib-hls/tree/fix-keyurl

I'm happy to add unit tests and submit the pull request with a little guidance as to which specific JS modules/sample playlist I should add them (I'm guessing the m3u8_test.js?)

Thanks!

**Comment by dmlap** [comment]
@stevemayhew nice find! Can you open up a PR so we can comment on the change more easily?

**Comment by stevemayhew** [comment]
Sure.  Will do

**Comment by stevemayhew** [comment]
@dmlap The first checkin failed jsHint, that is fixed.  The top of tree for the branch passes all the build tests (on my mac).   Here's the pull request.  Let me know if/where I should add tests:
https://github.com/videojs/videojs-contrib-hls/pull/203

Also I'm looking at an issue with video/audio sync for the same stream.  I'll try to extract the transport streams that cause the issue.

**Comment by dmlap** [comment]
Fixed via https://github.com/videojs/videojs-contrib-hls/pull/203
