### ISSUE TITLE
`video-hls.min.js` are not installed by bower

### ISSUE THREAD

**Issue by hanfeisun** [videojs/videojs-contrib-hls#204]
I use `bower install videojs-contrib-hls`, but found there is no `dist` folder in the `bower_components/videojs-contrib-hls` folder.. Is it possible for videojs-contrib-hls add the `video-hls.min.js` for bower package?

**Comment by hanfeisun** [comment]
currently there isn't a "concatenated" js file, so I need to import every js file in my HTML page if I don't want to use `npm install` and `grunt build` in the `video-hls` folder..

**Comment by dmlap** [comment]
We'd have to make some pretty significant changes to our release process to address this. I'll think on how best to approach that.

**Comment by Maypeur** [comment]
Why don't you provide the easiest solution ? A simple videojs-contrid-hls.min.js instead of making the more complicated way of using 3rd party software like npm, grunt who no ones want ?

**Comment by cadesalaberry** [comment]
What about taking the `dist/*` out of the `.gitignore` so that changes get updated after each commits ?

**Comment by mgreer** [comment]
Agreed: had to do this locally anyway in order to commit the built file.

**Comment by evanbeard** [comment]
+1

**Comment by numbata** [comment]
+1

**Comment by cladera** [comment]
+1

**Comment by muratakbal** [comment]
+1

**Comment by Cweili** [comment]
+1

**Comment by dmlap** [comment]
Some status update for folks hanging on to this thread: we've tried to formalize a release process that commits the dist/ as part of the [plugin generator](https://github.com/videojs/generator-videojs-plugin) project. Our focus right now is making sure 1.x aka MSE playback supports all the streams that the old Flash version did but once that is stabilized we'd like to adopt the build and publishing processes in the generator (which would add bower support to all tagged releases). If anyone wanted to take a stab at migrating over the plugin generator's publishing process before we get to it, PRs are always welcome!

**Comment by kohey18** [comment]
+1

**Comment by smilemd** [comment]
up, +1

**Comment by jetway-software** [comment]
+1

**Comment by ssurana2** [comment]
+1

**Comment by gkatsev** [comment]
No need to post any more +1, please use the new github reaction feature to show your support instead.

**Comment by gesinger** [comment]
As of video.js 6, bower is no longer officially supported (see https://github.com/videojs/video.js/issues/4012). As mentioned in the video.js issue, there are bower-npm resolvers to help manage dependencies on npm when using bower. Please use those if you need support for your bower setup. Thank you.
