### ISSUE TITLE
hls for live streaming works just after stopping the stream

### ISSUE THREAD

**Issue by yurevich1** [videojs/videojs-contrib-hls#207]
While streaming video shows nothing. But it starts just after rtmp streaming stop. How to fix it?

**Comment by gkatsev** [comment]
Are you trying to play back an RTMP stream? If so, you should open an issue against the main videojs repo as this plugin is strictly for HLS.

**Comment by yurevich1** [comment]
hls, of course. If I open realtime stream (nginx + rtmp to hls) on my iPad - all works correctly. But if I open stream in hls - nothing.
The debugger in Chrome  says all files are downloaded. Very strange - the are downloaded but never play.

index.m3u8:

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:15
#EXT-X-DISCONTINUITY
#EXTINF:10.000,
10.ts
#EXTINF:10.000,
11.ts
#EXTINF:10.000,
12.ts
#EXTINF:10.000,
13.ts
#EXTINF:10.000,
14.ts
#EXTINF:10.000,
15.ts
#EXTINF:10.000,
16.ts
#EXTINF:10.000,
17.ts
#EXTINF:10.000,
18.ts
#EXTINF:10.000,
19.ts
#EXTINF:10.000,
20.ts
#EXTINF:10.000,
21.ts


The flash begin to play when server write into end of the file:
#EXT-X-ENDLIST

**Comment by dmlap** [comment]
@yurevich1 I think we'll need a test stream to be able to debug this properly. Do you have a public URL that demonstrates the issue?

**Comment by dmlap** [comment]
Closing this because we haven't heard from @yurevich1. Please re-open if you're able to provide a test stream to debug.
