### ISSUE TITLE
Add support for MP3 audio

### ISSUE THREAD

**Issue by rdgRmCore** [videojs/videojs-contrib-hls#209]
There is a todo in the segment parser to add MP3 support. Can this be added?

I can see that videojs can play back .mp4 files that have mp3 audio. So, it should be able to play back the transport streams that contain mp3 audio. 

I would like this support to be added.
I have been reading through the code and it looks like what is needed is to add a window.videojs.Hls.Mp3Stream
similar to what exists for AacStream. Or is there another approach that should be used?
One question I have is about the audiocodecid. In the aac-stream.js there is this line:

          // AAC is always 10
          aacFrame.writeMetaDataDouble("audiocodecid", 10);

What should the audiocodecid be set to for MP3 audio?

**Comment by dmlap** [comment]
Yes, we would need a class similar to AacStream that would collect and translate MP3 data to get appended into the SWF. If you're interested in adding that support, check out #3. @raytiley gave this a shot and we never got around to merging it because a bunch of refactoring was going on.

**Comment by rdgRmCore** [comment]
Thanks for the pointer. I will check it out.

**Comment by rdgRmCore** [comment]
@dmlap, 
I made the changes based on the previous work of @raytiley.
I tested the changes localy with a test stream and the audio track played back.
The changes are on the master branch of my fork.
Should I create a pull request?

**Comment by gkatsev** [comment]
If you think it's good for review, go ahead an open a PR :)

**Comment by rdgRmCore** [comment]
@gkatsev 

I tried to create the pull request.
The Travis CI is failing.
It looks like some tests are failing on the new Mp3 class.
I am not sure how to proceed.
I am not sure what exactly is failing.
I don't know how to run the tests locally.

**Comment by gkatsev** [comment]
You can see the test output on travis: https://travis-ci.org/videojs/videojs-contrib-hls/builds/50511160#L339
You can run the tests by simply running `npm test` inside the project.
Also, check out the [CONTRIBUTING.md](https://github.com/videojs/videojs-contrib-hls/blob/master/CONTRIBUTING.md) which has more info.

**Comment by rdgRmCore** [comment]
I am running Ubuntu and this is what happens when I run npm test:

npm test

> videojs-contrib-hls@0.10.4 test /home/rdg/projects/videojs-contrib-hls
> grunt test

sh: 1: grunt: not found
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

**Comment by gkatsev** [comment]
You need to install `grunt-cli` locally. See https://github.com/videojs/videojs-contrib-hls/blob/master/CONTRIBUTING.md#modifying-the-code

**Comment by rdgRmCore** [comment]
@gkatsev 

Thanks for all your help. I am now able to run the tests locally. However, the output doesn't make a whole lot of sense. Here is the first error as far as I can tell.

<pre>
[1A[2K[31mChrome 40.0.2214 (Linux) segment parser creates an flv header FAILED[39m
	beforeEach failed on creates an flv header: undefined is not a function
	TypeError: undefined is not a function
	    at new videojs.Hls.SegmentParser (/home/rdg/projects/videojs-contrib-hls/src/segment-parser.js:24:19)
	    at Object.module.setup (/home/rdg/projects/videojs-contrib-hls/test/segment-parser.js:42:16)
	    at runHook (/home/rdg/projects/videojs-contrib-hls/node_modules/qunitjs/qunit/qunit.js:916:20)
	    at process (/home/rdg/projects/videojs-contrib-hls/node_modules/qunitjs/qunit/qunit.js:573:24)
	    at begin (/home/rdg/projects/videojs-contrib-hls/node_modules/qunitjs/qunit/qunit.js:618:2)
	    at /home/rdg/projects/videojs-contrib-hls/node_modules/qunitjs/qunit/qunit.js:634:4
	
	Died on test #2     at /home/rdg/projects/videojs-contrib-hls/test/segment-parser.js:46:3
	    at /home/rdg/projects/videojs-contrib-hls/test/segment-parser.js:375:3: Cannot read property 'getFlvHeader' of undefined
	TypeError: Cannot read property 'getFlvHeader' of undefined
	    at Object.<anonymous> (/home/rdg/projects/videojs-contrib-hls/test/segment-parser.js:47:51)
	    at Object.Test.run (/home/rdg/projects/videojs-contrib-hls/node_modules/qunitjs/qunit/qunit.js:885:28)
	    at /home/rdg/projects/videojs-contrib-hls/node_modules/qunitjs/qunit/qunit.js:1014:11
	    at process (/home/rdg/projects/videojs-contrib-hls/node_modules/qunitjs/qunit/qunit.js:573:24)
	    at begin (/home/rdg/projects/videojs-contrib-hls/node_modules/qunitjs/qunit/qunit.js:618:2)
	    at /home/rdg/projects/videojs-contrib-hls/node_modules/qunitjs/qunit/qunit.js:634:4
	
</pre>

It seems like there is a problem creating an object. I don't know what line of code is failing. Can you tell what line of code is failing from the output?

**Comment by gkatsev** [comment]
Seems like there an issue on line 24 of the segment-parser.js:
```sh
    TypeError: undefined is not a function
        at new videojs.Hls.SegmentParser (/home/rdg/projects/videojs-contrib-hls/src/segment-parser.js:24:19)
```

Also, you can open the `test/videojs-hls.html` file in a browser and use the debugger to pause on expections.

**Comment by rdgRmCore** [comment]
@gkatsev 

OK. Thanks for taking a look. I was confused because there are two segmet-parser.js files. One of them is under test the other is under src.

It seems like when the unit test is running that it doesn't know about the Mp3Stream class that is in the file src/mp3-stream.js

How do tell the tests where to find mp3-stream.js?

**Comment by gkatsev** [comment]
You'd need to add it to both the `videojs-hls.html` and the `karma.conf.js` files in the appropriate place.

**Comment by rdgRmCore** [comment]
@gkatsev 

Thanks again for your help. The tests pass locally. The Travis CI build completed.

**Comment by forbesjo** [comment]
See my comment here https://github.com/videojs/videojs-contrib-hls/pull/214#issuecomment-158205285 could you update your PR?
