### ISSUE TITLE
How can i use videojs-contrib-hls

### ISSUE THREAD

**Issue by shivamg705** [videojs/videojs-contrib-hls#220]
How can i use videojs-contrib-hls to play a m3u8 file streaming through wowza media server.I have download videojs-contrib-hls and copy in apache2 sever and open example.html and found lots of errors in console of broswer

**Comment by dmlap** [comment]
Have you checked out the [Getting Started](https://github.com/videojs/videojs-contrib-hls#getting-started) section of the README?

**Comment by dmlap** [comment]
I'm going to assume the README was sufficient. Feel free to comment again here if you're still running into issues.
