### ISSUE TITLE
Support for WebVTT

### ISSUE THREAD

**Issue by ntadej** [videojs/videojs-contrib-hls#226]
It would be nice to have WebVTT support in HLS.

I found this example that is not crossdomain protected:
http://cdnbakmi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_uka1msg4/flavorIds/1_vqhfu6uy,1_80sohj7p/format/applehttp/protocol/http/a.m3u8

**Comment by gkatsev** [comment]
Yes, it would. Especially since videojs now has really nice vtt support.
Unfortunately, it's unlikely we'll get to that any time soon.
However, if you are willing to submit a PR, we'll gladly review it.

**Comment by squarebracket** [comment]
The changes in #681 allows for doing this easily now, yes? I didn't dig into the code too much, but based on what's written [here](https://github.com/videojs/videojs-contrib-hls/blob/master/docs/multiple-alternative-audio-tracks.md#startup-how-tracks-are-added-and-used), it looks like a similar flow could be used to implement handling the WebVTT playlist + segments.

**Comment by BrandonOCasey** [comment]
Yeah the flow would probably be similar to what is outlined there

**Comment by mjneil** [comment]
This is happening in #1064 !Keep an eye on the PR for updates. Closing this issue for now.

**Comment by squarebracket** [comment]
:tada: :champagne:
