### ISSUE TITLE
How to abort playing and downloading segment?

### ISSUE THREAD

**Issue by ysksuzuki** [videojs/videojs-contrib-hls#234]
I want to abort playing and downloading segment, and display error message immediately, when a segment download is failed. But xhr continue to move forward ignoring the error. I tried to add error handling like below but it didn't work. Please tell me how to handle it correctly.

I would really appreciate your help.

```
videojs.on('error', function () {
      var mediaError = videojs.error();
      if (goog.isDefAndNotNull(mediaError) && goog.isDefAndNotNull(mediaError.status)) {
        if (mediaError.status == 503) {
          this.error({'message': 'Service Unavailable')});
        } else if (mediaError.status == 403) {
          this.error({'message': 'Forbidden')});
        } else {
          this.error({'message': 'Other error'')});
        }
      }
    });
```

**Comment by dmlap** [comment]
This isn't configurable behavior right now in the tech. Our principle has been "keep on playing if it is at all possible". We would be open to a PR that added an event whenever a segment download error occurred, if you're up for it.

**Comment by ysksuzuki** [comment]
@dmlap I see. I'll try it.

**Comment by dmlap** [comment]
We now temporarily blacklist playlists with segments that are too slow to download or error.
