### ISSUE TITLE
Quality switching repeats chunks

### ISSUE THREAD

**Issue by ntadej** [videojs/videojs-contrib-hls#236]
We have some problems with our live streams on quality switching. Some chunks get repeated after switch.

Details what happens on quality switch:
 - all already downloaded chunks from previous quality play to the end
 - video freezes but audio repeats from one or two chunks from new quality
 - after that audio/video are in sync again and video plays normally

Note that our streams might not have ADTS header available at start (error Assertion failed: Error no ATDS header found).

Our streams do not have audio and video aligned. PR #213 helps with that and does not affect quality switching.

I have sent the private test URL to email to @dmlap.

**Comment by dmlap** [comment]
#213 has been merged and some additional fixes have been merged in the meantime. Are you still seeing this issue in master, @ntadej?

**Comment by ntadej** [comment]
Unfortunatelly, yes. There don't seem to be any visible improvements. In some cases it even took longer for playback to recover to normal state.
