### ISSUE TITLE
Duration of entire media clip isn't updated, even though durationchange is triggered

### ISSUE THREAD

**Issue by jstarpl** [videojs/videojs-contrib-hls#237]
Sometimes (esp. considering short clips, around 5s length, but for longer ones too), when Flash tech is used for playback of HLS media, the duration available in the main player code doesn't get updated. The HLS duration() and updateDuration() functions get called and return proper values, however Video.JS doesn't get them and displays an invalid duration in the UI and returns invalid value for videojs().duration().

**Comment by jstarpl** [comment]
I've managed a quick fix, however I'm not well versed in the structure of the plugin to know if this is a good way to fix this.

`--- "a/videojs.hls-21daf1f-left.js"
+++ "b/videojs.hls-d7f9669-right.js"
@@ -360,6 +360,7 @@ videojs.Hls.prototype.updateDuration = function(playlist) {
   // if the duration has changed, invalidate the cached value
   if (oldDuration !== newDuration) {
     player.trigger('durationchange');
+    player.duration(newDuration);
   }
 };`

**Comment by forbesjo** [comment]
We believe this is fixed, if this is still a problem with the latest version please let us know!
