### ISSUE TITLE
Overriding player.hls.selectPlaylist crashes video if you provide old playlist reference

### ISSUE THREAD

**Issue by vasklund** [videojs/videojs-contrib-hls#238]
Essentially,

**this works:**
```javascript
var userSelectedQuality = 720;

player.hls.selectPlaylist = function () {
  return player.hls.playlists.filter(function (playlist) {
    return playlist.attributes.RESOLUTION.height === userSelectedQuality;
  });
}
```

**but this doesn't work:**
```javascript
var userSelectedQuality = 720;

var selectedPlaylist = player.hls.playlists.filter(function (playlist) {
  return playlist.attributes.RESOLUTION.height === userSelectedQuality;
});

player.hls.selectPlaylist = function () {
  return selectedPlaylist;
}
```

The reason the latter fails is because when selecting a new, unused playlist for the first time (e.g. switching quality), an ajax request is made, and upon finishing does a deep clone and merge of the `player.hls.playlists.master` object, so the `selectedPlaylist` variable above is referencing an old object not in `player.hls.playlists.master` anymore. This causes errors and completely crashes videos.

Admittedly, the documentation for `player.hls.selectPlaylist` states
> You must, however, be sure to return a valid media playlist object that is present in player.hls.master.

but there is no hint that playlists objects are overwritten, not simply updated, after some async playlist updates.

At the very least, I suggest the documentation be updated to mention this, but I'm also interested in knowing if there's any reason not to accept "old" playlist objects in `loader.media` too, to make code like the above work. I got this working pretty easily by making two small changes in `loader.media`:

after
```javascript
if (typeof playlist === 'string') {
  if (!loader.master.playlists[playlist]) {
    throw new Error('Unknown playlist URI: ' + playlist);
  }
  console.log('playlist = loader.master.playlists[playlist];', playlist)
  playlist = loader.master.playlists[playlist];
}
```

I added

```javascript
// make sure we always use the newest playlist object, even if an old reference was passed in
playlist = loader.master.playlists[playlist.uri];
```
and 

```javascript
if (loader.master.playlists[playlist.uri].endList) {
```

can then also be simplified to

```javascript
if (playlist.endList) {
```

**Comment by vasklund** [comment]
I'd be happy to prepare a PR, I just want to make sure I'm not missing anything (in the latter case, updating the code).

**Comment by dmlap** [comment]
Everything in your report sounds correct. I'm not totally sure whether it's worth the extra code to support using an out-of-date playlist in selectPlaylist() but if it's just a tiny update, it doesn't seem like a bad thing. If it's easy to put together a PR to discuss, that would be great. Thanks!

**Comment by forbesjo** [comment]
Is this still an issue?
