### ISSUE TITLE
Two HLS streams, different resolution: no video in one of them [question]

### ISSUE THREAD

**Issue by Ulv** [videojs/videojs-contrib-hls#239]
We have some playback problems with our streams.

Details on problem: we have 2 live HLS streams

* Video: H.264, _1280x736_, 30fps Audio: MPEG AAC, 48Khz
* Video: H.264, _1920x1080_, 30fps Audio: MPEG AAC, 48Khz

First stream plays fine in videojs, second - no video (only sound).

Streams:

* normal playback: http://live.kinetiksoft.com/video/cam17.m3u8
* no video in videojs: http://live.kinetiksoft.com/video/cam11.m3u8

We want to use videojs in our platform, so we are willing to donate 100$ for quick solution.

**Comment by dmlap** [comment]
Hi @Ulv, it's not obvious to me why your second stream isn't displaying video but if you can keep them live for awhile, we'll try to take a look.

**Comment by Ulv** [comment]
Thank you very much for reply @dmlap! We will keep our streams live.

**Comment by dmlap** [comment]
@Ulv seems to be working for me in master now.
