### ISSUE TITLE
Using EVENT playlist, seeking is not possible

### ISSUE THREAD

**Issue by jadzik1956** [videojs/videojs-contrib-hls#242]
Hello,

according to apple playlist documentation using event type playlist it is possible to seek anyway in the event from the beginning. But this doesn't work for me - always playing live. There is  just text "LIVE" instead of seek bar.  
OS: WIN7
Flash: 17.0

m3u8 playlist content:
#EXTM3U
#EXT-X-PLAYLIST-TYPE:EVENT
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:9.520000,
57.ts

......
#EXTINF:8.000000,
165.ts
#EXTINF:8.000000,
166.ts
#EXTINF:9.160000,
167.ts

**Comment by dmlap** [comment]
This is an issue with the video.js skin and live content-- programmatically, you can seek during live streams if you'd like. We don't have plans right now to add seeking capabilities to the base video.js live skin but would definitely be open to a PR!

**Comment by dmlap** [comment]
A better live skin should probably be handled in video.js itself or a stand-alone plugin. Closing the issue here but it would still be very cool if someone was looking for a project.
