### ISSUE TITLE
WebCam Live streaming ?

### ISSUE THREAD

**Issue by ychoucha** [videojs/videojs-contrib-hls#247]
Hello,

can we make a webcam live streaming ?

**Comment by dmlap** [comment]
If you're looking to stream to a small audience (1-10), you're probably better off with a peer-to-peer solution involving [WebRTC](http://www.html5rocks.com/en/tutorials/webrtc/basics/).

This project can live stream to large audiences but you'd have to setup a streaming server or work with a service provider first. [Wowza](http://www.wowza.com/forums/content.php?88-How-to-configure-Apple-HLS-packetization-%28cupertinostreaming%29) is one possibility if you want to try setting up your own live server, or you could checkout a service like [Zencoder](http://blog.zencoder.com/2013/07/01/transcoding-and-live-streaming-with-zencoder-s3-cloudfront/) if you don't want to go through that hassle.
