### ISSUE TITLE
HLS playback not working if techOrder set

### ISSUE THREAD

**Issue by gotling** [videojs/videojs-contrib-hls#248]
I am building a player that will play both HLS streams and Youtube videos.

To play Youtube videos I need to add *"youtube"* to techOrder.

Problem is that HLS streams stop working if I do so.

[GitHub repository with examples](https://github.com/gotling/video-js-hls-youtube)

**Comment by gkatsev** [comment]
By default this tech adds itself to the tech order in the beginning. But if you're setting a custom tech order, you need to make sure to add hls back in. The tech name is `hls` and should probably come before `html5` in the tech order list.

**Comment by gotling** [comment]
Ok, that was easy enough to fix. Is there any documentation mentioning the the tech name `hls`? I couldn't find it.

**Comment by gkatsev** [comment]
I guess this would be the closest: https://github.com/videojs/videojs-contrib-hls#options
