### ISSUE TITLE
blank screen 

### ISSUE THREAD

**Issue by imdummyhelpme** [videojs/videojs-contrib-hls#254]
i followed the instructions given on readme and i tested the to see if it was issue with the m3u8 file here using videojs hls example http://www.flashls.org/videojs/flash_demo.html it played fine. However when i used  videojs-contrib-hls the m3u8 file doesn't play it shows an blank screen. I'm not sure if im doing something wrong i'm new to js any help will be appreciated.

Here is link for index https://github.com/imdummyhelpme/imdummyhelpme.github.io/blob/master/index.html

**Comment by ReggiePuksta** [comment]
if you just use `videojs('test-vid')` and delete `player.play()` it should work.
Otherwise you might have wrong script sources. You can use Chrome dev tools Network tab. There you can see all resources that were loaded. Use ctrl+shift+i to bring it up and choose network tab.

**Comment by imdummyhelpme** [comment]
i tried that  but still doesnt work im sending screenshot of network tab http://i.imgur.com/Yv8kr7b.png thanks for helping http://imdummyhelpme.github.io/index.html i made git page as well

**Comment by ReggiePuksta** [comment]
If you open your Console tab on Chrome Dev tools you will see that your server that contains .m3u8 file doesn't have CORS headers setup. I guess you are using Wowza server, so this might help: http://www.wowza.com/forums/showthread.php?21818-Adding-CORS-to-the-HTTP-header
There is probably a way to do it through the Wowza Manager UI as well.

**Comment by imdummyhelpme** [comment]
I don't think m3u8 file is the issue because when I tested the same file at  http://www.flashls.org/videojs/flash_demo.html it works fine I tried couple of other players as well they all work fine with same file its just that I like videos player framework  better then the other ones

**Comment by ReggiePuksta** [comment]
As far as I know that flasHLS and videojs-hls-tech are two different things. I know, it's confusing. The demo page above uses modified videojs swf file https://github.com/mangui/video-js-swf that implements flasHLS project. So for flash to work with external resources you need crossdomain.xml file. Which is on your server root already. That's why it works fine if you use your .m3u8 link on the demo page. If you want to use video-hls-tech across domains, you have to setup CORS headers on your server.

**Comment by imdummyhelpme** [comment]
Okay so if I was to use flashbulbs it might work since swf was modified? Thanks for helping

**Comment by ReggiePuksta** [comment]
Actually I tried to use flasHls locally with videojs. It was no success. It might be that you need very old version of videojs, not sure. Though videojs-hls tech works fine for me with Cors enabled.

**Comment by imdummyhelpme** [comment]
For Cors with your own 'eu8 file or the one  have? To my u derstanding Cors has be enabled on wowza server right

**Comment by ReggiePuksta** [comment]
Yeah, my own. Yes.

**Comment by imdummyhelpme** [comment]
Thanks for explaining you have been really helpful

**Comment by dmlap** [comment]
@imdummyhelpme it does look like you are missing CORS headers on your m3u8 files. Flashls is Flash-based (not surprising) and uses a different mechanism to determine whether m3u8 requests are allowed or not. Check out [enable-cors.org](http://enable-cors.org/) for instructions on how to setup CORS on your server.

@ReggiePuksta thanks for the help diagnosing this one!
