### ISSUE TITLE
Unable to call currentTime on any of existing events

### ISSUE THREAD

**Issue by damirka** [videojs/videojs-contrib-hls#255]
Maybe I'm not getting the things right, but as the regular user I'm unable to correctly set the currentTime on any of the existing events.

I'm trying to use "loadedmetadata" to use currentTime method:
-> black screen, video is loading (on progress bar) but unable to play (more often)
-> or sets normally - video is in position, first frame is visible, video is playing

Is there any information I can give to describe it better?

**Comment by dmlap** [comment]
Would you mind setting up an example somewhere ([jsbin](http://jsbin.com/?html,output) perhaps)? I'm not sure exactly what the issue is from your explanation.

**Comment by gotling** [comment]
I had this problem as well together with contrib-ads, but with version 0.16.0 it seems to be working as expected. Before that I was doing trix on event 'loadeddata' which seemed to be working all the time but was sometimes slow to load.

**Comment by dmlap** [comment]
Just tried this with 1.3.7 and it seemed to be working fine:

```js
player.on('loadedmetadata', function() {
  console.log('current time', player.currentTime());
});
```

Let us know if you're still having problems.
