### ISSUE TITLE
Seek end

### ISSUE THREAD

**Issue by TuanLDT** [videojs/videojs-contrib-hls#259]
when I seek to end video, then seek to any position again and click button play. Video isn't play well. sometime it occurring, sometime not.

**Comment by dmlap** [comment]
Would you mind putting together a minimal example? (You can use [jsbin](http://jsbin.com/?html,output) or something similar)

**Comment by TuanLDT** [comment]
I run example.html. See error: http://lh6.googleusercontent.com/-ITLBn8Rr9r8/VVHVC2rPSOI/AAAAAAAAAHI/T_TOJkqbjIM/w440-h330-p/e1.png

**Comment by TuanLDT** [comment]
I think my problem have been solved.
But if you seek to the end of the progress bar and then seek to any position on the progress bar. Finally, you press the play button. The video will play, however it don't play from the position that you
selected, it play to the first segment

**Comment by TuanLDT** [comment]
@dmlap

**Comment by grantgingell** [comment]
Is there any chance this issue with the seek bar will be fixed? This pull request seems to fix the symptoms, but it has not been merged.

Thanks!

**Comment by rakesprogress** [comment]
Is there any chance of a fix for the seek bar overflowing? [This pull request (#345)](https://github.com/videojs/videojs-contrib-hls/pull/345) seems to fix the symptoms, but it has not been merged. 

Thanks!

**Comment by forbesjo** [comment]
This looks fixed, closing.
