### ISSUE TITLE
VIDEOJS: Unknown PID parsing TS packet: 256 after seek

### ISSUE THREAD

**Issue by bclwhitaker** [videojs/videojs-contrib-hls#261]
STR:
Load this stream: http://23.253.32.184/bctest_sync_issue.php
Click on the "Load video, seek to 6min and play (=> sync issue)" button

Expected Result:
No Unknown PID logging to console.

Current Result:
VIDEOJS: Unknown PID parsing TS packet: 256 is logged multiple times to the console.  It doesn't appear to have any affect on playback as far as I can tell though?

**Comment by yaboo777** [comment]
+1

**Comment by drumlight** [comment]
The sample streams seems to have been taken down but I saw the same message when I had a dedicated PCR pid configured in the encoder instead of embedding PCR in the video PID.

**Comment by drumlight** [comment]
Playback also worked for me but on a live stream I would expect to see some synchronization issues eventually.

**Comment by forbesjo** [comment]
We believe this is fixed in the latest version, if anyone else sees this issue please let us know!
