### ISSUE TITLE
Seeking freezes video but continues playing audio

### ISSUE THREAD

**Issue by FranklinWaller** [videojs/videojs-contrib-hls#263]
When i seek a video to say 2 seconds, the video freezes but the audio will keep playing. The stream comes from a blob file, so it is not "live" streaming.

Here is my m3u8 file:

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-PLAYLIST-TYPE:event
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:18
#EXTINF:17.88,
blob:http%3A//localhost%3A9001/967d19b3-6c82-4a9a-98b3-45cc3e6570b5
#EXT-X-ENDLIST

The blob file runs on it own smoothly without any problems

**Comment by dmlap** [comment]
How did you produce your blob file? Does it have the same issues if you access it over standard HTTP instead of through `blob:`?

**Comment by FranklinWaller** [comment]
The blob file was produced by appending TS files. Which the player can handle when you start from 0. And if i try to access it from standard HTTP it's still the same.

**Comment by dmlap** [comment]
If it happens over standard HTTP, can you put the segment with this issue somewhere public so we can see what's happening?

**Comment by dmlap** [comment]
No response on this one for awhile, so I'm closing.

**Comment by sgavali** [comment]
I'm also seeing this issue on android phone, after seek some times audio continues but video is frozen. If I use pause and play after this situation video resumes correctly. Is this chrome decoder issue ?

**Comment by sgavali** [comment]
Adb logs shows no video decoder prints when video is in freeze condition. Manual pause and play resumes decoding.

**Comment by Agnostic** [comment]
I don't know why these issues are being closed even if there are more people having the same issue, I saw some tickets talking about some problems I had and closed because "no response for a while" or insufficient information, currently I am having this issue, after seeking the video freezes, I have to manually pause and play again to "fix" this behavior

**Comment by gesinger** [comment]
Hey @Agnostic , sorry to hear you are seeing the issue still. Often times the problem ends up getting fixed through changes we make over time, and we close issues that should be fixed. And other times the problem still exists, but if we haven't seen it ourselves, it's hard to identify it as a bug and create a fix for it. For tickets where there's a [reduced test case](https://css-tricks.com/reduced-test-cases/) using a [jsbin template](http://jsbin.com/vokipos/8/edit?html,output), we make our best effort to fix the problem, and leave it open as long as we continue to see the problem. But if we don't have an example of the problem, and haven't seen it/can't reproduce it, we close the ticket, as it often has to do with a person's specific configuration, stream, or an error in another part of their application. We'd be happy to look into the issue if you can provide a reduced test case for it. Feel free to re-open the issue or create a new one with a jsbin example. Thank you.

**Comment by Agnostic** [comment]
I understand, I'll try to share a test case on the next time, also I will try to be up to date with the library, thank you!
