### ISSUE TITLE
HLS plugin fails on variant stream error

### ISSUE THREAD

**Issue by mpotra** [videojs/videojs-contrib-hls#264]
When using a master playlist to define variant streams, if the selected stream - usually the first - is not available, due to network or server issues, then the plugin fails without any fallback mechanism.
This results in an unrecoverable error:
> HLS playlist request error at URL: http://domain404.tld/chunklist_w1294938361_b620000.m3u8

which is pushed up the chain to videojs, resulting in a complete fail.

The problem is that in this scenario the plugin should attempt to use the following variant stream, or at least provide a way to continue the process of loading an adjusted playlist, where the failing variant stream is removed from the master playlist.
At this point, due to the anonymous nature of the methods of the PlaylistLoader init and processing, there's no way to achieve a fix by external code.

Here's a sample master playlist:
> #EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=650000,CLOSED-CAPTIONS=NONE,SUBTITLES="subs"
 http://domain404.tld/chunklist_w1294938361_b620000.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=620000,CLOSED-CAPTIONS=NONE,SUBTITLES="subs"
http://domain.tld/001f69b494.smil/chunklist_w1294938361_b620000.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=300000,CLOSED-CAPTIONS=NONE,SUBTITLES="subs"
http://domain.tld/001f69b494.smil/chunklist_w1294938361_b300000.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=64000,CLOSED-CAPTIONS=NONE,SUBTITLES="subs"
http://domain.tld/001f69b494.smil/chunklist_w1294938361_b64000_ao.m3u8

If the first variant stream (bandwidth 65000, on `domain404.tld`) returns a 404 HTTP response, or any other failure response, then the error is triggered and the whole chain stops.

**Comment by featheast** [comment]
I am having exactly the same issue with you @mpotra , and wondering if you or anyone else have a solution yet?

**Comment by ahomu** [comment]
i have same issue too...

**Comment by featheast** [comment]
I have been trying by either re-init or re-load the HLS plugin or the playlists, but not having any luck so far.

**Comment by forbesjo** [comment]
Is this still an issue?
