### ISSUE TITLE
Choppy video during live stream

### ISSUE THREAD

**Issue by JanSunavec** [videojs/videojs-contrib-hls#268]
After aprox, 5 minutes video gets more and more choppy. Especialy new version 0.15.0 is pretty bad. I did few test with timeline in Chrome. videojs-contrib-hls is getting more and more memory (not memory leak) Then garbage collector empty part of memory and during this time player play choppy video. 

My hls live streams has 3 variants and each chunk was 6 seconds long.

**Comment by dmlap** [comment]
Do you have an example page we can see this on?

**Comment by dmlap** [comment]
It's been a month without any activity on this one, so I'm going to close it. If you're still running into this issue, please let us know.
