### ISSUE TITLE
discontinuity breaking playback

### ISSUE THREAD

**Issue by dtrikannad** [videojs/videojs-contrib-hls#269]
I'm having trouble trying to get my m3u8 file to play past the discontinuity point. 

I have two 30 second clips in the m3u8 code below. The video playback starts with total length reflecting 1:00, but about 10-15 seconds into playback, the total length shifts to 30 seconds and then when the current marker reaches around 28 seconds, the player freezes. IF, however, I fast forward to around the 27 second mark as soon as the video starts playing, it will play right through the discontinuity point. 

Any thoughts?

Here is the content of the M3U8 i'm using:

#EXTM3U
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:3
#EXTINF:2.0687,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_1_segment00000.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_1_segment00001.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_1_segment00002.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_1_segment00003.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_1_segment00004.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_1_segment00005.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_1_segment00006.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_1_segment00007.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_1_segment00008.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_1_segment00009.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_1_segment00010.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_1_segment00011.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_1_segment00012.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_1_segment00013.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_1_segment00014.ts
#EXTINF:0.5005,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_1_segment00015.ts
#EXT-X-DISCONTINUITY
#EXTINF:2.0687,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_2_segment00000.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_2_segment00001.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_2_segment00002.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_2_segment00003.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_2_segment00004.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_2_segment00005.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_2_segment00006.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_2_segment00007.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_2_segment00008.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_2_segment00009.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_2_segment00010.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_2_segment00011.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_2_segment00012.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_2_segment00013.ts
#EXTINF:2.0020,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_2_segment00014.ts
#EXTINF:0.3670,
http://localhost:3000/hls_files/wyattearp/6500/wyattearp_2_segment00015.ts
#EXT-X-ENDLIST

**Comment by dtrikannad** [comment]
Forgot to mention that this occurs in both Firefox and Chrome browsers on Mac OS X Yosemite, but seems to play just fine in the safari browser.

**Comment by dmlap** [comment]
I could see this being related to https://github.com/videojs/videojs-contrib-hls/pull/267. Would you mind retesting against master?

**Comment by dtrikannad** [comment]
I have tested on both but thought the most relevant place to post my findings was on 267.

**Comment by dmlap** [comment]
@dtrikannad did you add your findings to #267? I didn't see any comments from you in that thread.
