### ISSUE TITLE
Requesting an full example without node server.

### ISSUE THREAD

**Issue by imdummyhelpme** [videojs/videojs-contrib-hls#273]
im  still learner I haven't setup an node server so it's hard for me to understand how the plugin actually works without using node. An simple html example will really help me and another users as well. Thank you in advance. Just videojs has it on their home page using vide tag along with all the scripts that ar needed thank you.

**Comment by hubertperron** [comment]
+1 for this. It's not really clear how to use the plugin at all

**Comment by anthonyettinger** [comment]
I can't figure it out either. Does the .min file have everything I need?

I jsut load the 3 js files and create my video tag, but it doesn't work in Chrome.

**Comment by dmlap** [comment]
I've updated the getting started instructions in the README a bit and created a [live demo](http://videojs.github.io/videojs-contrib-hls/)! If anyone is still having trouble setting things up, please let us know.
