### ISSUE TITLE
Non-aligned streams issues

### ISSUE THREAD

**Issue by ntadej** [videojs/videojs-contrib-hls#278]
There are two issues with handling of non-aligned TS streams.

At the start of playback, you expect the NAL header at the beginning of packet. If not, you want to write data to an existing frame (which is non-existent) and fails. Therefore PR #225 is necessary.

After parsing of each segment you [flush](https://github.com/videojs/videojs-contrib-hls/blob/master/src/videojs-hls.js#L785) h264 frame using `this.segmentParser_.flushTags();` which corrupts the frame which may be inbetween two segments. This is visible during playback (picture freezes for a short but visible time). Commenting this line out helps, but probably this is not a valid fix.

**Comment by dmlap** [comment]
Interesting stuff. I think we should figure out how to get this working but just out of curiosity, does this sort of stream pass in the [media stream validator](https://developer.apple.com/library/ios/technotes/tn2235/_index.html#//apple_ref/doc/uid/DTS40010221-CH1-VALIDATORTOOL)?

**Comment by ntadej** [comment]
Here is the validator output: https://gist.github.com/ntadej/245e53acc6b7548d418a

The stream plays completely fine on iOS or OS X.

**Comment by forbesjo** [comment]
Is this still an issue?

**Comment by ntadej** [comment]
Yes, we tested version 2.2.0 few days ago with our streams that have approximately 1 second delay between audio and video. There are two possible scenarios that still happen (none of them is ok):
 - only first segment of stream gets played with audio/video in sync, then stops without any error in console or in MSE log
 - stream plays continuously but with audio/video out of sync (delay is noticeable)

You should still have access to our test live stream.

**Comment by gesinger** [comment]
It looks like gist may no longer exist. Any chance you still have a stream available that exhibits this issue?

**Comment by gesinger** [comment]
Closing for now. If you are still experiencing this issue with the latest version of videojs-contrib-hls (as of this comment, v5.5.3), please re-open the issue and if you have the gist available, or can provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output), we'd appreciate it. Thank you.
