### ISSUE TITLE
Limit segment/buffer download

### ISSUE THREAD

**Issue by dtrikannad** [videojs/videojs-contrib-hls#281]
I was wondering if there was a mechanism within the existing api to limit the number of segments that get pulled in advance of rendering through the player. Is this possible?

Tried labeling this as a question but it isn't working for me. Sorry.

**Comment by dmlap** [comment]
Yep, you can set the [GOAL_BUFFER_LENGTH](https://github.com/videojs/videojs-contrib-hls/blob/master/src/videojs-hls.js#L55) to whatever number of seconds of content you'd like to be pre-buffered.
