### ISSUE TITLE
Retrieving metadata from ID3 tags for Safari

### ISSUE THREAD

**Issue by oldcookie** [videojs/videojs-contrib-hls#286]
With this plugin, I can get metadata via WebVTT tracks for Chrome and Firefox, but on Safari, the tracks remains disabled.   Is there anything specific I need to do to get it working on safari for live streaming?

**Comment by dmlap** [comment]
contrib-hls defers to native support for HLS when available, and Safari on Mac has built-in support. Unfortunately, Safari doesn't support timed metadata without weird hacks like using <object> to embed the video. You could override [isSupported()](https://github.com/videojs/videojs-contrib-hls/blob/ab0670dd420473f056677290b255a5dbe294c8f5/src/videojs-hls.js#L940) for contrib-hls to be used on Safari.

It's worth thinking about whether deferring to native support is the right design. We could just rely on the techOrder, for instance. The only scenario where that doesn't quite work correctly is if you have mixed mp4 and HLS sources on a browser without native HLS, and you'd prefer HLS to be used even if native MP4 playback is possible.

**Comment by oldcookie** [comment]
Thanks @dmlap, overriding would work in my case.  

Not sure what's the best way though, I mean, in most cases defaulting to native is probably good.  In this particular case, it's a bit weird cause natively has less functionality available.
