### ISSUE TITLE
Tearing/melting when scrubbing in Firefox

### ISSUE THREAD

**Issue by forbesjo** [videojs/videojs-contrib-hls#289]
Seen using the code after Gary's fix post 0.16.0.
While scrubbing an HLS video in Firefox 38 the frames melt together for a second, I am able to reproduce this 100% of the time.
I'm not seeing this issue in Chrome.

![may 29 2015 11-08](https://cloud.githubusercontent.com/assets/7529098/7885649/0f1320e2-05f3-11e5-9c6b-c9a2c56e20e1.gif)

![may 29 2015 11 15](https://cloud.githubusercontent.com/assets/7529098/7885817/244a66d6-05f4-11e5-80ae-83b8f4899178.gif)

**Comment by dmlap** [comment]
git bisect says it was introduced in 63c045e6d74efc88fbeec47e2c8b8662aaf83ac0

**Comment by dmlap** [comment]
Removing [metadata injection when the random access indicator is set](https://github.com/videojs/videojs-contrib-hls/blob/c61a7591747df0ffce3c288adc1fc83c98209a55/src/segment-parser.js#L264) in the TS adaptation field causes firefox to delay rendering the new video location but removes the distortion.

**Comment by dmlap** [comment]
It also delays rendering the new location in Chrome and others, unfortunately.
