### ISSUE TITLE
CDN ?

### ISSUE THREAD

**Issue by chovy** [videojs/videojs-contrib-hls#291]
Can I load these two libraries off a cdn somewhere like the `video.js` library?

```
<script src="videojs-media-sources.js"></script>
<script src="videojs-hls.min.js"></script>
```

**Comment by mmcc** [comment]
We don't host these on a CDN, but you could use something like [rawgit](http://rawgit.com) if you'd like.

**Comment by heff** [comment]
RawGit wouldn't work here because we don't store a compiled version of the library anywhere in the repo. We might consider using the approach we're using for video.js here too, where the release gets compiled and tagged off in a branch that never gets merged back into master.

**Comment by mmcc** [comment]
Ah you're right, I was assuming there was a dist in the release tags like with VJS.

**Comment by dmlap** [comment]
We recently added a contrib.json so we can automate more of the release process. I plan on adding dist files to the released tags soon so hopefully this one won't be an issue much longer.

**Comment by heff** [comment]
Nice. Let me know if you want help setting up something like in core.

**Comment by cadesalaberry** [comment]
@dmlap are you planning on including the `dist/` folder anytime soon ? I would love to have it accessible !

Cheers :monkey:

**Comment by dmlap** [comment]
@cadesalaberry I spent awhile improving the release process yesterday but haven't fixed dist/ yet. Still working on it!

**Comment by cadesalaberry** [comment]
@dmlap Thanks a lot for the update, I will check the repo regularly meanwhile.

**Comment by forbesjo** [comment]
See https://cdnjs.com/libraries/videojs-contrib-hls
