### ISSUE TITLE
Request to add this plugin to bower an npm

### ISSUE THREAD

**Issue by carpasse** [videojs/videojs-contrib-hls#300]
I would like to request that we add this plugin to bower and npm to ease the dependency management.

Well technically speaking the plugin is already on npm, but I am missing a bin folder with the "compiled" version of the plugin.

Thanks a lot in advance.

**Comment by gkatsev** [comment]
It should have been there but seems like we're ignoring `dist/` in the `.npmignore` file.

**Comment by carpasse** [comment]
Want me to do a quick PR to remove the dist from .npmignore??

Also regarding bower, do you have any plans to publish the plugin there?

**Comment by forbesjo** [comment]
Closing since this plugin should be on npm.
