### ISSUE TITLE
Use WebkitDataCue for ID3 tags?

### ISSUE THREAD

**Issue by dmlap** [videojs/videojs-contrib-hls#303]
Safari creates a WebkitDataCue for in-band metadata track cues. The constructor is public and usable. Should we do the same when it's available or stick with VTTCue?

**Comment by dmlap** [comment]
@gkatsev any thoughts on this one?

**Comment by gkatsev** [comment]
Sounds like this might be the correct course of action. Safari already has this and Chrome has filed an intent to implement (https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/U06zrT2N-Xk/RFS_q-Hi2wMJ).
The spec is available here: http://www.w3.org/html/wg/drafts/html/master/semantics.html#datacue
Seems right now that it required to be used for metadata tracks but are trying to remove that restriction: https://www.w3.org/Bugs/Public/show_bug.cgi?id=25261

**Comment by saxena-gaurav** [comment]
This is getting addressed in #395
