### ISSUE TITLE
Fullscreen from Iframe breaks the plugin

### ISSUE THREAD

**Issue by jstarpl** [videojs/videojs-contrib-hls#317]
I'm having an issue with going fullscreen from an iframe on Chrome. I have a iframe embed code - if a user decides to go fullscreen while playing a video in this iframe the video stops playing and goes black. There is no way to make the player working agian apart from refreshing the page.

Has anyone experienced anything simmilar?

**Comment by gkatsev** [comment]
Make sure that your iframe has the `allowfullscreen` attribute on it (possibly with vendor prefixing as well). You won't be able to take the player fullscreen otherwise.

**Comment by jstarpl** [comment]
I have allowfullscreen attribute on the element and the player actually goes full screen - it's just that the "video" content disappears and the playback gets stuck (the timecode doesn't progress).

**Comment by gkatsev** [comment]
Oh, I see. I somehow totally missed that part.
I've not heard of anything similar happening. What version of videojs/hls are you using?

**Comment by jstarpl** [comment]
I'm running HLS plugin 0.12.0 with Video.JS 4.12.5.

Here's the debug report when running the .dev.js version:

VIDEOJS: Video.js: paused unavailable on Hls playback technology element. TypeError: this.el_.vjs_getProperty is not a function
    at api.(anonymous function) [as paused] (http://127.0.0.1:8001/***:66674:45)
    at vjs.Player.techGet (http://127.0.0.1:8001/***:63031:31)
    at vjs.Player.paused (http://127.0.0.1:8001/***:63086:16)
    at null.<anonymous> (http://127.0.0.1:8001/***:89221:44)
    at HTMLDivElement.ret (http://127.0.0.1:8001/***:59606:15)
    at HTMLDivElement.data.dispatcher (http://127.0.0.1:8001/***:59081:29)
    at Function.vjs.trigger (http://127.0.0.1:8001/***:59326:25)
    at vjs.Component.trigger (http://127.0.0.1:8001/***:61212:7)
    at null.<anonymous> (http://127.0.0.1:8001/***:65491:19)
    at ret (http://127.0.0.1:8001/***:59606:15)

**Comment by jstarpl** [comment]
Yup, I've just updated to the latest version and it's still happening.

**Comment by dmlap** [comment]
Are you setting `display: block` on the player or anything? Chrome and Firefox reload the videojs-swf if the `<object>` element is removed from the DOM and the symptoms you're reporting sound similar.

**Comment by dmlap** [comment]
Haven't heard back on this one in awhile. If you're still running into this issue, please re-open.

**Comment by jstarpl** [comment]
Well, I've checked your suggestion, and I'm not setting display: block on neither the video-js div or the object containing the flash player backend, so that's not it.

**Comment by dmlap** [comment]
@jstarpl I'm not sure what it might be then. Any chance you could put together an example to show us?

**Comment by dmlap** [comment]
Closing since we haven't heard back on this one.
