### ISSUE TITLE
html5 hls?

### ISSUE THREAD

**Issue by alex-steel** [videojs/videojs-contrib-hls#325]
A short question: why do you use flash (not mse + html5) and do you plan to replace flash in future?

**Comment by dmlap** [comment]
We use Flash today for backwards compatiblity-- MSE is not enabled by default in Firefox or IE < 11. We do have plans to add MSE-based HLS in the near future but it's a big project. You can check out our progress in the [feature/mp2t-to-mp4 branch](https://github.com/videojs/videojs-contrib-hls/tree/feature/mp2t-to-mp4) or check out [a simple demo](http://videojs.github.io/videojs-contrib-hls/mse-demo/).

**Comment by alex-steel** [comment]
Thanks!
