### ISSUE TITLE
How to capture event when discontinuity is hit in manifest

### ISSUE THREAD

**Issue by dtrikannad** [videojs/videojs-contrib-hls#328]
Can you provide me with any sample code for calling a javascript function for when a discontinuity is hit in a manifest? Ideally, this would work across both native HLS and the VideoJS-SWF players.

Thanks.

Deep

**Comment by dmlap** [comment]
There is no way that I'm aware of to find out when a discontinuity is encountered when native HLS is being used. I don't think we have an obvious event to listen for in the HLS tech but that's something we could consider.

**Comment by dmlap** [comment]
What's the use-case for this?

**Comment by Llorx** [comment]
To add a bit of info for this to be available, nginx rtmp from Arut creates a discontinuity tag line (`EXT-X-DISCONTINUITY`) between .ts files inside m3u8 manifest. This usually happens when resetting an stream.

**Comment by dtrikannad** [comment]
Looking to know when either a specific TS file is playing so that the player can take custom actions. I'm looking to serve ads server side from within the m3u8 manifest of the main program but need to lock playback controls during ads etc and then unlock them when the ad is done.

**Comment by dmlap** [comment]
You could use [in-band metadata tracks](https://github.com/videojs/videojs-contrib-hls#in-band-metadata) to signal timed info (like ads) during playback. It's not signaling the discontinuity specifically but I can say that other folks have used it to trigger these sorts of player changes successfully.

**Comment by codex-corp** [comment]
@dmlap 
can you please write a example how to use in-band meta data with videojs
check the code for jwplayer
```
player.onMeta(function(evt) {
    if (evt.metadata.TXXX) {
        //console.log(evt.metadata.TXXX);
        index = evt.metadata.TXXX.indexOf("adID:");
        if (index >= 0 ){
            req = evt.metadata.TXXX.substring(index+5);
            req2 = decodeURIComponent(req);
            //console.log(req2);
    
            player.playAd(req2);
        } 
    }	
});
```

**Comment by dmlap** [comment]
@codex-corp We try to stick with the HTML5 standard APIs wherever possible so that you can use the same code whether features are supported natively (i.e. iOS) or not. ID3 tags are exposed in HTML5 video as a metadata text track. Here's how you could listen to find out that a video has ID3 metadata and log out the tags:

```js
player.textTracks().on('addtrack', function(e){
  // find out if the new track is metadata
  var track = e.track;
  if (track.kind === 'metadata') {

    // a cuechange event fires when the player crosses over an ID3 tag
    track.on('cuechange', function() {

      // in reality, there may be more than one cue active at a time
      // we'll ignore that for simplicity in this example
      console.log('found an ID3 tag!', track.activeCues[0]);
    });
  }
});
```

**Comment by codex-corp** [comment]
@dmlap 
Great , thanks!

**Comment by gesinger** [comment]
In addition to @dmlap 's recommendation of in-band metadata tracks, we also now support the "soft standard" of EXT-X-CUE-OUT, EXT-X-CUE-OUT-CONT, and EXT-X-CUE-IN (can see some examples of their use in https://github.com/videojs/m3u8-parser/blob/63dd2e4dad33dbb53d71cb3ae06c802a284a4baa/test/m3u8.test.js ) by setting the useCueTags option: https://github.com/videojs/videojs-contrib-hls#usecuetags

Please let us know if these do not satisfy your use case. Thanks.
