### ISSUE TITLE
0.17.3 dist code missing from GitHub releases tab

### ISSUE THREAD

**Issue by vasklund** [videojs/videojs-contrib-hls#330]
I know you're updating your build process and so on, just wanted to give a heads up in case it's a simple miss :)

(I'll just clone and build locally, so feel free to close this issue.)

**Comment by dmlap** [comment]
Darn. Thanks for letting us know.

**Comment by dmlap** [comment]
The automation still isn't fixed but I did add official builds for 0.17.3.
