### ISSUE TITLE
i find pkcs7.unpad.js

### ISSUE THREAD

**Issue by sujkh85** [videojs/videojs-contrib-hls#331]
https://github.com/videojs/videojs-contrib-hls/blob/master/example.html

34 line

```
<script src="node_modules/pkcs7/dist/pkcs7.unpad.js"></script>
```

Where can I get ?

**Comment by dmlap** [comment]
If you use one of the [releases](https://github.com/videojs/videojs-contrib-hls/releases), it's included automatically. If you're trying to contribute to contrib-hls, check out the [contribution guide](https://github.com/videojs/videojs-contrib-hls/blob/master/CONTRIBUTING.md#modifying-the-code).
