### ISSUE TITLE
Error no ATDS header found

### ISSUE THREAD

**Issue by tokmak** [videojs/videojs-contrib-hls#334]
Having an issue playing h3u8 stream - getting following error: 
"Error no ATDS header found" 

What does that mean?
Is it stream related issue?

Thanks,
Dmitry

**Comment by dmlap** [comment]
Do you have an example we can look at?

**Comment by dmlap** [comment]
This can be reproduced on example.html by seeking to 15:15:

```js
player.currentTime(15.25 * 60);
```

**Comment by tokmak** [comment]
Hi, thanks for the response. I dont have a public url

**Comment by gesinger** [comment]
@dmlap , was this using a different stream at the time (from bipbop), or have we addressed this issue in the meantime? I ran `player.currentTime(15.25 * 60)` in utils/stats/index.html and index.html and have not encountered the error.

**Comment by dmlap** [comment]
Yes, this should have been fixed after we moved Flash to use mux.js. Please reopen if you're still experiencing it.
