### ISSUE TITLE
Firefox hangs for my example

### ISSUE THREAD

**Issue by c3iq** [videojs/videojs-contrib-hls#335]
Hello,
  I have set up HTML example that works using the link to the bipbopall.m3u8.  When I point it to my own example Firefox hangs forever.  The JS I have used is downloaded from http://videojs.github.io/videojs-contrib-hls/.  Firefox is 38.0.5 on GNU/Linux.  I use ffmpeg to create the videos:

/usr/local/video/bin/ffmpeg -y -threads 0 -i remux.m2ts -filter:v yadif -crf 12 -minrate 1500K -maxrate 1500K -bufsize 1500K -preset veryslow -c:a aac -strict experimental -ac 2 -b:a 128k -ar 44100 -c:v libx264 -pix_fmt yuv420p -profile:v baseline -level 21 -b:v 1500K -r 25 -g 25 -keyint_min 50 -x264opts "keyint=50:min-keyint=50:no-scenecut" -f hls -hls_time 2 -hls_flags single_file -aspect "1280:720" -s "1280x720" 1004_20150530185500.m3u8

I think it may important to point out '-hls_flags single_file', the main m3u8 looks like this:

#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=400000,RESOLUTION=640x360
640x360/400K/1004_20150530185500.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=400000,RESOLUTION=1280x720
1280x720/400K/1004_20150530185500.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1500000,RESOLUTION=640x360
640x360/1500K/1004_20150530185500.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1500000,RESOLUTION=1280x720
1280x720/1500K/1004_20150530185500.m3u8

and a sub m3u8 looks like:

#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:2
#EXT-X-MEDIA-SEQUENCE:2249
#EXTINF:2.000000,
#EXT-X-BYTERANGE:467932@998734020
1004_20150530185500.ts
#EXTINF:2.000000,
#EXT-X-BYTERANGE:411908@999201952
1004_20150530185500.ts
#EXTINF:2.000000,
#EXT-X-BYTERANGE:416796@999613860
1004_20150530185500.ts
#EXTINF:2.000000,
#EXT-X-BYTERANGE:491808@1000030656
1004_20150530185500.ts
#EXTINF:0.320000,
#EXT-X-BYTERANGE:131412@1000522464
1004_20150530185500.ts
#EXT-X-ENDLIST

I'm using nginx to deliver the video:

  location /hls {
    root /usr/storage;
  }

The test URLs are here:

http://v00ltv00003l.dmu.ac.uk/ExampleHLS/indexBlip.html
http://v00ltv00003l.dmu.ac.uk/ExampleHLS/ (this may hang your browser)

![hlsstuck](https://cloud.githubusercontent.com/assets/13135237/8457097/544c1758-2007-11e5-99ff-176d6759a932.png)

Am I barking up the wrong tree in hoping to use this plugin?  The video is over an hour long.

Best regards.

**Comment by gkatsev** [comment]
The reason why it's failing is that we do not currently support byterange requests for segments with the same ts file.

**Comment by c3iq** [comment]
I'll try elsewhere for now.  I have thousands of videos, without single_file I might reach the limits of the file system.  Good luck with this plugin.
