### ISSUE TITLE
Set AES Decryption key dynamically

### ISSUE THREAD

**Issue by alex-steel** [videojs/videojs-contrib-hls#336]
Hello!
Is there any method for setting AES decryption key dynamically?
Thanks!

**Comment by dmlap** [comment]
Are you looking for some sort of programmatic way of providing an encryption key for segments, outside of specifying a URL in the manifest?

**Comment by alex-steel** [comment]
yes

**Comment by dmlap** [comment]
That's outside standard HLS behavior so it's outside of our focus today. Sorry we can't be of more help.
