### ISSUE TITLE
Videos randomly freezing a few seconds before end

### ISSUE THREAD

**Issue by vasklund** [videojs/videojs-contrib-hls#338]
We've come across an issue where videos sometimes freeze and refuse to buffer the last few seconds of a clip. The problem occurs very nondeterministically and scrubbing can both fix and cause the problem.

We think we've tracked down the problem and know how it can be solved, and I'm working on a test case (might be difficult) and a robust solution, and will update with details and open a PR as soon as I can. For now, I just wanted to check if you recognize the problem and open an issue to track progress/discussion.

We've seen the issue since we started using contrib-hls around version 0.10.0.

[playing as usual](http://gyazo.com/ec8565bb286391202f7c2c6978a8c4f5)
[sudden freeze, even though last segment is downloaded successfully](http://gyazo.com/71e7e2151e52be7153c6d4d2476dc504)

**Comment by vasklund** [comment]
Our bad! Seems the problem was with videojs-contrib-media-sources and was fixed with 0.3.2 and 1.0.0. If it's OK I'll leave the issue open for a few days while we do some more extensive testing, but it seems the issue doesn't exist with 1.0.0.

**Comment by dmlap** [comment]
@vasklund very glad to hear that! If your testing turns up anything else, please let us know.

**Comment by vasklund** [comment]
Haven't seen the issue since we bumped media-sources, so closing the issue.
