### ISSUE TITLE
Streaming fails for videos with no audio with 0.17.3 release

### ISSUE THREAD

**Issue by pbacci** [videojs/videojs-contrib-hls#341]
Hello, I tried to update videojs-hls but I am hitting a problem with files that do not include audio tracks. I isolated a simple test case that compares the behavior with a working version of videojs-hls (0.11) and the latest one.

Below is a screnshot of the stack trace I see:

![screenshot 2015-07-07 17 56 24](https://cloud.githubusercontent.com/assets/2723677/8560846/87cfafc6-24d1-11e5-9c68-3bbe0eb4aeee.png)

**Comment by pbacci** [comment]
here is an isolated way to repro. Decompress the zip file and point the browser to test_failing.html. There is also the same exact content that works (test_working.html) with 0.11 version

https://www.dropbox.com/s/8jnge9aqs9gelam/test.zip?dl=0

**Comment by pbacci** [comment]
@dmlap did some digging today to isolate when the regression got introduced and it's originating in

commit cc20895dd4992590f7cf36da181f5020c36c67d7
Author: David LaPalomento <dlapalomento@gmail.com>
Date:   Thu Jun 18 15:27:21 2015 -0400

    Record min and max PTS values for segments
    Segment duration can have different interpretations in different contexts. To ensure we have all the information we need to seek accurately, record PTS valu
es for the audio and video streams within a segment. For #314.

**Comment by dmlap** [comment]
@pbacci thanks for the investigation! I believe we need to add some guards around calls to the segment parser's [PTS stat gathering](https://github.com/videojs/videojs-contrib-hls/blob/6f177803cb9db71d6eb774f65cefe0d78ffa75a9/src/segment-parser.js#L466-L480) so it doesn't blow up if the audio or video track is missing.

**Comment by pbacci** [comment]
thanks a lot for the quick fix @dmlap !
