### ISSUE TITLE
Support EXT-X-BYTERANGE

### ISSUE THREAD

**Issue by jpfranco** [videojs/videojs-contrib-hls#342]
Hello, I'm trying figure out whether there is something wrong with our streams or with videojs-contrib-hls itself. I'm testing a few videos that were processed with Amazon's Elastic Transcoder (HLS protocol version 4) and I'm experiencing some strange behavior. 

On Chrome the videos take considerably longer to start playing than on an HLS capable browser, and when playback begins, the duration displayed on the player changes to 2x the actual duration of the video. Some times when you seek forward, the duration will increase again, and then it will keep on increasing over time.

This doesn't seem to happen with other HLS streams that I've found on the web (including the one on your test page), but the streams I'm testing play without issues on Safari and Android Chrome using vanilla VideoJS. CORS is also properly set up.

I don't have the full setup online, but I do have two sample streams with this issue:
[stream 1](https://authproxy-1.ocdevel.net/s3-m3u8/organization-jpenterprises/video-0gRO9PQqL/video-hls-low.m3u8?Signature=h8acTufNizcaa4LwTQftKJfYsf4lZwNINHKUz~dcPirKyCr9kEMg33eG0dU5AMntoQP5O5k3Rs4KZrWvcl9iFEhKrnO80D4FD98Z6qBChmt3fNEB1-xff5gRu9ZE6QKA6unq1Pszl~m-~xLSlG4-7EsGgrSRrtp2swD93b5SOG14VeWSWUM9wK5mgkml4tE51mFZhoQ8f9OqTC2bLnJHIC1UjcZ9t0NyBaZRy7vesk03bHBopG1LAqErsHFJqfRa2yTAOX1LF7NWpbFPSrKoQqnzhS~C~BlsOQWCPnO6dUlG815~DlsVUBEUzx3LnZ0chKbUzI9mON3MxAZAVyiptg__&Key-Pair-Id=APKAJ5JH3L2ZNI5QDHEQ&Expires=2147483647)
[stream 2](https://authproxy-1.ocdevel.net/s3-m3u8/organization-mergetests/video-yRwEYDmGZ/video-hls-low.m3u8?Signature=F1DSwemAq9l28zEdd~PLBFforcBk4iR9GB1~LpXRU7MfozFxljbRmxeDs8b62Npz5iechSsd4wFIhqPX5AY2TIqcGU406gIxlzSDKZ9M7UWk4N13qYjUbAtJk3zp-JmETbKkTflg6BmE11dMy8YYTuUoEzAMjTjyI7xTvhRQfmvqj94sB9UoPptIXO1V1h2t7o9pUNrzOR7Cwj6e06sTyTNbq8dijfevW~oHWxNK5~pWpa4Wb0OLYdACL7CSyoGmYcMKYbWUI2yf2ZmIMOFa4SY6rxhAKhQ6hpnHiBO0u1ePzF8UGnYlVj5ZEDhXj~QKWa3NNxqBO-Hh05IaDSQ88A__&Key-Pair-Id=APKAJ5JH3L2ZNI5QDHEQ&Expires=2147483647)

I'm using the following versions:
- VideoJS: 4.12.10
- VideoJS Flash Component: 4.7.0
- videojs-contrib-media-sources: 0.3.1
- videojs-contrib-hls: 0.17.2 (My streams don't play at all when using 0.17.3)

**UPDATE**
It seems that the slow startup issue is due to the fact that we're using the EXT-X-BYTERANGE tag, which doesn't seem to be currently supported by the library (is this correct?). So I guess that since byte ranges are being ignored, the full source file is being downloaded before playback begins. I'm not sure whether this is also related to the increasing duration issue that I'm experiencing.

Thanks

**Comment by dmlap** [comment]
Yes, we don't support BYTERANGE style HLS today and that would definitely explain the slow startup. Elastic Transcoder should be able to produce segmented HLS though. Any background on why you're using unsegmented HLS right now?

**Comment by jpfranco** [comment]
@dmlap yes, sorry about the late reply. We're trying out HLS 4 because we use signed urls, so with byte ranges we can avoid having to sign a bunch of separate .ts files. We do keep a separate HLS 3 stream, so I guess we'll just switch to that for now. Do you guys have plans to implement these newer HLS features? Thanks

**Comment by dmlap** [comment]
Ah, ok. I haven't heard much demand for BYTERANGE support so it hasn't been high on the list of priorities so far. We do have plans to implement some HLS v4 features soon (multiple audio track support is at the top of the list). If you're feeling ambitious, we'd certainly be interested in a PR to add BYTERANGE support.

**Comment by spg** [comment]
I would definitely be interested in byterange support. +1

**Comment by dmlap** [comment]
I'd really like to have it included as well and, while it's not trivial, I think it should be relatively straight-forward. If anyone has some time and is interested in creating a PR, it would be much appreciated!

**Comment by thenewguy** [comment]
Maybe byte range should be added to the list of unsupported features on the README?

There are tests that seem to indicate that byte ranges are supported:
- https://github.com/videojs/videojs-contrib-hls/blob/master/test/manifest/byteRange.js
- https://github.com/videojs/videojs-contrib-hls/blob/master/test/manifest/byteRange.m3u8

I thought I read awhile back that the byte ranges would be downloaded in js and passed into the flash player?

**Comment by dmlap** [comment]
byte-range support is in!
