### ISSUE TITLE
HLS playlist request error

### ISSUE THREAD

**Issue by paulwang55** [videojs/videojs-contrib-hls#343]
Hi,
I am a new user to use video.js & videojs-contrib-hls.

I use the example.html to test my m3u8 playlist. I receive the following error "HLS playlist request error" when I load my example.html.

The sample m3u8 can be worked properly.
<source
       src="http://solutions.brightcove.com/jwhisenant/hls/apple/bipbop/bipbopall.m3u8"
       type="application/x-mpegURL">

 Its content is 
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1, BANDWIDTH=200000
gear1/prog_index.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1, BANDWIDTH=311111
gear2/prog_index.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1, BANDWIDTH=484444
gear3/prog_index.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1, BANDWIDTH=737777
gear4/prog_index.m3u8

My m3u8 file's content is -

#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:4249
#EXTINF:10,
sample_512k-1436430885.ts
#EXTINF:10,
sample_512k-1436430895.ts
#EXTINF:10,
sample_512k-1436430906.ts
#EXTINF:10,
sample_512k-1436430917.ts
#EXTINF:10,
sample_512k-1436430927.ts
#EXTINF:10,
sample_512k-1436430938.ts

It cannot be processed using the example.html.

How can I modify the example.html to process my m3u8 playlist ? It is an variant playlist.

The stream is a live streaming.

#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:4249
#EXTINF:10,
sample_512k-1436430885.ts
#EXTINF:10,
sample_512k-1436430895.ts
#EXTINF:10,
sample_512k-1436430906.ts
#EXTINF:10,
sample_512k-1436430917.ts
#EXTINF:10,
sample_512k-1436430927.ts
#EXTINF:10,
sample_512k-1436430938.ts

Any suggestion is appreciated.

Regards,

Paul Wang

**Comment by dmlap** [comment]
Does your stream work in Safari or on iOS? Do you have [CORS](https://developer.mozilla.org/en-US/docs/HTTP/Access_control_CORS) configured for your video?

**Comment by paulwang55** [comment]
Hi David,
My stream can be worked in Safari and iOS when I excute "example.html" with my m3u8 playlist.

I don't have CORS configured for my "Live TV" stream.

Regards,

Paul Wang

**Comment by paulwang55** [comment]
Hi David,
I get the following error message from my "Google Chrome" Javascript Cpnsole.

XMLHttpRequest cannot load "my index_512k.m3u8". No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://172.16.63.146' is therefore not allowed access.

Do you have any suggestion how  I can solve this error ?

Regards,

Paul Wang

**Comment by drumlight** [comment]
Paul,

It depends a little upon the webserver that is hosting the stream but the documentation should be easy to find online. For Nginx I’ve enabled CORS for all domains with the final line in the short snippet of my server configuration below.

server  ## For Serving HLS Segments
{
    listen       80;
    server_name  localhost;
    add_header Access-Control-Allow-Origin *;
……….

In your case you could also only access for the domain you are coming from by replacing the wildcard with a specific IP eg
add_header Access-Control-Allow-Origin 172.16.63.146;

Hope that helps but a quick search for your webserver and “enable CORS” should provide documentation relevant to your specific server.

Jake

**Comment by dmlap** [comment]
Thanks for the help, @drumlight! 

@paulwang55: I'm going to close this issue since it seems to be CORS-related but feel free to keep adding questions in here if you have problems with the setup.
