### ISSUE TITLE
All request error !!! Only works for the sample file http://solutions.brightcove.com/jwhisenant/hls/apple/bipbop/gear1/prog_index.m3u8  

### ISSUE THREAD

**Issue by htn264** [videojs/videojs-contrib-hls#347]
Only the sample file that you provided http://solutions.brightcove.com/jwhisenant/hls/apple/bipbop/gear1/prog_index.m3u8  

The script can run. All other working public m3u8 that VLC can play, this script videojs-contrib-hls can not run.  A playlist.m3u8 generated by Wowza this script also can not read. 

Error : 
HLS Playlist request error at URL : ....

**Comment by dmlap** [comment]
Do you have [CORS](https://developer.mozilla.org/en-US/docs/HTTP/Access_control_CORS) configured for your m3u8 and TS files? This plugin is in use by people with Wowza servers right now so there's definitely something else going on.

**Comment by htn264** [comment]
I have not touch the CORS at all. Do I have to configure CORS ?
- I do not only try the one from my Wowza, I also try links from public places (VLC can play) but the script does not play.HLS Playlist error at URL.
- For the link from Wowza, it is a MP4 VOD file I add playlist.m3u8 at the end. VLC can play but the script reports error: HLS Playlist error at URL.  Do I have to configure anything and where is the guide? Thank you.

**Comment by htn264** [comment]
I will try to configure CORS. It is weird. It is from the same domain (just different port) and the cross domain error still occurred.
For the m3u8 from public places, I guess they are blocked also.

**Comment by dmlap** [comment]
Many mobile browsers have HLS built-in. Built-in browser support isn't subject to the same security requirements that javascript has so in many cases cross-domain HLS can be played back without CORS on those platforms.

It sounds like this is a CORS configuration issue so I'm going to close it.
