### ISSUE TITLE
What will be with HLS support after death of Flash?

### ISSUE THREAD

**Issue by 4z5lz** [videojs/videojs-contrib-hls#350]
Hello,

It seems that the death of Flash era in the near future... 
http://www.wired.com/2015/07/adobe-flash-player-die/

Currently, videojs-contrib-hls requires flash for HLS support for major desktop browsers. 
What will be with HLS support after the death of Flash?

It's not just a rhetorical question.

**Comment by gkatsev** [comment]
We're currently working on making this work with [MSE](https://en.wikipedia.org/wiki/Media_Source_Extensions) and mp4s. MSE is supported in all current major browsers and will be shipping in MS Edge. The only possible issue is Firefox, which currently has a whitelist for MSE support, but firefox is supposed to drop the whitelist in a recent future version.
When we have the MSE version of HLS, it will use MSE when available and drop down to flash only for browsers that would require it, like IE10 and older version of firefox.
Thanks for the question. Hopefully, the above helps.
