### ISSUE TITLE
autoplay attribute causes start playing at very beginning segment of live chunklist

### ISSUE THREAD

**Issue by eminden** [videojs/videojs-contrib-hls#351]
when playing live video and autoplay attribute exists on video tag, videojs-hls-contrib sometimes start downloading the very first segment listed in downloaded chunklist instead of the latest segments. 

tested with latest videojs-hls-contrib # v0.17.5

**Comment by dmlap** [comment]
You are correct and I happen to be working on this right now :) Thanks for the report!

**Comment by dmlap** [comment]
Should be fixed in 0.17.6.
