### ISSUE TITLE
audio only playlist not working

### ISSUE THREAD

**Issue by eminden** [videojs/videojs-contrib-hls#357]
Audio only playlist is logging to console as follows , and no sound is produced.

tested with putting a reverse_proxy in front of the following url for cors headers and an audio only stream produced by wowza, both has the same problem.

https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear0/prog_index.m3u8

VIDEOJS: Unknown PID parsing TS packet: 2834
video.dev.js:1457 VIDEOJS: Unknown PID parsing TS packet: 175
video.dev.js:1457 VIDEOJS: Unknown PID parsing TS packet: 1808
video.dev.js:1457 VIDEOJS: Unknown PID parsing TS packet: 3858
video.dev.js:1457 VIDEOJS: Unknown PID parsing TS packet: 4537
video.dev.js:1457 VIDEOJS: Unknown PID parsing TS packet: 6138
video.dev.js:1457 VIDEOJS: Unknown PID parsing TS packet: 7059
video.dev.js:1457 VIDEOJS: Unknown PID parsing TS packet: 1941
video.dev.js:1457 VIDEOJS: Unknown PID parsing TS packet: 5282
video.dev.js:1457 VIDEOJS: Unknown PID parsing TS packet: 6830
video.dev.js:1457 VIDEOJS: Unknown PID parsing TS packet: 3442
video.dev.js:1457 VIDEOJS: Unknown PID parsing TS packet: 2233
video.dev.js:1457 VIDEOJS: Unknown PID parsing TS packet: 6693
video.dev.js:1457 VIDEOJS: Unknown PID parsing TS packet: 851
video.dev.js:1457 VIDEOJS: Unknown PID parsing TS packet: 7155
video.dev.js:1457 VIDEOJS: Unknown PID parsing TS packet: 1698
video.dev.js:1457 VIDEOJS: Unknown PID parsing TS packet: 4959
video.dev.js:1457 VIDEOJS: Unknown PID parsing TS packet: 5992
video.dev.js:1457 VIDEOJS: Unknown PID parsing TS packet: 4918
video.dev.js:1457 VIDEOJS: Unknown PID parsing TS packet: 5860
video.dev.js:1457 VIDEOJS: Unknown PID parsing TS packet: 4022

**Comment by drumlight** [comment]
I haven’t checked up in the last couple of releases but the last time I saw a similar message it was because my stream had a dedicated PCR pid rather than including it in the video pid. It seems like a similar situation might occur with an audio only stream as the PCR may not be where it is expected.

Jake

**Comment by dmlap** [comment]
@eminden we don't support packed AAC segments yet. In the meantime, if you re-encode with audio-only TS segments it should work.
