### ISSUE TITLE
HLS stream pasues with no controls, .mp4 stream plays fine

### ISSUE THREAD

**Issue by jcapucla** [videojs/videojs-contrib-hls#364]
I've copied the configuration for my HLS player directly from the HTML source of the example:
http://videojs.github.io/videojs-contrib-hls/

I have an adjacent player running an .mp4 stream with no issues. Both the .mp4 and HLS files reside in the same folder on the same Cloudfront distribution.

here is a link to a demo illustrating the problem: http://goo.gl/Ug6oMI

It is possible that I have just configured it incorrectly. But I've stripped away any complexity, and basically copied and pasted the example, and it still doesn't work. I've verified that the HLS stream is encoded correctly by playing using VLC player. I've been tweaking it for 72 hours now, and can't seem to make any headway. Please advise.

EDIT: here is a link to the HLS files:
https://drive.google.com/folderview?id=0B24zb81XZ4CcUmVCTG0tOVJPNmc&usp=sharing

UPDATE: I verified that the files were being served with the correct Content-Type headers (application/x-mpegURL and video/MP2T).

UPDATE 2: Both streams play on my android phone, so the native HLS functionality seems to be OK. But in chrome on my desktop the Flash fallback player begins in a paused state and is unresponsive.

Thanks in advance for any help.

**Comment by alexyats** [comment]
I've sent you my proposal at upwork and after that I've digged a little bit more and solved your issue. You should store all the files from this repository to your web-server: https://github.com/videojs/videojs-contrib-hls/tree/master/src

after that, fix your html by including all the script files:

```html
<!DOCTYPE html>
<html>

  <head>
  <title>HLS demo</title>
  <link rel="stylesheet" media="all" href="/assets/application-08966a2aa8d19440e3bfe53f06c22cc1.css" data-turbolinks-track="true" />
  <script src="/assets/application-dae5af3023c9512a5ee13cb82147321e.js" data-turbolinks-track="true"></script>
  <meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="SHhft2TuB/14lIRWOpdqxV3r12hlOt1hQpMoux2TgXFCSxkZP4Zbb0ynYXtTKRc5Ef7EXjBohYNTuHpSokns9A==" />
</head>

  <body>
    
  <div class='margin-container'>
  <video id=example-video-1 width=640 height=360 class="video-js vjs-default-skin" controls>
    <source
      src="http://cdn.lsatengine.com/HLS3/HLSdemo/HLSdemo.m3u8"
      type="application/x-mpegURL">
  </video>
</div>

<br><br>

<div class='margin-container'>
  <video id=example-video-2 width=640 height=360 class="video-js vjs-default-skin" controls>
    <source
      src="http://cdn.lsatengine.com/HLS/HLSdemoVid.mp4"
      type="video/mp4">
  </video>
</div>
<link href="https://vjs.zencdn.net/4.12/video-js.css" rel="stylesheet">

<script src="//vjs.zencdn.net/4.12/video.js"></script>
<script src="javascript/videojs-media-sources.js"></script>
<script src="javascript/videojs-hls.js"></script>
<script src="javascript/xhr.js"></script>
  <script src="javascript/flv-tag.js"></script>
  <script src="javascript/exp-golomb.js"></script>
<script src="javascript/h264-extradata.js"></script>
  <script src="javascript/h264-stream.js"></script>
  <script src="javascript/aac-stream.js"></script>

  <!-- m3u8 handling -->
  <script src="javascript/stream.js"></script>
<script src="javascript/metadata-stream.js"></script>
  <script src="javascript/segment-parser.js"></script>
  <script src="javascript/m3u8/m3u8-parser.js"></script>
  <script src="javascript/playlist-loader.js"></script>
  <script src="javascript/playlist.js"></script>

  <script src="javascript/decrypter.js"></script>

  <script src="javascript/bin-utils.js"></script>

<script>
  var player1 = videojs('example-video-1');
</script>

<script>
  var player2 = videojs('example-video-2');
</script>
      
  </body>
  
</html>
```

**Comment by jcapucla** [comment]
Hi alexyats-

Thanks for looking in to this; I didn't see any response on Upwork though. Can you verify/resend it?

Also, I've added those js files to a public folder on my server, and linked to them as you suggested. But the stream is still failing.  Please see the demo:  http://goo.gl/Ug6oMI

I was also able to take a quick screenshot of an error message:
HLS playlist request error at http://cdn.lsatengine.com/HLS3/HLSdemo/HLSdemo.m3u8

You can see it in the screenshot below:
![hls error screenshot](https://cloud.githubusercontent.com/assets/826448/9326320/b8b87d6a-454d-11e5-9d46-0f0a39ba847a.png)

**Comment by alexyats** [comment]
it is working ok now, but you should do one of two things:

1) either start chrome with  --disable-web-security option (see screenshot attached)
2) or enable CORS (cross-origin-resource-sharing) on your storage. It should add Access-Control-Allow-Origin: * for all your hls files, because your player is requesting the content from another domain than itself resides. 

it seems something is broken at upwork now but they promising to fix it soon.

**Comment by jcapucla** [comment]
Great. This was the problem. I had assumed that because my cdn and website were on the same domain, my XHR requests wouldn't need a CORS setup. I was mistaken: apparently all requests with different hosts or subdomains requires CORS.

**Comment by alexyats** [comment]
glad to hear it was resolved. Could you please leave a review for me at upwork (Alexey Y)?

**Comment by jcapucla** [comment]
Sure. No problem. I will contact you through upwork.

**Comment by dmlap** [comment]
@alexyats thanks for the help getting to the bottom of this issue!

**Comment by jcapucla** [comment]
Hey Alexey- I contacted an "Alexey Y" on github, but it wasn't you. Please
send me a link to your user profile, and I will be happy to leave you a
positive review.

Send it to justin.capuano at gmail.com. And thanks again for the help.
