### ISSUE TITLE
We hiring: Alternate audio tracks, subtitltes and ABR enhancements sponsoring proposal

### ISSUE THREAD

**Issue by scramatte** [videojs/videojs-contrib-hls#365]
Hello,

We need support for alternate audio tracks, subtitltes and ABR.
We are interested into sponsoring development of such enhancements

**Comment by forbesjo** [comment]
@imbcmdth thoughts? We already have audioTracks

**Comment by dmlap** [comment]
All of these features are now supported in the master branch of this project:

- HLSv4-style alternate audio tracks
- Subtitles through embedded CEA-608 or sidecar WebVTT
- Adaptive bitrate selection and customization via overriding `selectPlaylist()`
