### ISSUE TITLE
Unable to get property 'mergeOptions' of undefined or null reference

### ISSUE THREAD

**Issue by luhaiyong** [videojs/videojs-contrib-hls#366]
hi ,i down the v0.3.1 (videojs-contrib-media-sources)and v0.17.8 (videojs-contrib-hls )
the run the example.html from the folder videojs-contrib-hls-0.17.8
occur this issue:
Unable to get property 'mergeOptions' of undefined or null reference
plz help

**Comment by gkatsev** [comment]
What version of videojs are you using?

**Comment by luhaiyong** [comment]
hi , 
v0.3.1 (videojs-contrib-media-sources)
v0.17.8 (videojs-contrib-hls )
the latest (video.js-master)

**Comment by gkatsev** [comment]
the 0.17.8 release of contrib-hls isn't compatible with videojs 5 (what's currently in videojs master).

**Comment by luhaiyong** [comment]
<script src="video.js"></script>
<script src="videojs-media-sources.js"></script>
<script src="videojs-hls.min.js"></script>
and i cant see the file videojs-hls.min.js,where is it?

**Comment by luhaiyong** [comment]
could u tell me ,which version ,i can use ?

**Comment by forbesjo** [comment]
Closing, if you are still having problems please open a new issue
