### ISSUE TITLE
Detecting audio only playback

### ISSUE THREAD

**Issue by ntadej** [videojs/videojs-contrib-hls#369]
I'm trying to detect, which quality is currently playing (I know the limitations of mediachange event). The use case is to display audio only message, so users do not think that something is wrong.

The main question would be, can I detect when player switches from audio only to video and back?

**Comment by dmlap** [comment]
We don't have a first-class API for this at the moment but we do annotate the segments with PTS information based on the streams we process while buffering. So you could do something like this:

```js
if (player.hls.playlists.media().segments[i].minAudioPts !== undefined) {
  // there is audio available for this segment
} 
```

Would that work?

**Comment by ntadej** [comment]
Isn't `player.hls.playlists.media()` the playlist currently selected by `player.hls.selectPlaylist`? This would mean that it may already change compared to currently played stream.

I currently detect audio only quality by reading current playlist and comparing it with our backend. The problem is, that it changes before actual playing content.

**Comment by gesinger** [comment]
Sorry this ticket has gone a long time without much attention. We recently added the ability to track which segments are currently in the buffer and when they change via the segment-metadata text track: https://github.com/videojs/videojs-contrib-hls#segment-metadata . This should help to know not just which playlist is selected, but which is actually playing. Please let us know if this doesn't resolve your use case. Thank you.
