### ISSUE TITLE
Can't play HLS from Cloudfront and S3

### ISSUE THREAD

**Issue by davek60** [videojs/videojs-contrib-hls#371]
I have been trying to get streaming to work from Amazons cloudfront I have a video on cloudfront that plays ok on VLC but errors with playback in video.js. The same page but with local video works fine.
The links are below
cloudfront 
https://d18woh43lxx04b.cloudfront.net/wildlife/wildlife.m3u8

my page to cloudfront
https://pcsmarts.biz/vjs/example1.html

local page
https://pcsmarts.biz/vjs/example.html

any idea what is wrong?

**Comment by gkatsev** [comment]
You need to make sure that you have CORS headers enabled, see [here in the README](https://github.com/videojs/videojs-contrib-hls#hosting-considerations). I can see that you don't currently have that up on your m3u8 or ts files.
