### ISSUE TITLE
HLS Live: player.currentTime() with polyfill different to Safari

### ISSUE THREAD

**Issue by chriswiggins** [videojs/videojs-contrib-hls#372]
With live playlists, I'm finding that `player.currentTime()` with the polyfill is generating different values to Safari.  I have a live playlist that's being generated by nginx-rtmp and a snapshot can be found here: [index.m3u8](https://gist.github.com/chriswiggins/7afa98ba77d5638fbacd)

Values taken within ~5 seconds of each other:
Safari currentTime: `5344.378033333333`
Chrome currentTime: `173670.46699999998` (this value remains the same and doesn't change)

This results in weird behaviour when trying to get DVR working as in #354. Safari's currentTime appears to be the duration at which it started streaming into the playlist, plus the amount of time it has been playing. For example if it started playing at `currentTime == 600`, then 30 seconds later `currentTime == 630` 

Not sure what I can do further to debug this as the value seems to come straight out of the polyfill?
Any ideas?

**Comment by chriswiggins** [comment]
Its also noted here [docs/live.md](https://github.com/videojs/videojs-contrib-hls/blob/c18e3df75d44d5552ce0521f37bbbfd8bbfc6c5e/docs/live.md#live-hls-research) so we should make sure the same behaviour is seen (or mimicked) in the browser version

**Comment by gesinger** [comment]
Hey @chriswiggins , sorry this issue has gone so long without much attention.

If you are still experiencing the issue with the latest version of videojs-contrib-hls (as of this comment, v4.1.1), would you happen to have a playlist that is accessible (the gist didn't appear to have full URIs for the segments)?

Thanks again for reporting the issue!

**Comment by gesinger** [comment]
Closing for now. If you are still experiencing this issue with the latest version of videojs-contrib-hls (as of this comment, v5.0.0), please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output)? Thank you.
