### ISSUE TITLE
[bug] When you view the HLS player displays the current time incorrectly

### ISSUE THREAD

**Issue by KorsaR-ZN** [videojs/videojs-contrib-hls#374]
We faced a strange behavior of the player. Viewing the playlist, when the time reaches ~18 second, the player changes the current time to incorrect value
What can it be related to?

This behavior is shown in the following playlist: [test.zip](https://drive.google.com/file/d/0BxDkwGMJ98ueZ0FXeEVpMTF2RGc/view?usp=sharing)

![screenshot from 2015-09-01 19 53 18](https://cloud.githubusercontent.com/assets/579410/9610610/62f35ffc-50e3-11e5-8bfd-5681679d37c5.png)

**Comment by sgavali** [comment]
I'm also seeing such issue after seek, progress bar starts from 0, while player is playing from seeked location. 
Sometimes player does not seek to desired location.

**Comment by sgavali** [comment]
What could be reason for progress bar showing incorrect playback time ?

**Comment by forbesjo** [comment]
Is this still an issue?
