### ISSUE TITLE
videojs(video).currentTime() does not do what is documented for HLS sources

### ISSUE THREAD

**Issue by himslm01** [videojs/videojs-contrib-hls#391]
When I call videojs(video).currentTime(position), where video is the <video> element and position is a number, the player does not do anything.

Is it expected that a videojs player playing an HLS file (a complete m3u8 with a EXT-X-ENDLIST at the end of the file) should seek to the time given in the currentTime([SECONDS])?

When I call videojs(video).currentTime(), where video is the <video> element, I'm always returned 0.

Is that expected?

Both seem to be at variance to the videojs documentation.

When the video I'm playing is an mp4 the above functions exactly as documented.

**Comment by dmlap** [comment]
That definitely should work. Are you creating your video player at the same time you're trying to seek? You do have to wait until the `loadedmetadata` event fires before you begin seeking.

**Comment by aramazhari** [comment]
@dmlap I've tried this on an Android device in crosswalk browser and it doesn't work. The currentTime is simply ignored and always says 0. Even after the video starts playing it still isn't seekable. This may not be videojs but actually those particular devices with problems. The content within our m3u8 files are .ts extensions.

**Comment by dmlap** [comment]
Ah, ok. The latest release of this project just delegates to the native HLS implementation on Android. On most devices, live streaming on Android is very broken and things like currentTime() behave non-deterministically. 

In our development branch, we're putting the finishing touches on an update that would allow us to take more control of playback and the API on Android devices. We're still tackling issues with some content before we do an official release but you can clone that branch and try it out on Android with your videos today.

**Comment by himslm01** [comment]
In my instance, this issue is seen on non-Android platforms.

I've added an on('loadedmetadata', function() {}); to my test, which displays a button, which, when clicked, always returns 0 for the HLS media in my demo.

https://github.com/himslm01/videojs_test2

**Comment by dmlap** [comment]
@himslm01 What browser are you testing with?

**Comment by himslm01** [comment]
Ive tested on both Chrome and Firefox, they both show the same.

**Comment by dmlap** [comment]
@himslm01 now that I look at it, I think the problem might be how you're calling videojs. After you initialize videojs for the first time, you'll get weird issues if you call `videojs(videoElement)` again. I'd suggest saving a reference to the player when you initialize it, and re-using that reference in your event handlers. If that's inconvenient, you can use `videojs(theDivThatVideoJsCreatedDuringInit)` to get another reference to the player. I'm closing this one but feel free to re-open if you still have issues.
