### ISSUE TITLE
Video not fetched while using local address

### ISSUE THREAD

**Issue by ajf-** [videojs/videojs-contrib-hls#396]
I am using the same example as in the front page:

```
    <video id=example-video width=600 height=300 class="video-js vjs-default-skin" controls>
      <source
         src="http://solutions.brightcove.com/jwhisenant/hls/apple/bipbop/bipbopall.m3u8"
         type="application/x-mpegURL">
    </video>
    <link href="https://vjs.zencdn.net/4.12/video-js.css" rel="stylesheet">
    <script src="video.dev.js"></script>
    <script src="videojs-media-sources.js"></script>
    <script src="videojs.hls.min.js"></script>
    <script>
      var player = videojs('example-video');
    </script>
```

And I was wondering what is happening when the html file is opened from a `file://` origin (locally). 
It works perfectly from a local server, but when opened directly, it seems to have trouble retrieving the feed. 

While on a server (e.g. http://localhost:8080), the network tab shows three xhr requests: 

```
fileSequence0.ts
fileSequence1.ts
fileSequence2.ts
```

While on a local address (e.g. file://), the network tab shows:

```
fileSequence0.ts
fileSequence1.ts
fileSequence2.ts
fileSequence3.ts
fileSequence4.ts
etc.
```

And carries on never ending. 

Is there anything in particular I need to do for this to work on a local file address? It seems that this is not a CORS issue. 

Thanks

**Comment by gkatsev** [comment]
Given that this project relies on flash (though, hopefully not for much longer) you have to load it in over a local webserver because flash doesn't like loading in over the file: protocol.

**Comment by dmlap** [comment]
Unfortunately, browsers block XHRs over the file protocol, too. This one seems like it is a limitation of web security, so I'm closing.
