### ISSUE TITLE
More robust buffering

### ISSUE THREAD

**Issue by dmlap** [videojs/videojs-contrib-hls#399]
Make sure that buffering is behaving sensibly and explainably for all scenarios involving switching playlists, dealing with discontinuities, or playing live events.

**Comment by mischizzle** [comment]
I'm currently looking at getting the plugin to reconnect after network disconnection. From this issue, I'm assuming this is in the pipeline, but not yet implemented? 

If I get something working, I'll create a pull request

**Comment by dmlap** [comment]
@mischizzle network disconnection wasn't something I was thinking of this when I filed this issue, but that would be an awesome. I'm closing this one but definitely open that PR if you find any issues with disconnection scenarios.

The original motivation for this was fixed with #397 so I'm closing.
