### ISSUE TITLE
Is cache for hls working?

### ISSUE THREAD

**Issue by novoxudonoser** [videojs/videojs-contrib-hls#401]
Is cache for hls working?

I have a video with #EXT-X-ALLOW-CACHE:YES , I use the newst video.js and video-hls.js and media-sourses, but local cache is'nt woring. When i try to see the previous part it starts to download all ts fragments.

**Comment by gkatsev** [comment]
I don't think we currently support that directly. However, the browser should cache the ts segments and so subsequent requests shouldn't actually re-download the segments from scratch.

**Comment by novoxudonoser** [comment]
Sanks a lot for fast answer. You're right, I think cache headers will do the stuff.
