### ISSUE TITLE
Switching Streams & HLS in Safari - uses HTML5 tech, how to force HLS tech to be used?

### ISSUE THREAD

**Issue by ablearcher9** [videojs/videojs-contrib-hls#403]
Hi there,

I'm trying to build an HLS player that allows the user to select which bandwidth stream they are playing.

A few questions:
- To allow switching streams I'm overriding `videojs.Hls.selectPlaylist` and then seeking by `setCurrentTime` to the current time to trigger the player to start using that stream, is there a better solution for this? It's a little janky.
- In Safari, as it plays native HLS, videojs is not using the hls tech, and as such I don't have access to any of this functionality. I've tried removing the html5 tech but then it just says it can't play the media file.

Thanks in advance!

**Comment by dmlap** [comment]
We always fall back to the native implementation if it's available today but it would be cool to allow an override. Feel like trying a PR? (Make sure to base it on the `development` branch if you do.)

**Comment by forbesjo** [comment]
We are currently working on this, stay tuned! :tv:

**Comment by aun343** [comment]
@forbesjo 

I desire to use the videojs of hls tech and access to some of this functionality in Safari and Edge.
Could you tell me when to complete?

**Comment by Jrubensson** [comment]
Any news on this? Would also like to use some functions relative to the HLS-object in VideoJS in Safari, and would be glad if I could override the native Safari playback.

**Comment by aamelegy** [comment]
I'm also using hls.xhr.beforeRequest for securing the urls but it is not working in safari and android. Would be cool if I can override the native implementation

**Comment by gesinger** [comment]
For those asking about overriding behavior and having access to more of videojs-contrib-hls' functions within browsers that have native implementations, overrideNative (https://github.com/videojs/videojs-contrib-hls#overridenative) is the solution for that, however, there is a known bug with overriding Safari's playback: https://github.com/videojs/videojs-contrib-hls/issues/1005 

Please follow that issue if you're looking for a solution for Safari. Thanks.

**Comment by aamelegy** [comment]
@gesinger I think it is no related only to safari. I'm trying to override the native HLS it is not working on Safari and on Android Chrome which also supports Native HLS. There is no errors generated in the console but still the native HLS is used. 

I'm using HLS stream that requires a secure token generated by the client to be sent with the manifest files or segments, but no way to do it without "hls.xhr.beforeRequest".

I'm willing to contribute to fix the bug can you give me any pointer where to dig in the code ?

**Comment by gesinger** [comment]
Thanks for giving it a shot @aamelegy . If you are having trouble with getting overrideNative to work (that isn't due to https://github.com/videojs/videojs-contrib-hls/issues/1005 ), would you be able to open a new issue and provide a reduced test case using our [starter template](http://jsbin.com/vokipos/8/edit?html,output)? Thanks.
