### ISSUE TITLE
Not working on FIrefox (ver 41.0.1)

### ISSUE THREAD

**Issue by lunejy** [videojs/videojs-contrib-hls#408]
Hi,

Cannot play the one in the demo page (http://videojs.github.io/videojs-contrib-hls/) with the latest firefox.

![demo_error](https://cloud.githubusercontent.com/assets/12489279/10211783/98328b3a-67bc-11e5-89ec-78b09eaad878.PNG)

The error message on Console says:
Specified "type" attribute of "application/x-mpegURL" is not supported. Load of media resource http://solutions.brightcove.com/jwhisenant/hls/apple/bipbop/bipbopall.m3u8 failed.

**Comment by forbesjo** [comment]
I see the error as well but the video does load for me.
<img width="849" alt="screen shot 2015-10-01 at 10 41 09 am" src="https://cloud.githubusercontent.com/assets/7529098/10223819/0a7ef766-6829-11e5-896d-882504b52224.png">

**Comment by forbesjo** [comment]
__Just tried it on Windows 10 and it does not load__

**Comment by lunejy** [comment]
Interesting.. I tested it on Windows 8 and Windows 10 with the latest firefox, but it didn't work. What's your firefox version?

**Comment by forbesjo** [comment]
41.0.1 and I just installed it on my Win 10 machine

**Comment by forbesjo** [comment]
This plugin does require flash to be installed (I didn't have it installed on my initial test on Windows 10)

**Comment by misteroneill** [comment]
Looks like the video is not served via SSL, we'll want to fix that. I am getting the following error in Firefox 41.0.1 on OS X:

> Blocked loading mixed active content "http://solutions.brightcove.com/jwhisenant/hls/apple/bipbop/bipbopall.m3u8"

**Comment by lunejy** [comment]
Thanks, I manually installed Flash from https://get.adobe.com/flashplayer/

But without manually installing the plugin, is it possible for Firefox to detect whether the flash plugin is not installed in the current browser, and display a message to install the plugin easily? I'm hosting a webpage and the most of users are not tech-savvy.

**Comment by forbesjo** [comment]
I believe it will fall back to the mp4 version (given you provide one) instead of prompting the user to install flash. I'll see if there are any video.js issues that discuss adding a prompt for flash.

**Comment by dmlap** [comment]
Looks like this one would be better handled in video.js proper, closing.
