### ISSUE TITLE
Multiple async bitrate error

### ISSUE THREAD

**Issue by Llorx** [videojs/videojs-contrib-hls#410]
Hi,

I have a m3u8 file that has inside multibitrate m3u8 files too. They can't be synced easily so, in the long term, they start to differ from each other. This is because I'm getting an rtmp stream, creating an hls stream whith it and also transcoding that stream and creating other 2 hls streams. I can sync the transcoded streams easily using one ffmpeg instance and a bunch of commands, but I cannot control the main stream, and I don't want to transocde it too because I don't want to lose quality.

This is the problem that happens when async happens:
In the line 133 in playlist.js we have this line: `segment = playlist.segments[right]`. The problem is that `right` is a really bigger number than `playlist.segments.length`, so `segment` becomes undefined, with all the errors that happens after this.

`right` is bigger than `playlist.segments.length` because of the line 187 in playlist.js: `endSequence - playlist.mediaSequence`: `endSequence` is right, is the last sequence in the playlist, but `playlist.mediaSequence` is wrong, as is the secuence in the current playlist (I think), but not in the playlist that is not synced, so if the playlist that is not synced is X segments after/before the other list, the calculation will be wrong.

I think that to fix this it should calculate the difference in seconds to the end of the stream in the current playlist and change to the file that is the same amount of time away in the second playlist, instead of asuming that both streams and perfectly synced.

**Comment by Llorx** [comment]
I've made a workaround, adding this in the line 185 in playlist.js:
    // accumulate the segment durations into the result
    /* added code */
    if (endSequence - startSequence > playlist.segments.length) {
        endSequence = startSequence + playlist.segments.length;
    }
    /* end added code */
    result += accumulateDuration(playlist,

This ensures that it will not ask for more segments than needed.

**Comment by gesinger** [comment]
Hey @Llorx , sorry this ticket has gone a long time without much attention. I know you've posted the workaround, but we've made a lot of changes to videojs-contrib-hls in the meantime.

Would you be able to give the latest version (as of this comment, v4.1.1) a shot? If it's still a problem, would you be able to re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/edit?html,output)? If it's still problematic, we can take another look at the snippet and see if it works for the new flow.

Thank you again for reporting the issue.

**Comment by Llorx** [comment]
I've switched to Flowplayer some time ago, as I needed a production-secure release.

Since videojs-contrib-hls has changed a lot lately, I have to give it a try again.

Thank you for the follow up.
