### ISSUE TITLE
Reseting the video progress after manual override

### ISSUE THREAD

**Issue by siner55** [videojs/videojs-contrib-hls#412]
I'm working on manual bitrate switching in addition to providing adaptive bitrate.

So after doing this:

player.hls.playlists.media = function() {
            return player.hls.playlists.master.playlists[0];
};      

How can I reset (forget) the current progress and switch to the new stream instantly rather then waiting for the loaded media and then switching?

Thanks

**Comment by dmlap** [comment]
`playlists.media` is a getter/setter, you should not overwrite it with a function of your own. Instead, you would do something like this:

```js
player.hls.playlists.media(player.hls.playlists.master.playlists[0]);
```

If I understand your question correctly, you can swap to the beginning of a different quality level and turn off automatic adaptive switching using the src attribute:

```js
player.src('low.m3u8');
```

If you want to asynchronously load the playlist and then swap over at the next opportunity, use the setter version of media() like in my first example.
