### ISSUE TITLE
hls over mse can't play certain streams

### ISSUE THREAD

**Issue by shacharz** [videojs/videojs-contrib-hls#414]
tested with development updated to e3c7a1bc3b3b9afb55d54848c029c3d8ca59d03d (30sep15)
changed the src in /example.html

https://livestream.peer5.com/video/kite/index.m3u8 - get freezes after a few seconds
http://wowza.streams.peer5.com:1935/vod/smil:orionVodSplitAV.smil/playlist.m3u8 - doesn't play

**Comment by arikgilad** [comment]
Also have problems playing:
http://makostore-vh.akamaihd.net/i/SHORT/CH22_NEWS/2015/09/press_vtr2_n20150903_v1/press_vtr2_n20150903_v1_,500,850,.mp4.csmil/master.m3u8?hdcore=3.0.3

The video will start playing but after seeking the video is distorted or freeze while sounds is still playing properly.

**Comment by dmlap** [comment]
@arikgilad I downloaded the [second segment](http://makostore-vh.akamaihd.net/i/SHORT/CH22_NEWS/2015/09/press_vtr2_n20150903_v1/press_vtr2_n20150903_v1_,500,850,.mp4.csmil/segment2_1_av.ts?null=) of that stream to debug and it looks like there isn't any video data in it. ffmpeg is unable to transmux it and Quicktime only plays audio. I think you have something misconfigured.

**Comment by dmlap** [comment]
@shacharz it looks like some segments in the wowza stream declare an audio track but do not actually contain any audio data. Part of the segment-transformation process is sitting around waiting for audio data and so nothing gets fed to the video. We're looking into a fix.

**Comment by Pablo76** [comment]
@dmlap regarding second segment: there is *probably* no issues with the segment (HLS spec would need to be consulted if something like that is allowed). Basically, it looks like entire entire original .ts was split into chunks on 188-byte boundary and without 1st segment other segments are useless. If you simply concatenate chunks then everything will play fine. You can also play the stream in VLC to confirm that in fact there is video data in second segment. flashls also plays this clip perfectly.
The reason ffmpeg cannot "see" video in second chunk is because sps+pps are only in the first egment.

**Comment by dmlap** [comment]
@Pablo76 the HLS spec does require at least one keyframe per segment (see [the first full paragraph on page 6](https://tools.ietf.org/html/draft-pantos-http-live-streaming-17#section-3)). It is probably possible to play back this stream over MSE but it would be a big challenge and might make buffering worse for streams that were well-formed. It's not clear to me, for instance, what the player should do if it's asked to seek into a segment without a keyframe. We'd have to keep buffering backwards an arbitrary number of segments and hold those intermediate segments in-memory until we encountered the keyframe and could transmux to fMP4.

If someone has a clever idea to simplify that workflow and wants open up a PR, that would be awesome. Absent that though, I'm not inclined to tackle streams missing per-segment keyframes anytime soon.

**Comment by Pablo76** [comment]
Sorry for late reply. Just to make it clear: this stream has no key-frames, but at the same time it doesn't need them to play video or seek. According to HLS segments SHOULD have keframes and should be playable on their own, but should means that they don't have to :)

So, there are two separate issues: 1) keyframes, 2) decoder specific info, a.k.a. sps+pps.
This particular stream doesn't need keyframes, it has something equivalent. If you try to naively search for IDR-nal type you won't be able to handle the stream properly. Try to re-wrap stream using ffmpeg into mp4 (-vcodec copy, without re-encoding h264 bitstream), and you'll see that seeking works even tough it looks as if the stream doesn't have any keyframes: it has recovery points instead.
2) decoder specific info... these are present in first segments only in this stream. So, if switch happens to alternative stream on 1+Nth segment and if there is no decoder specific info present before handling keyframe (or something equivalent) then hls-contrib should try to retrieve it from first segment in the stream, first segment of a stream must have decoder specific info available.

**Comment by dmlap** [comment]
True enough: SHOULD is not MUST, you've hoisted me by my own pedantic spec reference :)

There are two significant challenges playing back this stream that I can see. First off, we carry very little state across segments in the transmux right now and we'd need to hold on to the decoder specific info at least to get this working. Buffering correctly to fetch the decoder specific info would be the other big change. We just modified our buffering strategy to always attempt to fetch segments that would append onto the buffered range that currently contains the playhead. I'm sure that could be enhanced to look back to the first segment if required but segment fetching isn't very well encapsulated right now so it could be tricky.

That seems like a bigger job than the other streams in this thread so it might be worthwhile to track it separately.

**Comment by ironweber** [comment]
Any updates on this? ... I am having a very similar issue. Though the segment with no keyframe plays in Firefox 48 but does not play in Chrome 52 (MacOS 10.11.6) I thought this might be a MSE issue but hls.js plays the stream fine in both Firefox and Chrome. The loadeddata event never fires and also when I go to chrome://media-internals/ there isn't anything there.

**Comment by forbesjo** [comment]
I'm not seeing any issues with the posted sources, closing since this seems to have been addressed.
