### ISSUE TITLE
fallback to flash in non supporting browsers

### ISSUE THREAD

**Issue by shacharz** [videojs/videojs-contrib-hls#415]
the plugin should fallback to flash if it can't play hls over mse
tested on /examples

**Comment by dmlap** [comment]
It should be falling back to Flash already if MSE isn't supported. What browsers were you testing with?

**Comment by shacharz** [comment]
Tested it then on FF 41.

**Comment by dmlap** [comment]
Everything should be working (including using MSE in FF42) as of 1.2.0. Please reopen if you're still seeing issues.

**Comment by shacharz** [comment]
Tested again on a bunch, FF41 looks ok now (plays on Flash).
IE11 on win8.1 is not playing and not falling back to Flash.
