### ISSUE TITLE
Releases are source only since 0.17.6

### ISSUE THREAD

**Issue by thenewguy** [videojs/videojs-contrib-hls#417]
I had a longer response written but it got lost.  Let me know if this requires elaboration...

The releases after 0.17.5 (i.e. [v0.17.9](https://github.com/videojs/videojs-contrib-hls/releases/tag/v0.17.9)) on github do not seem to contain contact version or uglify version output.  I couldn't find a discussion about this so I am guessing these were unintentionally removed from the releases

**Comment by cladera** [comment]
+1

**Comment by Tralapo** [comment]
This was discussed in #167 too. For people who don't know how to build it, this plugin is not usable right now. Should me made easier to deploy by including the build.

**Comment by sgavali** [comment]
+1

**Comment by sgavali** [comment]
Where can I get working js files for latest 0.17.x release. Can someone update demo page using those so they can be easily available without building plugin.

**Comment by dmlap** [comment]
[1.2.2](https://github.com/videojs/videojs-contrib-hls/releases/tag/v1.2.2) includes built artifacts again. Sorry about the inconvenience!

**Comment by sgavali** [comment]
1.3.0 is source only too.

**Comment by sgavali** [comment]
I tried to build dist package by cloning and running grunt, so far no luck.

**Comment by Tralapo** [comment]
Download -> ```npm install``` -> ```grunt build``` works for me.

**Comment by sgavali** [comment]
I'm using these steps;

$ npm config set strict-ssl false
$ npm config set registry "http://registry.npmjs.org/"
$ npm -proxy http://abcd:80 install videojs-contrib-hls@0.17.9
$ grunt build

Warning at grunt build,
>>Warning: Task "build" not found. Use --force to continue.
>>Aborted due to warnings.

Configuration used, ubuntu 15.04, 
$ npm -version 
1.4.21

$ grunt -version
grunt-cli v0.1.13

$ nodejs --version
v0.10.25

grunt v0.4.5

**Comment by gkatsev** [comment]
You won't be able to build it from an npm install because there's devDependencies. If you clone the git repo and run `npm install` in that folder, you should be able to then run `grunt build`

**Comment by gkatsev** [comment]
You can also download the "source code" tarball from the releases page.
