### ISSUE TITLE
1.0.1-0 is not stable when segment load

### ISSUE THREAD

**Issue by Rorchach** [videojs/videojs-contrib-hls#418]
I want to use 1.0.1-0 in my project, but i find it has some bug in load segment at low bandwidth.
The bug happens in 'PlaylistLoader.prototype.getMediaIndexForTime_' function.
So I want to fix it, can you tell me where is the standdard hls load rule?

**Comment by dmlap** [comment]
Have you tried 1.1.0? We made a number of fixes to buffering in that release.

**Comment by forbesjo** [comment]
Please reopen if this is still an issue
