### ISSUE TITLE
No-Flash HLS on Chrome?

### ISSUE THREAD

**Issue by jimkang** [videojs/videojs-contrib-hls#421]
I know you guys probably didn't write this [video.js blog post](http://blog.videojs.com/post/130143694631/video-js-5), but I was wondering if you were able to clear something up about what I think it says about videojs-contrib-hls:

> Added support for HTTP Live Streaming in desktop browsers WITHOUT Flash

The basic premise of this project seems to be to check to see if there's native HLS support (as in Safari), then fall back to Flash for HLS. So, is there another video.js HLS project somewhere that supports HLS on, say, Chrome, without Flash?

**Comment by gkatsev** [comment]
This is the project. Unfortunately, it isn't quite ready yet. See the development branch and follow this thread for updates: https://github.com/videojs/videojs-contrib-hls/issues/382
Sorry for the confusion.

**Comment by jimkang** [comment]
OK, thanks for the clarification!

**Comment by gkatsev** [comment]
No problem.
