### ISSUE TITLE
Android chrome crashes when it's moved to background

### ISSUE THREAD

**Issue by sgavali** [videojs/videojs-contrib-hls#424]
I'm observing chrome player crash when it is moved to background and then playback is resumed by bringing chrome to foreground.

videojs-contrib-hls - v0.17.1
Video.js v4.12.11 
Android chrome version 46.x
Android version 4.x

I'm seeing segmentation fault after lots of  "( 5780): hasBufferAvailable empty" prints. 

This maybe similar issue as https://github.com/videojs/video-js-swf/issues/95

**Comment by sgavali** [comment]
Is there way to trigger buffering in this scenario ?

**Comment by dmlap** [comment]
In the 0.x releases of this project, native HTML5 video is being used to playback HLS. This sounds like a device/browser/OS issue. We might be able to fix it in the 1.x release using MSE. Any chance you've tried out a later version on Android Chrome?

**Comment by sgavali** [comment]
Latest version of chrome also shows this issue.

**Comment by sgavali** [comment]
Is 1.x beta available for testing ?

Between I tried hls plugin mentioned in https://github.com/videojs/videojs-contrib-hls/issues/437 it does solves this issue.

But I saw crash on Galaxy S3 (android 4.3 and latest chrome) with this error,
>> SsbSipMfcDecInit] IOCTL_MFC_DEC_INIT failed

**Comment by dmlap** [comment]
@sgavali yes, it is. You can clone this project and build the `development` branch to try out the absolute latest, or pull it down from npm via `videojs-contrib-hls@1.2.0`.

**Comment by sgavali** [comment]
Thanks dmlap, I see 1.2.1 is released, but I'm getting errors while using it. Issue maybe version of video.dev.js and videojs-media-sources.js, I'm using these from videojs-contrib-hls demo page.

Error's are 
1. Uncaught TypeError: videojs.extend is not a function
2. VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this video.

**Comment by sgavali** [comment]
I could run 1.2.1 latest video.js and videojs-media-sources.js. There is no crash on galaxy S3 we can close this issue.
