### ISSUE TITLE
Pause-resume video starts at different location

### ISSUE THREAD

**Issue by sgavali** [videojs/videojs-contrib-hls#426]
I'm seeing while doing pause and resume playback starts at few seconds earlier than paused position. I have forced I frame duration every 0.5 sec while creating mp4 using ffmpeg, so it should ideally start max 0.5 sec earlier than paused location.

**Comment by dmlap** [comment]
What version of contrib-hls are you using? Do you have an example segment anywhere we could look at?

**Comment by sgavali** [comment]
I'm using v0.17.1, issue is specific to device and not stream.
Also on some device I see different playback time stamp than what it should be, is this issue in Chrome stack ?

**Comment by dmlap** [comment]
Do you still see this issue in contrib-hls 1.x? What devices are you testing on? Also, if you have a publicly available stream we can try it against, that would help.
