### ISSUE TITLE
Firefox 42 now supports MSE videojs-contrib-hls fails to load media

### ISSUE THREAD

**Issue by aronallen** [videojs/videojs-contrib-hls#427]
I am trying to open the following stream in Firefox with VideoJS 5.0 and videojs-contib-hls 1.1.0
```
http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8
```
I get the following error in the console
```
Specified "type" attribute of "application/x-mpegURL" is not supported. Load of media resource http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8 failed. localhost:3002
All candidate resources failed to load. Media load paused.
```
It correctly displays the length of the video, but it fails to play.

**Comment by tchakabam** [comment]
So first off, if you are looking for a HLS player backed by MSE, check this out, maybe it'll actually play your stream on Firefox: https://github.com/dailymotion/hls.js

This Videojs project is actually backed by Flash right now, even if some MSE support for the HLS contrib is supposed to be in the works.

AFAIU the ricky thing here is that MSE on Firefox doesn't support TS I think. You'd need to transmux the stream to an MP4 container. That's the only container supported and codec has to be AAC/H264. Chrome has much better support here for different kind of streams and codecs (but even they don't support TS natively). You can check that with `MediaSource.isTypeSupported('video/MP2T')`.

In a similar way when Flash is used as a backend, everything is transmuxed to FLV afaik. Similar work will have to be done to make this work with MSE, no?

**Comment by dmlap** [comment]
Firefox doesn't support source buffers that carry both audio and video data streams combined together right now. We switched to that format because it fixed buffering issues in Chrome 45 but the workarounds don't seem necessary anymore in Chrome 46. We're [in the middle of splitting audio and video back out again](https://github.com/videojs/videojs-contrib-media-sources/pull/51), which should fix FF.

**Comment by dmlap** [comment]
@aronallen basic playback support for FF via MSE should be in place in 1.2.0. Closing this one based on that but please reopen if it doesn't work for you after updating.
