### ISSUE TITLE
Chrome exception and no audio in latest development branch.

### ISSUE THREAD

**Issue by ogzpub** [videojs/videojs-contrib-hls#441]
I haven't had time to dig into the latest commits at all but sometime between 2015-11-12 and yesterday chrome started throwing the error below and playing video without audio.

Uncaught QuotaExceededError: Failed to execute 'addSourceBuffer' on 'MediaSource': This MediaSource has reached the limit of SourceBuffer objects it can handle. No additional SourceBuffer objects may be added.

The line of code triggering it is this.

this.audioBuffer_ = nativeMediaSource.addSourceBuffer('audio/mp4;codecs="' + this.codecs_[1] + '"');

If I get some time I'll try and look at what changed but I'm not terribly familiar with this project's code as of yet. Let me know if you want me to try anything as well.

Thanks!

**Comment by ogzpub** [comment]
I just realized this is actually code from videojs-contrib-media-sources that's throwing the error. However it's only when I update my snapshot of this project that the issue occurs. If I rollback to my version of videojs-contrib-hls to the 12th it works with both the media-sources from the 12th and the most recent version.

**Comment by imbcmdth** [comment]
Do you have an example of a playlist on which this happens?

**Comment by ogzpub** [comment]
Every stream I've tried from a wowza server has done it. Here's one from their demo page that I confirmed does as well.

` http://184.72.239.149/vod/smil:bigbuckbunnyiphone.smil/playlist.m3u8`

**Comment by ogzpub** [comment]
I have some good news. Updating to videojs-media-sources 2.4.1 fixed the issue. I almost didn't notice though as I didn't realize videojs-contrib-hls was bundling it's own copy and overriding mine. Is that intentional?

**Comment by dmlap** [comment]
@ogzpub glad to hear it's working! We're trying to make this project a bit easier to integrate in 1.0 so we're bundling more up in the official distribution. Sorry if that was confusing.
