### ISSUE TITLE
On LIVE HLS (DVR) stream media object is not updated

### ISSUE THREAD

**Issue by FDiskas** [videojs/videojs-contrib-hls#442]
Hello, on LIVE HLS (m3u8) stream
Every time after playlist request was done the media object is not updated.
For example if playlist content is

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-PLAYLIST-TYPE:EVENT
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:10.000000,
1448020624.ts
#EXTINF:10.000000,
```

The media object content is `hls.playlists.media_`

``` js
{uri: "http://***.m3u8", allowCache: true, discontinuityStarts: Array[0], playlistType: "EVENT", targetDuration: 10…}
```

And on other request the playlist got the `#EXT-X-ENDLIST` tag the media object still shows nothing about that 

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-PLAYLIST-TYPE:EVENT
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:10.000000,
1448020624.ts
#EXTINF:10.000000,
#EXT-X-ENDLIST
```

Returns the same object
`hls.playlists.media_`

``` js
{
   allowCache: true,
   discontinuitySequence: 0,
   discontinuityStarts: [],
   mediaSequence: 0,
   playlistType: "EVENT",
   segments: [],
   targetDuration: 10,
   uri: "http://***.m3u8"
}
```

It should return updated object

``` js
{
   allowCache: true,
   discontinuitySequence: 0,
   discontinuityStarts: [],
   endList: true,
   mediaSequence: 0,
   playlistType: "EVENT",
   segments: [],
   targetDuration: 10,
   uri: "http://***.m3u8"
}
```

Missing `endList: true`. If I manually change that object `hls.playlists.media_.endList = true` the player acts as it should on DVR streams.

Currently I'm using
"videojs": "4.12.15",
"videojs-contrib-hls": "0.17.8",
"videojs-contrib-media-sources": "1.0.0",

**Comment by dmlap** [comment]
One related thing to note: we suffix variable names with `_` to indicate they're "private" and could change between releases. If you want access to the media playlists currently in use, you should call `hls.playlists.media()` on the playlist loader (which essentially returns `media_`).

I've seen this streams swap from live mode to VOD mode when `#EXT-X-ENDLIST` is added to the media playlist myself without issues. Is there anything else interesting about your stream setup that might be influencing this?

**Comment by FDiskas** [comment]
Then `#EXT-END-LIST` added the player does not trigger `ended` event

**Comment by FDiskas** [comment]
And you got the ended event?

**Comment by FDiskas** [comment]
And if I try `player.hls.duration()` I always get response as `Infinity`

**Comment by gesinger** [comment]
Hey @FDiskas . Sorry this ticket has gone a long time without much attention. We've made a lot of changes to videojs-contrib-hls in the meantime, particularly around how we handle live streams. Would you be able to give the latest version (as of this comment, v5.2.1) a shot? If it's still a problem, would you be able to re-open the issue and provide a test case with your stream using [this template](http://jsbin.com/vokipos/8/edit?html,output)? Thanks.

**Comment by gesinger** [comment]
Closing for now. If you are still experiencing this issue with the latest version of videojs-contrib-hls (as of this comment, v5.3.3), please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.
