### ISSUE TITLE
Stop using `targetDuration` as the default for segment duration in playlist functions

### ISSUE THREAD

**Issue by imbcmdth** [videojs/videojs-contrib-hls#443]
We use `targetDuration` as a default in several places as a guard against there being no individual segment duration. The m3u8 parser already sets the segment duration to the target duration if none was provided in the manifest. We should remove all instances of that check and trust that all segments will have a duration set by the time we see them in `playlist.js` and `playlist-loader.js`.

**Comment by gesinger** [comment]
I think we might be OK on this one now @imbcmdth
