### ISSUE TITLE
Trouble with HLS using Latest VideoJS and Media Source Code v2.4.0

### ISSUE THREAD

**Issue by acornils** [videojs/videojs-contrib-hls#449]
Attempting to use HLS video with the follow

ing JS player and html code and am getting the following error message in IE 11. Chrome seems to have an issue as well but just displays no compatible source video found which is the same result in IE 11 if ignore the issue and proceed with code execution. It should also be noted this only happens when I use the video.js file downloaded from the GitHub project source control for the video js project. If I use <script src="http://vjs.zencdn.net/5.2.2/video.js"></script> IE and Chrome load without errors but Just get the spinning buffering/loading wheel/circle in the video window. Browsers with Native HLS support like iOS and Ironically Edge seem work just fine which makes sense.

/*! videojs-contrib-hls - v1.2.1 - 2015-11-21
Unhandled exception at line 2926, column 3 in http://localhost:50282/Scripts/videojs.hls.js
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'extend'
```
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="http://vjs.zencdn.net/5.2.2/video-js.css" rel="stylesheet">

    <!-- If you'd like to support IE8 -->
    <script src="http://vjs.zencdn.net/ie8/1.1.0/videojs-ie8.min.js"></script>
</head>

<body>
    <video id="my-video" class="video-js" controls autoplay preload="auto" width="640" height="264"
           poster="MY_VIDEO_POSTER.jpg" data-setup="{}">
        <!-- <source src="http://192.168.42.214/media/BehindTheBikini_Open.mp4" type='video/mp4'>-->
        <source src="http://solutions.brightcove.com/jwhisenant/hls/apple/bipbop/bipbopall.m3u8" type="application/x-mpegURL">
        <p class="vjs-no-js">
            To view this video please enable JavaScript, and consider upgrading to a web browser that
            <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
        </p>
    </video>


    <script src="Scripts/video.js"></script>
    <script src="Scripts/videojs.hls.js"></script>
    <script src="Scripts/videojs-contrib-media-sources-2.4.0/src/videojs-media-sources.js"></script>

</body>
</html>
```

**Comment by sgavali** [comment]
I also see issue with IE, I'm using all latest plugins.
>>VIDEOJS: InvalidStateError Video is not ready. (Video.js)

**Comment by Tralapo** [comment]
You don't have to include videojs-media-sources.js I found out recently, contrib-hls.js contains one itself. 

The stream in your example is working for me (except in Firefox, which is, as always, complaining about origin of the stream). Are you sure your video.js file is build right? I would think that's the problem if it's not happening with the CDN-version?

**Comment by forbesjo** [comment]
Please reopen if this is still an issue
