### ISSUE TITLE
Unable to play media without an audio track.

### ISSUE THREAD

**Issue by ogzpub** [videojs/videojs-contrib-hls#453]
After some tests it would seem that archived content (at least everything I have tested) without an audio track silently fails to play. No errors are thrown it simply requests the first segment and then sits there eternally. Oddly, live streams without an audio track seem to play fine.

**Comment by dmlap** [comment]
Does your m3u8 have codec attributes on the STREAM-INFs? We need to be smarter about audio or video only content but we should work correctly if you warn us ahead of time when you're using single-track streams.

**Comment by ogzpub** [comment]
@dmlap It does indeed have the codec attribute.
```
CODECS="avc1.66.31"
```
These particular files were created with Adobe's Flash Media Live Encoder by just unchecking the audio source.

**Comment by forbesjo** [comment]
Is this still an issue? If so please reopen.
