### ISSUE TITLE
discussion seek behaviour

### ISSUE THREAD

**Issue by sgavali** [videojs/videojs-contrib-hls#455]
I'm observing different seek related behavior across different android phone, and it does not seems to be related to content.

1. After seeking sometime progress bar in UI starts from 0, playback is happening at desired point in video. Adding alert with currentTime shows correct value.
2. After seeking playback starts after few seconds in some phone, the delay is sometimes 10sec or so, I'm using RPI and system is not much loaded.
3. Sometimes seek does not happen to desired location, ie seek happens to some earlier location

**Comment by dmlap** [comment]
Can you add some details on the platform(s) you're seeing this problem on? Specifically: browser and version, OS and version, device make and model.

**Comment by sgavali** [comment]
I'm seeing issue on Android, it's not specific to OS / Chrome version. Issue 3 is easily seen on Xiomi redmi 4i phone. What may be causing this, is this related to https://github.com/videojs/videojs-contrib-hls/issues/358 ?

**Comment by sgavali** [comment]
One more observation, on doing multiple seeks I'm seeing crashes due to audio discontinuity. The content is playing properly without doing seek.

1)
D/NuPlayer( 254): got audio decoder EOS
D/NuPlayer( 254): got audio decoder discontinuity, (consume status: 0, 0)
W/NuPlayerRenderer( 254): numFramesAvailableToWrite(8916), mAudioSink frameCount(8916), mAudioQueue size(1), numFramesPlayed(0), mNumFramesWritten(0)
D/NuPlayerRenderer( 254): audio played time(0 us), system time(235749053376 us),[S-A](2260842 us)
I/AudioSink( 254): [stop] stop
D/AudioTrack( 254): audiotrack 0xabb16150 stop done
D/MediaPlayer( 4252): handleMessage msg:(100, 1, -1004)
D/NuPlayerRenderer( 254): audio position EOS
E/MediaPlayer( 4252): Error (1,-1004)
E/NuPlayerDecoder( 254): Stream error for OMX.MTK.VIDEO.DECODER.AVC (err=-1004), EOS successfully queued

2)
E/NuPlayer( 238): audio track encountered an error (-1004)
E/ ( 238): not in avi mode
V/MediaPlayer(30374): message received msg=100, ext1=1, ext2=-1004
E/MediaPlayer(30374): error (1, -1004)
V/MediaPlayer(30374): callback application
V/MediaPlayer(30374): back from callback
V/MediaPlayer(30374): getCurrentPosition
E/NuPlayer( 238): video track encountered an error (-1004)
V/MediaPlayer(30374): message received msg=100, ext1=1, ext2=-1004
V/MediaPlayer(30374): seekTo 6136808
E/MediaPlayer(30374): Attempt to perform seekTo in wrong state: mPlayer=0x59b32168, mCurrentState=0
V/MediaPlayer(30374): message received msg=100, ext1=-38, ext2=0
E/MediaPlayer(30374): error (-38, 0)

**Comment by sgavali** [comment]
I checked with 1.2.1 plugin and crash issue looks to be gone. It was seen with 0.x plugin.

Regarding seek issue no 3, I still see using 1.2.1, putting alert in seeked event the time shown is correct, but progress bar shows different value. 
It happens frequently when seek is done towards end of video while current position is at beginning. The progress bar still shows old value, does this mean for calculation of progress bar %, playback time before the seek is getting used ?

**Comment by dmlap** [comment]
@sgavali 3) sounds like it may be a video.js issue. What is player.currentTime() returning and what are you expecting?

**Comment by sgavali** [comment]
One more observation. Sometimes seeked event is not coming, and player continue to show loading spinner. Any seem using seekbar does not help.
For issue 3 I'm seeing current time corresponding to seeked location which is different than intended position.

**Comment by sgavali** [comment]
The last issue looks same as https://github.com/videojs/video.js/issues/2647
But I can still see using latest video js and hls plugin on some android phones.

**Comment by forbesjo** [comment]
Is this still an issue?

**Comment by forbesjo** [comment]
Closing
