### ISSUE TITLE
Playback problems when audio and video are not aligned

### ISSUE THREAD

**Issue by ntadej** [videojs/videojs-contrib-hls#456]
There are several playback problems on development branch when audio and video are not aligned. It's same for LIVE or VOD playlists:
1. Segments are not downloaded in sequence. Example: 0 1 2 1 2 3
2. Audio glitches on segment-to-segment transitions
3. Random freezes on LIVE, same position on VOD each time (with no errors or warnings in chrome://media-internals)

**Comment by gesinger** [comment]
Hey @ntadej . Sorry this ticket has gone a long time without much attention. We've made a lot of changes to videojs-contrib-hls in the meantime, including work on playback with misaligned content. Would you be able to give the latest version (as of this comment, v4.1.1) a shot? If you're still seeing those issues, would you be able to re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/edit?html,output)?

Thank you again for reporting the issue.
