### ISSUE TITLE
Implicit HE-AAC signaling problem

### ISSUE THREAD

**Issue by ntadej** [videojs/videojs-contrib-hls#457]
Is there a way to detect required audio codec without adding it to m3u8 playlist?

I'm getting
```Implicit HE-AAC signalling is being used. Please use mp4a.40.5 instead of mp4a.40.2 in the mimetype.```

**Comment by dmlap** [comment]
It would require digging into the individual AAC packets. It might be computationally/code-size expensive and it's something we don't currently have implemented. I think Chrome is being overly picky about decoder configuration though and filed [an issue](https://code.google.com/p/chromium/issues/detail?id=563197) to see if the restrictions could be loosened.

If we were going to detect HE-AAC, it would have to happen during the segment transmuxing process so this should probably be refiled against [mux.js](https://github.com/videojs/mux.js) if you'd like to discuss it further.
