### ISSUE TITLE
Infinite looping after multiple seek

### ISSUE THREAD

**Issue by sgavali** [videojs/videojs-contrib-hls#458]
Plugin version 1.2.1
After doing multiple seeks player goes in infinite loop and tries to download same chunks again and again.
![121](https://cloud.githubusercontent.com/assets/13160501/11439527/01de0554-9522-11e5-8bac-a5f015c7c4b2.jpg)

**Comment by sgavali** [comment]
I can reproduce using bipbopall.m3u8 .
![121](https://cloud.githubusercontent.com/assets/13160501/11440920/b032ec96-952c-11e5-8026-94aafb78c9ae.jpg)

**Comment by imbcmdth** [comment]
This is something we have noticed too and are eager to fix before the v1.x.x release milestone.

Thank you for your report @sgavali

**Comment by sgavali** [comment]
I checked using 1.3.0 and issue is fixed. Thanks.
