### ISSUE TITLE
[Development v1.2.2] Uncaught InvalidStateError: MediaSource.addSeekableRange()

### ISSUE THREAD

**Issue by Tralapo** [videojs/videojs-contrib-hls#460]
Upgraded to v1.2.2 of the development branch, fixes a few problems, thanks for that.

But it's also introducing a new problem for me. My livestreams won't play initially. I get a lot of errors in the console and the poster stays visible, no video. After a few times pressing pause/play, the stream does get going in Chrome.

Console output Chrome (name blanked):

![knipsel](https://cloud.githubusercontent.com/assets/11296429/11456686/9ce1ca08-9690-11e5-99fa-2194137eb0d8.JPG)

**Comment by dmlap** [comment]
This is occurring when you're just starting up your live stream? If that's the case, does it still occur once it's been streaming for 30-45 seconds? Could you capture your m3u8 responses when this is occurring and add them to this issue?

**Comment by Tralapo** [comment]
Behavior is a bit different. I have a page with only one player, it gives me the same error but starts playing when I hit play.

I have another page with four players, all (except from id= off course) the same as my one-video page and those streams only show the video after hitting play/pause a few times. In the meantime, it's downloading .m3u8 and .ts files as expected and normal.

The MediaSource.addSeekableRange() error is coming up all the time when the stream is up and running. After 30 seconds of playing, my console counted 275 of those errors.

With 1.2.0 everything is fine.

**Comment by Tralapo** [comment]
I have a page with four players and those streams only show the video after hitting play/pause a few times. In the meantime, it's downloading .m3u8 and .ts files as expected and normal.

The MediaSource.addSeekableRange() error is coming up all the time when the stream is up and running. After 30 seconds of playing, my console counted 275 of those errors. That's with one video playing, but it's picking up that error from the other players too (as they do download .ts files while they aren't playing).

With <1.2.2 everything is fine.

On a page with only one player, the error seems to stop after 4-5 times.

**Comment by Tralapo** [comment]
With 1.3.0 and Video.JS v5.3 Chrome still trows a ``Uncaught InvalidStateError: MediaSource.addSeekableRange() can only be invoked when the duration is Infinity`` at me, but only once and it does not prevent the stream from starting like it did in 1.2.2. 

So it doesn't look like it's still a problem.

**Comment by dmlap** [comment]
Thanks for the update, @Tralapo! We're going to keep this one open until we get rid of that exception but I'm glad it's not breaking playback anymore.

**Comment by lime-green** [comment]
I get the same exception. The video stops indefinitely after about 10 seconds (still shows as unpaused but it is not playing the content), but the XHR requests are being made. Switching to version 1.2.1 solved the issue though.

**Comment by billybobilly** [comment]
Having same problem.  The code in videojs.hls.js looks like it is erroring when you try to set the start and stop of the seekable range to 0 and 0 but the buffer length (duration) is not Infinity.  

Is it possible that the error is thrown when the player initially trys to load a left-over segment from a previous live stream of the same name?

We stream live with a particular hash in the file name.  That name gets reused the next time we stream the same event.  When the player first loads, it will load the last segments of the previous live stream (only now as VOD) until the new live stream is available.  

We wait until the live stream has actually started before calling play().  The problem for us is that this exception is preventing me from calling play() when the live stream is in fact ready and duration == Inifinty.  Play() has no effect at that poiint.

**Comment by amkgo** [comment]
I get this error just one time whenever I refresh the page.(videojs-contrib-hls ver 1.3.7 / videojs ver 5.6)

I use only a <video> tag in the <body>:
```
  <video id="example" class="video-js vjs-default-skin" controls preload="none" width="640" height="360" data-setup="{}">
    <source src="http://192.168.1.12/hls/test.m3u8" type="application/x-mpegURL">
  </video>
```

**Comment by howieye** [comment]
The newest videojs-contrib-hls
 * @version 3.1.0
Found this error too.

**Comment by adam187** [comment]
Still issue at @ 3.5

**Comment by WoZ** [comment]
See the same error on 3.5.3. I have some extra info about percentage of errors in different browsers.
97% of errors were received from Opera 39+ (up to 42) on Windows 7, 8.1 and 10, OS X, other 1.5% from Vivaldi browser and the last 1.5% from Chromium and Chrome.

I think it's common problem on Opera.

**Comment by gesinger** [comment]
Sorry this ticket has gone a long time without much attention. We've made a lot of changes to videojs-contrib-hls in the meantime, and haven't seen this issue in a while. Would anyone who is experiencing this issue be able to give the latest version a shot (as of this comment, v5.4.0), and provide a sample stream if you're still seeing issues? Thank you.

**Comment by gesinger** [comment]
Closing for now. If you are still experiencing this issue with the latest version of videojs-contrib-hls (as of this comment, v5.4.1), please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.
