### ISSUE TITLE
Fedora 23, Firefox 42, Flash 11.2.202.548...

### ISSUE THREAD

**Issue by FDiskas** [videojs/videojs-contrib-hls#461]
There is a big lag on HLS videos
https://youtu.be/cKOtUcYJS4Y
OS info: http://whatsmybrowser.org/b/PYUBG1Y

**Comment by Tralapo** [comment]
I'm not experiencing lag like you show in your video, but when Flash is used my streams do have hiccups where the stream stops for a millisecond and then jumps ahead again (Firefox 42, media sources disabled, Windows 10).

**Comment by gesinger** [comment]
@FDiskas , are you still experiencing the lags with the latest version of the player?

**Comment by FDiskas** [comment]
:water_buffalo:
No lag using http://whatsmybrowser.org/b/YL6D2PF
But there is some other issue: http://i.imgur.com/YZi9cZZ.png using whatsmybrowser.org/b/H1DOV00
