### ISSUE TITLE
Volume issue

### ISSUE THREAD

**Issue by FDiskas** [videojs/videojs-contrib-hls#462]
http://videojs.github.io/videojs-contrib-hls/
in console enter
```js
player.volume(0.3)
```
then
```js
localStorage
```
then you will get
```js
Storage {volume: "0.3"}
```
Refresh the page
```js
player.volume()
```
you will get `1`
```js
localStorage
```
you will get
```js
Storage {volume: "0.3"}
```
Something wrong with volume value remembering.

**Comment by gkatsev** [comment]
Volume remembering hasn't really been supported in a long time in videojs. It's been buggy and partially removed already. In videojs 5, it's not present at all. See https://github.com/videojs/video.js/issues/1929
That thread also mentions that there's a plugin available to do this: [videojs-persistvolume](https://github.com/theonion/videojs-persistvolume).

**Comment by FDiskas** [comment]
Thanks but event that plugin does not works :) only stores the values.

**Comment by gkatsev** [comment]
Well, that's an issue for that plugin then :P
