### ISSUE TITLE
Should development be merged into master?

### ISSUE THREAD

**Issue by gkatsev** [videojs/videojs-contrib-hls#467]
I think it might be time to merge dev branch into master.

**Comment by Tralapo** [comment]
I'm using the development branch in a live environment for some time now. There are some bugs, but on the other hand: the master branch isn't working at all with Video.JS v5.

So I think it's a good idea.

**Comment by shacharz** [comment]
Something is unclear with the releases here.
You've just added this to 1.0 Release milestone, while 1.2.2 was released a couple of days ago.

**Comment by gkatsev** [comment]
@shacharz the current 1.x releases are not full releases and more of prereleases. We've released them so that people can try it out and report issues and help us get a full release for HLS with MSE.

**Comment by dmlap** [comment]
Updated our [example page](http://videojs.github.io/videojs-contrib-hls/) to use 1.x.

**Comment by Tralapo** [comment]
Looks like development is now merged in master? Correct?

**Comment by dmlap** [comment]
@Tralapo it is. Development is now tracking our update to es6ify everything.
