### ISSUE TITLE
[1.3.0 Development] Stream stops in Flash

### ISSUE THREAD

**Issue by Tralapo** [videojs/videojs-contrib-hls#471]
I upgraded my development area to contrib-hls 1.3.0 and Video.JS 5.3 (tried with 5.2 too) and noticed the Flash fallback does not seem to work very good anymore.

Tried this in IE 11 on Win7, which does not have MSE support and Firefox 42 on Win10 with MSE disabled.

The player will fall back to Flash, but the stream stops after a few seconds (looks like end of first .m3u8 list) with a 'Network error' in console. Works fine with MSE enabled and in Flash < contrib-hls 1.3.0, so looks like a new problem with the plugin and not a serverissue.

**Comment by Tralapo** [comment]
@dmlap I did a new build with the latest commits from @imbcmdth and found out something interesting. Tested again with Firefox 42, MSE disabled in about:config.

- First, loading the page;
- Hit play;
- The loading spinners stays visible, stream stops after the first .m3u8 file ends (3 .ts files);
- Hit pause, hit play again;
- Video reloads, loading spinner disappears this time and stream will keep on playing without stopping;

**Comment by dmlap** [comment]
Hmm. We have a couple fixes queued up for Flash and they sound similar to the symptoms you're describing. I'm hoping we'll finally get this one nailed in the next release. Stay tuned.

**Comment by Tralapo** [comment]
Latest commits did indeed fix this problem. But now it's the HTML5 one that's breaking after a few segments (#483).
