### ISSUE TITLE
How to seek to the "live edge" of an ongoing HLS stream

### ISSUE THREAD

**Issue by hejinqiao** [videojs/videojs-contrib-hls#472]
Hi, I am trying to develop a command center webpage to display live streams from a few cameras. I successfully made the connection, but the stream seems to come in as a string of clips, since sometimes when I reload the video, it will go back to the starting point of the second latest stream and play it again instead of play the most real time stream (I think because the latest has not been loaded yet). So how can I solve this problem?
THANKS in advance!

**Comment by dmlap** [comment]
You can use the [seekable](http://docs.videojs.com/docs/api/player.html#Methodsseekable) attribute on the player to determine the beginning and end of the live window for a live stream (`player.seekable.end(0)` is the "live edge").

**Comment by hejinqiao** [comment]
@dmlap hi, but it says player.seekable.end(0) is not a function? I am pretty new to this stuff, i will really appreciate if you would like to guide me more specifically. Thank you very much!

**Comment by dmlap** [comment]
Dang, I screwed up. The correct code is `player.seekable().end(0)` (note the extra method invocation). Sorry!
