### ISSUE TITLE
Clean up timestampOffset-ing

### ISSUE THREAD

**Issue by dmlap** [videojs/videojs-contrib-hls#474]
The code that [determines when and where to set timestamp offsets](https://github.com/videojs/videojs-contrib-hls/blob/2286959ff23f554107a011a6c07e97d68cbf1a30/src/videojs-hls.js#L925) should be reorganized for clarity.

**Comment by gesinger** [comment]
@dmlap , looks like we changed where/when we're setting timestampOffset to only do it when we're on a different timeline (we are crossing a discontinuity), and when the start of the segment is less than the current timestampOffset. OK to close?
