### ISSUE TITLE
is bufferedTime check wrong?

### ISSUE THREAD

**Issue by norlin** [videojs/videojs-contrib-hls#475]
Hello!

https://github.com/videojs/videojs-contrib-hls/blob/development/src/videojs-hls.js#L864
Why there is a check only for current region and not for current + all following (in case if we have more than 1 region)?

**Comment by dmlap** [comment]
Imagine this scenario: we have five more seconds of content in the current buffered region, then a gap of 10 seconds, then two minutes of buffered content. We want to continue fetching segments to fill that gap (even though we have a lot buffered) so that we don't stall when we hit it.

**Comment by norlin** [comment]
That's ok, but when we have 2 (or more) ranges one by one? Say 0-60 & 60-120, and current time == 55. It will get 5 sec buffered time and will start to fetch next segment while it's already buffered.
