### ISSUE TITLE
Switching to the Flash fallback when the codec is not supported

### ISSUE THREAD

**Issue by n4gashi** [videojs/videojs-contrib-hls#479]
HI there,

I'm currently trying to deploy my application in production that is using an HLS source. The thing is that everything is working properly, except in Chrome. 

I tried with a video that does not have a specific codec and everything was working fine, but with a `x-mpegURL` video with `#EXT-X-STREAM-INF` codec set to : `CODECS="avc1.42E01F,mp4a.40.2"`

I've seen in several places that the avc codec is not supported by Chrome at the moment, so I was wondering if it was possible to switch to the flash fallback in that case.

Here is the result on Chrome : 
![screen shot 2015-12-16 at 4 23 57 pm](https://cloud.githubusercontent.com/assets/10873860/11857927/7f900896-a411-11e5-89a7-325d90a426f6.png)

And here is how my file is made : 

```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=264000,RESOLUTION=400x300,CODECS="avc1.42E01F,mp4a.40.2"
https://storage.googleapis.com/starmakerapptest2-hrd_media_transcodings/recordings/5450219493261312/264k-400x300/264k-400x300.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=728000,RESOLUTION=640x480,CODECS="avc1.42E01F,mp4a.40.2"
https://storage.googleapis.com/starmakerapptest2-hrd_media_transcodings/recordings/5450219493261312/728k-640x480/728k-640x480.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1628000,RESOLUTION=640x480,CODECS="avc1.42E01F,mp4a.40.2"
https://storage.googleapis.com/starmakerapptest2-hrd_media_transcodings/recordings/5450219493261312/1628k-640x480/1628k-640x480.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=64000,CODECS="mp4a.40.5"
https://storage.googleapis.com/starmakerapptest2-hrd_media_transcodings/recordings/5450219493261312/64k-audio-only/64k-audio-only.m3u8
```

Thanks

**Comment by ehsan89** [comment]
+1

**Comment by halibegic** [comment]
+1

**Comment by forbesjo** [comment]
With Flash slowly dying, especially in Chrome, we will not be implementing this fallback feature.
