### ISSUE TITLE
withCredentials not working in dev branch

### ISSUE THREAD

**Issue by ziddey** [videojs/videojs-contrib-hls#481]
this.options_ = {};
    if (this.source_.withCredentials !== undefined) {
      this.options_.withCredentials = this.source_.withCredentials;
    } else if (videojs.options.hls) {
      this.options_.withCredentials = videojs.options.hls.withCredentials;
    }
    this.playlists = new videojs.Hls.PlaylistLoader(this.source_.src, this.options_.withCredentials);

^ Currently, this is lines 160-166 (https://github.com/videojs/videojs-contrib-hls/blob/61350b49cd0e49aa46e03ae33d69dc2f1edc458b/src/videojs-hls.js)

For the first condition, passing via the source object results in case insensitivity (i.e. it must be referenced as `this.source_.withcredentials`). Changing this fixes it.

The second condition is the one documented in the readme, and no longer works. Console shows `VIDEOJS: WARN: The Hls component was added to the videojs object when it should be registered using videojs.registerComponent(name, component)`

Then line 1053:
`    withCredentials: this.source_.withCredentials,`
should instead be
`    withCredentials: this.options_.withCredentials,`

These changes allow setting withCredentials=true in the source tag. 
Setting via videojs options is broken.

**Comment by tenacex** [comment]
https://github.com/tenacex/videojs-contrib-hls/commit/2ff25f7e9325111ff4652b48abba0d4daf60dce1

**Comment by abdulla16** [comment]
I'm running version 1.3.5 and I'm also running into the same issue that @ziddey is running into. Any chance the fix for this issue will be merged into master soon?

**Comment by darrennolan** [comment]
Confirm we have the same issue but strangely enough, Chrome seems to behave fine without withCredentials being passed against the source.


Not sure if I'm right in doing so, but I updated to the following;

```
if (this.source_.withcredentials !== undefined || this.source_.withCredentials !== undefined) {
    this.options_.withCredentials = this.source_.withcredentials || this.source_.withCredentials;
  } else if (videojs.options.hls) {
    this.options_.withCredentials = videojs.options.hls.withCredentials;
  }
  this.playlists = new videojs.Hls.PlaylistLoader(this.source_.src, this.options_.withCredentials);
```

Which if I understand correctly, allows the withCredentials to still be set (as camelCase) with `videojs.src([]);` as well as taking it from the lowercase attribute.

**Comment by seankoji** [comment]
@tenacex that commit you linked to doesn't seem to have any fix for the issue that I can see?

**Comment by forbesjo** [comment]
This is probably fixed, if not please reopen
