### ISSUE TITLE
Video hitching

### ISSUE THREAD

**Issue by camlowe** [videojs/videojs-contrib-hls#482]
Hey there,

I'm encountering an issue where the video will pause for a few ms. It seems to occur when loading a new ts segment. Tested in chrome (version 47.0.2526.106), and firefox (version 42.0), and been confirmed by multiple users in different locations.

You can see examples here:
v1.2.2 https://streamshark.io/example/videojs/
v1.3.1 https://streamshark.io/example/videojs/index2.html (This version occasionally freezes, but the length of the hitch is shorter.)

The HLS source (https://hls.live.metacdn.com/hls-live/2050C7/bezcdkndy/streamshark-example_/streamshark-example_2064.m3u8) plays back fine natively in Safari.

**Comment by cowanmax** [comment]
I have the same problem. http://bulgartravel.tv/videojs. It has little stops video :( I have no idea to fix it.. I have tested in Firefox.

**Comment by dmlap** [comment]
That is some weird behavior. Anything info either of you could share about how you're encoding your streams?

**Comment by cowanmax** [comment]
love FP but it has problems with crossdomain policy :(

**Comment by imbcmdth** [comment]
MSE (at least in Chrome) has issues with fragments that do not start with keyframes. As a work-around, we detect those cases and pull the first keyframe forward (extending it's duration.) That "work-around" accounts for the hitching that you are seeing. If you re-segment on keyframes, the stream should play without issue.

**Comment by cowanmax** [comment]
Which H264 profile you can recommend ? Now I use H264 Baseline, level 3.1, keyframe frequency 4 sec, threads 4, network buffer 20. We have a 2 streams 700 & 1500 kbit/sec 1280x720

**Comment by cowanmax** [comment]
vMix with 2 RTMP streams > Adobe Media Server > VideoJS

**Comment by cowanmax** [comment]
have anybody any ideas to fix it??

**Comment by camlowe** [comment]
Apologies for the delay in getting back to you guys.

We're using ffmpeg to broadcast the stream with a *key frame interval* of **2 seconds**, and a *segment length* of **10 seconds**.

Cmd line for broadcast (we're broadcasting in two qualities, but only using the higher quality in the videojs example):

ffmpeg -threads 2 -re -fflags +genpts -stream_loop -1 -i $F \
    -s 640x360 -ac 2 -f flv -vcodec libx264 -profile:v baseline -b:v 600k -maxrate 600k -bufsize 1200k -r 24 -g 48 -ar 44100 -c:a libfdk_aac -b:a 64k $S1 \
    -s 1920x1080 -ac 2 -f flv -vcodec libx264 -profile:v baseline -b:v 2000k -maxrate 2000k -bufsize 4000k -r 24 -g 48 -ar 44100 -c:a libfdk_aac -b:a 64k $S2

Above should be setting keyframe every 2 seconds (48 frames).  Keyframes should be aligned with each segment start as 2 seconds divides evenly into the segment length of 10 seconds.

**Comment by camlowe** [comment]
Hi guys,

Any updates on this issue?

**Comment by cowanmax** [comment]
Now we have use an uppod player (it's free) and it works great with HLS. But it use Java for desktops and HTML5 for Android and iOS.

**Comment by dmlap** [comment]
We have [a fix for this](https://github.com/videojs/mux.js/pull/57) on the way.

**Comment by camlowe** [comment]
Awesome! Thanks @dmlap :) The video hitching has been removed.

The only issue we're seeing now is that the stream will stop after 7-10 minutes.

Example here: https://streamshark.io/example/videojs/v2.html

**Comment by gesinger** [comment]
Hey @camlowe , are you still experiencing the issue where the stream stops after 7-10 minutes?

**Comment by camlowe** [comment]
Hi @gesinger, I've just done a test on the latest version and it does appear to no longer an issue.

I'll close this ticket.
