### ISSUE TITLE
'waiting' event is not fired when buffering

### ISSUE THREAD

**Issue by shaharmor** [videojs/videojs-contrib-hls#484]
Hi,

When the player goes into buffering state, the 'waiting' event should be fired but its not.
Also, when playback continues, it isn't firing the 'playing' event either.

**Comment by samward1985** [comment]
+1

**Comment by gesinger** [comment]
Sorry this ticket has gone a long time without much attention. We've made a lot of changes to videojs-contrib-hls in the meantime. Would you be able to give the latest version (as of this comment, v4.1.1) a shot? If it's still a problem, would you be able to re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/edit?html,output)?

Thank you again for reporting the issue.
