### ISSUE TITLE
Aspect ratio not detected

### ISSUE THREAD

**Issue by ntadej** [videojs/videojs-contrib-hls#485]
Aspect ratio is not detected on latest development version. It worked OK with 0.17.

**Comment by aydinkn** [comment]
I have same problem with v1.3.8
Chrome result:
<img width="829" alt="screen shot 2016-02-18 at 11 46 12" src="https://cloud.githubusercontent.com/assets/5111036/13139746/b5c6b71e-d636-11e5-9e69-bfc722c60866.png">
Firefox result:
<img width="828" alt="screen shot 2016-02-18 at 11 45 49" src="https://cloud.githubusercontent.com/assets/5111036/13139755/c252abaa-d636-11e5-8850-4ab95731a074.png">

**Comment by dmlap** [comment]
Closing this one in favor of the mux.js issue.
