### ISSUE TITLE
Little stops HLS stream

### ISSUE THREAD

**Issue by cowanmax** [videojs/videojs-contrib-hls#487]
Hi All!
I have setup video.js with HLS. It works well.
But sometimes it plays with little stops (video), sound is ok. What you can recommend with it? I have use latest version of contrib-hls. I have tested in Firefox. In IE works well.
You can try here - http://bulgartravel.tv/videojs
Thanks.

**Comment by ChiliChili** [comment]
Hi! How to generate m3u8 stream? Maybe with ffmpeg+rtmp+nginx?

**Comment by cowanmax** [comment]
We use an Adobe Media Server.

**Comment by ChiliChili** [comment]
I mean, unfortunately, this is not my experience. It was a similar problem, but nginx and ffmpeg solution and parameterization solved.

**Comment by dmlap** [comment]
This looks like a case of missing keyframes on segments. We have a [new and amazing strategy](https://github.com/videojs/mux.js/pull/57) to deal with it that is working it's way through testing right now.

**Comment by dmlap** [comment]
Closing as a dupe of #482
