### ISSUE TITLE
Android 

### ISSUE THREAD

**Issue by hyurtseven81** [videojs/videojs-contrib-hls#488]
I'm using 1.3.1 version from npm packages with vjs 5 

On desktop browsers and ios there is no problem but when i try to use player on android devices or with android user agent it shows a "The media could not be loaded, either because the server or network failed or because the format is not supported" error after downloading index.m3u8 file

**Comment by hyurtseven81** [comment]
After testing with 1.3.3 version, there is no problem

**Comment by hyurtseven81** [comment]
There is another problem, when i try to play video on android devices sometimes and some devices player sends byterange request to m3u8 and it takes 2 kb empty manifest and it shows  "The media could not be loaded, either because the server or network failed or because the format is not supported" error and can't play

**Comment by hyurtseven81** [comment]
Problem has solved, 

The problem was about Allow-access headers android devices look those headers to play video,

I didn't know that.

Thank you

**Comment by bobgle** [comment]
Can you tell us more about the headers, which ones are important? Any link? There doesn't seem to be anything specific in the docs, except for CORS which we have enabled.

**Comment by Abdurraheem** [comment]
i am also facing same problem ..can u help me..its not playing in android its shows same error...media could be not loaded,either becoz the server or network failed or becoz the format is not supported
