### ISSUE TITLE
videojs5 doesn't retry a request on failed HLS segment

### ISSUE THREAD

**Issue by arikkrol1** [videojs/videojs-contrib-hls#493]
If a requests to an HLS .ts segment fails the player doesn't try to fetch it again.
To tests this I interfered with the XHR of the first segment and caused it to fail. The player didn't recover.
Previous versions of videojs did recover.

**Comment by arikkrol1** [comment]
Same goes for failed m3u8 playlist request.

**Comment by campones** [comment]
same happen if your internet is too bad and can't follow the stream. It will stop dl .ts file while .m3u8 are still downloaded. It should at least try to fetch new segments

**Comment by dmlap** [comment]
We recently added a mechanism that temporarily blacklists a playlist if a segment or m3u8 fail. So the player should try to switch to a different quality level if it runs into segment issues with a particular stream. Are you not seeing that behavior in the most recent release?

**Comment by campones** [comment]
Sorry I can't tell, I work with single bitrate streams

**Comment by dmlap** [comment]
Ok. I'd look into providing alternate streams then-- retrying segments within the same stream is not something we have planned for this project. If it's difficult to produce multiple streams for some reason, you could try faking it by creating a stub master m3u8 and adding duplicate entries for your primary m3u8.

**Comment by jaq316** [comment]
I would suggest something along the lines of... If the playlist is blacklisted but there are no other playlists, retry the download of the segment for a configurable amount of time, or at least, fire off an event so that we can handle this case in some other way. What do you guys think about that?
