### ISSUE TITLE
Playing segment

### ISSUE THREAD

**Issue by hyurtseven81** [videojs/videojs-contrib-hls#494]
Hi,

How can i get currently playing segment?

Thank you

**Comment by hyurtseven81** [comment]
I've found a way to find current playing segment but when discontinuety comes it gives undefined,

Is there any help?

var _mediaIndex = _self.playlists.getMediaIndexForTime_(_self.tech_.currentTime());
var _segment = _self.playlists.media().segments[_mediaIndex];
console.log(_segment);

**Comment by dmlap** [comment]
Can you provide some background on why you're trying to determine the current segment that is playing? getMediaIndexForTime() is the way we go about it internally to the plugin but I'm curious what your use-case is.

**Comment by hyurtseven81** [comment]
Actually we're working a dynamic ad insertion project for live streams, we add some extra metadata on advert ts's like #EXT-ADVERT with discontinuety tag, we added advert property on segment object in hls plugin and we can get back it with above _segment object, and i've finally solved the problem, now i can get playing segment with discontinuety and advert properties and i can fire an event that says start request ads from adserver and it's working right now, but i've made a lot of changes.

i can share my code but i'm not sure it is a generic solution of course, but now i can do dynamic ad insertion on player side with some modifications on m3u8 files.

By the way i developed a bitrate selector menu,
[videojs.hls.txt](https://github.com/videojs/videojs-contrib-hls/files/87481/videojs.hls.txt)

you can check my modifications with // HY: Custom add comments

Thank you for your help

**Comment by piotr-cz** [comment]
Unfotunetally this hack doesn't work anymore.
The getMediaIndexForTime function is not exposed anymore.

**Comment by gesinger** [comment]
Closing as this case looked like it was resolved.

However, for anyone else in a similar solution, I wanted to add some generic information on why there isn't an easy API to grab the currently playing segment, and what might be done to solve your issue.

Figuring out the currently playing segment is hard. To determine which one is playing requires some rough guesswork based on the segment and the state of the buffer before and after appending the segment, then relying on the timing to remain accurate.

Different use cases often seem to require knowledge of the currently playing segment, but many times can be resolved in other ways. For instance, id3 metadata may be a good option to trigger necessary info when the segment is playing.

Each use-case is unique though, and can be solved in different ways.
