### ISSUE TITLE
Playing Interrupted on chrome with encrypted stream without IV(initialization vector)

### ISSUE THREAD

**Issue by u0x01** [videojs/videojs-contrib-hls#495]
FFMPEG Transcode command:

```
#!/bin/sh
BASE_URL=${1:-'.'}
openssl rand 16 > file.key
echo $BASE_URL/file.key > file.keyinfo
echo file.key >> file.keyinfo
ffmpeg -i test.mp4 -f hls -hls_time 10 -hls_key_info_file key.info -hls_list_size 0 stream.m3u8
```

This output streams will interrupt when segment end play on chrome.
But IE and safari all is good working, How to fix it?

**Comment by gesinger** [comment]
Hey @u0x01 , sorry this ticket has gone a long time without much attention. I gave it a shot with the latest version of videojs-contrib-hls (as of this comment, v5.3.3), and it seemed to work on Chrome. Please give it a shot and let us know if you're still seeing issues. Thank you.
