### ISSUE TITLE
IE crash with 11 players on one page

### ISSUE THREAD

**Issue by cowanmax** [videojs/videojs-contrib-hls#496]
Hi All!
I have created 11 players on one page and IE each time drops. Firefox 47 works well.
Look at this page - nightbus.ru/testvideo.html
The problem was with with IE - it having limited local storage for xhr requests. I have added preload="none" to each video element so nothing is preloaded and now it works well.Many thanks to mister-ben.

**Comment by dmlap** [comment]
Eventually, we run into resource limitations on the browser and I think 11 players with preloading on a page is something we won't be able to support. Glad `preload=none` solved your problem though and thanks for reporting the issue!
