### ISSUE TITLE
old version works but new version of videojs hls does not work , 

### ISSUE THREAD

**Issue by htn264** [videojs/videojs-contrib-hls#498]
I have two problems
1) I see on the PC browser that it is loading m3u8 link content but the player is still using Flash ? I want it uses HTML5 only?
the source has type "application/x-mpegURL"

2) I use an old version of videojs.hls and media-sources (I downloaded 3-4 months ago. The new version of these two files could not run - there is error : there is no videojs.extend function

**Comment by htn264** [comment]
I see on the information that it is still requires Flash :( :(
How about the second problem that is mentioned above ?

**Comment by dmlap** [comment]
The [latest release](https://github.com/videojs/videojs-contrib-hls/releases/tag/v1.3.7) uses HTML-based playback anywhere that supports the Media Source Extensions API. It requires video.js 5.x (which I believe is why you were seeing your problem 2). Everything else sounds good. If you're having trouble setting it up, check out our [example page](http://videojs.github.io/videojs-contrib-hls/).
