### ISSUE TITLE
Issue with playback of an audio-only elementary stream

### ISSUE THREAD

**Issue by ram651** [videojs/videojs-contrib-hls#499]
I've been unable to get an audio-only ES to playback with video.js and videojs-contrib-hls.
The code for the simple demo player is as follows, any ideas?

```
    <video id="video" width="640" height="264" class="video-js vjs-default-skin" controls>
        <source src="http://db3.indexcom.com/bucket/ram/00/05/05.m3u8"
                type="application/x-mpegURL">
    </video>

    <script src="video-js-5.4.4/video.js"></script>
    <script src="videojs-contrib-media-sources-2.4.3/src/videojs-media-sources.js"></script>
    <script src="videojs.hls.js"></script>
    <script>
        var player = videojs('video');
        player.play();
    </script>
```

**Comment by ehsan89** [comment]
+1

**Comment by eminden** [comment]
Is the any plan to support AAC container (audio only streams) on the development branch? I guess what @ram651 is looking for this as same as me.

**Comment by dmlap** [comment]
We're looking into it as part of supporting alternate audio/video aka media groups. It's still early but we're getting started with #387.

**Comment by forbesjo** [comment]
I'm able to play and hear the posted source with the latest version of this plugin, closing since this seems to be addressed.
