### ISSUE TITLE
HLS audio only

### ISSUE THREAD

**Issue by eranwo** [videojs/videojs-contrib-hls#501]
Hi,
Is it possible to play static mp3 files in HLS with video js?

**Comment by Tralapo** [comment]
Why would you? Every browser supports native mp3-playback with ```<audio>``` these days.

**Comment by eranwo** [comment]
You are right, but i need prevent download the mp3 files.
So, far as I know streaming is the best way to protect from downlod.
It's  for audio on demand project.
Maybe anyone know how to do this?

**Comment by dmlap** [comment]
Playing back mp3s is out of the scope for this project, sorry.
