### ISSUE TITLE
[Development] Usage as ES6-style import?

### ISSUE THREAD

**Issue by nickygerritsen** [videojs/videojs-contrib-hls#509]
I would like to use videojs-contrib-hls using an ES6-style import, but that seems to be impossible currently.
Are there any plans on changing this? Or should I just keep on including the file separately in my HTML?

**Comment by dmlap** [comment]
We're in the middle of es6ifying the project right now! We should have a PR open something this week (I think).

**Comment by nickygerritsen** [comment]
Great! I guess I can wait a week :).

If you need any feedback or so with the ES6-thingy, let me know!

**Comment by nickygerritsen** [comment]
Btw (maybe not the right spot to ask), but is such a plan also in the works for the DASH contrib plugin?

**Comment by dmlap** [comment]
I'd love to es6ify contrib-dash too but I don't know of anyone currently working on it. Feel like submitting a PR? :)

**Comment by nickygerritsen** [comment]
Perhaps if you have ES6'ed contrib-hls I can use that as a basis for dash :).

**Comment by dmlap** [comment]
The development branch is now converted to es6 and building to babelify!

**Comment by nickygerritsen** [comment]
\o/
