### ISSUE TITLE
Stream playing in Safari cannot detect signal loss

### ISSUE THREAD

**Issue by hejinqiao** [videojs/videojs-contrib-hls#513]
When I use code below to monitor stream, it works fine in Chrome because when I turn off the live stream, the player will fetch a error. However, in safari, once I turn off the stream source, the video will just freeze there, and according to the console log, the error is still none and readyState is still 4. How should I resolve this issue?

if(player.readyState()==4){
//setTimeout to regularly check whether stream is properly played
}
else if(player.error()){
//handle error
}

**Comment by dmlap** [comment]
Safari uses OS-level native HLS support for playback-- this project isn't involved in it at all. Sounds like a frustrating Safari limitation. Sorry!
