### ISSUE TITLE
Cannot play short hls m3u8 file in Firefox with html5 tech

### ISSUE THREAD

**Issue by a2dmen** [videojs/videojs-contrib-hls#514]
It  works fine with Chrome and use flash with IE, however if the video is less then 10-15 second, The Firefox cannot go to the end of the video and the player's duration time shows zero. It become stuck with loading but without any request
I use videojs 5.3.0,videojs-media-sources 2.4.3 and videojs-contrib-hls 1.3.4.
My Firefox version is 43.0.4
So how should I fix this issue??
Any ideas??

**Comment by dmlap** [comment]
@a2dmen we just fixed a FF issue in 1.3.7 which I think could be behind this bug. Any chance you can retry with the latest version?
