### ISSUE TITLE
Use `currentSegment` to get the URL of the current TS segment?

### ISSUE THREAD

**Issue by hanfeisun** [videojs/videojs-contrib-hls#517]
As HLS is adaptive, multiple stream can be used for different bandwidth and the switching can occur automatically..

I'm going to use `console.log` to show which stream I was using. I tried to get the URL of the resolution-specific m3u8 file ( `1080p.m3u8` or `480p.m3u8` ) or the resolution-specific TS file (`1080p/1.ts` or `480p/1.ts`). I tried `player.currentSrc` API (http://docs.videojs.com/docs/api/player.html#MethodscurrentSrc) but it only returns the URL of the original m3u8 file instead of the resolution-specific m3u8 file or ts file..

Is it possible for videojs-contrib-hls to get the current TS file?

**Comment by hanfeisun** [comment]
Maybe related to https://github.com/videojs/videojs-contrib-hls/issues/494

I'm not sure whether there is an easier way.

**Comment by dmlap** [comment]
We don't currently have a way of determining that. Can you elaborate on why you'd like to know it?

**Comment by dmlap** [comment]
Closing since there hasn't been any activity here.

**Comment by mogita** [comment]
In my case, this is relevant to the custom logics based on the file names of the segments, which are predefined by the video/streaming service provider. Being unable to fetch this information simply disabled me from implementing those custom in-browser logics, I'll have to do it the harder way. I think this should make sense. :)

**Comment by piotr-cz** [comment]
Did you guys find a way to retrieve current playing segment?
