### ISSUE TITLE
TypeError: segmentInfo.buffered is null

### ISSUE THREAD

**Issue by navruzm** [videojs/videojs-contrib-hls#518]
Hi,
Latest version of videojs-contrib-hls(v1.3.4) on Firefox (v43.0.4 Mac or Linux) randomly throwing `TypeError: segmentInfo.buffered is null` error. Sometimes it happens 30 seconds after video started, sometimes 10 minutes later.

I dig a little bit and find out that sometimes Firefox returns [empty buffered object](https://github.com/videojs/videojs-contrib-hls/blob/6ad52bb285130e337820481ce0293c0fa25c81db/src/videojs-hls.js#L1180). I think we need to make sure that we had buffered object in [this line](https://github.com/videojs/videojs-contrib-hls/blob/6ad52bb285130e337820481ce0293c0fa25c81db/src/videojs-hls.js#L1258).

**Comment by dmlap** [comment]
I think we have this fixed in 1.3.7. Please re-open if you're still seeing it!
