### ISSUE TITLE
Live stream will halt after reproducing first segments

### ISSUE THREAD

**Issue by cladera** [videojs/videojs-contrib-hls#520]
The video starts playing as expected, but after it has played the first three segments, it won't continue playing.

I use Wowza server and this is the structure Wowza generates:

- **playlist.m3u8**: It points to other playlists one for each quality. In my case I use 720p, 480p, 360p and 240p. 
- **chunklist_xxxxx.m3u8**. It always contains three TS segments. Each segment is 10 seconds length, which means every 30 seconds the chunklist has rotated all segments.  This is how Wowza behaves by default for live streams.

In debugging console I can see how Hls downloads the playlist.m3u8, the chunklist and the first three segments. After some seconds it downloads the chunklist again and also the fourth segment, but it won't never reproduce it nor download more segments so the stream eventually stops.

I'm coming across this issue since I upgraded to v1.3.4. Currently I use v1.2.2 which works perfectly.

**Comment by mgood** [comment]
This sounds like the issue described in #491. Unfortunately it doesn't look like there's a solution yet, but take a look at the discussion there.

**Comment by cladera** [comment]
Thank you @mgood,
It does like the issue you mention. I'm closing this issue then.
