### ISSUE TITLE
Cannot get the player to play content in Chrome or Firefox

### ISSUE THREAD

**Issue by djevo1** [videojs/videojs-contrib-hls#523]
I keep getting an invalid media source notice on the player when it loads. works fine in safari and ios but not in chrome or firefox.
![screen shot 2016-01-19 at 4 31 59 pm](https://cloud.githubusercontent.com/assets/16768999/12432598/31edffca-beca-11e5-8463-91c6fb67f8b9.png)

**Comment by thomaspeeters** [comment]
Can you try setting the MIME type to `application/vnd.apple.mpegurl` instead of `application/x-mpegURL` and reporting back if that solves the problem?

**Comment by djevo1** [comment]
That fixed the problem, however the seekbar doesn't show up on a dvr stream

**Comment by thomaspeeters** [comment]
I have no experience with DVR streams, hopefully someone else can help you with that.

**Comment by dmlap** [comment]
That's the default behavior for video.js and live streams. There's been a good deal of [discussion about improving it](https://github.com/videojs/videojs-contrib-hls/issues/354) but nothing solid yet.
