### ISSUE TITLE
Demo not playing in Firefox on ubuntu

### ISSUE THREAD

**Issue by shacharz** [videojs/videojs-contrib-hls#525]
I get this error in the console
```javascript 
NotSupportedError: Operation is not supported
```
http://videojs.github.io/videojs-contrib-hls/

**Comment by imbcmdth** [comment]
What version of FF?

**Comment by shacharz** [comment]
43

**Comment by dmlap** [comment]
I don't have an Ubuntu machine handy. Anyone else able to verify this issue?

**Comment by SteffenDE** [comment]
I can confirm it. FF 44.0.2, Ubuntu 14.04.4.

**Comment by nafisakanwal** [comment]
Demo is not working at mobile Firefox, 
Please anyone can helps 
thanks in advance

**Comment by forbesjo** [comment]
Is this still an issue?

**Comment by shacharz** [comment]
seems to be working, thanks
