### ISSUE TITLE
Firefox crashes with MPEG AAC Audio (mp4a).

### ISSUE THREAD

**Issue by GeorgySerga** [videojs/videojs-contrib-hls#528]
Firefox crashes when video player from the example.html tries to run the HLS stream. Video codec: H264 - MPEG-4 AVC, audio codec: MPEG AAC Audio. Everything is fine when audio codec is A52 Audio (AC3). Can't provide logs because crash is instant. Don't know how to debug this one. Firefox 43.0.4, Ubuntu 14.04.
Chrome's log: `MediaError {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported."}`

**Comment by dmlap** [comment]
Do you know whether your audio is AAC-LC or HE-AAC (or both?). If you're not using AAC-LC, you will need to have a CODECS attribute that specifies the AAC codec specifically in your master m3u8 file. The codec string for HE-AAC is `mp4a.40.5`.

**Comment by GeorgySerga** [comment]
> Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 171 kb/s
    Stream #0:2: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, 5.1, fltp, 196 kb/s

Looks like it's AAC-LC. Checked with the latest FF stable version (44.0.*) on Ubuntu right now, still crashes.

**Comment by dmlap** [comment]
Oh, looks like you have two audio tracks in there. We haven't really dealt with that at all yet. Any chance you have an example segment somewhere we could look at?

**Comment by dmlap** [comment]
It seems like this one is related to support for multiple inband audio tracks. That would be a complicated enhancement that we don't have plans for right now so I'm going to close this one. If anyone is interested in giving it a shot, please open a PR!
