### ISSUE TITLE
in firefox doesn't play hls 

### ISSUE THREAD

**Issue by Alesiks** [videojs/videojs-contrib-hls#531]
I have problems with playing hls in firefox (in Chrome and Safari works good). In Firefox player loads first frame and stops, when I reload page it loads another frame and stops again. We have a live playlists in hls streaming().  But it works in firefox  when I use Video on Demand Playlist from http://videojs.github.io/videojs-contrib-hls/. What can be the problem? 
it's my code:
``````      
<video id=example-video width=960 height=540 class="video-js vjs-default-skin" controls>
            <source
                    src="/media/masterplaylist"
                    type="application/vnd.apple.mpegurl"/>
        </video>
        <script src="libs/video-js/video.js"></script>
        <script src="libs/videojs-hls/videojs.hls.min.js"></script>
        <script>
            var player = videojs('example-video'       );
            player.play();
        </script> 
``````

and my playlists examples, master and index:
``````
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=8700000, RESOLUTION=1920x1080, CODECS="mp4a.40.2,avc1.64001f"
/media/1920x1080_8700000.m3u8?uuid=xxx
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2191000, RESOLUTION=960x540, CODECS="mp4a.40.2,avc1.64001f"
/media/960x540_2191000.m3u8?uuid=xxx

``````

``````
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:14
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-DISCONTINUITY-SEQUENCE:0
#EXT-X-DISCONTINUITY
#EXTINF:5.041,
/media/Mic/1920x1080_8700000/stream00000.ts
#EXTINF:4.963,
/media/Mic/1920x1080_8700000/stream00001.ts
#EXTINF:5.005,
/media/Mic/1920x1080_8700000/stream00002.ts
#EXTINF:5.005,
/media/Mic/1920x1080_8700000/stream00003.ts
#EXTINF:5.005,
/media/Mic/1920x1080_8700000/stream00004.ts
#EXTINF:5.005,
/media/Mic/1920x1080_8700000/stream00005.ts
```````

**Comment by gkatsev** [comment]
Can you include the versions of videojs-contrib-hls used and also versions of browsers tested against? Thanks.

**Comment by Alesiks** [comment]
my versions:
videojs-contrib-hls - v1.3.5 
video-js-5.6.0
firefox 44.0

**Comment by Alesiks** [comment]
We found that it is our problem. Some problems in transcoding video and creating .ts files. 
Thanks.

**Comment by HankBrown** [comment]
Wish you had said more about what you found. I'm scratching my head with the same issue.
In this case I am using files created by the bitmovin encoding service.
Perhaps the demo page at http://videojs.github.io/videojs-contrib-hls/ could show an ffmpeg command line or similar. The search continues...
