### ISSUE TITLE
Playback of HLS with URL containing query parameters

### ISSUE THREAD

**Issue by veeyenkay** [videojs/videojs-contrib-hls#536]
Hi,

I have HLS content being served by a PHP script. The URL to the master playlist is the below format:
http://mydomain.com/download_video.php?path=/HLS Test/hls/hls_master_me.m3u8

When I try to play this URL using the videojs player, the request to the media playlist corresponding to hls_me_4 representation has the URL as:
http://mydomain.com/hls_me_4/hls_me_4.m3u8
But what I am expecting is:
http://mydomain.com/download_video.php?path=/HLS Test/hls/hls_me_4/hls_me_4.m3u8

How can I resolve this problem?

Regards
Karthik

**Comment by whatvn** [comment]
your server has to reply with full m3u8 url

**Comment by veeyenkay** [comment]
Is it possible to update the player source code to generate URL in this format? Can you give some pointers on where the URL is getting generated on the player?

**Comment by gkatsev** [comment]
The player doesn't generate any urls. It just takes what it is given and tries to to use it.
You can try replacing the space in there with the the encoded something like: http://www.mydomain.com/download_video.php?path=/HLS%2520Test/hls/hls_me_4/hls_me_4.m3u8
The player will not work if it doesn't get working url.

**Comment by dmlap** [comment]
Sounds like a server misconfiguration so I'm closing. Please re-open if it turns out otherwise!
