### ISSUE TITLE
VIDEOJS: WARN: player.hls is deprecated. Use player.tech.hls instead.

### ISSUE THREAD

**Issue by FDiskas** [videojs/videojs-contrib-hls#542]
VIDEOJS: WARN: player.hls is deprecated. Use player.tech.hls instead.
But if try to use suggested syntax I got "undefined"

**Comment by dmlap** [comment]
Oops, we need to update that warning. The correct method is:

```js
player.tech({ IWillNotUseThisInPlugins: true }).doSomething();
```

[Video.js Doc](IWillNotUseThisInPlugins)

**Comment by HeyWrecker** [comment]
I clicked the Video.js Doc link and received a GitHub 404 page.

**Comment by FDiskas** [comment]
The link is 404

**Comment by dmlap** [comment]
Oops again. Here's the [actual doc link](http://docs.videojs.com/docs/api/player.html#Methodstech)

**Comment by HankBrown** [comment]
What if doSomething() no longer exists?
player.hls.xhr.beforeRequest() and videojs.Hls.xhr.beforeRequest()
have apparently moved elsewhere.

Need to get some extra params into the uri.
"This is try and prevent misuse of techs by plugins" and zero familiarity with the codebase says I better ask how...
Please and thank you.
