### ISSUE TITLE
Base URL is not updated if url was redirected

### ISSUE THREAD

**Issue by Naouak** [videojs/videojs-contrib-hls#548]
If the HLS playlist source url return a 302 HTTP code to another location, videojs-contrib-hls doesn't update the url for subsequent playlist elements.

Example:
http://example1.com/playlist.m3u8 > 302 to http://example2.com/playlist.m3u8
http://example2.com/playlist.m3u8 > first chunk: chunk1.ts
The player should query : http://example2.com/chunk1.ts
The player is currently querying : http://example1.com/chunk1.ts

**Comment by gkatsev** [comment]
Hm... that's an interesting problem. The spec for the 302 status code tells us to not use the new URI for the new requests, 301 tells us to use the new URI. However, segments and media manifests are relative to the location of the m3u8 file, so, if the playlist was redirected, do we use the new URI for the playlist or our original one?
I assume that Safari/iOS is able to play this correctly?

**Comment by Naouak** [comment]
Safari and Edge play this correctly.

I look if there is an easy way to get this issue right but it seems XHR
doesn't tell if there was a redirection.

**Comment by gkatsev** [comment]
Yeah, it looks like we cannot read the value without making a separate HEAD request directly and looking at the headers: https://dvcs.w3.org/hg/xhr/raw-file/tip/Overview.html#infrastructure-for-the-send%28%29-method

**Comment by dmlap** [comment]
I'm going to close this because it seems like a browser limitation that we won't be able to work around. If anyone has any creative solutions though, please comment!

**Comment by dcamillo** [comment]
Hi Naouak,
Are you sure you are able to play this on EDGE ?
I have this issue on IE-EDGE.
So I am testing the index.html
https://github.com/videojs/videojs-contrib-hls/blob/master/index.html

I clone the project using git and at first attemp does not matter URL I place in the TextBox it does not play the new URL, always the one was loaded in the Video tag.

Am I doing something wrong ? Are you guys able to play it successfuly ?
