### ISSUE TITLE
Sometimes the video freezes on 15-30 seconds.

### ISSUE THREAD

**Issue by mikeevstropov** [videojs/videojs-contrib-hls#553]
Sometimes the video freezes on 15-30 seconds:
http://warnerfilm.ru/online/sotnya
But same m3u8 playlist work fine on Clappr:
http://cp.moonplayer.ru/serial/e40589935fd708c44147d1339c0c53c5/iframe
Just watch the video (about 2 min) from first page.

video.js v5.7.1
videojs-contrib-hls.js v1.3.7

**Comment by tenacex** [comment]
I watched the first video, and it didn't freeze for me.
