### ISSUE TITLE
Live is not working

### ISSUE THREAD

**Issue by shlomimo123** [videojs/videojs-contrib-hls#554]
Hi
I am tring to play this live stream
http://nasatv-lh.akamaihd.net/i/NASA_101@319270/index_1000_av-p.m3u8
but its freezing after 10 seconds
Do you know why?

**Comment by Tralapo** [comment]
Known. Livestreams stop playing after the first .m3u8 file is 'finished'. See #483 and #491. No solution.

**Comment by tenacex** [comment]
@Tralapo, I have confirmed that the current build indeed fixes this issue.

**Comment by billybobilly** [comment]
Unfortunately, we are seeing that the live works now, but the problem has now moved to when you use a VOD as the source of an encode.

https://github.com/videojs/videojs-contrib-hls/issues/483

**Comment by ssanth** [comment]
I am still seeing this issue on live streams
videojs 5.15.1
contrib hls v4.1.1
Mainly on chrome and looking for a fix.
