### ISSUE TITLE
HLS videos do not always fire the 'ended' event

### ISSUE THREAD

**Issue by cdhowie** [videojs/videojs-contrib-hls#555]
This appears to be the same issue as #111.  I have had this issue with 1.3.5 and 1.3.7 (have not tested any other versions).  Sometimes the `ended` event does not fire when an HLS video ends, which causes major issues with our integration.

This only seems to be an issue on Chrome currently. I have tested on Firefox and found no issues.

**Comment by ravi155** [comment]
+1

**Comment by svenspielvogel** [comment]
i was able to fix it in https://github.com/videojs/videojs-contrib-hls/pull/561. Any better ideas?

**Comment by FDiskas** [comment]
+1

**Comment by cdhowie** [comment]
The v2.0.0 release has fixed this problem for me, but I don't know about others.

**Comment by cdhowie** [comment]
I take it back; there are still some videos where the ended event doesn't fire, even with v2.0.0.

**Comment by FDiskas** [comment]
what if dynamically #EXT-ENDLIST was added to playlist?
For me it looks like hls object is not updated correctly.
I don't have anything specific to this, but just the gues...

**Comment by elmehdielkettani** [comment]
I have investigated the issue and noticed that it happens with a number of my streams. The common thread between the streams is that the last segment is very small (100ms or so). I hope that helps.

**Comment by gesinger** [comment]
Sorry this ticket has gone a long time without much attention. We've made a lot of changes to videojs-contrib-hls in the meantime. If it's still a problem for anyone, would you be able to re-open the issue and provide a reduced test case using the latest version via [this template](http://jsbin.com/vokipos/8/edit?html,output)?

Thank you for reporting the issue, and for all of the added info.
