### ISSUE TITLE
video js is aborting playback while playing m3u8 playlist in chrome where as in other browsers it plays fine

### ISSUE THREAD

**Issue by jequin** [videojs/videojs-contrib-hls#556]
I am using videojs for playing a m3u8 VOD stream. Everything works fine untill tested in chrome.
videojs aborts playback saying browser does not support.
The media files which are in the playlist (m3u8) are .ts format.
Note: I am using contrib-hls and yes it is set up correctly.
Please make sure when you test the stream, make it url encoded.
```
<script>
myPlayer.src({
          //myPlayer is my object for <video>
          type: "application/x-mpegURL",
          src: "http://hitsradio.videocdn.scaleengine.net/hitsradio-vod/play/sestore8/hitsradio/10  years - Beautiful.mp4/playlist.m3u8"
        });
myPlayer.play();
</script>
```

For html

```
<video id = "example video">
</video>
```

here is the screenshot for error `http://prntscr.com/a3f6sk`

**Comment by dmlap** [comment]
The m3u8 URL you provided is 404ing (and the response is missing CORS). Do you have another stream that is still running?

**Comment by dmlap** [comment]
Closing since we haven't heard back on this in awhile. Please re-open if you're still running into this issue.
