### ISSUE TITLE
Uncaught TypeError: Cannot read property 'supportsNativeMediaSources' of undefined

### ISSUE THREAD

**Issue by amkgo** [videojs/videojs-contrib-hls#563]
When using the "videojs-hls.js" from v1.3.9, from Chrome development console shows:

`Uncaught TypeError: Cannot read property 'supportsNativeMediaSources' of undefined`

The error is caused by `supportsNativeMediaSources()` from `videojs-hls.js` in line 138 which is as following:

```
// register source handlers with the appropriate techs
if (videojs.MediaSource.supportsNativeMediaSources()) {
  videojs.getComponent('Html5').registerSourceHandler(videojs.HlsSourceHandler('html5'));
}
```

There is no error if using `videojs.hls.min.js` of v1.3.7.

Andrew

**Comment by gesinger** [comment]
Hey @amkgo , sorry this ticket has gone a long time without much attention. We've made a lot of changes to videojs-contrib-hls in the meantime. Would you be able to give the latest version (as of this comment, v4.1.1) a shot? If it's still a problem, would you be able to re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output)?

Thank you for reporting the issue.
