### ISSUE TITLE
Video playing freezes after the first chunk in Firefox, Chrome, working in Safari, IE

### ISSUE THREAD

**Issue by kchris78** [videojs/videojs-contrib-hls#564]
This is the place:
[http://files.rtl.hu/ex.html](url)

After the first chunk (10-12 sec) the playing freezes. Every time!! It is not working in Firefox, Chrome (Windows), working in IE. In OS X it is working in Firefox and Safari but not working in Chrome..
The buffering continues after all... When I seek the playing is OK until the next chunk. In the console noting can be seen.

Thanks!

This VOD stream is OK for Apple devices, I wanted to merge the video serving for IOS and Desktop devices. Unluckily I have no access to the IIS HLS server (after all it is working with the iOS App).

**Comment by tomaj** [comment]
Same problem here. Safari is working perfect, but Chrome freeze as @kchris78 mentioned.

Versions:
 - Video.js 5.5.3
 - videojs-contrib-hls - v1.3.7

**Comment by luklapp** [comment]
I can reproduce this issue. Video.js 5.7.1, videojs-contrib-hls 1.3.11

**Comment by kchris78** [comment]
Upgraded the video and videojs-hls to version 2.0.1 but the problem is still there :(.

**Comment by bson** [comment]
We're seeing the same.  If we keep reloading it sometimes work, maybe 20-25% of the time.  If we use the network console tab to set a high latency, > 200ms, it fails consistently - as in, never starts up properly.  Verified it occurs in Chrome on OSX, while Safari is fine.  IE is fine on Windows; Chrome fails.  I don't think we're tried Firefox on either yet.

**Comment by bson** [comment]
We narrowed down the problem to calling .load() from the .ready() callback.  If we only use .src() and follow it with .play() if we want to autoplay, then it works fine.

**Comment by gesinger** [comment]
Sorry this ticket has gone a long time without much attention. It looks like the original sample page may no longer exist.

We've made a lot of changes to videojs-contrib-hls in the meantime (including around gaps, which potentially was causing the freeze in the original problem). Would you be able to give the latest version (as of this comment, v5.0.0) a shot? If it's still a problem, would you be able to re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output)?

Thank you for reporting the issue.
