### ISSUE TITLE
Troubled stream

### ISSUE THREAD

**Issue by gkatsev** [videojs/videojs-contrib-hls#565]
Copying over from https://github.com/videojs/video.js/issues/3132. The m3u8 file is available here: http://05h1.vp9.tv:8484/chn/VP9HN1T/v.m3u8
The player gets stuck at some point and stops playing back. It'll continue reloading the m3u8 but will stop fetching segments.
I have a few segments saved locally in case/when the stream goes down.

**Comment by minh1903** [comment]
Thanks @gkatsev,  I hope this issue will be fixed as soon as.

**Comment by dmlap** [comment]
One quick observation: the live window in this playlist is very small, just three segments. You will probably get more stable playback if you increase the number of segments available in the m3u8 at any point in time to 5 or greater.

**Comment by minh1903** [comment]
@dmlap where can I increase the number of segments in window ?

**Comment by dmlap** [comment]
That's configured server-side. You'd have to check the documentation for whoever/whatever is backing that live stream.

**Comment by minh1903** [comment]
@dmlap Thanks :+1:

**Comment by dmlap** [comment]
Glad that sorted it out!
