### ISSUE TITLE
Does it work with a live broadcast

### ISSUE THREAD

**Issue by sobytes** [videojs/videojs-contrib-hls#566]
Great plugin works great for a hls playlist for adaptive bitrate but i cannot seem to get it to work with a live broadcast is this even possible? Or is this plugin not designed for live broadcasts?

Test version here.
[http://jsbin.com/cecesojale/edit?html,output](http://jsbin.com/cecesojale/edit?html,output)

Thanks

**Comment by mimcz** [comment]
Isn't the problem with your source? I tried this one and it works ok on your test version:
https://playertest.longtailvideo.com/adaptive/wowzaid3/playlist.m3u8

It looks like you don't have CORS (Access-Control-Allow-Origin') on your source.

**Comment by keylase** [comment]
with this source https://playertest.longtailvideo.com/adaptive/wowzaid3/playlist.m3u8 stream is frozen after 30 seconds.
Source with seems

**Comment by gkatsev** [comment]
Unfortunately, we cannot play back HLS videos that do not have CORS headers. Please see the [hosting considerations](https://github.com/videojs/videojs-contrib-hls#hosting-considerations) in the README for more details.
Thanks.
