### ISSUE TITLE
local Filesystem & Cordova Error ? Project must be on a Webserver?

### ISSUE THREAD

**Issue by beyondthestatic** [videojs/videojs-contrib-hls#567]
Hey guys, i tested this lib on my webserver with various HLS Streams, and it works great!

So i wanted to give it a try inside of Adobe Cordova. After developing and previewing it on my local Filesystem I experienced that it was not possible to play a HLS Stream from file:// ... /index.html

**VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. **

Can anybody tell me what's the dependency that it will not work locally and in this case in Adobe Cordova as well ?

THX a lot,*m

**Comment by gkatsev** [comment]
Unfortunately, we cannot play back from `file://`. That is because we use XmlHttpRequest (XHR) to load the HLS manifests and segments and `file://` is disallowed from XHR.
For bests results, we really do urge you to use a webserver with CORS enabled.

**Comment by beyondthestatic** [comment]
Thanks @gkatsev  for this quick response.

If I may, i have an additional Question on that subject.

This CORS Problem results because of the `*.m3u` Parser, right?
If i would Whitelist the Domain of the HLS Stream (in Adobe Cordova) theoretically it should work?

Or are there any additoonal CrossDomain Requests i have to watch out for, in this lib?

thx in advance!

**Comment by gkatsev** [comment]
Both the manifests and ts segments are loaded in over XHR. Normal browsers do not allow you to do XHR from the `file://` protocol or to `file://` protocols, I do not know about Cordova.

**Comment by beyondthestatic** [comment]
it is the same in Cordova, but i guess if we add the video-CDN's Domain to the CORS-Whitelist it might work. THX a lot!
