### ISSUE TITLE
How To Setup

### ISSUE THREAD

**Issue by neverguessme** [videojs/videojs-contrib-hls#570]
Hey, I am all new to this and its my first time. I am on a really busy schedule and would appreciate if someone could help me out.

I have a wordpress plugin for video.js but the thing is I don't know how to play live hls files from there. So I stumbled upon this repository. 

I tested my livestream at http://www.flashls.org/videojs/flash_demo.html and it works well.

Can someone please help me.

1. How do I setup this video.js on my website
2. How to add the hls plugin
3. How to enable it for live video, that can play on all browser and devices. 

If someone already has a code built and can let me use it or explain to me it would be great. I have tried looking at the installation documents and stuff for hours and I don't understand it :(.

Thanks in advance.

**Comment by dmlap** [comment]
We have a live example and instructions on this project's [github page](http://videojs.github.io/videojs-contrib-hls/). Just so you're aware, this project is completely different from flashls. If you need support on using that project, you should head over to [the flashls repo](https://github.com/mangui/flashls)
