### ISSUE TITLE
Buffer problem with flash 

### ISSUE THREAD

**Issue by hyurtseven81** [videojs/videojs-contrib-hls#571]
I have a weird problem with flash tech,  

Player tries to download segment just before start to play that segment and it causes buffering before all segments, but it just happening on some resolutions, for example on 13" macbook pro problem is always happening but on 15.4" macbook pro when resolution is retina there is no problem but if you increase the resolution to max level there is a problem.

I tried a lot of samples hls but situation always same.

When i try to play this hls with html5 tech there are another problems like infinite segment load, freezes and audio-video sync problems. So i couldn't success to play this hls without problems.

HLS: https://cdn.blutv.com.tr/kdv/S6/HLS_VOD/92658_d24b/index.m3u8
Videojs: 5.71
VideojsSwf: 5.0.1
Videojs HLS: 1.3.5 to 2.0.0

**Comment by hyurtseven81** [comment]
I've found an interesting situation, if you decrease browser size to half of the screen when you use max resolution on 15.4 macbook pro, there is no problem again, so i think the problem is related to resolution. but i don't know where can i look?

I'm waiting your help.

Thank you.

**Comment by hyurtseven81** [comment]
One more detection, if player width > 1300px there is problem
if player width < 1300px there is no problem

**Comment by dmlap** [comment]
If you're using Flash-based HLS playback, you need to worry about the tightening rules for Flash. Safari and Chrome will put Flash into a "power saving" mode if your player is below a certain size or not visible on the screen initially.

**Comment by dmlap** [comment]
Tried your stream in MSE playback mode. Looks like your first segment is detected as starting at 0.044 seconds and so our segment fetching logic is cycling around trying to find media data for that initial fraction of a second.

**Comment by hyurtseven81** [comment]
Thank you for your quick reply, we're trying to fix our hls's

**Comment by dmlap** [comment]
A little more info: your first segment is detected as starting at 0.044 seconds because that's when the audio begins. The player actually plays fine through that gap but our segment fetching logic isn't smart enough to realize a gap that small at the start of the video is not relevant.

**Comment by hyurtseven81** [comment]
Thanks for your helps, we fixed one of our HLS with ffmpeg and with this fix everything seems perfect.

https://cdn.blutv.com.tr/kdv/S6/HLS_VOD/92744_f130/index.m3u8

Thanks again.
