### ISSUE TITLE
Cannot play hls stream with audio codec AAC-LC ("mp4a.40.2")

### ISSUE THREAD

**Issue by whatvn** [videojs/videojs-contrib-hls#574]
Problem on chrome, video cannot be play, videojs stop, error code: MEDIA_ERROR_DECODE

```
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support
```

and 

```
Uncaught InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.
```

appendBuffer error appears in these lines of code: 

``` javascript
  if (segmentObj.bytes) {
        tempBuffer = new Uint8Array(segmentObj.bytes);

        // Combine the individual segments into one large typed-array
        segmentObj.segments.forEach(function (segment) {
          tempBuffer.set(segment, offset);
          offset += segment.byteLength;
        });

        destinationBuffer.appendBuffer(tempBuffer);
```

On firefox, video can be played for some seconds then stop without error. 
I've checked my stream and it's AAC-LC, so audio codec is correctly defined in m3u8 playlist. 
Stream url to test:  http://s1.videofly.vn/2016/03/01/3CRb9VV17JJ.m3u8

**Comment by halibegic** [comment]
+1

**Comment by vietlongn** [comment]
+1

**Comment by juliomenendez** [comment]
Any solution for this yet?

**Comment by dmlap** [comment]
We got started on adding support for alternate audio tracks and finishing that up has kept us from looking into a lot of these decode errors. We're wrapping up alternate audio right now though, so we should start addressing these cases soon.

One thing to note is there are a *lot* of different unrelated reasons for MEDIA_ERR_DECODE. If you have a public stream we can test against, adding that to the thread would be incredibly helpful.

**Comment by creativefull** [comment]
+1

**Comment by gesinger** [comment]
Hey @whatvn , sorry this ticket has gone a long time without much attention

I tried the test stream in the original issue, but it looks like it must've expired.

We've made a lot of changes to videojs-contrib-hls in the meantime. Would you be able to give the latest version (as of this comment, v4.1.1) a shot? If it's still a problem, would you be able to re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/edit?html,output)?

And for others also seeing the issue/similar issues, @dmlap is right that MEDIA_ERR_DECODE can be various different cases. If anyone is seeing an issue along those lines, please feel free to open a new issue with a reduced test case. Thank you.
