### ISSUE TITLE
Make it easy to play other videos on the demo page

### ISSUE THREAD

**Issue by shacharz** [videojs/videojs-contrib-hls#579]
This will make testing of the latest version with certain streams a lot easier, and might raise adoption

**Comment by dmlap** [comment]
Good point! Any chance you'd be interested in opening a PR to add it?

**Comment by tenacex** [comment]
@shacharz What do you exactly mean by making it easy to play other videos on the demo page? Currently you can input a url to a stream, do you mean to say that we should add something like a drop down menu feature?

**Comment by shacharz** [comment]
@tenacex 
> Currently you can input a url to a stream

How? I dont see any query string option or something like that from the source code



> do you mean to say that we should add something like a drop down menu feature?

Yea, that's what I had in mind

**Comment by forbesjo** [comment]
Closed by #819
