### ISSUE TITLE
Cache gets invalidated

### ISSUE THREAD

**Issue by mpaldheCM** [videojs/videojs-contrib-hls#582]
I am trying to play m3u8 files.
The ts segments are fetched repeatedly.
allowCache is set to True.

However, I see that the cache is possibly getting invalidated because it reaches the following part of the code:
  // if the duration has changed, invalidate the cached value
  if (oldDuration !== newDuration) {
    // update the duration
    if (this.mediaSource.readyState !== 'open') {
      this.mediaSource.addEventListener('sourceopen', setDuration);
    } else if (!this.sourceBuffer || !this.sourceBuffer.updating) {
      this.mediaSource.duration = newDuration;
      this.tech_.trigger('durationchange');
    }
  }

The if condition is satisfied because oldDuration and newDuration differ by 0.2 or 0.3 seconds.
I am unable to figure out why the duration keeps chaning.
Please help!
Thank you!

**Comment by dmlap** [comment]
We cache of the length of the video so we avoid triggering some video processing more than strictly necessary. The duration may be updated when downloading and buffering a segment reveals that it actually is longer (our shorter) than advertised in the m3u8 file. The times in the m3u8 are often incorrect by seconds or more. 

The allowCache directive actually applies to the video segment files, and we let the browser's standard caching logic take care of that.
