### ISSUE TITLE
i cant play my hls vod

### ISSUE THREAD

**Issue by momkin** [videojs/videojs-contrib-hls#583]
hello
i think there is bug with your script

please can you check this exemple

http://s2.lody.to/s2.html

thanks

**Comment by dmlap** [comment]
For some reason, tiny gaps are being detected between the segments of your video. We need to do some investigation to figure out why.

**Comment by momkin** [comment]
Hello
i don't know why its working with flashhls and daylimotion hls script

but its not working with yours !

can you please check why ?

**Comment by tenacex** [comment]
I noticed that this is an encrypted stream. The second segment, where the lag in playback is seen, is failing to decrypt properly on my hls-fetcher that uses the same decryption that we use in contrib-hls. The 4th segment, which is a 4 second segment, also is not decrypting properly, thus causing playback to stall. I am looking into what is going wrong during decryption and will keep you posted.

**Comment by momkin** [comment]
thank you very much !

**Comment by momkin** [comment]
also i'm using this for streaming
https://github.com/*kaltura*/*nginx*-vod-module
if this helps !

**Comment by tenacex** [comment]
It says link not found.

**Comment by momkin** [comment]
https://github.com/kaltura/nginx-vod-module

**Comment by momkin** [comment]
Hello any news ??

its working perfectly with https://github.com/dailymotion/hls.js/releases

**Comment by dmlap** [comment]
@momkin I'm no longer able to access your stream. Can you provide a link to an m3u8 that's still up?

**Comment by momkin** [comment]
http://s2.lody.to/hls/16ar.mp4/index.m3u8

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by theleon** [comment]
Hi, any updates on that?

**Comment by gesinger** [comment]
Sorry this ticket has gone a long time without much attention.

@momkin , I tried the m3u8 you posted with the latest player, and it seems to work for me.

Would you be able to give the latest version (as of this comment, v4.1.1) a shot? If it's still a problem, would you be able to re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/edit?html,output)?

Thank you for reporting the issue.
