### ISSUE TITLE
Some HLS playlists return `MEDIA_ERR_DECODE` on Chrome

### ISSUE THREAD

**Issue by ChrisWhiten** [videojs/videojs-contrib-hls#584]
I'm looking into moving my existing video player over to video.js with this hls plugin (which looks fantastic, by the way).  It seems like the plugin is having trouble with certain HLS playlists, though.  Here is a small demo derived from the example provided by this repo:

``` html
<!DOCTYPE html>
<html>
  <head>
    <title>VJS test</title>
  </head>
  <body>
  <div class="video-js vjs-default-skin vjs-controls-enabled">
    <video id=example-video width=960 height=400 class="video-js vjs-default-skin" controls >
          <source
             src="http://204.101.47.141:8080/cameras/IYnHqNXQg3n474bQ/video.m3u8?begin=1457326800000&end=1457413199999&stream=82e97bc4-5f24-4b3d-8548-63da11ab947e"
             type="application/x-mpegURL"></source>
        </video>
  </div>

    <link href="http://vjs.zencdn.net/5.4/video-js.css" rel="stylesheet">
    <script src="http://vjs.zencdn.net/5.4/video.js"></script>
    <script src="node_modules/videojs-contrib-hls/dist/videojs.hls.min.js"></script>

    <script>
      var player = videojs('example-video');
    </script>
  </body>
</html>
```

The URL provided in the video source is throwing the following 2 exceptions on Chrome:
`VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support.`

`Uncaught InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.`

On Firefox, the player plays a few seconds of the stream, before throwing similar errors.

For reference, that video works perfectly fine on Safari.  Furthermore, replacing the source with `http://solutions.brightcove.com/jwhisenant/hls/apple/bipbop/bipbopall.m3u8` works fine on Chrome.

Is this an error in the usage of the plugin?  Are there other options I should be using to support this stream?

**Comment by dmlap** [comment]
It sounds like your HLS is doing something interesting. How are you creating your videos? Can you put up a segment captured from your failing video somewhere public?

**Comment by ChrisWhiten** [comment]
@dmlap The URL provided in the example (`http://204.101.47.141:8080/cameras/IYnHqNXQg3n474bQ/video.m3u8?begin=1457326800000&end=1457413199999&stream=82e97bc4-5f24-4b3d-8548-63da11ab947e`) should be publicly accessible.  

I've spent some time reviewing it with a colleague and we've found some interesting details.  This particular stream was created by a DVR using an HTTP stream straight from VLC (using a command like `vlc -vvv --loop my_footage.ts --sout '#standard{access=http,mux=ts,dst=:8812}'`).  On that same DVR, streams recorded from a true RTSP stream work perfectly with this setup.  Perhaps there is something different about the way VLC handles this

**Comment by dmlap** [comment]
Interesting! Thanks for the additional info about the capture.

**Comment by leighfarrell** [comment]
I seem to be having the same issue with some of my HLS files. Certain ones work great in Chrome, while others trigger the above errors. They're all being instantiated the same way, which leads me to believe it might have to do with how the videos are being created/encoded. Any progress/leads on this?

**Comment by samward1985** [comment]
+1

feeds are working fine in other browsers...chrome having issues

**Comment by gesinger** [comment]
Hey @ChrisWhiten , sorry this issue has gone so long without much attention.

I tried the stream listed above, but it looks like the playlist is now empty.

We've made a lot of changes to videojs-contrib-hls in the meantime. Would you be able to give the latest version (as of this comment, v4.1.1) a shot (you can also use [this template](http://jsbin.com/vokipos/edit?html,output) to create a reduced test case with the stream)?

**Comment by gesinger** [comment]
Closing for now. If you are still experiencing this issue with the latest version of videojs-contrib-hls (as of this comment, v5.0.0), please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.
