### ISSUE TITLE
Some m3u8 files do not work with byte range

### ISSUE THREAD

**Issue by mpaldheCM** [videojs/videojs-contrib-hls#586]
Hi!

I am using the videojs player to play m3u8 files.
I noticed that some files are getting stuck without throwing any console errors or warning.
https://s3-us-west-2.amazonaws.com/cm-users/video/prod/61/67/tw-v52606167/tw-v52606167_cf.m3u8
Is an example of such a file.

It plays fine until 8(or 9) seconds and then stalls. No console errors, no warnings, no network errors.

I noticed, that if I change the file to have full byte range like https://s3-us-west-2.amazonaws.com/cm-users/video/prod/61/67/tw-v52606167/tw-v52606167_cf_full_byte_range.m3u8, then it plays completely fine.
It is exactly the same chunk.

The file plays fine on quicktime and vlc.

Not sure why the bug is coming up.

Thank you!

EDIT:
I missed some information.
I did notice that a lot of xhr requests are timing out because the timeout in xhr call is only around 50 ms for those.
So I updated the code to:
    timeout: Math.max((segment.duration \* 1.5), 0.5) \* 1000,
so that the timeout is at least 500 ms.
Original code:
    timeout: (segment.duration \* 1.5) \* 1000,

Original timeout condition:
![timeout of chunk call](https://cloud.githubusercontent.com/assets/12402159/13619466/11d111c4-e53e-11e5-86a2-8f607521e4e6.png)

New situation: no timeout, but video is stuck:
![video stuck no errors](https://cloud.githubusercontent.com/assets/12402159/13619474/21a6afbe-e53e-11e5-9527-7fc1c1b69d46.png)

Though the screenshots look of a different player, the base player is still video.js player.

If I manually scroll forward a couple of seconds, it continues working fine.

**Comment by gkatsev** [comment]
I wonder if the issue is that we set the end of the range to be offset+length-1 see [here](https://github.com/videojs/videojs-contrib-hls/blob/master/src/videojs-hls.js#L1089). This could possibly cause us to miss a byte.

**Comment by gkatsev** [comment]
No, Looks like it should be fine as is, I previously tested with the last segment and the content-length in the response was correct for both, tried a different segment and without the `-1` it produced a content-length of one extra byte.

**Comment by mpaldheCM** [comment]
The tests in manifest have the same format. So I doubt if we are missing any bytes. Also the first three or four byte ranges work perfectly fine. So why does it fail only around the 8th/9th second?

**Comment by mpaldheCM** [comment]
I missed some information.
I did notice that a lot of xhr requests are timing out because the timeout in xhr call is only around 50 ms for those.
So I updated the code to:
    timeout: Math.max((segment.duration * 1.5), 0.5) * 1000,
so that the timeout is at least 500 ms.
    Original code: timeout: (segment.duration * 1.5) * 1000,

PS: Editing the original post to add this.

**Comment by mpaldheCM** [comment]
I am trying to debug this issue, and I think this can be a relevant cause?
http://stackoverflow.com/questions/28105950/html5-video-stalled-event

**Comment by gesinger** [comment]
Hey @mpaldheCM , sorry this issue has gone so long without much attention.

I tried the link posted above, but it looks to have expired.

We've made a lot of changes to videojs-contrib-hls in the meantime. Would you be able to give the latest version (as of this comment, v4.1.1) a shot? If it's still a problem, would you be able to re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/edit?html,output)?

Thank you.
