### ISSUE TITLE
how do I change the videojs.Hls.GOAL_BUFFER_LENGTH value?

### ISSUE THREAD

**Issue by FDiskas** [videojs/videojs-contrib-hls#588]
I have a Live stream and I need to change buffer size. Right now the segments duration on LIVE video are max 30s.
Looks like it is hardcoded: https://github.com/videojs/videojs-contrib-hls/blob/25033e312281bfa1eb227d96055975568cb63c57/src/videojs-hls.js#L145

The segments duration I calculated like so:
```js
$.each(player.tech_.hls.playlists.media().segments, function (key, item) {
    duration += item.duration;
  });
```

**Comment by dmlap** [comment]
It's a little dangerous to fiddle with but you can just write over it at runtime. It's only a constant by convention. If you do decide to change it, keep in mind that setting it too low will cause some of your viewers to buffer during playback, and setting it too high will waste money on bandwidth that may never be used.

**Comment by FDiskas** [comment]
So why I opened that issue...
I dont know how to change this. I need an example.
I tryed just `videojs.Hls.GOAL_BUFFER_LENGTH = 60;` but this not works. Still got the same 30s. buffer.
And one more issue. It should be imposible to seek LIVE stream to the time that is lower than the buffer size.

**Comment by FDiskas** [comment]
@dmlap - reopen the issue.
