### ISSUE TITLE
Can I use videojs to download all the TS files from a  m3u8 playlist file?

### ISSUE THREAD

**Issue by SudoPlz** [videojs/videojs-contrib-hls#590]
Hello I'm not sure if my question is correct, but please spend a few seconds to explain to me how to do this?
The title is my question.

**Comment by tenacex** [comment]
Directly, not that I know of. But.... Feel free to use this: https://github.com/tenacex/hls-fetcher/tree/livestream-support

**Comment by SudoPlz** [comment]
This looks exactly what I was looking for I'll test it immediately, thank you tenacex!

**Comment by tenacex** [comment]
@SudoPlz @imbcmdth wrote the original, so you can thank him! I am adding my addition for livestream support to the npm registry, so you keep a lookout for that in the next hour or so. it will be `live-hls-fetcher`

**Comment by SudoPlz** [comment]
Great I will be waiting for this, thanks !

**Comment by SudoPlz** [comment]
Also it would really save some time for me if you told me which files I need in order to run it in a javascript file instead of a as a command in the terminal.

**Comment by tenacex** [comment]
What do you mean by what files you need?

**Comment by SudoPlz** [comment]
I guess that was just my lazy part talking. I wondered if there was a quick way to discard all the code that has to do with the command line, and just use the library from javascript code.

**Comment by tenacex** [comment]
It would be pretty easy to do actually. Pessimist is the module that feeds the input into the starting function. The whole project starts at the `getIt` function in index.js. So just hook up your code to that part.

**Comment by SudoPlz** [comment]
Awesome, exactly the answer I was looking for, thanks again man..!!

**Comment by tenacex** [comment]
:+1:

**Comment by SudoPlz** [comment]
`npm install live-hls-fetcher` works by the way, is it your latest code (because you have lots of branches)

**Comment by tenacex** [comment]
If not, you can clone my repo, switch to the livestream-support branch, and then run `npm i -g ./`

**Comment by SudoPlz** [comment]
I'm using 
`
"dependencies": {
    "live-hls-fetcher": "tenacex/hls-fetcher#livestream-support"
  },
`
on my package.json and I'm positive that I receive the correct branch.

**Comment by tenacex** [comment]
perfect.

**Comment by SudoPlz** [comment]
Awesome, I did exactly what I wanted to do, now I have another quick question (last one I promise..) are you aware of any code that binds the ts files into 1?

**Comment by tenacex** [comment]
Checkout https://github.com/videojs/mux.js. It will take some time, but if you hook it up directly, you could feed the data from the ts segments into it and get back content in an mp4 wrapper.
