### ISSUE TITLE
Audio pops in Firefox

### ISSUE THREAD

**Issue by mattblaha** [videojs/videojs-contrib-hls#592]
I noticed on my own stream that in Firefox, if I listen closely, I can hear a pop at a regular interval that I'm pretty sure happens each time a new segment starts. I thought it was just my stream, but then I noticed the same thing happens with the Tears of Steel video in the demo. I tested on FF 44 on both a Mac running Mavericks and on Fedora 23. Also FF 45 on El Capitan. Both were Firefox 44.0.2. It does not happen in Chrome on either OS, or Safari on the Mac.

**Comment by tenacex** [comment]
I wasn't able to replicate this bug in FF 44.0.2 on Yosemite. What is the link to the exact stream you are using?

**Comment by mattblaha** [comment]
I just tried it on several more Macs and with several more sets of ears. We just used the test page here:

http://videojs.github.io/videojs-contrib-hls/

It's really the perfect example. Listen right as the count down hits one and the rocket engine fires up. The first pop shows up right there, but I can't hear it in Chrome or Safari, just Firefox.

**Comment by carloscarnero** [comment]
On FF 44.0.2 on Linux (Fedora) I confirm that audio discontinuities can be heard from the [public test](http://videojs.github.io/videojs-contrib-hls/). The same happens in an internal VoD source, where each segment is 10 seconds, and the pops are audible at each segment start.

**Comment by cdhowie** [comment]
+1 Happens for me in Firefox 44.0.2 on OS X 10.11.3, but not in Chrome, with every HLS video I try.

**Comment by waster** [comment]
Same for me in Firefox for HLS in FF 45.0 (Windows/Linux) for audio only stream.

**Comment by PNixx** [comment]
+ 1 in Firefox 45.0.1 on OS X 10.11.4

**Comment by JackSimth** [comment]
I am seeing the same thing, with both audio and video (combined stream).  I'm fortunately testing with a CentOS server, and have full root access.  I actually went through and compared the apache logs to the underlying files:

What seems to me to be going on is that the player isn't actually buffering the segments in FireFox (that, or it stops playing to pull the next - either way).  The skip happens at segment borders, and when I went through the apache logs, my test client was pulling the segments every nine seconds, while the m3u8 file was reporting that the segments were eight seconds long (I'm rounding in both cases - 8.015 is close enough to 8 for my purposes, and the apache logs in question had a resolution of 1 second, but still, it was pulling less often than it should have).  I was also able to confirm this is what's going on by setting things up to exaggerate the issue - setting the stream to 8 mbps and then using tc (linux traffic control settings command) to limit the server to 10 mbps on that card exaggerated the issue to a serious degree - the fraction of a second skip I'd been dealing with became about six seconds long.  

So my conclusion is that it's either not actually downloading segments before they're needed, or it stops playing while it's downloading segments.  I'm only seeing this behavior in FireFox - I'm not seeing it in Chrome or Edge.

**Comment by JackSimth** [comment]
I should probably add a short log snippet showing the behavior from when I was doing some testing... sorry for the delay, I don't always think things through.

Apache log:
10.0.0.95 - - [23/Aug/2016:08:00:02 -0700] "GET /hlstest/main6.ts HTTP/1.1" 200 7294588
10.0.0.95 - - [23/Aug/2016:08:00:11 -0700] "GET /hlstest/main0.ts HTTP/1.1" 200 9155600
10.0.0.95 - - [23/Aug/2016:08:00:21 -0700] "GET /hlstest/main1.ts HTTP/1.1" 200 7279924
10.0.0.95 - - [23/Aug/2016:08:00:31 -0700] "GET /hlstest/main2.ts HTTP/1.1" 200 7230668

The m3u8 file that ffmpeg was spitting out at the moment of that last entry:
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:20
#EXTINF:8.003000,
main6.ts
#EXTINF:9.803000,
main0.ts
#EXTINF:8.002000,
main1.ts
#EXTINF:8.003000,
main2.ts
#EXTINF:8.002000,
main3.ts

**Comment by JackSimth** [comment]
Huh, that's interesting... following apache logs while looking at the underlying files with a simple while true loop:

It only seems to happen when the player is loading *just* the oldest entry.  For whatever reason, it doesn't always pre-load the three I've got listed.  When it starts with the middle or last entry, everything's fine for a long, long time.  

Is there any way to change the player behavior such that it tries to load at least three segments always (maybe an initialization variable)?

**Comment by JackSimth** [comment]
This snapshot was generated by way of a simple while true loop running on the server to give me a nice live view of what my browser was pulling and what the server was showing.

#EXTM3U
#EXT-X-TARGETDURATION:7
#EXT-X-VERSION:4
#EXT-X-MEDIA-SEQUENCE:608
#EXTINF:8.004933,
asegment.8.ts?stream=5&cam=AWeRTla4wtLAtfca&time=1473435188
#EXTINF:7.995000,
asegment.9.ts?stream=5&cam=AWeRTla4wtLAtfca&time=1473435196
#EXTINF:7.976022,
asegment.10.ts?stream=5&cam=AWeRTla4wtLAtfca&time=1473435204
Fri Sep  9 08:33:33 PDT 2016
10.0.0.95 - - [09/Sep/2016:08:32:45 -0700] "GET /hls/asegment.1.ts?stream=5&cam=AWeRTla4wtLAtfca&time=1473435132 HTTP/1.1" 200 1973436
10.0.0.95 - - [09/Sep/2016:08:32:48 -0700] "GET /hls/alayer.m3u8?stream=5&cam=AWeRTla4wtLAtfca HTTP/1.1" 200 308
10.0.0.95 - - [09/Sep/2016:08:32:53 -0700] "GET /hls/asegment.2.ts?stream=5&cam=AWeRTla4wtLAtfca&time=1473435140 HTTP/1.1" 200 1990732
10.0.0.95 - - [09/Sep/2016:08:32:55 -0700] "GET /hls/alayer.m3u8?stream=5&cam=AWeRTla4wtLAtfca HTTP/1.1" 200 308
10.0.0.95 - - [09/Sep/2016:08:33:01 -0700] "GET /hls/asegment.3.ts?stream=5&cam=AWeRTla4wtLAtfca&time=1473435148 HTTP/1.1" 200 1976068
10.0.0.95 - - [09/Sep/2016:08:33:02 -0700] "GET /hls/alayer.m3u8?stream=5&cam=AWeRTla4wtLAtfca HTTP/1.1" 200 308
10.0.0.95 - - [09/Sep/2016:08:33:09 -0700] "GET /hls/asegment.4.ts?stream=5&cam=AWeRTla4wtLAtfca&time=1473435156 HTTP/1.1" 200 1983400
10.0.0.95 - - [09/Sep/2016:08:33:09 -0700] "GET /hls/alayer.m3u8?stream=5&cam=AWeRTla4wtLAtfca HTTP/1.1" 200 308
10.0.0.95 - - [09/Sep/2016:08:33:16 -0700] "GET /hls/alayer.m3u8?stream=5&cam=AWeRTla4wtLAtfca HTTP/1.1" 200 308
10.0.0.95 - - [09/Sep/2016:08:33:17 -0700] "GET /hls/asegment.6.ts?stream=5&cam=AWeRTla4wtLAtfca&time=1473435172 HTTP/1.1" 200 1972496
10.0.0.95 - - [09/Sep/2016:08:33:20 -0700] "GET /hls/alayer.m3u8?stream=5&cam=AWeRTla4wtLAtfca HTTP/1.1" 200 308
10.0.0.95 - - [09/Sep/2016:08:33:27 -0700] "GET /hls/alayer.m3u8?stream=5&cam=AWeRTla4wtLAtfca HTTP/1.1" 200 308
10.0.0.95 - - [09/Sep/2016:08:33:27 -0700] "GET /hls/asegment.7.ts?stream=5&cam=AWeRTla4wtLAtfca&time=1473435180 HTTP/1.1" 200 1991108
10.0.0.95 - - [09/Sep/2016:08:33:27 -0700] "GET /hls/asegment.8.ts?stream=5&cam=AWeRTla4wtLAtfca&time=1473435188 HTTP/1.1" 200 1970240
10.0.0.95 - - [09/Sep/2016:08:33:28 -0700] "GET /hls/asegment.9.ts?stream=5&cam=AWeRTla4wtLAtfca&time=1473435196 HTTP/1.1" 200 1976068

-	Fixed itself for a while when it decided to load all three.  Then eventually crashed again, but it took a while.

**Comment by mattblaha** [comment]
I recently noticed a this issue seems to have been fixed, perhaps inadvertently by some other change.

Running a side by side comparison with an old install and a new install, both quite identical except for the videojs/videojs-contrib-hls versions, the pops are gone with the new code but present with the old.

Can anyone else verify the same results?

**Comment by gesinger** [comment]
This was fixed as part of https://github.com/videojs/videojs-contrib-media-sources/pull/104 and https://github.com/videojs/mux.js/pull/120 . Thank you for updating @mattblaha , and thank you to everyone else for reporting the issue and adding debugging information.
