### ISSUE TITLE
Error 4 with PC chrome

### ISSUE THREAD

**Issue by sgavali** [videojs/videojs-contrib-hls#593]
1.3.7 hls plugin and 5.6 videojs is working with PC chrome when I host it locally using tomcat.
But when I integrate it in web app it does not work in PC chrome, it works fine on phone.
I see swf file is not getting loaded, on same web app 0.x plugin is working with PC chrome.

What could be issue ?

**Comment by dmlap** [comment]
We've been doing a ton of work to improve compatibility in recent releases. Have you tried the latest version?
