### ISSUE TITLE
What's the difference between v2.x and v1.x releases?

### ISSUE THREAD

**Issue by thomaspeeters** [videojs/videojs-contrib-hls#594]
I can't find a changelog entry or a comment anywhere explaining the difference between these apparently different release channels. Could someone elaborate?
Will v1.x become deprecated?

**Comment by thenewguy** [comment]
A changelog update or some sort of short blog post summary would be very helpful if you are able to find the time for it.  The current changelog indicates that 0.17.6 is the official version and doesn't mention the 1.x or 2.x branch at all

**Comment by FDiskas** [comment]
+1

**Comment by dmlap** [comment]
@imbcmdth [updated our changelog](https://github.com/videojs/videojs-contrib-hls/commit/b51a71be373d7e84019b53e1efd6ed7493c84d64) with the changes between releases. The big difference is switching to using es6 in 2.x.
