### ISSUE TITLE
Endless downloading of segments before video starts

### ISSUE THREAD

**Issue by abrudin** [videojs/videojs-contrib-hls#595]
For some of our streams, before the video is started, the player downloads the video segments over and over until the video is started, causing possibly infinite amounts of bandwidth being used. The order of the downloaded segments is as follows:
1,2,1,2,3,1,2,3,4,1,2,3,4,5 etc. continuing until the last segment in the playlist (and also then repeating).

The issue is reproducible in at least Chrome and Firefox.

After some basic research, it seems to be a problem when appending to the buffer, but if you start the player, the stream works just fine. An example of a stream behaving like this (but with only 3 segments) is here:
http://contrib-hls-test.s3-website-eu-west-1.amazonaws.com/hls/master.m3u8

Embed it with preload=auto and controls, and open your network tab.

**Comment by waster** [comment]
The same problem for me for audio-only stream with the latest videojs 5.8.0 and videojs-contrib-hls 2.0.1 in FF 45.0 (Windows) but not in Chrome. Player starts to download ts-segments infinitely however stream is playing.

**Comment by tenacex** [comment]
We are working on the segment loading logic right now. It should fix your problem, stay tuned and checkout the `better-fetching` branch.

**Comment by waster** [comment]
I tried to do npm test and it's failed:

 /usr/local/src/videojs-contrib-hls/src/master-playlist-controller.js:241:13: Unexpected "todo" comment.

**Comment by ravi155** [comment]
+1

**Comment by pedromcunha** [comment]
Any updates on this issue? Currently dealing with it myself.

**Comment by gesinger** [comment]
Sorry this ticket has gone a long time without much attention.

I tried out the original URL with the latest player, and couldn't reproduce the issue.

We've made a lot of changes to videojs-contrib-hls in the meantime (particularly around segment loading logic). Would anyone experiencing the issue be able to give the latest version (as of this comment, v4.1.1) a shot? If it's still a problem, would you be able to re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/edit?html,output)?

Thank you all for reporting the issue.
