### ISSUE TITLE
GOAL_BUFFER_LENGTH Impossible to increase

### ISSUE THREAD

**Issue by FDiskas** [videojs/videojs-contrib-hls#598]
My problems on all videojs-contrib-hls versions:
----------------
- [ ] 1. I need to increase the buffer size to 60s.
- [ ] 2. On live streams player starts video from beginning not from the last available buffer. (player still trying to download first segment from live playlist)
- [ ] 3. Missing `ended` event on `m3u8` with `#EXT-ENDLIST` tag dynamically added.

#### For problem 1. I tried this:
- [x] Overwritted `videojs.Hls.GOAL_BUFFER_LENGTH` constant on player init
- [x] Made the fork and changed the constant in [source code](https://github.com/FDiskas/videojs-contrib-hls/blob/development/src/videojs-contrib-hls.js#L27) and recompiled to dist
- [x] Tried all `videojs-contrib-hls` versions
- [ ] Going deeper to the source code

#### For problem 2.
- [x] As work around
```js
if (player.duration() === Infinity) {
   // Something like this - cant remember exact code.
   player.tech.hls_.playlist().media.seekable.end(0);
}
```
- [x] Tryed by modifying the source code (fail)
- [ ] Prepare the demo for the demonstration off the issue

#### For the problem 3.
- [x] As a workaround on `timeupdate` event I'm calculating all downloaded segments duration and then the current time reaches the duration I'm manually triggering `ended` event.

   > p.s. On live streams `player.duration()` returns `Infinity` so I need to calculate it by hand.
- [ ] Prepare the demo for the demonstration off the issue
- [x] Tried by modifying the source code (fail)

### And what else?
1. Do I need to write more info about issues that plugin community could make some changes with fixes?
1. Should I try to make fixes by self (looks like impossible for me) and make some Pull request?
1. Should I make a fork and work with it alone?
1. Are this happens to others?

> Sorry for bad english

**Comment by dmlap** [comment]
Can you paste in a snapshot of your m3u8 while your live stream is up? With live streams, buffering is complicated. We try to start playback three segments from live point which may be less time than `GOAL_BUFFER_LENGTH`. If that's the case, the buffer length is limited by the amount of content available in the m3u8. You'd need to seek backwards from the live point to make sure there's enough room to fill 60 seconds of buffer.

**Comment by FDiskas** [comment]
in m3u8 file i have 6 segments with 10s. duration each. There always is minimum 6 segments. So I changed [constant](https://github.com/videojs/videojs-contrib-hls/blob/master/src/playlist.js#L13)
I changed [GOAL_BUFFER_LENGTH](https://github.com/videojs/videojs-contrib-hls/blob/master/src/videojs-contrib-hls.js#L27) to 60. Rebuilded the scripts to `dist` and runned included tests in `development` branch and there was ~17 failed tests. All them talks about seek problems or something.

**Comment by dmlap** [comment]
Since you have only 60 seconds of content available, you won't be able to see much effect from modifying the goal buffer length. Our default seek point would be 30 seconds from live in your setup which means the maximum possible buffer size would be only 30 seconds. if you seek back to the very beginning of the seekable window (that is, `player.seekable().start(0)`), the player might be able to buffer the full content window and get approximately 60 seconds buffered. You would be in danger of "falling off the back" of the content window in that case though, so I wouldn't recommend it.

Any chance you could elaborate on why you need 60 seconds of content buffered in your player?

**Comment by FDiskas** [comment]
> Any chance you could elaborate on why you need 60 seconds of content buffered in your player?
Just to have more time for server sync

**Comment by dmlap** [comment]
Are you experiencing playback problems with the default settings? Sorry to keep digging here, it's just an unusual setup and I want to make sure we're working on the right solution.

**Comment by FDiskas** [comment]
Yes, sometimes the video is to close to the live last segment in playlist. If the are some issues with stream servers and segments are not synchronized correctly the user's video is usually stops playing if reaching the last segment. So I need to increase that and force users to watch live with 60s. delay.

**Comment by forbesjo** [comment]
Is still an issue?

**Comment by FDiskas** [comment]
:information_source: I'm not working on that project any more.

**Comment by FDiskas** [comment]
You can check all problems here http://bit.ly/2aEjHvF
