### ISSUE TITLE
Artifacts when seeking video (latest versions)

### ISSUE THREAD

**Issue by jpfranco** [videojs/videojs-contrib-hls#603]
Seen on Chrome. Sorry I don't have the full setup online, but I do have a url of the [video source](https://authproxy-1.ocdevel.net/s3-m3u8/organization-yer/video-jKD0eLGgZ/video-hls3-high.m3u8?Signature=JTcDD~-Wf9zx7e8YU8pCbwZuRKEXzwHrPv8TNIr3MmgKAIN-RpTZrHlrxpkJtiZzdLgygkR3ETAVD7z~u1oG2iUtuhUzioCS1UyJf-LIkPL7H6u~HSWnOEbZyS0Jyrj5CYzCox6l54y82arsp7zVZ-QRYLwr4Urf~cUMtci7kSJ0MzUFttqkpIfohF2k2RGM9vLxhQ-0ibR2NX04bCBDN8sKDtkxIAjek3PWo4GsSN~3RuxpIE-RZE57J65nC7tBSwal5EVCCpAP~TkdeOGeYs1maDXYiFlW8lvfcSSYb5DDZ6Y7JWRW-4t1Wob-S-jQypmR9mfUUXwSciityOYkuA__&Key-Pair-Id=APKAJ5JH3L2ZNI5QDHEQ&Expires=2147483647)

![screen shot 2016-03-17 at 11 22 21 am](https://cloud.githubusercontent.com/assets/1322503/13856545/f1913e2e-ec32-11e5-96e2-b040474bca39.png)

These are the versions we're using:
 - videojs: 5.6.0
 - videojs-contrib-hls: 2.0.0 (Also tried 2.0.1)

It seems that a recent change in mux.js might be causing this. If I manually install mux.js version 2.0.2 before building the plugin, the issue seems to go away. Thanks

**Comment by dmlap** [comment]
Hmm... that is interesting. Seems likely to be related to https://github.com/videojs/mux.js/pull/57 but the exact mechanism isn't clear to me. Thanks for the report!

**Comment by aydinkn** [comment]
I confirm this issue. I upgrade conrtib-hls from 1.3.11 and show up this problem.

**Comment by bachue** [comment]
I found if you disable `Hardware-accelerated video decode` from chrome://flags, this issue wouldn't be existed.

**Comment by forbesjo** [comment]
This was a regression in one of the recent versions of Chrome. The problem is not caused by contrib-hls.

**Comment by aydinkn** [comment]
But, I don't have this problem with contrib-hls 1.3.11 on chrome @forbesjo

**Comment by forbesjo** [comment]
@imbcmdth what are your thoughts?

**Comment by t-n** [comment]
This seems to be fixed with contrib-hls 2.1.1 and mux.js 2.1.2

**Comment by jpfranco** [comment]
@t-n yes, it's working for me too with the latest mux.js
