### ISSUE TITLE
Errors and/or endless buffering IE 11

### ISSUE THREAD

**Issue by jstevens79** [videojs/videojs-contrib-hls#604]
Tested in Windows 7 and 10: In IE 11 on Windows 10, I get Access-Control-Allow-Origin header errors, and CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED. In Windows 7, I just get an nondescript error. (I can access MP4 video files in the directory, so I don't think it's a CORS issue)

The demo page's loader for videojs-contrib-hls just spins endlessly in IE 11 as well... maybe there's a bug for IE?

**Comment by tenacex** [comment]
IE11 is having some issues. We are currently working on patching these up.

**Comment by sonar0007** [comment]
I also get CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED on version 2.0.1
Is there any hope for that issue being fixed in a near future?

**Comment by sonar0007** [comment]
I have get rid of that error on IE 11 using following setup
videojs-contrib-media-sources - version 3.0.1
Video.js  - version 5.8.8
videojs-contrib-hls - version 2.0.1

I have provided 2 sources *.webm and *.m3u8  to video tag
I got that working on chrome/firefox/safari/IE/Edge(checked only newest versions)

**Comment by GarethMobey** [comment]
Hello Lukas-wojcik,

Could you please give a brief explanation of what you did.  Struggling with the same issue at the moment.

Many thanks

**Comment by lukasz-wojcik** [comment]
I have used all abovementioned libs in those exact versions(did not check newer versions if there are any)
In my view I have placed html that looks like this:

```html
<video id="my_id">
  <source src="http://link.to.video.m3u8" type="application/x-mpegURL"/>
  <source src="http://link.to.video.webm" type="video/webm"/>
  <source src="http://link.to.video.mp4" type="video/mp4"/>
</video>
```

**Comment by GarethMobey** [comment]
Thank you very much.
