### ISSUE TITLE
Can't play m3u8 with EXT-X-DISCONTINUITY

### ISSUE THREAD

**Issue by waster** [videojs/videojs-contrib-hls#606]
Hello,

I tried to test m3u8 with discontinuity tag but it can not be played with Firefox (Chrome plays it well) with html5 tech that is default for Firefox 45 in Ubuntu 15.10. It stops with the following message in console: "The media playback was aborted due to a corruption problem or because the media used features your browser did not support". 

[Here](http://hlsserverdev.hostingradio.ru:8080/audio/test-discont-vjs.html) is the example.

**Comment by gesinger** [comment]
Hey @waster , sorry this ticket has gone a long time without much attention.

I saw that the URL is no longer up, but would you be able to give the latest version (as of this comment, v4.1.1) a shot? If it's still a problem, would you be able to re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/edit?html,output)?

Thank you again for reporting the issue.
