### ISSUE TITLE
Cookies are not sent with manifest file requests

### ISSUE THREAD

**Issue by scaryguy** [videojs/videojs-contrib-hls#607]
This issue is very similar to https://github.com/videojs/videojs-contrib-hls/issues/481 , however, It's not a 'branch' bug I guess. It's simply not working. The example on the README file does not work either. Once the source URL is a third party URL, even though all headers are set properly. `Access-Control-Allow-Credentials:true` is set and also `Access-Control-Allow-Origin` is set too. There is no problem with accessing the manifest files. But cookies are not sent with the request.

Isn't this a bug?

**Comment by gkatsev** [comment]
Are you setting the `withCredentials` option when initializing videojs?

**Comment by scaryguy** [comment]
Sure, I do. Here is how I instantiate the videojs object:

```javascript
var player = videojs('example-video', {hls: {withCredentials: true}}, function() {
this.play();	
});
```

**Comment by scaryguy** [comment]
Any ideas?

**Comment by gkatsev** [comment]
It's either the same issue as #481 or something new. Will you be able provide a reduced test case/m3u8 url?

**Comment by elmehdielkettani** [comment]
Facing the same issue. 'withCredentials' does not seem to work for me either.

**Comment by stoicbuddha** [comment]
I'm also having the same issue now.  Are there any updates for this?

**Comment by stoicbuddha** [comment]
@will3216 That's not the same issue. This is what happens when it doesn't send things with the manifest files.
![image](https://cloud.githubusercontent.com/assets/18359863/21736675/3d0adebe-d427-11e6-840a-eef05277bdd4.png)

**Comment by will3216** [comment]
@stoicbuddha Yeah, I was mistaken. I found the issue I was having: I had npm installed the wrong video-contrib-hls package

**Comment by gesinger** [comment]
Sorry this ticket has gone a long time without much attention. Judging from the example provided, it looks like the problem was the options that were passed. In the example provided, the options are set to `{hls: {withCredentials: true}}`, however, the option should be inside of the tech, i.e., `{html5: {hls: {withCredentials: true}}}`. Please give it a shot and let us know if you're still seeing issues with the latest version of videojs-contrib-hls (as of this comment, v5.4.1). Thank you.

**Comment by stoicbuddha** [comment]
I'm still having this issue as of videojs-contrib-hls v5.10.1

I instantiate the player like so:
`videojs(opts.videotagid, {
				"controls": !opts.disablecontrolbar,
				"autoplay": false,
				"preload": opts.preload,
				"poster": '',
				"loop": opts.loopplayback,
				"html5":
					{
						hls: {
							withCredentials: true
						}
					}
			}, function() { ...
`

**Comment by stoicbuddha** [comment]
It seems to be fine in Chrome (haven't tried FF yet), but fails in Safari 11.
