### ISSUE TITLE
no compatible source was found for this video using IE8

### ISSUE THREAD

**Issue by winterfellzone** [videojs/videojs-contrib-hls#609]
Hi there,
I'm using videojs-contrib-hls with Video.js and it's IE8 Fallback.
When trying to playback a m3u8 manifest, im getting an error:
"no compatible source was found for this video".
This error only occures when using IE8, when using Chrome the video is played just fine.
BTW, The stream is working just fine when using VLC as well.
Thanks in advance,
Johnny.

**Comment by dmlap** [comment]
This project only supports IE>=10. IE8 is just too slow to be able to play back HLS content acceptably on reasonable hardware. I'd suggest including an mp4 as a fallback source for IE8.
