### ISSUE TITLE
A Question Regarding HLS Manual bitrate switching

### ISSUE THREAD

**Issue by winterfellzone** [videojs/videojs-contrib-hls#610]
Hi,
I was able to play my m3u8 manifest, which contains 4 renditions.
I'd like the player to do Adaptive Bit Rate, as it currently does, but i'd like to have also the option to choose manualy which bitrate i'd like to play.
Is it possible? and how? perhaps through the use of an API?
Thanks in advance !

**Comment by tenacex** [comment]
I believe you can accomplish what you are trying to do by using: https://github.com/videojs/videojs-contrib-hls#hlsselectplaylist
