### ISSUE TITLE
Too many playlist.m3u8 requests

### ISSUE THREAD

**Issue by halibegic** [videojs/videojs-contrib-hls#611]
Hi,

I'm just wondering if someone can confirm that this behavior is ok, because plugin is requesting playlist.m3u8  10 times in a row?

Log:
![list](https://cloud.githubusercontent.com/assets/3328291/13980937/77d813ec-f0e1-11e5-9e53-5b610ed4c58b.png)

Response:
![details](https://cloud.githubusercontent.com/assets/3328291/13980943/79dcadd8-f0e1-11e5-8254-4e6b298fd92d.png)

**Comment by gkatsev** [comment]
Do they download 10 times in a row immediately without any wait between them?

**Comment by halibegic** [comment]
Yes

**Comment by forbesjo** [comment]
Could you provide a reduced test case?

**Comment by halibegic** [comment]
Thank you for your reply.
Plugin was working correctly for the past two days and I don't know what caused this problem.
Maybe I have some network issue or something like that but if it's occurs again I will provide you demo link.

Thank you.

**Comment by forbesjo** [comment]
Thanks for the quick reply, I'll close this issue for now and it can be reopened when necessary.
