### ISSUE TITLE
playing m3u8 ,stop playing when random time

### ISSUE THREAD

**Issue by y284663247** [videojs/videojs-contrib-hls#613]
playing m3u8 ,stop playing when random time,any time after  ,the video is stop to play,skip the time is ok,

**Comment by y284663247** [comment]
in chrome browser, the question happened,

**Comment by billybobilly** [comment]
related?  #650

**Comment by gesinger** [comment]
Sorry this ticket has gone a long time without much attention. We've made a lot of changes to videojs-contrib-hls in the meantime. Would you be able to give the latest version (as of this comment, v4.1.1) a shot? If it's still a problem, would you be able to re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/edit?html,output)?

Thank you again for reporting the issue.
