### ISSUE TITLE
Firefox selects HLS file but can't play it

### ISSUE THREAD

**Issue by webcast33** [videojs/videojs-contrib-hls#620]
I am running Firefox 45 without Flash. The "application/x-mpegURL" source precedes the "video/mp4" source. Firefox selects the HLS stream, plays it fine for about 10 seconds, then speeds through the video (fast motion) for about 2 seconds, and then just spins. No errors on the console; the network display shows no gets after the 4th chunk.

So it appears that this version of Firefox cannot support HLS without Flash. Should it not then skip the HLS source and select the progressive download source? Any work-around for this?

By the way, in my tests of IE 11 with Flash, the HLS file was streamed through the Flash Player, but the video was choppy and there were long seek times.

On the other hand, Chrome handles HLS streams beautifully.

Thanks very much.

**Comment by gkatsev** [comment]
What versions of videojs and contrib-hls are you using? Also, what OS are you running this on?
Currently, contrib-hls (and actually videojs) isn't smart enough to switch from one tech to another when there's a playback error, so, if it detects that HLS+MSE is supported, it tries to play that.

**Comment by webcast33** [comment]
gkatsev,
Thanks for answering. I'm using video.js 5.8.0 and video-contrib-hls.js 2.0.1. My tests were run on a Windows 7 machine.

**Comment by webcast33** [comment]
I just wanted to mention that my Firefox problems occur in version 45, which I believe should support HLS through the MSE. As I reported, when I tried to stream an on-demand file from our CDN using the current versions - video.min.js (v 5.8.0) and videojs-contrib-hls.min.js (v2.0.1) - I experience the odd effect of the video speeding up after 8-10 seconds and then freezing (with a spinner). But when I fall back to older versions - video.js (v 5.4.6 ) and videojs.hls.min.js (v 1.3.1) - it works much better: no speed-up and no freezing, though there is a slight, but noticeable, pause in the video (not audio) each time a new fragment is transferred from our CDN.

**Comment by gesinger** [comment]
Hey @webcast33 , sorry this ticket has gone a long time without much attention. We've made a lot of changes to videojs-contrib-hls in the meantime. Would you be able to give the latest version (as of this comment, v4.1.1) a shot? If it's still a problem, would you be able to provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output)?

Thank you for reporting the issue.

**Comment by gesinger** [comment]
Closing for now. If you are still experiencing this issue with the latest version of videojs-contrib-hls (as of this comment, v5.0.0), please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.
