### ISSUE TITLE
Adaptive bitrate selection doesn't work in fullscreen (Chrome)

### ISSUE THREAD

**Issue by drizzt** [videojs/videojs-contrib-hls#621]
When I go to fullscreen and so my resolution change the stream is not switched to a "better" one

**Comment by dmlap** [comment]
Right now, we don't throw away any buffered content when you move to fullscreen. With our standard buffering settings, that means it can take up to 30 seconds for the player to adapt to the new dimensions.

**Comment by dmlap** [comment]
We could remove some portion of the buffer (currentTime + 5 seconds, say?) on the fullscreen transition to force a quicker upswitch. The downside of that approach is we risk stalling if the network happens to dip in performance right then.

**Comment by gesinger** [comment]
This was since released as part of #659 . While the timing has changed slightly for fastQualityChange_ since that release, this should switch faster than when first reported.

Thank you again for reporting @drizzt .
