### ISSUE TITLE
Playing encrypted m3u8's

### ISSUE THREAD

**Issue by sevagsim** [videojs/videojs-contrib-hls#627]
I don't see a way to play encrypted m3u8's using FairPlay in this repo, is there something I'm missing or is there a plugin to do that?

**Comment by imbcmdth** [comment]
Fairplay encryption is not supported yet but is something we are planning on adding support for at some point in the near future. If this is something you decide to add yourself, we welcome any contributions!

**Comment by sevagsim** [comment]
Thanks!
