### ISSUE TITLE
Chrome not downloading new chunks

### ISSUE THREAD

**Issue by justinoue** [videojs/videojs-contrib-hls#631]
I'm using the latest version of video.js (5.8.7) and videojs-contrib-hls (2.0.1), and Chrome 48 on Ubuntu 14.04. Chrome seems to download the first 5 chunks almost immediately, and then that's it. Playback just stops. It is consistent with every video I have tried.

Firefox is working fine for reference (as does JWPlayer).

**Comment by jlwuleo** [comment]
~ ~, I have encountered the same problem today, you can play properly on the IE11 browser, will not stop, waiting line

**Comment by billybobilly** [comment]
related? #650

**Comment by dmlap** [comment]
Do you have a link to an example stream?
