### ISSUE TITLE
Seek bar not selectable for hls on android

### ISSUE THREAD

**Issue by alouane** [videojs/videojs-contrib-hls#634]
Is there a way to force use of videojs hls plugin on Android instead of native HLS of Android devices?

**Comment by dmlap** [comment]
Not today. It would be a cool addition if you're interested in contributing!

**Comment by gesinger** [comment]
This has since been added. You can override native playback using `videojs.options.hls.overrideNative = true` (or by setting `overrideNative` to `true` as part of the hls options). Thanks for reporting the issue @alouane
