### ISSUE TITLE
Using videojs-contrib-hls with browserify

### ISSUE THREAD

**Issue by alexchern** [videojs/videojs-contrib-hls#636]
Hi guys, 

A novice question. 

I've been using videojs player for some time:
var videojs = require('video.js');

Now, I'd like to add hls support, so, I'm doing this:
videojs.Hls = require('videojs-contrib-hls');

    ...
                videojsPlayer.src({
                    src: "http://localhost:8080/videos/index.m3u8",
                    type: 'application/x-mpegURL'
                });
                videojsPlayer.play();

Am I doing something wrong? I get 
"Cannot read property 'EventTarget' of undefined" in my player. If I remove videojs.Hls = require('videojs-contrib-hls'); the player works (not with hls, of course)

So, it looks exactly like the previously reported (#635) issue.

Thanks,

Alex

**Comment by gkatsev** [comment]
You actually don't need to `videojs.Hls = require(...)`, when you require `videojs-contrib-hls`, it binds itself to videojs.
Are you requiring it directly or using the `dist` file?

**Comment by alexchern** [comment]
Hi Gary, thanks for your help. 

I tried to replace videojs.Hls = require(...) with just require('videojs-contrib-hls'); but it didn't help.
How should I do this? Sorry for the novice questions...

Thanks,

Alex

**Comment by gkatsev** [comment]
I think one of the issues is that we always shim videojs into the build, we should fix that.
As a workaround, you could do something like this:
```js
var videojs = require('video.js');
window.videojs = videojs;
require('videojs-contrib-hls');
```
When we fix the issue, you should be able to omit line 2.

**Comment by alexchern** [comment]
Hi Gary,

Yep, that worked! It also solved my other problem with playlist plugin.

Thanks a lot,

Alex

**Comment by gkatsev** [comment]
Ah, cool, didn't realize it was the same issue. I'll try and go through out plugins and update the build process this week.

**Comment by aydinkn** [comment]
Hi, this method didn't work for me.
```
const videojs = global.videojs = require('video.js');
require('videojs-contrib-hls');
```
I've got this error:
Uncaught TypeError: Cannot read property 'xhr' of undefined
```
// request the specified URL
    request = this.hls_.xhr({
      uri: srcUrl,
      withCredentials: withCredentials
    }, function (error, req) {
    .....
```

**Comment by aydinkn** [comment]
I found my problem. When i fetch master playlist for quality switcher:
```
let loader = new videojs.Hls.PlaylistLoader(playlistSource);
loader.on('loadedplaylist', function () {
        // Fetch quality for quality switcher
```
I got this error.

**Comment by nehakhandelwal** [comment]
Hi I have done code like below:
html : 
<video id="really-cool-video" className="video-js vjs-default-skin" preload controls width="600" height="300">
            </video>

JS: 
import video from 'videojs-contrib-hls';
import videojs from "video.js";
window.videojs = videojs;

let player = videojs("really-cool-video", {html5: {
     hls: {
     withCredentials: false}}});

 player.src({
     src: "http://clips.vorwaerts-gmbh.de/big_buck_bunny.webm",
     type: 'video/webm'
     });
 let hls = player.tech({ IWillNotUseThisInPlugins: true }).hls;
palyer.play();


and this hls is coming undefined.

me too have the same issue and apply all things u have suggested. still facing same issue.Please suggest.

**Comment by gkatsev** [comment]
@nehakhandelwal what browser are you running this on? How are you compiling and bundling your javascript?

**Comment by nehakhandelwal** [comment]
browser is mozila and chrome

**Comment by ducdigital** [comment]
FYI This should work for webpack. `window.videojs` did not work for me here
```
global.videojs = videojs;
require('./dist/videojs-contrib-media-sources.js');
```

**Comment by asokani** [comment]
Either method didn't work for me - Webpack2

Just add this to your `webpack.config`:

```
new webpack.ProvidePlugin({
    'window.videojs': 'video.js/dist/video.min',
}),
```

and replace `const videojs = require('video.js');` with `const videojs = window.videojs;`. That workaround works for me.

**Comment by hungsama** [comment]
I'm using for React create webapp for WebOs LG an Samsung Tizen.
I had been run build on chrome and firefox browser, it's OK !
Hower, when run on webOs and Tizen will appear error : 
"VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. 
MediaError"
Please, help me !

This code here: 
----------------------------------------------------------------------------------------------------------------
import React from 'react'
import video from 'videojs-contrib-hls';
import videojs from "video.js";
window.videojs = videojs;

class PlayerStream extends React.Component {

  componentDidMount() {
   let player = videojs("really-cool-video", {
    html5: {
      hls: {
        withCredentials: false
      }
    }
   });

   player.src({
     src: "http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8",
     type: 'application/x-mpegURL'
   });
    player.play();
  }
  render() {
    return <div style={{color:"red"}}>
```
    <video id="really-cool-video" controls>
    </video>
```
    </div>
  }
}
export default PlayerStream

**Comment by Hoshinokoe** [comment]
Provided solution doesn't work for me. 
`var videojs = require('video.js');
window.videojs = videojs;
require('videojs-contrib-hls');`

All require modules combined into one single file and videojs-contrib-hls fails after load:

Uncaught TypeError: Cannot read property 'EventTarget' of undefined
    at Object.<anonymous> (BC8B1AB3F6A7B6D221C89543E59CDE21.js:sourcemap:2739)
    at Object.n.9 (BC8B1AB3F6A7B6D221C89543E59CDE21.js:sourcemap:2739)
    at r (BC8B1AB3F6A7B6D221C89543E59CDE21.js:sourcemap:2738)
    at BC8B1AB3F6A7B6D221C89543E59CDE21.js:sourcemap:2738
    at Object.<anonymous> (BC8B1AB3F6A7B6D221C89543E59CDE21.js:sourcemap:2744)
    at Object.n.77 (BC8B1AB3F6A7B6D221C89543E59CDE21.js:sourcemap:2745)
    at r (BC8B1AB3F6A7B6D221C89543E59CDE21.js:sourcemap:2738)
    at e (BC8B1AB3F6A7B6D221C89543E59CDE21.js:sourcemap:2738)
    at BC8B1AB3F6A7B6D221C89543E59CDE21.js:sourcemap:2738`

As result it breaks whole app.
@gkatsev please think about any possible workaround.

**Comment by RobertLowe** [comment]
@Hoshinokoe same issue, in `meteor.js` (if that's what you're using), I had to put, `video.js`, `videojs-flash.js`, `videojs-contrib-hls.js` into the `compatibility` folder which is essentially loading libs in `<head>` rather then having `babel `/`meteor` concat them... So try just loading them in `<head>` 😞 

pls fix, lost ~3 hours
