### ISSUE TITLE
dist code missing from v2.1.x releases

### ISSUE THREAD

**Issue by thenewguy** [videojs/videojs-contrib-hls#640]
Same issue as https://github.com/videojs/videojs-contrib-hls/issues/330

releases for v2.1.1, v2.1.0, and v1.3.9-0 do not contain the `videojs-contrib-hls.js` or `videojs-contrib-hls.min.js` files

**Comment by thenewguy** [comment]
Perhaps it would be helpful in this situation if there was a brief howto in the readme to go over building the project when this happens

**Comment by forbesjo** [comment]
This is fixed, closing
