### ISSUE TITLE
videojs.Hls.xhr.beforeRequest has no effect

### ISSUE THREAD

**Issue by cambeyer** [videojs/videojs-contrib-hls#656]
Chrome v49, latest videojs & videojs-contrib-hls:

videojs.Hls.xhr.beforeRequest = function(options) {
  /*
   * Modifications to requests that will affect every player.
   */
  return options;
};

The function is never called.  I am expecting this to be called before each new segment is downloaded, with options.uri showing the intended *.ts.  Am I mistaken about the usage of this function?  I don't have another browser readily available to test as I am developing on a Chromebook.

**Comment by powrsurg** [comment]
By latest do you mean you pulled from source, or the latest distribution. There was a bug in this and it was fixed 19 days ago.

**Comment by apatinoyu** [comment]
Hello @cambeyer, did you make it work? because I made it work but I had new issues on Safari and Edge, here the new issue -  [Issue](https://github.com/videojs/videojs-contrib-hls/issues/949)
Thanks.

**Comment by cambeyer** [comment]
@apatinoyu I was able to make it work after I pulled from source per @powrsurg's suggestion.  I haven't had need for this functionality recently and have only ever tried it in Chrome, never Safari or Edge.
