### ISSUE TITLE
beforeRequest resets options

### ISSUE THREAD

**Issue by powrsurg** [videojs/videojs-contrib-hls#657]
The newly committed beforeRequest function will reset any options that were previously set. Ideally it should instead merge with existing options so that the results of beforeRequest take precedence.

**Comment by gesinger** [comment]
@powrsurg , it looks like the beforeRequest function will allow a user to modify the options then return the resultant options object (or return the options object without any change). Were you seeing otherwise?

**Comment by powrsurg** [comment]
@gesinger, beforeRequest [replaces existing options](https://github.com/videojs/videojs-contrib-hls/blob/master/src/xhr.js#L28). I believe that it should instead call mergeOptions to merge the existing options, with the options from beforeRequest overriding the existing options. Ideally I feel the code would be beter with:
`      if (newOptions) {
        options = mergeOptions(options, newOptions);
}`

**Comment by gesinger** [comment]
You're right that it does replace options.

The recommended use of it though is to simply modify/remove/add the options that are needed: https://github.com/videojs/videojs-contrib-hls#hlsxhr

I think both accomplish the same goal, it just depends on how you want the API to look. Merging allows a user to return a separate object that gets merged in vs current functionality which allows a user to modify the object in-place.

**Comment by gesinger** [comment]
@imbcmdth what do you think of using a merge instead of replacing?

**Comment by powrsurg** [comment]
@gesinger, this is going back a number of months where I am not working on that aspect of the project right now, but I believe the issue I had experienced was that the default timeout that is added a few lines prior was being lost since it was being replaced. I had to update my function to ensure that a timeout was set.

**Comment by gesinger** [comment]
Thanks for reporting, and for the recommendation of using a merge. We may end up adding that as an enhancement, so that the API can be used in either way, but I gave the API a test as-is, and so long as the options are read/modified from and returned in the beforeRequest function, they persist and are used.
