### ISSUE TITLE
Android HLS fails when cookies are required

### ISSUE THREAD

**Issue by powrsurg** [videojs/videojs-contrib-hls#660]
Browsing the Android issue tracker shows that it does not send cookies with their native HLS implementation. This is better expressed in issue https://code.google.com/p/android/issues/detail?id=79866 in their bug tracker (though they mark it as a duplicate of https://code.google.com/p/android/issues/detail?id=17553, though I don't believe it actually is).

As such, all videos that require withCredentials in order to play will fail on Android.

**Comment by dmlap** [comment]
Currently, we let native HLS implementations take over if they're available. It seems reasonable to add some option to use contrib-HLS even when a native implementation is available, though. Interested in trying to write a PR for that?

**Comment by powrsurg** [comment]
I was literally just starting to write a bug report for the main videojs library because this issue occurs there too for non-HLS content. On Android every request that needs withCredentials will fail because the native playback function does not send cookie data with it. The only way for a site to deliver content that requires cookies is for Html5.nativeSourceHandler.canPlayType, Html5.nativeSourceHandler.canHandleSource, and videojs.HlsSourceHandler.canPlayType to detect Android requests that need withCredentials and prevent them from return a successful criteria.

I have currently figured out how to detect Android, but have not yet determined how to detect the specific player for the given request that is being tested. Once I do that I will submit a pull request to patch such.

**Comment by powrsurg** [comment]
It was just pointed out to me that I have been mistaken on this. Applying crossorigin="use-credentials" fixed this for me.
