### ISSUE TITLE
How to embed m3u8 Stream?

### ISSUE THREAD

**Issue by rickymartinss** [videojs/videojs-contrib-hls#663]
Hi , any one knows how can we embed m3u8 stream on our own website with iframe code? as i have seen a site onhockey [dot] tv he is using m3u8 streams on his site with iframe code. i have searched over internet alot but didnt find my answer. please help me out as i will be highly appreciated

Thanks n regards
Umar

**Comment by gesinger** [comment]
Hey @rickymartinss , sorry this issue has gone a long time without much attention.

If you take a look at http://output.jsbin.com/bisajo , I created a sample page with an iframe referencing  our example template http://jsbin.com/vokipos/8/edit?html,output to play an m3u8 file using Video.js and videojs-contrib-hls. You can see the code for the iframe at http://jsbin.com/bisajo/edit?html and the template above for the page it is referencing. Hope this helps!
