### ISSUE TITLE
Win 8.1 IE11 PRoblem

### ISSUE THREAD

**Issue by serhatcelep** [videojs/videojs-contrib-hls#667]
It doesn't work Win 8.1 IE11 browser. Did you test this platform?

![image](https://cloud.githubusercontent.com/assets/5413103/14783681/e8ba5ebc-0af9-11e6-92de-6e9721f560c8.png)

**Comment by dmlap** [comment]
We have but we see a lot of differentiation between MSE behavior within IE11 that we still don't understand. On some machines, things works great and on others MSE doesn't work at all. The current theory is Windows updates to the underlying media libraries affect MSE support in IE and it's not clear what is installed where.

**Comment by dmlap** [comment]
As a workaround, you can force Flash-based HLS on IE11 if too much of your audience seems to be encountering it.
