### ISSUE TITLE
Video.js plays hls video too fast on firefox

### ISSUE THREAD

**Issue by mayanksriv** [videojs/videojs-contrib-hls#669]
Trying to run Videojs sample on different browsers to check compatibility with HLS (stream-url: http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8)

This below code works fine on chrome and IE, but the video runs too fast on firefox(v45) on Windows7 OS.

using video.js (v5.8.8) and videojs-contrib-hls (v2.0.1)

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>test</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="node_modules/video.js/dist/video-js.css" rel="stylesheet">
    <script src="node_modules/video.js/dist/video.js"></script>
    <script src="videojs-contrib-hls.js"></script>
  </head>
  <body>
    <video id="my-video" class="video-js" controls preload="auto" width="640" height="264" data-setup='{}'>
    <source src="http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8" type='application/x-mpegURL'>
    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a web browser that
      <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
  </video>
  <script>
    var player = videojs('my-video');
    player.play();
  </script>
  </body>
</html>
```

Originally opened issue here:
https://github.com/videojs/video.js/issues/3279#issuecomment-214419779

But as per comments, moving it against [videojs-contrib-hls](https://github.com/videojs/videojs-contrib-hls) here.

**Comment by afulist** [comment]
Similar issue to me. But v2.0.0 work fine.

**Comment by mayanksriv** [comment]
Used v2.0.0. Video didn't start for me. I had to scribe on the progress bar to start the video and then it played ok.

**Comment by cdhowie** [comment]
We are having the same issue on v2.0.1.  The first chunk plays fine, but in the next chunk the video plays super fast while the audio does not, and it plays through the next chunks so fast that it has to stop to buffer.

This only seems to happen in Firefox, and only on Windows (tested both 7 and 10) -- I do not have the issue at all on OS X.

**Comment by philhq** [comment]
Same issue here on FF windows.

**Comment by forbesjo** [comment]
I'm unable to reproduce this issue, if it's still happening for others please link a source (or a video of the video playing too fast)
