### ISSUE TITLE
Can this amazing plugin support ie <= 9 by using flash ?

### ISSUE THREAD

**Issue by victoryboss** [videojs/videojs-contrib-hls#677]
Thank you for developing this amazing plugin. But it does not work when ie <= 9.Can you support these boring ie9/ie8 use flash like this videojs flash plugin.(url: https://github.com/mangui/flashls ) .

**Comment by gkatsev** [comment]
Unfortunately, this plugin can't really support older IE than 10 because most of the work happens in javascript and two big things that we depend on (TypedArrays and CORS) don't really work properly in those browsers or the available shims are too slow to be practical for this usecase.
