### ISSUE TITLE
Only audio plays (player displays black background) on Firefox

### ISSUE THREAD

**Issue by jpfranco** [videojs/videojs-contrib-hls#679]
I've only seen this issue on two sources so far, so it seems like an edge case triggered by something particular about these:

https://authproxy-p1.gbox.com/s3-m3u8/organization-gboxprod1/video-Bko3W8L-/video-hls3-preview.m3u8

https://authproxy-p1.gbox.com/s3-m3u8/organization-gboxprod1/video-r1cx1WHZ/video-hls3-preview.m3u8

videojs: 5.9.2
videojs-contrib-hls: 2.0.1

This was seen on Firefox 45.0.2 for Mac. The sources are played correctly on Chrome and Safari. If you seek to another point in the video the problem will go away, so this is only seen on the first playthrough. Thanks

**Comment by gesinger** [comment]
Hey @jpfranco , sorry this issue has gone a long time without much attention.

I know Firefox 45 is long past, but I gave it a try with the latest versions of Video.js and videojs-contrib-hls and it works with Firefox 50.1.0. If you are still seeing this issue, please re-open the ticket and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output)? Thank you!
