### ISSUE TITLE
Live HLS Wowza stream freezing in Chrome/Firebox on latest versions (but not IE or Android)

### ISSUE THREAD

**Issue by gak2** [videojs/videojs-contrib-hls#691]
Hi,

I am really struggling with this issue of a live HLS stream from Wowza freezing after 10 seconds in Chrome/Firefox. I have tried all combinations of videojs 5.2.0 » 5.10.1, and videojs.hls 1.2.0 » 2.2.0, to no avail. It does stream fine to Android though, so I don't think Wowza setup is the problem.

On both Chrome and Firefox, it looks as though the media blocks run into a loop ...

media_w1438989202_52.ts media_w1438989202_53.ts media_w1438989202_54.ts media_w1438989202_53.ts media_w1438989202_54.ts media_w1438989202_53.ts

... after 10secs this fails and the browser goes into an endless request for the same media_xxxxxx.ts chunklist. Result is: video stops dead in Chrome, and on Firefox goes into eternal loading-circle.

Bizarrely, it will keep playing in IE, where is seems to alternate loading .m3u8, .ts, .m3u8, .ts, .m3u8 ... it would be great if I could even see a link where someone has this working correctly?

Thanks - all help greatly appreciated :)

**Comment by dmlap** [comment]
We have this sort of thing reported from time to time and it is typically something weird in the TS segments. We can't fix it without an example TS, though. Can you capture one of the segments that are getting downloaded in a loop and attach it to this issue?

**Comment by gak2** [comment]
Hi @dmlap thanks for getting back to me!

I suspect you're right: after some digging, it looks like the video source [_Vahana » Wowza_] is somehow corrupting the **Audio** stream.  Looks like there might be missing audio samples.  So I'm attempting to resolve this at the source first .. then I'll come back here to confirm!

Thanks again - watch this space ..

**Comment by forbesjo** [comment]
Please reopen if filling in the missing audio samples didn't work.
