### ISSUE TITLE
Video buffer and start playing time

### ISSUE THREAD

**Issue by erbing** [videojs/videojs-contrib-hls#693]
The beginning of the video buffer after the end of the video playback time will add the default buffer it for a few seconds

**Comment by gesinger** [comment]
Hey @erbing , sorry this ticket has gone a long time without much attention. We've made a lot of changes to videojs-contrib-hls in the meantime. Would you be able to give the latest version (as of this comment, v4.1.1) a shot? If it's still a problem, would you be able to re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output)?

Thank you for reporting the issue.
