### ISSUE TITLE
Gruntfile is missing? 

### ISSUE THREAD

**Issue by HankBrown** [videojs/videojs-contrib-hls#694]
Thanks to all.

I'm unable to continue because I need to add some args to the uri and the docs are obsolete.

MY REAL ISSUE:
Here is where I am stuck: https://github.com/videojs/videojs-contrib-hls/issues/542

So to find my way around the source I tried for a basic clone.

CURRENT ISSUE: Gruntfile.js is missing?

POSSIBLY RELATED ISSUE: https://github.com/videojs/videojs-contrib-hls/issues/692

A few other issues that I do not think matter, but I include a summary below.

(1)
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN prefer global marked@0.3.5 should be installed with -g

(2)
{ Error: ENOENT: no such file or directory, unlink '/Users/brownhanky/Projects/VIDEOJSHLS/test/test-manifests.js'
{ Error: ENOENT: no such file or directory, unlink '/Users/brownhanky/Projects/VIDEOJSHLS/test/test-expected.js'
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',

(3)
uglifyjs dist/videojs-contrib-hls.js --comments --mangle --compress -o dist/videojs-contrib-hls.min.js
WARN: Dropping unused variable receivedTimeStamp [dist/videojs-contrib-hls.js:4990,4]
WARN: Dropping unused variable numFrames [dist/videojs-contrib-hls.js:5161,6]
(+ many more)

(4)
Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started

book15:VIDEOJSHLS brownhanky$ find . -name grunt.*
./node_modules/base64-arraybuffer/grunt.js
./node_modules/videojs-contrib-media-sources/node_modules/videojs-font/lib/grunt.js
./node_modules/videojs-font/lib/grunt.js
./node_modules/videojs-ie8/grunt.js

Here I cut and pasted a suggested solution from SO.

(5)
book15:VIDEOJSHLS brownhanky$ npm install grunt --save-dev
...lots of npm messages)...
bower                           ENOENT No bower.json present

**Comment by gkatsev** [comment]
Yeah, the CONTRIBUTING.md is completely out of date. We don't use grunt anymore.
Everything is done through npm scripts, an overview can be found here: https://github.com/videojs/generator-videojs-plugin/blob/master/docs/standards.md#automation
The tl;dr is that you can run `npm run build` to contrib-hls, `npm test` to run the tests. Also, `npm start` will set up a watcher that re-builds contrib-hls while also running a local web server that serves up the project directory.
The npm and uglify warnings shoudn't be an issue.
Hope that helps.

**Comment by HankBrown** [comment]
Thank you for a prompt an helpful answer.
