### ISSUE TITLE
Incorrect Keyframe when seeking / looping

### ISSUE THREAD

**Issue by ptrwtts** [videojs/videojs-contrib-hls#695]
We are creating an application that lets you "trim" within a HLS playlist. When you trim, it loops the video between the markers you set, by seeking back to the start point.

However, if the seek point is midway between two keyframes, it will continue using an old keyframe (from further along in the video), until it reaches a new keyframe, causing artifacting. Here's a video showing this happen: 

https://youtu.be/vG7lWj00rJc

Is there any way to avoid this? The ideal behaviour is that after seeking, it immediately uses the correct keyframe, rather than waiting to reach a new one (excuse my noob understanding of how keyframes work). 

This issue doesn't occur on iOS / Android where we use native HLS playback / ExoPlayer, so it would seem to be related to VideoJS or the browser implementations (my testing was in Chrome).

**Comment by gkatsev** [comment]
What version of contrib-hls are you using? Also, what versions of Chrome and on what OS were you testing with? Also, can you please provide a [reduced test case](https://css-tricks.com/reduced-test-cases/)? It would make it a lot easier for us to reproduce the issue you are experiencing and thus fixing it.
Thanks.

**Comment by ptrwtts** [comment]
So while creating a reduced test case, I discovered that 2.1.1 actually fixes the issue. We were using 2.0.1 on our site. Is this stable, or should we hold out a little longer for a stable 2.1? Thanks!

**Comment by gkatsev** [comment]
You should be able to use 2.1.1 if it fixes the issue for you.

**Comment by ptrwtts** [comment]
Cheers
