### ISSUE TITLE
Playing .ts files directly

### ISSUE THREAD

**Issue by icruces** [videojs/videojs-contrib-hls#696]
Hi,

Is it possible (or easy to implement) to play .ts files in videojs with this plugin. 

Basically, I have a repository of .ts files (video/mp2t) that I need to play in a web application, but I don't have m3u8 files. I can play them in Safari, but not in other browsers.

Thanks.

**Comment by dmlap** [comment]
We don't have plans to support raw TS playback in this repo. You could probably build something yourself with [mux.js](https://github.com/videojs/mux.js). If you do, please let us know!
