### ISSUE TITLE
player.hls is deprecated warning

### ISSUE THREAD

**Issue by pedromcunha** [videojs/videojs-contrib-hls#698]
Originally posted in this [issue](https://github.com/videojs/video.js/issues/3318#issuecomment-218797478)

Hey all, thanks for creating this great library. I'm currently playing hls video and every time I try to access the tech via this function:

var playlist = e.tech({
   IWillNotUseThisInPlugins: true
}).hls.playlists.media();
I receive a warning that looks like this:
VIDEOJS: WARN: player.hls is deprecated. Use player.tech.hls instead.

Is there a different way that I should be accessing the tech? I tried to do tech.hls but it results in undefined.

**Comment by BrandonOCasey** [comment]
I think that I fixed this in a more recent version of HLS, what version are you currently using?

**Comment by pedromcunha** [comment]
We're currently using version 2.1.1, was there a new version released?

**Comment by BrandonOCasey** [comment]
2.2.0 was recently released with a fix but a few other things as well. You will need to use video.js 5.10.1+ to use 2.2.0

**Comment by BrandonOCasey** [comment]
Did 2.2.0 resolve your issue?

**Comment by chnl** [comment]
it isn't resolved v.3.5.3 in combination with v5.11.6

**Comment by chnl** [comment]
this solved it for me however... 
var hls = player.tech({ IWillNotUseThisInPlugins: true }).hls;

**Comment by BrandonOCasey** [comment]
OK awesome! I am going to close the issue, if there are any other issues related to this feel free to comment or re-open
