### ISSUE TITLE
Adaptive bitrate switching issue with contrib-hls v2.2.0

### ISSUE THREAD

**Issue by vineetphillips** [videojs/videojs-contrib-hls#699]
In reference to the reduced test case provided below, The video has 4 bitrate variants (300 kbps, 600 kbps, 1 mbps and 2 mbps). It starts out fine selecting the highest bitrate variant which is around 2 mbps (optimal for my bandwidth). When I throttle the network to around 450 kbps, it rightly selects the lowest variant available at around 300 kbps. The issue occurs when I disable throttling. The desired effect would be that the stream will gradually go back up to 2 mbps. However that is not the case, it stays at 300 mbps or very rarely sometimes goes one level up to 600 kbps, but never back to the highest. I did not observe this in the previous stable release of the plugin.
The perplexing part is that selectPlaylist() is returning the right variant each time, but it is not being used.

Reduced test case:
http://clinton.njedge.net/gumbly3/videojs/reduced-test-case-hls-220.php

**Comment by imbcmdth** [comment]
Thank you for the test case! This is definitely an issue and we will be working on a fix. Stay tuned.

**Comment by vineetphillips** [comment]
Thanks! 
it seems to be an issue with SegmentLoader not having the updated playlist, if the playlist has been loaded previously. 
Right now, triggering "loadedplaylist" on media change to a fully loaded playlists seems to have fixed it for me. But I know this isn't the optimal solution, thanks for looking into it.

**Comment by vineetphillips** [comment]
3.0.5 resolved this issue. thanks.
