### ISSUE TITLE
Live Manifests longer than ~3 hours fail to play

### ISSUE THREAD

**Issue by justinoue** [videojs/videojs-contrib-hls#700]
I'm working on implementing VideoJS (5.9.2) and videojs-contrib-hls (2.0.1) and it would seem that live manifests with a DVR window longer than 3 hours with 10 second segments fail to play. It just sits and spins. If i shorten up the manifest it works fine.

A 3 hour manifest with 10 second segments equates to roughly 1080 segments.

**Comment by dmlap** [comment]
That's a surprise. Do you see segment XHRs being sent in the dev console?

**Comment by gesinger** [comment]
Hey @justinoue , we've made a lot of changes to videojs-contrib-hls in the meantime, including in live playback. We've also been successful with live streams greater than 3 hours. Would you be able to give the latest version (as of this comment, v4.1.1) a shot? If it's still a problem, would you be able to re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output)?

Thank you for reporting the issue.
