### ISSUE TITLE
Could you help to take a look at why the m3u8 file  can't  be played

### ISSUE THREAD

**Issue by ccba** [videojs/videojs-contrib-hls#701]
I implemented a player using the video.js(5.8.0) and hls(2.0.0)  to play the m3u8 file, but it doesn't work,  you can take a look by the URL : http://common.qupai.me/videoJS.html. 
I describe what i have checked from the example :
1. the request for the m3u8 file is successful , which contains 3 ts.
     #EXTM3U
    #EXT-X-VERSION:3
    #EXT-X-MEDIA-SEQUENCE:1
    #EXT-X-ALLOW-CACHE:NO
    #EXT-X-TARGETDURATION:10
    #EXTINF:9.576,
    wadefamily-wade-76_0.ts
    #EXTINF:10.010,
    wadefamily-wade-76_1.ts
    #EXTINF:7.541,
    wadefamily-wade-76_2.ts
   #EXT-X-ENDLIST
2. the first request for the wadefamily-wade-76_0.ts is sent , and the data is returned from the server successfully, but it is not playing, and no error is thrown, just the indicator of loading data is shown, the sequent ts files also haven't be sent to the server.

 by the way, if i run the URL in the safari, the m3u8 can be played, as you know the safari is able to decode hls by itself. 

i have no any idea why it is unable to be played.  Could someone help to take a look at it?

Thanks very much.

**Comment by dmlap** [comment]
Your m3u8 is working for me with contrib-hls 3.0.2 and video.js 5.10.2. Closing based on that. Please re-open if you still have issues after upgrading.
