### ISSUE TITLE
Lack of information about supported VJS versions

### ISSUE THREAD

**Issue by achru** [videojs/videojs-contrib-hls#707]
Hey guys,

Getting started guide is pretty straightforward, but I am missing one information,
as videojs 4 is still widely in use, it would be cool if there was a recommendation for which version should  be used with videojs 4 and from which it supports only 5,
could you point me that out ?

**Comment by gkatsev** [comment]
We should do a better job of this. I believe that the versions of contrib-hls that support videojs 4 are the pre 1.0 versions. The latest one being v0.17.9. I also want to add that while it works, it still has a lot of issues and missing features that were added in recent versions of contrib-hls, so, I would definitely urge you to update.

**Comment by dmlap** [comment]
It might not be the most discoverable location but you can check our [package.json](https://github.com/videojs/videojs-contrib-hls/blob/master/package.json#L88) to see the minimum video.js version for contrib-hls.
