### ISSUE TITLE
Flash tech start time.

### ISSUE THREAD

**Issue by vineetphillips** [videojs/videojs-contrib-hls#709]
For IE 11 and IE 10 on windows 7, we are falling back to use the flash tech for HLS. I wanted to set the start time for the video using currentTime(). What would be the best event to listen to, to set this? firstplay/canplay are inconsistent and play/playing do not work. 
Any input would be greatly appreciated. Thanks.

**Comment by gesinger** [comment]
Hey @vineetphillips , sorry this ticket has gone a long time without much attention. It's interesting that play/playing were not working for you, but we've made a lot of changes to videojs-contrib-hls in the meantime. Would you be able to give the latest version (as of this comment, v4.1.1) a shot? If it's still a problem, would you be able to re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output)?

Thank you for reporting the issue.
