### ISSUE TITLE
MediaSource.addSeekableRange() can only be invoked when the duration is Infinity

### ISSUE THREAD

**Issue by alexey2baranov** [videojs/videojs-contrib-hls#716]
Getting started example not works!!!
https://github.com/videojs/videojs-contrib-hls#getting-started

throws this error

> videojs-contrib-hls.js:6327 Uncaught InvalidStateError: MediaSource.addSeekableRange() can only be invoked when the duration is Infinity

My hls url is http://10.99.0.8:8080/TNT+/tracks-3,1/index.m3u8

The same url is played success with [https://github.com/dailymotion/hls.js](https://github.com/dailymotion/hls.js)

**Comment by dmlap** [comment]
That URL is using a private subnet IP address-- we won't be able to access it to help you debug. Do you have a public example anywhere?

**Comment by alexey2baranov** [comment]
I will try restrem it into internet as is (without recoding) and notify hire later

**Comment by kudoz83** [comment]
Having the same issue here - videojs 5.11 confrib-hls ver 3.3.0.

I've got a live stream running here 
https://j9x8b8p4.map2.ssl.hwcdn.net/hls/joshms-bre9g-qtmrc-8gkc7-3wqn2/index.m3u8

**Comment by adam187** [comment]
I have same issue, but apparently it works when `autoplay` option is enabled, then stream starts without this error. 

@alexey2baranov @kudoz83 can you confirm?

**Comment by adam187** [comment]
From what i debugged so for https://github.com/videojs/videojs-contrib-hls/blob/master/src/videojs-contrib-hls.js#L507-L508 setting source here should trigger `sourceopen` event and change `readyState` to `open` but apparently it doesn't  https://w3c.github.io/media-source/#h-mediasource-attach

Similar issues:
https://github.com/dailymotion/hls.js/issues/109
https://github.com/videojs/videojs-contrib-hls/issues/460

**Comment by kudoz83** [comment]
just to chime in, this is an issue for me with or without autoplay enabled.

**Comment by Syra** [comment]
Same problem (videojs-contrib-hls 3.4.0 & Video.js 5.11.0).
`videojs-contrib-hls.min.js:10 Uncaught InvalidStateError: MediaSource.addSeekableRange() can only be invoked when the duration is Infinity`

My index.m3u8.
> #EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:66
#EXT-X-TARGETDURATION:25
#EXTINF:25.000,
66.ts
#EXTINF:25.000,
67.ts
#EXTINF:25.000,
68.ts
#EXTINF:25.000,
69.ts
#EXTINF:25.000,
70.ts
#EXTINF:25.000,
71.ts

Generated via https://github.com/arut/nginx-rtmp-module.
Project https://github.com/dailymotion/hls.js didn't has that problem tho.

**Comment by ZacharySato** [comment]
Have the same issue with *.ts playlists.

> I don't get the error when I load a master M3U8 manifest that has multi-rendition sub-manifests

Same again. But in case of live stream video just stops at the end of first sub-manifest without any errors. The thing is that everything is fine with some outer sources like for example [http://web-cache.stream.ne.jp/www11/nhkworld-tv/dwstv/222468/live.m3u8](url).

**Comment by pedromcunha** [comment]
What's the status on this issue? Is there a workaround? Just started getting this error after updating to the latest version.

Error Message:
```
InvalidStateError·Uncaught InvalidStateError: MediaSource.addSeekableRange() can only be invoked when the duration is Infinity
```

Happens to us about 99% of the time on Chrome. Mostly on windows.

**Comment by mrmookie** [comment]
Same issue here 2 months later. Player still works but I see the errors.

**Comment by abondarenko** [comment]
The same for me.
Versions: videojs-contrib-hls 3.5.2 & Video.js 5.13.2
Browser: Google Chrome
Can't give you playlist sample. :-(

**Comment by gesinger** [comment]
Sorry this ticket has gone a long time without much attention. We've made a lot of changes to videojs-contrib-hls in the meantime, and haven't seen this issue in a while. It also looks like https://github.com/videojs/videojs-contrib-hls/issues/460 is the same issue. Going to close this one in favor of the older one, but would anyone who is experiencing this issue be able to give the latest version a shot (as of this comment, v5.4.0), and provide a sample stream if you're still seeing issues (I know that it has been a while, so the provided samples above are down)? Thank you.
