### ISSUE TITLE
3.x version supports webpack import?

### ISSUE THREAD

**Issue by xJoshx** [videojs/videojs-contrib-hls#718]
The 3.x version supports Webpack import? Because I've been reviewing #490 and #509 and I'm not sure if it is. At this moment I'm trying to import it with 

`import vjs from 'video.js'
window.videojs = vjs

require('imports?this=>window!videojs-contrib-hls')`

But still throwing errors

`index.js:10
Uncaught TypeError: Cannot convert undefined or null to objectmodule.exports @ index.js:10
VirtualSourceBuffer @ virtual-source-buffer.js:92
addSourceBuffer @ html-media-source.js:281
createSourceBuffer @ source-updater.js:40
SourceUpdater @ source-updater.js:66
mimeType @ segment-loader.js:328
addMimeType_ @ master-playlist-controller.js:773
setupSourceBuffer_ @ master-playlist-controller.js:746
(anonymous function) @ master-playlist-controller.js:149
trigger @ stream.js:95
(anonymous function) @ playlist-loader.js:338
(anonymous function) @ xhr.js:63(anonymous function) @ video.js:2514
loadFunc @ video.js:2392
readystatechange @ video.js:23222
index.js:10
Uncaught TypeError: Cannot convert undefined or null to objectmodule.exports @ index.js:10
VirtualSourceBuffer @ virtual-source-buffer.js:92
addSourceBuffer @ html-media-source.js:281
createSourceBuffer @ source-updater.js:40
SourceUpdater @ source-updater.js:66
mimeType @ segment-loader.js:328
addMimeType_ @ master-playlist-controller.js:773
setupSourceBuffer_ @ master-playlist-controller.js:746
handleSourceOpen_ @ master-playlist-controller.js:485
data.dispatcher @ video.js:20644trigger @ video.js:20748
`EventTarget.trigger` @ video.js:8634`

I'm currently trying to import it to a react module with ES6. In any case, can you give any way to achieve it in any version, please? I've not found any documentation about that, only with ES5.

**Comment by gkatsev** [comment]
See #600. It should all work except for our usage of webworkerify which doesn't work with webpack.
