### ISSUE TITLE
Cannot read property 'autoplay' of null

### ISSUE THREAD

**Issue by pedromcunha** [videojs/videojs-contrib-hls#722]
## Description

Currently we are seeing an error being thrown when using HTML5 videojs player to play HLS. The error is in regards to the autoplay prototype function.
## Steps to reproduce

It's very difficult to reproduce but this occurs at the beginning of an HLS stream, once it starts playing it sometimes (rarely) throws an error, which is documented below.
### Error output

Uncaught TypeError: Cannot read property 'autoplay' of null

`
Html5.prototype.autoplay = function autoplay() {
   return this.el_.autoplay;
 };
`
#### videojs

videojs (5.9.2)
videojs-contrib-hls (2.1.1)
#### browsers

Chrome (51)
#### OSes

Windows 10, 8.1, 7 (happens 97% of the time on windows OS)
Chrome OS
Mac OS

**Comment by Kasher** [comment]
:+1:

**Comment by gesinger** [comment]
Sorry this ticket has gone a long time without much attention.

I haven't seen that error happen recently, however, we've made a lot of changes to videojs-contrib-hls in the meantime. Would you be able to give the latest version (as of this comment, v4.1.1) a shot? If it's still a problem, would you be able to re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output)?

Thank you for reporting the issue.
