### ISSUE TITLE
No sound.

### ISSUE THREAD

**Issue by AlexMurm** [videojs/videojs-contrib-hls#725]
## Description
Hi. The problem is that there is no sound for particular stream: http://hls.tntmusic.cdnvideo.ru/tntmusic/tntmusic2.smil/playlist.m3u8. What could be the reason?

## Steps to reproduce
http://cdn.platformcraft.ru/alexmurm/tntmusic/tnt_new.html

### Expected
Workaround for this issue.

### videojs-contrib-hls
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 3.0.4

#### videojs
what version of videojs does this occur with?
video.js 5.10.2

#### browsers
what browser are affected?
I checked in Chrome and Firefox.

#### Operating Systems
I checked in Ubuntu 14.

Thanks in advance.

**Comment by julius** [comment]
+1 (videojs 5.10.4, contrib-hls 3.0.4)

**Comment by AlexMurm** [comment]
At the moment there are some problems with original stream (http://hls.tntmusic.cdnvideo.ru/tntmusic/tntmusic2.smil/playlist.m3u8). So this is new stream with the same issue for test purposes:
stream:
http://live.musicbox.cdnvideo.ru/musicbox/musicbox.sdp/playlist.m3u8
page url:
http://cdn.platformcraft.ru/alexmurm/tntmusic/test_hls.html

**Comment by julius** [comment]
The last contrib-hls version which has sound for me is 2.1.1

**Comment by PLobo87** [comment]
Also occurs on Mac / Chrome with videojs 5.10.4, contrib-hls 3.0.4

**Comment by zhufengme** [comment]
Also occurs on Win10 / Chrome51.0.2704.79 with videojs 5.10.4, contrib-hls 3.0.4

The test url: http://devlink.cn/videojs/test.html

**Comment by imbcmdth** [comment]
Your audio codec is `mp4a.40.34` which is MP3 audio using an old codec not supported by Chrome.

https://bugs.chromium.org/p/chromium/issues/detail?id=489520

Even if it was supported, mux.js does not have any provision to support MP3 in an mpeg2ts stream. I would recommend that you try switching to AAC encoded audio (a higher quality codec anyway!) stored in an ADTS stream.

**Comment by dmlap** [comment]
It would probably be helpful at this point to break out any remaining problems into separate issues. I'm going to close this one based on @imbcmdth's analysis. Don't hesitate to create a new issue (with an example m3u8) if anyone is still having problems with the latest release.
