### ISSUE TITLE
Can no longer access source media attributes

### ISSUE THREAD

**Issue by carloscarnero** [videojs/videojs-contrib-hls#727]
## Description
For several purposes (mostly end-user testing) I have a Video.js component that overlays on the player the **source** height and bandwidth about the currently playing segment, like this:

![hls](https://cloud.githubusercontent.com/assets/1102153/15766740/e6ccf1bc-290f-11e6-8b14-f3e429093015.png)

Something like a poor man's *Stats for nerds*, as seen on the YouTube player. Responding to the player's `timeupdate` event I used to be able to get that data from the `hls.playlists.media().attributes` object.

However, using the latest release I see no `attributes` property in the object returned from `hls.playlists.media()`. Is there any other way I could gather those numbers?

Please note that I need the **currently** playing data. If, in the future, the playlist changes (adaptive adjustment) then when the player switches, the overlaid numbers will change in unison.

## Additional Information
The component versions under this behavior is observed are:

* videojs-contrib-hls 3.0.4
* video.js 5.10.2

and I know for a fact that it used to work with:

* videojs-contrib-hls 2.0.1
* video.js 5.8.8

I'm seeing this behaviour under both Mozilla Firefox and Google Chrome, using their latest stable versions, under Ubuntu (Linux).

**Comment by imbcmdth** [comment]
I just tested it (in the latest 3.0.5) and it was working. Those attributes are optional in an HLS manifest and I would verify that the manifest you are trying to play has attributes specified.

**Comment by carloscarnero** [comment]
It turns out that @imbcmdth is correct. Upon closer examination, it became apparent that I was using the wrong playlist. Manually creating a simple Master Playlist with the [proper tags](https://tools.ietf.org/html/draft-pantos-http-live-streaming-19#section-4.3.4) was all I needed.
