### ISSUE TITLE
Blocked loading mixed active content error 

### ISSUE THREAD

**Issue by SharathEK** [videojs/videojs-contrib-hls#728]
HLS Playback gives "Blocked loading mixed active content" error in console and the video doesn't play. 

I'm using VideoJS player hosted in a page in https domain and the HLS stream comes from http domain, when this page is accessed in any browser (IE, FF or Chrome), it gives the above error and video doesn't load but it works properly in local environment.

Is there any way that I can fix it to play the HLS stream in this manner or HLS also should stream from a secured domain?

**Comment by dmlap** [comment]
Sorry, on most modern browsers requests for HTTP content will be blocked if they're loaded from an HTTPS page. Your best bet is to find a way to host your videos over HTTPS as well.
