### ISSUE TITLE
When using discontinuity flag it creates a flicker between segments

### ISSUE THREAD

**Issue by chrisfronda** [videojs/videojs-contrib-hls#729]

**Comment by chrisfronda** [comment]
Great help guys....or not...

**Comment by gkatsev** [comment]
Unfortunately, we're all very busy and can't always reply to issues immediately. If you'd like us to help you, can you please provide the information again?

**Comment by chrisfronda** [comment]
Hey Gary....thanks for responding.  I definitely understand that we all get busy!

Open this link in Chrome:  https://www.voilage.co/watch/fd59391f735e4734a5b8760fcd4ff3f6

You will see that there is flickering between frames.  You will notice that I am sending discontinuity flags between the content, that is because if I don't I get a whole new set of problems that it stops playback randomly after 7 sec.

**Comment by chrisfronda** [comment]
Any updates...now a total of a month with no answer or even a clue has gone by....I know we are all busy but I guess I am using JW Player after all...

**Comment by twinffity** [comment]
I can confirm this issue. It flickers when switching between bitrates.

**Comment by chrisfronda** [comment]
Gotcha...well is it considered a problem on my end or your end?  Should I be matching bitrates or is it acceptable that I'm not?  And if its your end, any idea on a fix for this?

**Comment by chrisfronda** [comment]
I do not get the flickering with JWPlayer

**Comment by chrisfronda** [comment]
Ugh...wasted my time again. JW Player it is.

**Comment by mmcc** [comment]
If someone else runs into this, please post a new issue with details and ideally a reduced test case so we can dig into it.

**Comment by chrisfronda** [comment]
If someone else runs into this, please be aware that no help will be provided by VideoJS guys.

I find it a bit odd MMCC you would not help for over a month and then post that you guys are happy to dig into it without attempting to resolve mine.

**Comment by mmcc** [comment]
@chrisfronda You were asked for more info and never gave anything but snarky responses. The worst of which aren't reflected in this thread since you seem to have deleted them. So yes, if someone else runs into this problem and would like to collaborate constructively with the rest of the community and maintainers to try and find a solution, they're welcome to.
