### ISSUE TITLE
Error When Open using playback google drive

### ISSUE THREAD

**Issue by creativefull** [videojs/videojs-contrib-hls#733]
yes i get error to when i using url from google drive

like this

`https://redirector.googlevideo.com/videoplayback?requiressl=yes&id=d1b3cfed90e018aa&itag=18&source=webdrive&app=texmex&ip=2604:a880:0:1010::8d4:8001&ipbits=32&expire=1465299416&sparams=requiressl%2Cid%2Citag%2Csource%2Cip%2Cipbits%2Cexpire&signature=7F83952D684CAA839E328E2970F856D2B5BCBDFA.2F1D4D036078433372BF390513971605320DC65C&key=ck2&mm=30&mn=sn-ab5l6n7z&ms=nxu&mt=1465284882&mv=m&nh=IgpwcjAxLmxnYTA3KgkxMjcuMC4wLjE&pl=48`

please help me :( 

player wan't play get show this error

`ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not`

but if i open using video html5 without it's working without error 

`
<video controls>
 <source src="https://redirector.googlevideo.com/videoplayback?requiressl=yes&id=d1b3cfed90e018aa&itag=18&source=webdrive&app=texmex&ip=2604:a880:0:1010::8d4:8001&ipbits=32&expire=1465299416&sparams=requiressl%2Cid%2Citag%2Csource%2Cip%2Cipbits%2Cexpire&signature=7F83952D684CAA839E328E2970F856D2B5BCBDFA.2F1D4D036078433372BF390513971605320DC65C&key=ck2&mm=30&mn=sn-ab5l6n7z&ms=nxu&mt=1465284882&mv=m&nh=IgpwcjAxLmxnYTA3KgkxMjcuMC4wLjE&pl=48" type="video/mp4"></source>
</video>
`

**Comment by dmlap** [comment]
Based on the video type attribute at the end of your comment, it sounds like you're trying to play an mp4. This project is for playing back HLS video. I'd suggest checking out a [primer or two on HTML video](http://www.html5rocks.com/en/tutorials/video/basics/) and if you still think you're having an HLS issue, filing  a new issue using our template.

**Comment by gkatsev** [comment]
Also, it was answered in the videojs issue: https://github.com/videojs/video.js/issues/3359#issuecomment-224389149
