### ISSUE TITLE
Fire event at the end of cues in a <track> in html5?

### ISSUE THREAD

**Issue by slowmove** [videojs/videojs-contrib-hls#737]
To be able to handle ads sequences an other metadata tracks it would be pleasant if there was some kind of event when the cues stops (i.e. the ad break is over).

**Comment by gkatsev** [comment]
Can you elaborate a bit more? Though, it sounds to me like this issue should belong in the main repo [video.js](/videojs/video.js/issues).

**Comment by slowmove** [comment]
@gkatsev as of now you do keep getting cue events when timed metadata events is fetched. Often this is used for ads, in which case you would like to have an event when the ad is over, i.e. the metadata has stopped.
I do understand that this may be impossible by how the metadata track is implemented in html5, but would like to get it confirmed in that case.

**Comment by gkatsev** [comment]
Are you using the metadata inside the hls stream? Also, how are you playing back the ads?
