### ISSUE TITLE
How to get a "ready" event

### ISSUE THREAD

**Issue by githubdoramon** [videojs/videojs-contrib-hls#744]
## Description

I am trying to add the "vjs-has-started" class to an audio tag, so it removes the big play button and show the video/audio controls.

The problem is that sometimes this work and sometimes don't... I think this happens because events are assyncrounous, and maybe videojs is doing some stuff after video-hls has loaded metadata and playlists.

Is there a way to get a real READY event?

Here is the code:

`var options = {`
`controlBar: {`
`fullscreenToggle: false`
`}`
`};`

`var audio = videojs(audioMarkupId, options, function() {`
`audio.addClass("vjs-has-started");`
`});`
`var hls = audio.tech({ IWillNotUseThisInPlugins: true }).hls;`
`hls.playlists.on("loadedplaylist", function() {`
`audio.addClass("vjs-has-started");`
`});`
`hls.playlists.on("loadedmetadata", function() {`
`audio.addClass("vjs-has-started");`
`});`
`

**Comment by gesinger** [comment]
Hey @githubdoramon , sorry this ticket has gone a long time without much attention. When you say that it doesn't work sometimes, were you seeing the events not firing?

Would you be able to give the latest version (as of this comment, v5.0.0) a shot? If it's still a problem, would you be able to provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output)?

Thank you.

**Comment by gesinger** [comment]
Closing for now. If you are still experiencing this issue with the latest version of videojs-contrib-hls (as of this comment, v5.1.0), please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.
