### ISSUE TITLE
Not possible to set video quality level when stream doesn't have audio

### ISSUE THREAD

**Issue by piotr-cz** [videojs/videojs-contrib-hls#745]
## Description

Not possible to set video quality level when stream doesn't have audio

Somehow the `renditionSelectionMixin` which sets representations on the hlsHandler is not invoked in my app.
Probably because there is no audio in the stream info (I'm streaming from live cams with no audio), [this code block](https://github.com/videojs/videojs-contrib-hls/blob/v3.1.0/src/videojs-contrib-hls.js#L429-L482) doesn't run
## Steps to reproduce

Explain in detail the exact steps necessary to reproduce the issue.
1. Create video tag and source which doesn't have audio
2. Create new videojs instance `window.player = videojs('#video');`
3. `player.hls.representations` function is not available
## Additional Information

This has been already reported by me in https://github.com/videojs/videojs-contrib-hls/issues/739#issuecomment-225453901, but after the issue has been closed and I didn't have information about audio
### videojs-contrib-hls

what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 3.1.0
#### videojs

what version of videojs does this occur with?
video.js 5.10.4
#### browsers

what browser are affected?
*
#### Operating Systems

what platforms (operating systems and devices) are affected?
*
### plugins

are any other videojs plugins being used on the page? If so, please list them with version below.
*
### Other JavaScript

are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by sobytes** [comment]
Also have this issue

**Comment by piotr-cz** [comment]
@sobytes Which _videojs-contrib-hls_ version are you using?

**Comment by BrandonOCasey** [comment]
I think that you will have to wait for the `loadedmetadata` event on the player before `player.hls.representations` will be available. Example:

``` JavaScript
player.on('loadedmetadata', function() {
  // player.hls.representations should be exist now
});
```

**Comment by piotr-cz** [comment]
@BrandonOCasey 
No, unfortunetally no joy. I've tried on 5 webcam streams and latest libraries.
player.hls.representations is still `undefined`

**Comment by piotr-cz** [comment]
So it seems that the source I'm using doesn't allow Multi-Bitrate HLS playlists (Adaptive bitrate streaming).

The source of index.m3u8 file is
```
#EXTM3U
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:8
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:137090
#EXTINF:7.480,
2016/09/14/08/41/45-07480.ts
#EXTINF:7.540,
2016/09/14/08/41/53-07540.ts
#EXTINF:7.470,
2016/09/14/08/42/00-07470.ts
#EXTINF:5.000,
2016/09/14/08/42/08-05000.ts
```

While in the [videojs-contrib-hls example](http://videojs.github.io/videojs-contrib-hls/) each playlist entry has properties like _BANDWIDTH_ and _RESOLUTION_

I'm not sure if this is the case, but even when I was able to invoke creation of _representations_, only available representation didn't have width attribute.

I think the readme file could state that when the _hls.representations_ function is not available, stream index file doesn't have any information on available adaptive bitrates.

**Comment by gkatsev** [comment]
Looks like the m3u8 you have is a media playlist. Those just have the video to play in a single resolution. To get multiple resolutions, you need a "master" playlist that has links to different media playlists with resolution and bandwidths properties for each of those playlists.
Yeah, we should update the documentation. Perhaps we can just make the representations always be available but in this case it only returns one item in the representations. Not sure if @imbcmdth has already thought through that, though.

**Comment by gesinger** [comment]
Thanks @gkatsev , and thanks @piotr-cz for reporting the issue.

We now have https://github.com/videojs/videojs-contrib-quality-levels which should provide a nicer API for quality level selection than the rendition one. This should also make cases involving media playlists easier. Please let us know if you have any trouble with it.

**Comment by piotr-cz** [comment]
Thanks, I'll check it out, but now I know that we need to setup media server to provide lower resolution streams.
