### ISSUE TITLE
can't find module

### ISSUE THREAD

**Issue by evilemon** [videojs/videojs-contrib-hls#746]
After the npm i ,global/document is needed;
your package.json :
##
      "devDependencies": {
    "babel": "^5.8.0",
    "babelify": "^6.0.0",
    "bannerize": "^1.0.0",
    "browserify": "^11.0.0",
    "browserify-shim": "^3.0.0",
    "connect": "^3.4.0",
    "cowsay": "^1.1.0",
    "doctoc": "^0.15.0",
    "glob": "^6.0.3",
    *****************"global": "^4.3.0",
    ... }
##

**Comment by gkatsev** [comment]
I thought we fixed that already...
Would you be willing to make a PR for that?

**Comment by forbesjo** [comment]
Fixed by https://github.com/videojs/videojs-contrib-hls/pull/788
