### ISSUE TITLE
Support for current stream date-time via EXT-X-PROGRAM-DATE-TIME tag?

### ISSUE THREAD

**Issue by pswolfe** [videojs/videojs-contrib-hls#747]
Does this player read in the ```EXT-X-PROGRAM-DATE-TIME``` at some point in order to report the current stream date time somehow? I'm looking for functionality in the API to read the current program date-time and was looking to extrapolate it from the included ```EXT-X-PROGRAM-DATE-TIME``` value. 

If this functionality does not yet exist, where would I look at expanding the library so that it would support ```EXT-X-PROGRAM-DATE-TIME```? It looks to me like ```playlist-loader``` would be the place to make changes. Let me know if I've missed something and this functionality is already here (or if its planned in an upcoming release), or, if not, how I can get started. Thanks very much!

**Comment by gkatsev** [comment]
We don't currently support it. The correct place would be to look in the [m3u8-parser](/videojs/m3u8-parser). I believe that @nickygerritsen was interested in that as well but I'm not sure whether he had a chance to start on it or anything but if he hasn't done work yet, a PR would be great.

**Comment by nickygerritsen** [comment]
I have not worked on it yet. Feel free to add it to `m3u8-parser` or otherwise I will add it at a later time.

**Comment by pswolfe** [comment]
Great, thanks @gkatsev and @nickygerritsen ! You'll have a PR coming up on the [m3u8-parser](https://github.com/videojs/m3u8-parser) soon.

**Comment by pswolfe** [comment]
Hey again. I've done the work on the parser; you can find the PR for [my proposed changes here.](https://github.com/videojs/m3u8-parser/pull/4)

**Comment by pswolfe** [comment]
This work has been merged into the parser codebase; will close the ticket once it becomes available through NPM.

**Comment by pswolfe** [comment]
Closing since this has been deployed in 1.1.0 of the m3u8-parser on [NPM](https://www.npmjs.com/package/m3u8-parser).
