### ISSUE TITLE
Question: How to approach integration of videojs-contrib-hls with Chromecast API.

### ISSUE THREAD

**Issue by askaliuk** [videojs/videojs-contrib-hls#749]
I have a general question.
I'm working Chromecast support for video.js with `videojs-contrib-hls`.
I need full synchronization between video.js player and Chromecast stream (similar to YouTube experience). Means when user changes volume, pause or performs other action I need to call Chromecast API to synchronize both streams. Also playback in the browser should be blocked with a special placeholder, which says `Casting to Chromecast`. 

There is only one project which support video.js 5:
https://github.com/benjipott/video.js-chromecast

They implemented all required functionality via custom tech (wrapper for HTML5 Media API).
Code is here:
https://github.com/benjipott/video.js-chromecast/blob/master/src/js/tech/chromecast.js

So they basically have custom handlers for `play`, `setVolume` etc.

My question is:
What is correct way to approach this task?
Extend `videojs-contrib-hls` somehow? Should chromecast tech work smoothly with `videojs-contrib-hls`?
Take completely different approach and simply listen to `video.js` events outside player scope and call appropriate Chromecast API?

Any help is appreciated. Thanks.

**Comment by gkatsev** [comment]
I'm not sure that a custom tech is really required. Most of the changes can be gotten via event listeners like for volume changes you can listen to `volumechange`. Check out this page for an example: http://videojs.com/advanced/. Some of the videos on there use contrib-hls.

**Comment by nickygerritsen** [comment]
The benjipott version should work. We are using it in our player with contrib-hls and contrib-dash and everything works.

Note that if you want to have a playlist with multiple items it doesn't work out of the box, but we have created a [fork](https://github.com/StreamOneNL/video.js-chromecast) that should work.

**Comment by askaliuk** [comment]
Thank you everybody. Very helpful.
