### ISSUE TITLE
video.js failing when changing source

### ISSUE THREAD

**Issue by xtatanx** [videojs/videojs-contrib-hls#755]
## Description

Helo guys,
I am creating a video carousel using Brightcove smart player which is built on top of videojs, every time I click on a thumbnail I update the src of the video player and automatically play the video. This is working good across all browsers however, on IE11 Windows 8.1 and also IE11 Windows7 I am having an intermittent error.

`VIDEOJS: TypeError: Unable to get property 'playlist' of undefined or null reference`

Which seems to be related to this block of code:

```
/**
   * Pass values to the playback tech
   *
   * @param {String=} method Method
   * @param {Object=} arg Argument
   * @private
   * @method techCall_
   */

  Player.prototype.techCall_ = function techCall_(method, arg) {
    // If it's not ready yet, call method when it is
    if (this.tech_ && !this.tech_.isReady_) {
      this.tech_.ready(function () {
        this[method](arg);
      }, true);

      // Otherwise call method now
    } else {
        try {
          this.tech_[method](arg);
        } catch (e) {
          _utilsLogJs2['default'](e);
          throw e;
        }
      }
  };
```
## Steps to reproduce

We are just getting an instance of the player using `var $player = videojs.getPlayers()["ideas-video-module"];` and every click on a thumbnail we are doing this:

```
    /**
     * Update videoPlayer url, share metadata and poster image
     *
     * @param  {String} videoUrl       url of the new video
     * @param  {Object} socialMetadata metadata to be used in share overlay
     * @param  {String} posterUrl      url of the new poster image
     */
    function updatePlayer(videoUrl, videoUrlMp4, socialMetadata, posterUrl) {
        $player.pause();
        // we change poster image here and add social metadata
        $player.src([
            {type: "application/x-mpegURL", src: videoUrl},
            {type: "video/mp4", src: videoUrlMp4}
        ]);
    }
```

For security reasons I don't think I will be able to share the url of the website. I will try to place a JSbin emulating this as soon as posible.

I appreciate if you guys have some inputs on why could we be facing this issue and probably if is related to the fact we are using HSL on this.

Regards

**Comment by sobytes** [comment]
I also seem to be getting this error.

**Comment by allensun421** [comment]
same problem here, how you guys solved it out?

**Comment by yonimor** [comment]
+ 1

**Comment by gesinger** [comment]
Sorry this ticket has gone a long time without much attention. We've made a lot of changes to videojs-contrib-hls in the meantime. Would anyone seeing this issue mind giving the latest version (as of this comment, v5.3.3) a shot? If it's still a problem, would you be able to provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output)? Thank you.

**Comment by gesinger** [comment]
Closing for now. If you are still experiencing this issue with the latest version of videojs-contrib-hls (as of this comment, v5.4.0), please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.
