### ISSUE TITLE
VIDEOJS: WARN: Problem encountered with the current HLS playlist. 

### ISSUE THREAD

**Issue by sobytes** [videojs/videojs-contrib-hls#756]
Hi All,

I seem to be getting a weird error think it might be something to do with my server settings.

I have a video encoded at 10 second segments .ts when the video loads first time it will normally work, then if i re run the page it will output lots or errors like it is caching the old stream i think?

It will then switch between every playlist with this error.

```
VIDEOJS: WARN: Problem encountered with the current HLS playlist. Switching to another playlist.
```

The weird thing is if i do a hard refresh it will then work fine again.
![screen shot 2016-06-23 at 20 50 26](https://cloud.githubusercontent.com/assets/2689776/16317688/2cfa962e-3984-11e6-80b5-f4686727f34c.png)

I am just wondering if there is something obvious i am missing?

My playlist looks like this

```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=752000,RESOLUTION=400x220,CODECS="avc1.42001e,mp4a.40.2"
hls0400k/18ba6da016eff80f0c9ade7ea632be5ac13b3aa27427ce93602ea2fce5d48d62.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1333000,RESOLUTION=480x264,CODECS="avc1.42001e,mp4a.40.2"
hls0600k/18ba6da016eff80f0c9ade7ea632be5ac13b3aa27427ce93602ea2fce5d48d62.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2830000,RESOLUTION=640x352,CODECS="avc1.4d001f,mp4a.40.2"
hls1000k/18ba6da016eff80f0c9ade7ea632be5ac13b3aa27427ce93602ea2fce5d48d62.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5792000,RESOLUTION=960x528,CODECS="avc1.4d001f,mp4a.40.2"
hls1500k/18ba6da016eff80f0c9ade7ea632be5ac13b3aa27427ce93602ea2fce5d48d62.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=7726000,RESOLUTION=1024x562,CODECS="avc1.4d001f,mp4a.40.2"
hls2000k/18ba6da016eff80f0c9ade7ea632be5ac13b3aa27427ce93602ea2fce5d48d62.m3u8
```

Thanks

I am running version 
version: 3.1.0 with videojs version: 5.10.4

**Comment by sobytes** [comment]
I increase my segments from 10s to 20s and it seemed to have resolved the issue ;)

**Comment by parkej60** [comment]
Seeing pretty much the exact same thing. Works fine in Safari, but get these errors in Chrome. Any updates?

**Comment by gesinger** [comment]
Hey @sobytes , sorry this ticket has gone a long time without much attention.

This error usually identifies a problem with downloading a segment/playlist (usually indicates a server error or a problem with the network), but may be hard to diagnose without seeing the stream itself. That said, judging by the CORS error reported, it looks like it has to do with the server settings. I'm not sure what the proper setup would be server-side to make it work, but if the browser is reporting that CORS error then the XHR will get an error and we'll try another playlist if available.

If you are still seeing this without CORS errors being reported, would you be able to give the latest version (as of this comment, v4.1.1) a shot? And if it's still a problem, would you be able to re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output)? Thank you.

**Comment by samueleastdev** [comment]
Hi @gesinger this issue has defiantly been resolved in one of the updates no longer having any issues.

**Comment by gesinger** [comment]
Thanks @samueleastdev ! Glad to hear it.
