### ISSUE TITLE
Cannot play any videos on 3.1.0 (Uncaught TypeError: Super expression must either be null or a function, not undefined)

### ISSUE THREAD

**Issue by cdhowie** [videojs/videojs-contrib-hls#760]
I am unable to play any videos using 3.1.0.  (Tested in Chrome on Windows.)  This HLS plugin fails with `Uncaught TypeError: Super expression must either be null or a function, not undefined` before any video files are even downloaded.  A quick Google suggests that this is due to using the ES6 `class A extends B` construct when `A` was not defined using the `class` keyword.

**Comment by cdhowie** [comment]
I'm not using Browserify, I'm just including this HLS script (using `<script>`) alongside video.js.

**Comment by gkatsev** [comment]
What version of videojs are you using? Are you using our built file from the releases?

**Comment by cdhowie** [comment]
videojs version 5.4.6.  Yes, I was using the 3.1.0 minified release.

**Comment by gkatsev** [comment]
Version 3.1.0 of contrib-hls requires videojs 5.10.1 and up because of the audiotrack functionality.

**Comment by cdhowie** [comment]
I see, thanks.
