### ISSUE TITLE
can't paly live hls on firefox

### ISSUE THREAD

**Issue by zisuc** [videojs/videojs-contrib-hls#764]
## Description

Hi, i try to play live HLS stream use latest videojs-contrib-hls. it works well on chrome.
but it  can't play on fireofx. i also try videojsv5.5.0 and videojs-contrib-hlsv2.2.0 videojsv5.10.0 and videojs-contrib-hlsv3.0.5. it has the same problems
## Steps to reproduce
1. npm install --save videojs-contrib-hls
2. play the demo index.html
## Results

can works well on chrome
but it cant paly on firefox v47

the error is
200    GET   playlist.m3u8    192.168.32.66
200    GET   playlist.m3u8    192.168.32.66
200    GET   playlist.m3u8    192.168.32.66
200    GET   playlist.m3u8    192.168.32.66
200    GET   playlist.m3u8    192.168.32.66

it looks like repeat load playlist.m3u8 ,but don't load .ts thus dont play

**Comment by gesinger** [comment]
Hey @zisuc , sorry this ticket has gone a long time without much attention. We've made a lot of changes to videojs-contrib-hls in the meantime. Would you be able to give the latest version (as of this comment, v4.1.1) a shot? If it's still a problem, would you be able to re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output)?

Thank you for reporting the issue.
