### ISSUE TITLE
feature request: fMP4 segments support

### ISSUE THREAD

**Issue by MichaelSavin** [videojs/videojs-contrib-hls#768]
As described in a [draft-pantos-http-live-streamingwwdc16-preview](https://developer.apple.com/services-account/download?path=/Documentation/HTTP_Live_Streaming_Internet__Draft_Preview/HLSdraftpantospreview.pdf) HLS in macOS v10.12 or later, iOS 10 or later, and tvOS 10 or later supports fMP4 segments, as they are used by MPEG-DASH as well. See [Apple introduces fragmented MP4 in HLS](https://bitmovin.com/hls-news-wwdc-2016/) article for examples.

**Comment by forbesjo** [comment]
@dmlap I believe you were working on a PR for this?

**Comment by dmlap** [comment]
I am. Fixing up the test cases and then I'll open a PR.

**Comment by forbesjo** [comment]
Closing, in progress at #829

**Comment by dmlap** [comment]
@MichaelSavin fmp4 support is in master now! Worth noting: the Flash fallback doesn't support fmp4 playback so it only works on browsers that support MSE (and don't have native HLS capabilities).
