### ISSUE TITLE
Long-term program will stop on the way

### ISSUE THREAD

**Issue by aun343** [videojs/videojs-contrib-hls#771]
## Description

It will not be requested after a specific(certain) .ts file.

this playlist is here.
https://movie.abemafresh.tv/playlist/movie.amebafresh.tv/movie/fresh20920/027/432/playlist.m3u8
- 13:14:55 From 23837.ts, ts files will be requested to continue suddenly
- 13:15:26 stop playing movie.

There may be a problem [that](https://github.com/videojs/videojs-contrib-hls/blob/master/src/playlist.js#L245) is in the segment of this area.

Similarly, 20 a few hours there is such a program will stop on the way.
https://movie.abemafresh.tv/playlist/movie.amebafresh.tv/movie/fresh20915/016/432/playlist.m3u8

But, short videos(just one hour.) can be played without last until the problem can play without last until the problem.
https://movie.abemafresh.tv/playlist/movie.amebafresh.tv/movie/fresh19517/008/432/playlist.m3u8
### Error output

There are no errors in console
### videojs-contrib-hls

videojs-contrib-hls 3.1.0
#### videojs

video.js 5.10.4
#### browsers
- Chrome Version 51.0.2704.103 (64-bit)
- Firefox 47.0
#### Operating Systems
- OS X 10.11.5 (15F34)
### plugins
- videojs-contrib-media-sources 3.1.2
### Other JavaScript
- React

Thanks.

**Comment by gesinger** [comment]
Sorry this ticket has gone a long time without much attention. I tried to check the streams, but it seems that they are now down. We've made a lot of changes to videojs-contrib-hls in the meantime. Would you be able to give the latest version (as of this comment, v5.3.3) a shot? If it's still a problem, would you be able to provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output)?

Thank you for reporting the issue.

**Comment by aun343** [comment]
@gesinger 

i'm very sorry.
that m3u8 domain has already moved.
here is new m3u8 URL.
https://movie.freshlive.tv/manifest/1024/archive.m3u8

**Comment by gesinger** [comment]
Hey @aun343 , thanks for posting the stream. I gave it a shot in Chrome 56/OS X with videojs-contrib-hls 5.3.3 and seeked to 13:14:06 and played through both of those times without any stopping. Would you be able to give the latest version a shot and see if it resolves the issue for you? Thanks.

**Comment by gesinger** [comment]
Closing for now. If you are still experiencing this issue with the latest version of videojs-contrib-hls (as of this comment, v5.4.0), please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.
