### ISSUE TITLE
Audio codec support for type ('audio/mp4;codecs="mp4a.804C"')

### ISSUE THREAD

**Issue by sharanpnabh** [videojs/videojs-contrib-hls#772]
## Description

I'm loading a HLS playlist (m3u8) from our server. Playback on Safari works fine with the video-js-contrib-hls plugin, but fails on Chrome. I can see that the playlist retrieval for multiple bitrates happens but playback fails with an error:

_videojs-contrib-hls.js:14048 Uncaught NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('audio/mp4;codecs="mp4a.804C"') is unsupported._

## Steps to reproduce
Sample playlist.

#EXTM3U
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",FORCED=NO,AUTOSELECT=YES,LANGUAGE="eng",NAME="eng",URI="subtitles_eng_933000.m3u8"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=933000,CODECS="avc1.674D401F966280A00B76028408080900000303E90000EA6094,mp4a.804C",RESOLUTION=480x272,SUBTITLES="subs"
933000.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1143000,CODECS="avc1.674D401F966280A00B76028408080900000303E90000EA6094,mp4a.804C",RESOLUTION=640x368,SUBTITLES="subs"
1143000.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1354000,CODECS="avc1.674D401F966280A00B76028408080900000303E90000EA6094,mp4a.804C",RESOLUTION=640x368,SUBTITLES="subs"
1354000.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1880000,CODECS="avc1.674D401F966280A00B76028408080900000303E90000EA6094,mp4a.804C",RESOLUTION=960x544,SUBTITLES="subs"
1880000.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3459000,CODECS="avc1.674D401F966280A00B76028408080900000303E90000EA6094,mp4a.804C",RESOLUTION=1280x720,SUBTITLES="subs"
3459000.m3u8
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=933000,CODECS="avc1.674D401F966280A00B76028408080900000303E90000EA6094",RESOLUTION=480x272,URI="iframe_933000.m3u8"
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1143000,CODECS="avc1.674D401F966280A00B76028408080900000303E90000EA6094",RESOLUTION=640x368,URI="iframe_1143000.m3u8"
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1354000,CODECS="avc1.674D401F966280A00B76028408080900000303E90000EA6094",RESOLUTION=640x368,URI="iframe_1354000.m3u8"
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1880000,CODECS="avc1.674D401F966280A00B76028408080900000303E90000EA6094",RESOLUTION=960x544,URI="iframe_1880000.m3u8"
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3459000,CODECS="avc1.674D401F966280A00B76028408080900000303E90000EA6094",RESOLUTION=1280x720,URI="iframe_3459000.m3u8"

### Error output
videojs-contrib-hls.js:14048 Uncaught NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('audio/mp4;codecs="mp4a.804C"') is unsupported.

### videojs-contrib-hls

videojs-contrib-hls 3.1.0

#### videojs

video.js 5.10.7

#### browsers

*Chrome

### plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*video-contrib-hls

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*no

**Comment by xarques** [comment]
Hi,

I've got the same issue on Chrome :
_videojs-contrib-hls.min.js:9 Uncaught NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('audio/mp4;codecs="mp4a.804c"') is unsupported._

Any updates ?

Thanks

**Comment by dmlap** [comment]
Codec support is handled by the individual browsers. It sounds like Chrome doesn't support that audio codec so unfortunately there's nothing we can do in this project. If you can, try re-encoding with a more common audio codec.

**Comment by xarques** [comment]
I tried to catch the exception raised by the native browser and then replace the codec by a default one (defaultCodecs = {"audio": "mp4a.40.2", "video":"avc1.4d400d"}.
It works but every 10 seconds (size of each segment), the player stops the video during 1 second and then plays the next segment. Any idea why ?

My workaround is available here :
https://gist.github.com/xarques/4b9f689c9287f99ce6fa85a84c57eb6d
