### ISSUE TITLE
Live stream stops working after a while when using Wowza

### ISSUE THREAD

**Issue by alonfixler** [videojs/videojs-contrib-hls#775]
Hi,

I'm using videoJs 5.10.5 and videojs-contrib-hls 3.1.0 with Wowza streaming server 4.4.1.
When streaming VOD everything works fine but when I'm trying to stream live I have the following problem: At some point, usually after 10-20 seconds of streaming, the streaming is stuck and on the network tab of the browser I see the following:

![image](https://cloud.githubusercontent.com/assets/2629128/16800826/f6a6e722-48ff-11e6-8542-0c9a72d2d2e6.png)

From the screen shot it appears it the browser is downloading the .m3u8 files but stops downloading the .ts chunks. I can see that the requests for the .m3u8 are **different** and aren't stuck on a loop with the same request:

![image](https://cloud.githubusercontent.com/assets/2629128/16800970/b90fc5e0-4900-11e6-8ab5-ea712cb2e580.png)

![image](https://cloud.githubusercontent.com/assets/2629128/16800983/c6900342-4900-11e6-8504-2f3f7d52a7bc.png)

After reviewing #625 I tried bigger values for the GOAL_BUFFER_LENGTH variable and I noticed that when I changed it to 60 and later on to 120 it took more time only the stream gets stuck. in #625 
it was later mentioned that the problem was only relevant for VOD and not for Live so I don't think it's the same issue.
I also thought that #550 might be related but over there it seems like that the same ts chunks are being downloaded and this is not the same as my problem. I also tried to apply the fixes in #561 but it didn't fix my problem.

Did anyone encountered with such a problem? Is there some configuration on the Wowza side that can help?

Thanks,

Alon

**Comment by crmsoft** [comment]
+1

**Comment by ikrong** [comment]
I got this weird problem too.

**Comment by titpetric** [comment]
I am experiencing a similar problem with shorter chunks. The m3u8 request before the last .ts gives me 3 chunks, with duration of [10, 10, 2.8], and playlist target duration probablly at 10 or 11 secs. Unfortunately you didn't include the m3u8 before the last .ts request, I suspect it might be the same. Did you ever solve this issue?

**Comment by alonfixler** [comment]
Hi,

I solved the issue by changing the following values in Cupertino Streaming Packetizer properites:
1. cupertinoMaxChunkCount: set it to 15 (Instead of the default which was 10).
2. cupertinoPlaylistChunkCount: set it to 10 (Instead of the default which was 3).

Alon

**Comment by ssanth** [comment]
I am facing this issue on live streams on chrome, 
videojs 5.15.1
contrib hls v4.1.1
Those settings are not helping as I want low latency as well.
Looking forward for a solution.

**Comment by gesinger** [comment]
Hey everyone, thanks for creating the issue and providing more information on it. Would anyone be able to provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output)? It would make it easier for us to see the problem. Thanks.

**Comment by ssanth** [comment]
https://github.com/videojs/videojs-contrib-hls/issues/982
in the above template, replacing the VOD stream with this live stream http://mahoaobj.b5695cde.cdnviet.com/tuandn/videojs/hls/vtv5-high.m3u8  will showcase the issue.

**Comment by apara** [comment]
We have been testing with Wowza streaming and are seeing the same behaviour.  After some time, the player just downloads the chunklist and no segments are being retrieved.

![image](https://cloud.githubusercontent.com/assets/923461/22997776/a4f00b96-f388-11e6-86ea-d3f0cf20f2ca.png)

The VLC player we have running side-by-side, is working just fine and is having no issues with playing the HLS stream.  We are also playing the RTMP stream at the same time using VideoJS and that stream is also continuing to play just fine.

Here is the .html file we are using to play our stream:

<head>
  <meta charset="UTF-8">
  <link href="https://vjs.zencdn.net/5.16.0/video-js.css" rel="stylesheet">
  <script src="https://vjs.zencdn.net/5.16.0/video.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/5.2.1/videojs-contrib-hls.js"></script>
</head>

<body>
  <div style="float:left">
    <video id="my-video" class="video-js" controls preload="auto" width="710" height="400" data-setup="{}">
      <source src="http://wcng.encoding.mediaplatformdev.com:1935/123-Live/Alex-Demo-Prep/manifest.m3u8" type='application/x-mpegURL'>
      <p class="vjs-no-js">
        To view this video please enable JavaScript, and consider upgrading to a web browser that supports HTML5 video
      </p>
    </video>
  </div>

  <script>

  (function pageInit(){ 
      var player = videojs('my-video');
      player.muted(true); // mute for testing purposes: "This is a demonstration of wirecast!"
      player.play();
  })();

  </script> 
</body>

This is a serious issue for us that is making us look at other solutions.

**Comment by gesinger** [comment]
Hey @apara , the txt file you linked to seems to just say "To view this video please enable JavaScript, and consider upgrading to a web browser that supports HTML5 video."

Do you happen to have a link to a publicly accessible m3u8?

**Comment by apara** [comment]
I re-uploaded the file zipped.  Working on making the stream available publically without exposing our server to script kiddies.

**Comment by apara** [comment]
Here is the public URL: 
http://wowza-1646319330.us-east-1.elb.amazonaws.com/123-Live/Alex-Demo-Prep/manifest.m3u8

Updated code to use the public URL:
[index2.html.zip](https://github.com/videojs/videojs-contrib-hls/files/778748/index2.html.zip)

**Comment by apara** [comment]
I have been able to re-create the failure.  Just need to leave the browser up and running for a bit.

![image](https://cloud.githubusercontent.com/assets/923461/23036981/9bd7b3f4-f439-11e6-87de-8882f1bf1c71.png)

**Comment by apara** [comment]
@gesinger I am leaving the stream running.  I can consistently get the HLS to hang.  All I do is start the browser and then walk away or get tied up in the meetings.  When I come back, it's usually hung.  Let me know if you are going to have a chance to look at or troubleshoot this, otherwise I will stop the stream.

**Comment by gesinger** [comment]
Hey @apara , thanks for posting the stream. Leaving it running now to see how it goes.

**Comment by gesinger** [comment]
Thanks for leaving the stream up @apara . Ran it a few times, and have some results.

As you said, when running with the latest version of videojs-contrib-hls, it'll eventually stop. There are a few reasons for this. (1) The playlist window is really short (there are only three segments in the playlist at any given point), meaning that normally mild issues (some explained in next points) will present themselves more often. (2) There are gaps between some segments. This is OK, as playback-watcher will skip over them, however, when it has to skip gaps, there is a slight delay (we give time in case the video catches up). With that combination (3) we fall off the back of the playlist. When this happens, we try to seek to the live point, however, if there is a gap at the live point or really slow responses (particularly with a short window) the player can get stuck.

The good news is that we were working on a fix for getting stuck when seeking in https://github.com/videojs/videojs-contrib-hls/pull/1006 . I tried the stream in this branch and have not seen it permanently freeze yet (has gone for over 8000 seconds, versus a permanent freeze in under 2000 seconds with main branch).

Feel free to try https://github.com/videojs/videojs-contrib-hls/pull/1006 , though we hope to get it into master and cut a new version soon (we just need to do some more testing for it).

**Comment by apara** [comment]
@gesinger I will leave the stream running for the weekend into next week.  Let me know when you are done with it and I will shut it down.

Thanks for the heads up on the playlist window, we may need to adjust that anyway for better reliability of the stream.  We will not make the change now,  until you have had a chance to test/verify new code/branch.

**Comment by apara** [comment]
@gesinger do you still need the stream running?

**Comment by vpowers** [comment]
I've tested this fix with PR #1006 and playback is working as expected. Test was done with a long running live HLS stream using Wowza. I can't confirm in the master branch (after merge) since playback of HLS is not longer working. Possibly related #1022.

**Comment by gesinger** [comment]
PR #1006 has since been merged and the m3u8s posted on this page are running for me. If anyone is still experiencing issues with the latest version of videojs-contrib-hls (at the time of this comment, v5.3.2), please let us know. Thank you all for the comments and examples.
