### ISSUE TITLE
HLS videos do not play in Flash mode

### ISSUE THREAD

**Issue by kevinzang** [videojs/videojs-contrib-hls#778]
## Description
I wasn't able to get any HLS videos to play on Windows 7 IE11, presumably because the player was falling back to Flash. To debug, I forced Flash mode by setting `player.options_.techOrder = ['flash'];`, and noticed that the same problem occurred on Chrome. It seems like the "sourceopen"/"webkitsourceopen" event never fires, which prevents the handler in `videojs.FlashMediaSource` constructor from executing. According to https://msdn.microsoft.com/en-us/library/dn440521(v=vs.85).aspx, indeed "sourceopen" is not supported on Windows 7 IE11; I'm not sure if it's normal for it to not fire in Chrome.

## Steps to reproduce

1. Go to http://videojs.github.io/videojs-contrib-hls/.
2. In Chrome console:

    ```
    var player = videojs.getPlayers()['example-video'];
    player.options_.techOrder = ['flash'];
    player.src(player.options_.sources);
    ```
3. Press play.

### Expected
Video should play.

### Actual
Video does not play.

### Error output
None.

## Additional Information
I was able to find a workaround by manually triggering "sourceopen":

```
player.on('loadedmetadata', function() {
  if (player.techName_ === 'Flash' && player.tech_ && player.tech_.hls) {
    var swfId = player.tech_.el().id;
    player.tech_.hls.mediaSource.trigger({
      type: 'sourceopen',
      swfId: swfId
    });
  }
});
```

But I was wondering whether there was a standard solution. As far as I remember, flash fallback used to work for me, and I didn't make any changes to my code, so I'm not sure why it's not working now.

**Comment by forbesjo** [comment]
We tried your steps to reproduce the issue but are not able to see what you are describing, if this is still an issue could you provide a demo player or source?

**Comment by arski** [comment]
@kevinzang was it failing always on W7IE11? I tried the steps to reproduce and it plays fine.. hmm.. is the patch really necessary?
