### ISSUE TITLE
How To Handle Live Streaming Which Isn't Live Yet

### ISSUE THREAD

**Issue by sackos** [videojs/videojs-contrib-hls#780]
## Description

It might seem like a silly issue but I would like to know if there's any way to handle live streaming which isn't live yet. I want to implement live streaming in my application. But what if user runs the player in a browser and live streaming is yet to begin. Is there any way to handle this case?

**Comment by sobytes** [comment]
Hi All,

Not a silly issue i would also like to know if there is a work around for this issue here is what i currently have.

Apologies for the terrible code in advance.
~~~
var isSafari = /^((?!chrome|android).)*safari/i.test(navigator.userAgent);

var videoPlayer = videojs("video", {
    "preload": "none",
    "techOrder": (isSafari) ? ["html5"] : ["flash", "html5"],
    "autoplay": true
}, function() {
    $("#video .vjs-control-bar").addClass("vjs-control-bar-float");
    $("#video .vjs-progress-control").css("opacity", 0);
    $("#video .vjs-remaining-time-display").text("LIVE");
    if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {

    } else {
        var extraButtons = [{
            text: "Brand",
            image: "/images/circle_red.png",
            link: "http://sobytes.com"
        }];
        for (var i = extraButtons.length - 1; i >= 0; i--) {
            var brandButton = videoPlayer.controlBar.addChild('button', {
                text: extraButtons[i].text,
                tabIndex: i
            });
            brandButton.addClass("sobytes-brand-button-" + i);
            $(".sobytes-brand-button-" + i).html("<a onclick='return false;' href='#'><img id='sobytes-live-image' width='20' src='" + extraButtons[i].image + "' /></a>");
        };
        var last_value = 0;
        var offline_test = 0;
        videoPlayer.on('timeupdate', function() {
            $("#sobytes-liveplayer-offline-message").hide();
            if (videoPlayer.currentTime() === last_value) {
                if (offline_test > 3) {
                    videoPlayer.userActive(true);
                    $("#video .vjs-live-display").text("OFFLINE");
                    $("#video .vjs-remaining-time-display").text("OFFLINE");
                    $("#sobytes-live-image").attr("src", "/images/circle_red.png");
                    offline_test = 0;
                }
                offline_test++;
            } else {
                offline_test = 0;
                $("#video .vjs-live-display").text("LIVE");
                $("#video .vjs-remaining-time-display").text("LIVE");
                $("#sobytes-live-image").attr("src", "/images/circle_green.png");
            }
            last_value = videoPlayer.currentTime();
        });
        videoPlayer.on('error', function() {
            $("#sobytes-mediajs-broadcaster-video-mobile-" + options.Pid).append('<span id="sobytes-liveplayer-offline-message">' + options.OfflineMessage + '. <a onclick="window.location.reload(); return false;" href="#">Refresh</a></span>');
            $("#sobytes-liveplayer-offline-message").css("opacity", 1);
        });
    }
});
~~~

The reason there is a safari call at the top is because safari does not handle rtmp streaming very well.

**Comment by sackos** [comment]
Hi @sobytes I really liked how you made use of timeupdate function to get around this issue. I'll certainly try to see if that could fit into my application. Thanks a lot!

**Comment by gesinger** [comment]
Sorry this ticket has gone a long time without much attention. There are a couple of approaches, depending on what you're looking for.

For the case where the live stream isn't a valid URL/stream yet: videojs-contrib-hls only focuses on playing provided HLS streams. Once the stream is provided to the player, videojs-contrib-hls expects the stream to be active and valid. However, this could be a good use-case as a plugin outside of videojs-contrib-hls (such that a stream is only set once it is live), or can be handled on the server by having a live stream running but using an image or simple animation as a placeholder.

For the case where the live stream is running, but you want to know when it transitions from some placeholder to the proper live stream: this could be a good use case for in-band metadata: https://github.com/videojs/videojs-contrib-hls#in-band-metadata . When the live stream starts (switch from the placeholder), the segment could come with some metadata to say that the stream is starting.

Hope these help, and thanks for posting and the shared workaround code.
