### ISSUE TITLE
Firefox: unresponsive script

### ISSUE THREAD

**Issue by RavWar** [videojs/videojs-contrib-hls#781]
I've encountered a very strange bug on Firefox. Depending on the number of links on the page and the size of hls playlist - Firefox may get unresponsive and result in this message:

![hls](https://cloud.githubusercontent.com/assets/675182/16903818/61d513fe-4c91-11e6-9bb6-0538aa853ab1.png)

Example: http://jsbin.com/silupudibo/edit?html,console,output
I've used a rather small playlist and had to compensate with a larger number of links. With bigger playlists link count can be much lower to cause significant delays and unresponsiveness.

On latest versions of Chrome and other browsers that i could get my hands on - everything works smoothly.

Btw, i had to go through hell to narrow down this issue, hope i'm not delusional and this thing exists :smile:

**Comment by RavWar** [comment]
I've found the issue: http://jsbin.com/fibuqawaxe/edit?html,output
Modification or removal of \<base\> tag in Firefox causes such freezes, but only if there are sufficient \<a\> tags present on the page. Probably Firefox has some kind of link re-validation logic on each \<base\> change.

This is a consistent problem which needs to be fixed. Not sure if reporting this bug (or maybe feature :smile:) inside Firefox bug tracker would yield anything anytime soon. We can try switching to a more robust solution like one hls.js has: https://github.com/dailymotion/hls.js/blob/master/src/utils/url.js

**Comment by forbesjo** [comment]
Should be fixed now with v3.6.12
