### ISSUE TITLE
CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED on Nexus 6P Chrome

### ISSUE THREAD

**Issue by mattsobo** [videojs/videojs-contrib-hls#782]
I created a m3u8 variant playlist with Apple's mediafilesegmenter and variantplaylistcreator.  The following playlist https://dl.sorcetrainingsystems.com/hls/matt/STS_SinDeqLvl1_01/STS_SinDeqLvl1_01z.m3u8 works successfully on my laptop with videojs-contrib-hls however on my Nexus 6p using Chrome I get an error.

http://jsbin.com/quqeviyoce/edit?html,output
http://sorcetrainingsystems.com/wp-content/themes/sorce/index_hls_test.php

Does this have something to do with the variant playlist?

**Comment by gkatsev** [comment]
contrib-hls doesn't run on Android yet, though, we'll be looking soon into enabling it.
You must be using a feature that Chrome for Android doesn't support.

**Comment by mattsobo** [comment]
Thank you for your response.  I was debugging a little more and when I modified the master playlist no error code occurred.  Is videojs-contrib-hls unable to parse the master playlist from Apple?  Or is this a Chrome issue.

Same page with modified master playlist: http://sorcetrainingsystems.com/wp-content/themes/sorce/index_hls_test2.php

I removed the multiple audio references.

Before (Error Code 4):
```
#EXTM3U
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio1",NAME="audio1",DEFAULT=YES,AUTOSELECT=YES,FORCED=YES,CHANNELS="1"
#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=1301043,BANDWIDTH=1344861,CODECS="mp4a.40.2, avc1.4d401f",RESOLUTION=640x360,FRAME-RATE=29.970,CLOSED-CAPTIONS=NONE,AUDIO="audio1"
med/STS_SinDeqLvl1_01.m3u8
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio2",NAME="audio2",DEFAULT=YES,AUTOSELECT=YES,FORCED=YES,CHANNELS="1"
#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=2629437,BANDWIDTH=2688516,CODECS="mp4a.40.2, avc1.4d401f",RESOLUTION=1280x720,FRAME-RATE=29.970,CLOSED-CAPTIONS=NONE,AUDIO="audio2"
high/STS_SinDeqLvl1_01.m3u8
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio3",NAME="audio3",DEFAULT=YES,AUTOSELECT=YES,FORCED=YES,CHANNELS="1"
#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=535653,BANDWIDTH=573764,CODECS="mp4a.40.2, avc1.42c01e",RESOLUTION=416x234,FRAME-RATE=29.970,CLOSED-CAPTIONS=NONE,AUDIO="audio3"
lo/STS_SinDeqLvl1_01.m3u8
```

After (Success on Android Chrome browser):
```
#EXTM3U
#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=1301043,BANDWIDTH=1344861,CODECS="mp4a.40.2, avc1.4d401f",RESOLUTION=640x360,FRAME-RATE=29.970
med/STS_SinDeqLvl1_01.m3u8
#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=2629437,BANDWIDTH=2688516,CODECS="mp4a.40.2, avc1.4d401f",RESOLUTION=1280x720,FRAME-RATE=29.970
high/STS_SinDeqLvl1_01.m3u8
#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=535653,BANDWIDTH=573764,CODECS="mp4a.40.2, avc1.42c01e",RESOLUTION=416x234,FRAME-RATE=29.970
lo/STS_SinDeqLvl1_01.m3u8
```

**Comment by gkatsev** [comment]
contrib-hls can parse it and even supports multiple audio but it doesn't run on Chrome for Android at all, everything is done natively. I do know that Chrome for Android doesn't support multiple audio tracks right now so, removing those to get it working makes sense.
We'll be looking soon into enabling contrib-hls on Chrome for Android because it lacks features that we support and it supports MSE APIs which contrib-hls uses.
Thanks.

**Comment by mattsobo** [comment]
Thank you
