### ISSUE TITLE
Question: how to bring a player back to `live` moment after pause?

### ISSUE THREAD

**Issue by askaliuk** [videojs/videojs-contrib-hls#783]
Hello,

I'm working on non-standard feature for HLS live playback.
When a user clicks `pause` - a player stops buffering new data.
But I need to bring user back to `live` moment (obviously `live` in terms of player. not clock time) by offering special custom button.

I tried to approach this with `player.bufferedEnd()` and simply call `player.currentTime(player.bufferedEnd());`.
Unfortunately this approach resets player to 00:00 by unknown reason. Also it does not really work, because as I mentioned above, after pause a player stops buffering and I don't know `the latest available time point` anymore in order to seek into live as close as possible.

So my questions:
* why player resets to 00:00 if I try to seek it into `bufferedEnd` point?
* how to get `the latest time point`, which is the closest to live, so I can bring user back upon request after pause?

Thank you.

**Comment by gkatsev** [comment]
Thanks for moving the issue here.
Can you elaborate on what you mean by the player reseting to 00:00 when you seek to `bufferedEnd`? Is the new currentTime returning 0 or just the display of the control bar?
Perhaps what you actually want to use is `seekable` rather than `bufferedEnd`. And get seek to the end of the last seekable range available.

**Comment by askaliuk** [comment]
Thank you very much for quick response.

1. new `currentTime` returning 0. It's simple to repeat. Just call `player.currentTime(player.bufferedEnd());` at any point of time. It's basically `seeking to the future` attempt. You may also try `player.currentTime(player.bufferedEnd() + X);` to see the same behaviour. 

2. Thank you for an advice about `seekable`. I'll work on this approach.

**Comment by gkatsev** [comment]
Did that work for you?

**Comment by askaliuk** [comment]
Yes. `seekable` is exactly what I need

**Comment by gkatsev** [comment]
Awesome!

**Comment by arnaudgandibleux** [comment]
@askaliuk Can you put an example of the solution?

**Comment by askaliuk** [comment]
```
var player = ....

var _getSeekable = function() {
        var seekable = null;
        if (player.seekable().length > 0) {
          seekable = player.seekable().end(0);
        }

        return seekable;
    },

var customButtonClickHandler = function() {
   var seekable = _getSeekable();
   player.currentTime(seekable);
}
```
