### ISSUE TITLE
Firefox and Live HLS still not working

### ISSUE THREAD

**Issue by Tralapo** [videojs/videojs-contrib-hls#789]
## Description
Video.js HLS is till failing for me in Firefox with all the recent builds. After hitting play, the screen goes black and the loading circle will show and keep spinning forever. 

I can see it downloads the first three .ts files after hitting play, but does not show them. After that, it's only downloading the .m3u8 files over and over and over again.

The latest version works fine in every other browser I tested, only Firefox fails. The oldest build I have available does work in Firefox, version 2.1.1 I build in April. When I hit play on that version I see a still, hitting pause/play then starts the stream and it will stream perfectly. Never got that working again with any versions after 2.1.1.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Download the latest minified version of HLS from the Releases page.
2. Include Video.js v5.10 from CDN
3. Hit play

### Expected
Livestream.

### Actual
Nothing. Loading spinner and a black screen.

### Error output
No errors.

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 3.1.0

#### videojs
what version of videojs does this occur with?
video.js 5.10.7

#### browsers
what browser are affected?
* Firefox

#### Operating Systems
what platforms (operating systems and devices) are affected?
* Windows 10

### plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* No

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* No

**Comment by forbesjo** [comment]
Could you provide a reduced test case or sample live stream that is causing the issue?

**Comment by Tralapo** [comment]
@forbesjo I was just making one, when the latest Firefox-update got pushed to my browser, version 48.0.2, Windows 10 64-bit and the problem seems to be over now.

Both 2.1.1 and VideoJS 5.10 in my live environment as well as VideoJS 5.11 and VideoJS-HLS 3.5.3 seem to play just fine now in Firefox.

**Comment by forbesjo** [comment]
Sounds resolved
