### ISSUE TITLE
How to use player.Hls function

### ISSUE THREAD

**Issue by jtcoolrevo** [videojs/videojs-contrib-hls#790]
I try to use videojs with hls.
But this library is not working.
I found the following worning error
"VIDEOJS: WARN: player.hls is deprecated. Use player.tech.hls instead."

Maybe, I think that I use Hls function instead of src.
But Hls function is not found....

let me know, what wrong of mine.

**Comment by BrandonOCasey** [comment]
As long as you have video.js and HLS included in your page you should be able to use it like this (from the examples in the README). basically we initialize the player, and the call player.src with src set to a url and type set to an hls source type.
``` JavaScript
var player = videojs('some-video-id');

player.src({
  src: "http://solutions.brightcove.com/jwhisenant/hls/apple/bipbop/bipbopall.m3u8",
  type: 'application/x-mpegURL'
});
```

**Comment by gesinger** [comment]
Closing for now. If it's still a problem, would you be able to re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output)? Thank you.
