### ISSUE TITLE
Seems to slip in Firefox 

### ISSUE THREAD

**Issue by sobytes** [videojs/videojs-contrib-hls#793]
## Description

Hi all i am testing in firefox and it seems to be slipping or clicks you can notice with headphones in it only seems to be firefox.
http://output.jsbin.com/rehapexihi
### Expected

smooth playback
### Actual

Skips 
### Error output

no error output
## Additional Information

Please include any additional information necessary here. Including the following:
### Sources

Is a certain segment or source affected? please link to it below.
### videojs-contrib-hls

videojs-contrib-hls 3.2.0 And i have tried the latest version from git still the same
#### videojs

what version of videojs does this occur with?
video.js 5.10.2
#### browsers

what browser are affected?
Firefox
### plugins

are any other videojs plugins being used on the page? If so, please list them with version below.
Vast ads
### Other JavaScript

are you using any other javascript libraries or frameworks on the page? if so please list them below.
jQuery

**Comment by cdhowie** [comment]
Is this the same as #592?

**Comment by sobytes** [comment]
Any suggestions on why this might be happening or what I can look into to help try find a solution?

Thanks

**Comment by mattblaha** [comment]
@sobytes 

I believe this is the same issue as #592. I'm not sure if this is the more info you need, but I've noticed the popping/slipping seems to occur exactly as segments are changed. If the segments are ten seconds each, listen closely and you can hear it at every ten second interval.

Debugging this is beyond me, but hopefully that will give someone else a clue as to what's going on.

**Comment by waster** [comment]
The same for me for audio only ts stream.

**Comment by JackSimth** [comment]
I am seeing the same thing, with both audio and video (combined stream).  I'm fortunately testing with a CentOS server, and have full root access.  I actually went through and compared the apache logs to the underlying files:

What seems to me to be going on is that the player isn't actually buffering the segments in FireFox (that, or it stops playing to pull the next - either way).  The skip happens at segment borders, and when I went through the apache logs, my test client was pulling the segments every nine seconds, while the m3u8 file was reporting that the segments were eight seconds long (I'm rounding in both cases - 8.015 is close enough to 8 for my purposes, and the apache logs in question had a resolution of 1 second, but still, it was pulling less often than it should have).  I was also able to confirm this is what's going on by setting things up to exaggerate the issue - setting the stream to 8 mbps and then using tc (linux traffic control settings command) to limit the server to 10 mbps on that card exaggerated the issue to a serious degree - the fraction of a second skip I'd been dealing with became about six seconds long.  

So my conclusion is that it's either not actually downloading segments before they're needed, or it stops playing while it's downloading segments.  I'm only seeing this behavior in FireFox - I'm not seeing it in Chrome or Edge.

**Comment by JackSimth** [comment]
I should probably add a short log snippet showing the behavior from when I was doing some testing... sorry for the delay, I don't always think things through.

Apache log:
10.0.0.95 - - [23/Aug/2016:08:00:02 -0700] "GET /hlstest/main6.ts HTTP/1.1" 200 7294588
10.0.0.95 - - [23/Aug/2016:08:00:11 -0700] "GET /hlstest/main0.ts HTTP/1.1" 200 9155600
10.0.0.95 - - [23/Aug/2016:08:00:21 -0700] "GET /hlstest/main1.ts HTTP/1.1" 200 7279924
10.0.0.95 - - [23/Aug/2016:08:00:31 -0700] "GET /hlstest/main2.ts HTTP/1.1" 200 7230668

The m3u8 file that ffmpeg was spitting out at the moment of that last entry:
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:20
#EXTINF:8.003000,
main6.ts
#EXTINF:9.803000,
main0.ts
#EXTINF:8.002000,
main1.ts
#EXTINF:8.003000,
main2.ts
#EXTINF:8.002000,
main3.ts

**Comment by JackSimth** [comment]
Huh, that's interesting... following apache logs while looking at the underlying files with a simple while true loop:

It only seems to happen when the player is loading *just* the oldest entry.  For whatever reason, it doesn't always pre-load the three I've got listed.  When it starts with the middle or last entry, everything's fine for a long, long time.  

Is there any way to change the player behavior such that it tries to load at least three segments always (maybe an initialization variable)?

**Comment by JackSimth** [comment]
This snapshot was generated by way of a simple while true loop running on the server to give me a nice live view of what my browser was pulling and what the server was showing.

#EXTM3U
#EXT-X-TARGETDURATION:7
#EXT-X-VERSION:4
#EXT-X-MEDIA-SEQUENCE:608
#EXTINF:8.004933,
asegment.8.ts?stream=5&cam=AWeRTla4wtLAtfca&time=1473435188
#EXTINF:7.995000,
asegment.9.ts?stream=5&cam=AWeRTla4wtLAtfca&time=1473435196
#EXTINF:7.976022,
asegment.10.ts?stream=5&cam=AWeRTla4wtLAtfca&time=1473435204
Fri Sep  9 08:33:33 PDT 2016
10.0.0.95 - - [09/Sep/2016:08:32:45 -0700] "GET /hls/asegment.1.ts?stream=5&cam=AWeRTla4wtLAtfca&time=1473435132 HTTP/1.1" 200 1973436
10.0.0.95 - - [09/Sep/2016:08:32:48 -0700] "GET /hls/alayer.m3u8?stream=5&cam=AWeRTla4wtLAtfca HTTP/1.1" 200 308
10.0.0.95 - - [09/Sep/2016:08:32:53 -0700] "GET /hls/asegment.2.ts?stream=5&cam=AWeRTla4wtLAtfca&time=1473435140 HTTP/1.1" 200 1990732
10.0.0.95 - - [09/Sep/2016:08:32:55 -0700] "GET /hls/alayer.m3u8?stream=5&cam=AWeRTla4wtLAtfca HTTP/1.1" 200 308
10.0.0.95 - - [09/Sep/2016:08:33:01 -0700] "GET /hls/asegment.3.ts?stream=5&cam=AWeRTla4wtLAtfca&time=1473435148 HTTP/1.1" 200 1976068
10.0.0.95 - - [09/Sep/2016:08:33:02 -0700] "GET /hls/alayer.m3u8?stream=5&cam=AWeRTla4wtLAtfca HTTP/1.1" 200 308
10.0.0.95 - - [09/Sep/2016:08:33:09 -0700] "GET /hls/asegment.4.ts?stream=5&cam=AWeRTla4wtLAtfca&time=1473435156 HTTP/1.1" 200 1983400
10.0.0.95 - - [09/Sep/2016:08:33:09 -0700] "GET /hls/alayer.m3u8?stream=5&cam=AWeRTla4wtLAtfca HTTP/1.1" 200 308
10.0.0.95 - - [09/Sep/2016:08:33:16 -0700] "GET /hls/alayer.m3u8?stream=5&cam=AWeRTla4wtLAtfca HTTP/1.1" 200 308
10.0.0.95 - - [09/Sep/2016:08:33:17 -0700] "GET /hls/asegment.6.ts?stream=5&cam=AWeRTla4wtLAtfca&time=1473435172 HTTP/1.1" 200 1972496
10.0.0.95 - - [09/Sep/2016:08:33:20 -0700] "GET /hls/alayer.m3u8?stream=5&cam=AWeRTla4wtLAtfca HTTP/1.1" 200 308
10.0.0.95 - - [09/Sep/2016:08:33:27 -0700] "GET /hls/alayer.m3u8?stream=5&cam=AWeRTla4wtLAtfca HTTP/1.1" 200 308
10.0.0.95 - - [09/Sep/2016:08:33:27 -0700] "GET /hls/asegment.7.ts?stream=5&cam=AWeRTla4wtLAtfca&time=1473435180 HTTP/1.1" 200 1991108
10.0.0.95 - - [09/Sep/2016:08:33:27 -0700] "GET /hls/asegment.8.ts?stream=5&cam=AWeRTla4wtLAtfca&time=1473435188 HTTP/1.1" 200 1970240
10.0.0.95 - - [09/Sep/2016:08:33:28 -0700] "GET /hls/asegment.9.ts?stream=5&cam=AWeRTla4wtLAtfca&time=1473435196 HTTP/1.1" 200 1976068

-	Fixed itself for a while when it decided to load all three.  Then eventually crashed again, but it took a while.

**Comment by react2k** [comment]
I think I'm seeing this same issue with FF 48.0.1 on OSX.

What I notice from network inspector is that, upon pressing play, Chrome immediately loads 3 segments in quick succession to build a substantial buffer. By contrast, FF only loads the first segment then waits until 10 seconds later to try loading the next one, really too late to maintain consistent play.

Seems to only affect live HLS feeds via Wowza for us. The bipbop_16x9_variant demo video pre-loads segments consistently in both browsers.

**Comment by gesinger** [comment]
The audio pops/clicks in Firefox were fixed as part of https://github.com/videojs/videojs-contrib-media-sources/pull/104 and https://github.com/videojs/mux.js/pull/120 . Thank you all for reporting the issue and the added information.
