### ISSUE TITLE
Is this plugin being replaced?

### ISSUE THREAD

**Issue by jgubman** [videojs/videojs-contrib-hls#797]
The README on https://github.com/Peer5/videojs-contrib-hls.js claims this plugin is being replaced, is that true?

**Comment by gkatsev** [comment]
I think that README misleading. It is a replacement for this project using hlsjs. This project is still well and alive.

**Comment by mmcc** [comment]
Yeah I think they mean it's a replacement for this project if you'd prefer
to use HLS.js, not that the project actually replaces this one.

The wording is confusing, though, we should put together a PR to clarify a
little (or see if they will).

-- 
Matthew McClure

**Comment by gkatsev** [comment]
Yeah, making a PR would be good. There's an issue on that project in the meantime.

**Comment by whadar** [comment]
We accepted the PR - We didn't mean to *replace* this plugin. 
Apologies again.

**Comment by gkatsev** [comment]
Thanks for being responsive :)
