### ISSUE TITLE
One missing chunk causes playback stop

### ISSUE THREAD

**Issue by mkhazov** [videojs/videojs-contrib-hls#799]
## Description
If there's a problem with loading one of the chunks, video stops with error `A network error caused the media download to fail part-way.`

## Sources
Playlist:
https://static.life.ru/posts/2016/06/421354/video/9c44566550edb876d50956a288cc44e3-480.m3u8

Lost chunk (404):
https://static.life.ru/posts/2016/06/421354/video/9c44566550edb876d50956a288cc44e3-4806.ts

## Steps to reproduce
1. Play the hls video
2. One segment is not loaded due to some network error

### Expected
Missing chunk should be skipped, video should continue playing.

### Error output
Video stops, displays the error message and wont play again
```
VIDEOJS: WARN: Problem encountered with the current HLS playlist. No suitable alternatives found.
VIDEOJS: ERROR: (CODE:2 MEDIA_ERR_NETWORK) A network error caused the media download to fail part-way.
```

### videojs-contrib-hls version
videojs-contrib-hls 3.3.0

### videojs version
video.js 5.11.0

**Comment by forbesjo** [comment]
If this condition is encountered in a master-playlist with multiple media-playlists,, we will blacklist the currently playing media-playlist and switch to another. In this case, there are no other renditions or media-playlists, and the blacklist logic triggers the error. This is as designed.

**Comment by vojneski** [comment]
Hi,
We have the same problem with HLS.
We use Video.js 5.11.6 and videojs-contrib-hls 3.5.3. 
For some reason when one .ts segment return 404, player stop playing video. 
Аlso happens with VOD HLS content. When first chunk is missing player cannot start playing. 
When we try with desktop player like MPV player, player ignore missing chunk and continue to play.

**Comment by rditreeni** [comment]
Hi, Use below set.

<link href="https://cdnjs.cloudflare.com/ajax/libs/video.js/5.13.0/video-js.min.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/video.js/5.13.0/video.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/3.5.3/videojs-contrib-hls.min.js"></script>

**Comment by rditreeni** [comment]
```
<link href="https://cdnjs.cloudflare.com/ajax/libs/video.js/5.13.0/video-js.min.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/video.js/5.13.0/video.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/3.5.3/videojs-contrib-hls.min.js"></script>
```

**Comment by vojneski** [comment]
Thanks for reply.
We test with this settings but unsuccessful.

Here is test URLs:

http://*54*89*99*99/chunk1/master.m3u8 - missing chunk 1
http://*54*89*99*99/chunk2/master.m3u8 - missing chunks 5, 10, 15, 20
http://*54*89*99*99/chunk3/master.m3u8 - missing chunks 1, 5, 10, 15, 20

We test with other player and player continue playing video.

**Comment by blagojcoJuca** [comment]
+1 for the same problem. As @mkhazov suggested, can that chunk be skipped or the player tried to reconnect to the stream (that is what the other players is doing)?

Thanks

**Comment by mkhazov** [comment]
@forbesjo, @imbcmdth 
Can this issue be re-opened and considered as a feature request?

**Comment by blagojcoJuca** [comment]
Here is another case: 

The player is playing several minutes and for some reason in some time when he try to her the m3u8 playlist it is receiving "Not found 404", If we manually download the the same link 1 second after, the link is reachable and the m3u8 playlist can be downloaded. Is possible the player to make few retries before he give up?

Attached is an image.
Thanks,
Blagojco

![not_found](https://cloud.githubusercontent.com/assets/6799344/18779410/3c14a57c-8179-11e6-8f3d-d7cc24379e26.png)

**Comment by yonimor** [comment]
+1

**Comment by lilyxs** [comment]
Two after to request TS file request is not too small, even if the file is still behind the request to the error still will not continue to play video, use the videojs@version 5.19 videojs-contrib-hls@version 5.3.3
