### ISSUE TITLE
unable to play audio only stream

### ISSUE THREAD

**Issue by tingulfsen** [videojs/videojs-contrib-hls#803]
## Description

In non-Safari browsers, I am unable to play audio only streams. Video works fine across all my browsers, though. This is my HTML:

```
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleHLS</title>
    <link href="http://vjs.zencdn.net/5.10.7/video-js.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/video.js/5.10.7/video.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/3.1.0/videojs-contrib-hls.js"></script>
  </head>
  <body>
    <h1>VideoJS HLS Plugin Loading from Wowza on localhost</h1>
    <audio id="wowza_audio" class="video-js vjs-default-skin" controls preload="auto" data-setup='{}'>
      <source src="http://localhost:1935/HLSTest/mp3:downrage.mp3/playlist.m3u8" type='application/x-mpegurl'/>
    </audio>
  </body>
</html>
```

This example works in Safari, but not in any other browser I've tried.

## Sources
This appears to apply to all sources I've tried (plain MP3 files).

## Steps to reproduce
Try playing an audio-only source as shown above.

### Expected
I expected the audio to play. Instead, when I press the play button, the player displays the (correct) length of the track and appears to go directly to pause. The progress bar just sits paused:

![screen shot 2016-08-01 at 2 31 03 pm](https://cloud.githubusercontent.com/assets/3740294/17309898/fe4bf6c0-57f5-11e6-9de9-649a599d7942.png)

### Error output
I am not getting any console output at all.

## Additional Information
Am I correct to assume that I should be able to play a regular MP3 file with videojs-contrib-hls? I've done a little JavaScript debugging, but if anyone has any ideas of where to start with this, I would really appreciate insights.

### videojs-contrib-hls version
videojs-contrib-hls 3.1.0 (the only version I've tried)

### videojs version
video.js 5.10.7

### Browsers
* Chrome 54.0.2815.0 (Official Build) canary (64-bit)
* Chrome 51.0.2704.103 (64-bit)
* Opera 38.0.2220.41
* Firefox 47.0

### Platforms
Mac OS X 10.10.5 64-bit

### Other Plugins
None

### Other JavaScript
None

**Comment by gkatsev** [comment]
I believe we don't support mp3s currently. Does it work if you use AAC?

**Comment by tingulfsen** [comment]
Thank you very much! It does indeed work if I re-encode using AAC.
