### ISSUE TITLE
Create releases for tags after v3.1.0

### ISSUE THREAD

**Issue by piotr-cz** [videojs/videojs-contrib-hls#805]
## Description
[Releases page](https://github.com/videojs/videojs-contrib-hls/releases) doesn't list latest releases, you have to click on _show x newer tags_ button.

Moreover releases doesn't include changes (listed in CHANGELOG.md) in meta description.

Changelog could be in format specified at [http://keepachangelog.com/] to separate _Added_, _Changed_ and _Fixed_ issues.

## Steps to reproduce

1. Click on [Releases page](https://github.com/videojs/videojs-contrib-hls/releases)
2. Releases after v3.1.0 doesn't show up
3. Available releases doesn't have meta description.

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 3.1.0

**Comment by BrandonOCasey** [comment]
I think I created them all and added all of the files for them. Thanks for bringing this to our attention

**Comment by piotr-cz** [comment]
Thank You!
