### ISSUE TITLE
Calling load() after play() puts contrib-hls in a strange state

### ISSUE THREAD

**Issue by nickygerritsen** [videojs/videojs-contrib-hls#806]
## Description

When you call `.load()` on the player after contrib-hls starts playing, the video will stop playing and the only way to get the player to work again is to load a new source.

See http://jsbin.com/kalarewido/edit?html,output for an example.
## Steps to reproduce

Explain in detail the exact steps necessary to reproduce the issue.
1. Initialize a video.js player with an HLS playlist
2. Call `.play()` on the player
3. Call `.load()` on the player
### Expected

Other types of videos just continue playing and ignore the load. I'd expect contrib-hls to do the same.
## Additional Information

As soon as you call `.load()`, `player.tech_.sourceHandler_` becomes `null`.
### videojs-contrib-hls version

videojs-contrib-hls 3.1.0 - 3.4.0 at least, but probably also others
### videojs version

video.js 5.10.x at least, but probably also others

**Comment by Kasher** [comment]
:+1: 
still happens in version 3.7.0-beta4

**Comment by forbesjo** [comment]
Moving to VHS
