### ISSUE TITLE
cant play in firefox

### ISSUE THREAD

**Issue by javadi69** [videojs/videojs-contrib-hls#809]
My player don't play hls video in firefox, in chrome and edge is fine.
Actually i think the problem is from my ts files,
I use ffmpeg in debian 8 to convert and generate hls file.
`ffmpeg -i input.mp4 -y -movflags +faststart -pix_fmt yuv420p -vbsf h264_mp4toannexb -flags -global_header  -c:v libx264 -c:a libfdk_aac -vbr 3 -profile:v baseline -level 3 -b:v 300k -b:a 96k -force_key_frames "expr:gte(t,n_forced*3)" -vf scale="trunc(oh*a/2)*2:240" -hls_list_size 0 -hls_time 3 hls/out_240p.m3u8`
when i convert video without audio, it's working in firefox with no problem,
but with audio, it won't work and the console says: NotSupportedError: Operation is not supported
Can anyone help me to fix this?
Thanks

**Comment by Vagdish** [comment]
http://caniuse.com/#search=aac
Firefox doesn't seem to natively support aac audio. Try to encode your audio stream with libmp3lame instead of libfdk_aac.

**Comment by forbesjo** [comment]
@javadi69 Firefox should support AAC audio. We are not sure exactly what is going with your encoding settings. We can't provide support for using FFMPEG to generate HLS because that is outside the scope of this project.

**Comment by jaq316** [comment]
I've also seen this. If you open the stream directly in Firefox, it plays, so FF definitely supports AAC audio.

**Comment by vantassell** [comment]
Firefox doesn't support AAC directly. It defers to the OS to provide proprietary codecs. That's why your firefox has audio (because your os is providing the codec) and your fathers firefox has no audio (because his os is not providing the codec).
