### ISSUE TITLE
Video stretches and truncates on chrome.

### ISSUE THREAD

**Issue by videoen** [videojs/videojs-contrib-hls#811]
## Description
Video playback with 480p videos stretches and truncates on chrome with HTML5 tech.
We are using wowza for HLS streaming.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Play any 480p video using Flash tech on chrome.
2. Compare the same with HTML tech there is a significant stretch and truncation in the video.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
5.11.0
#### browsers
chrome 52.
#### OSes
windows.
### plugins
videojs-contrib-hls. 3.3.0

**Comment by se7en007** [comment]
Just passing by, this issue is possibly due to bug in chrome version 52. FYI:- The same video(the one that I am testing) plays well on chrome v51, firefox and safari.

**Comment by forbesjo** [comment]
Could you provide an example source that demonstrates this issue for debugging, thanks!

**Comment by se7en007** [comment]
Sorry, but that will be difficult as it is from our platform. You can try any video which has rotation metadata set. Use imagemagick to get video which has orientation. You can check the bug here:  https://bugs.chromium.org/p/chromium/issues/detail?id=637312

**Comment by se7en007** [comment]
Sorry, you should check issue: (bug 632624). The earlier one is duplicate. This bug manifests as the rotated video is stretched to fit to the unrotated video size.

**Comment by forbesjo** [comment]
Looks like this is fixed in Chrome 53
