### ISSUE TITLE
Alternate audio playlists either fail on iOS or Chrome when audio track muxed into main playlist is present

### ISSUE THREAD

**Issue by Prendo93** [videojs/videojs-contrib-hls#812]
## Description

Briefly describe the issue.
When using a master playlist with both audio muxed into the video segments AND alternative audio playlists (totally separate segments), playback fails on either ios or chrome depending on how you signal the audio track in the main playlist.

The IOS compatible way is to signal with an audio line without a URI attribute as below:
`#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="en",NAME="Game Audio",DEFAULT=YES`

The Chrome (and I assume all mux.js-using browser) compatible way is:
`#EXT-X-MEDIA:URI="video/stream.m3u8"TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="en",NAME="Game Audio",DEFAULT=YES`
## Sources

You can view the affected sources here
ios compatible: http://dev-media.spalk.co/hls-sync/139/95/master-ios.m3u8
chrome compatible: http://dev-media.spalk.co/hls-sync/139/95/master.m3u8
## Steps to reproduce

Explain in detail the exact steps necessary to reproduce the issue.
1. Load either source in the other (incompatible) browser, using standard instructions on [readme.md](https://github.com/videojs/videojs-contrib-hls#getting-started).
2. Video playback will commence, sometimes with Audio, mostly without.
3. When trying to change the audio track, playback will either stall (ios) or just remain silent (Chrome).

Enter in the javascript console:
`player.audioTracks()[1].enabled = true;`
4. Load the other source, and you will see playback and switching work as expected.
### Expected

As above
### Error output

Cannot see any in the console.
### videojs-contrib-hls version

what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 3.4.0
### videojs version

what version of videojs does this occur with?
video.js 5.10.7
### Browsers

what browsers are affected? please include browser and version for each
*Chrome
*Safari, iOS Safari
### Platforms

what platforms are affected? please include operating system and version or device and version for each
- Tested on Mac OS X and iOS
### Other Plugins

are any other videojs plugins being used on the page? If so, please list them with version below.
*No
### Other JavaScript

are you using any other javascript libraries or frameworks on the page? if so please list them below.
*No

**Comment by Prendo93** [comment]
Confirmed same behaviour on Mac OS X FireFox

**Comment by forbesjo** [comment]
@gesinger check out https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8 and see if this fixes it

**Comment by Prendo93** [comment]
Update: The renditions were missing the audio codec in both manifests, I understand that the ios implementation can handle that, but the HTML5 cannot, hence the failure for the 'URI-less' manifest in HTML5 player.

**Comment by gesinger** [comment]
Thanks for the update @Prendo93 . Please let us know if you run into any other issues.
