### ISSUE TITLE
Support Alternate Audio in Android

### ISSUE THREAD

**Issue by Prendo93** [videojs/videojs-contrib-hls#813]
## Description
Briefly describe the issue.
Android does not show options for alternative audio when available.

Also when doing USB remote debugging ``player.audioTracks()`` returns undefined.

## Sources
Demonstration link

http://dev-media.spalk.co/hls-enc-test/

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Visit the above site in Android Chrome
2. Observe that there are no audio options rendered, and that the Change audio button does not do anything
3. Visit the page in Firefox, and observe that the audio should play
(Side note, the update to Chrome 52 seems to have broken alternate audio)

### Expected
Should be able to see and select from alternate Audio tracks

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 3.4.0

### videojs version
what version of videojs does this occur with?
video.js 5.11.0

### Browsers
what browsers are affected? please include browser and version for each
* Android Chrome

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* Android

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* No

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* No

**Comment by gkatsev** [comment]
Unfortunately, right now we don't run contrib-hls on Android, so, what you're seeing is a native behavior and Chrome for Android doesn't support multiple audio text tracks.
We are investigating enabling contrib-hls on Chrome for Android but haven't done so yet because we want to test it thoroughly. We've previously just let the native functionality take over because it generally provides a good enough experience and it's always nice when we can do less work and let the browser handle everything.

**Comment by Prendo93** [comment]
Thanks @gkatsev, I didn't realise that was native Android behaviour. Is the enabling of contrib-hls on android on the roadmap, or available on android behind a flag? Alternative audio tracks are a high priority for our project.

Kind regards,

**Comment by gkatsev** [comment]
It's on the road map. We probably should add an option to force it.

**Comment by benweidig** [comment]
Any updates in this issue?

**Comment by gesinger** [comment]
Hey @benweidig , if you'd like to override native HLS playback on Android, you can now use https://github.com/videojs/videojs-contrib-hls#overridenative . Let us know if you find any issues.

**Comment by benweidig** [comment]
Hi @gesinger,  I've tried overrideNative.

No matter what I can't get a language switcher to show up in Chrome in Android.
Firefox on Android is working as expected.

Maybe I dig a little deeper into the code tomorrow and debug it a little more to better understand where my problem is.

Thx!
