### ISSUE TITLE
Segment sorting seems to access an undefined attribute of a segmentObj

### ISSUE THREAD

**Issue by ColdHeat** [videojs/videojs-contrib-hls#815]
## Description

While trying to play an m3u8 I get the error `videojs.hls.js:9454 Uncaught TypeError: Cannot read property 'segments' of undefined`

With some console statements it seems that the type is being set to combined but the segmentObj does not have an associated combined atribute. 

I've tried changing combined to video but this seems to cause other problems. 
## Sources

Dont have a publically available source, sorry. 
### Expected

A HLS video playing. 
### Error output

![image](https://cloud.githubusercontent.com/assets/166333/17616082/66ca8e30-6040-11e6-90da-8063bc0e0ba0.png)
### videojs-contrib-hls version

Latest tagged release
### videojs version

Latest tagged release
### Browsers

Latest Chrome & Latest Firefox
*

**Comment by Poordeveloper** [comment]
I have similar issue, but mine is

> videojs-contrib-hls.js:3435 Uncaught TypeError: Cannot read property 'length' of undefined

```
if (!playlist.segments.length) {
        return;
}
```

> segments is undefined.

This happens when videojs failed to load m3u8 file, and tried to src again.

**Comment by forbesjo** [comment]
@ColdHeat does your stream start with combined audio/video and proceed to have segments with one or the other but not both?

**Comment by forbesjo** [comment]
@Poordeveloper This looks to be an unrelated issue, could you open as a separate issue.

**Comment by ColdHeat** [comment]
To the best of my knowledge it does not. It is a feed from a home security camera.

**Comment by royendgel** [comment]
same here mine is on line 15048
`videojs-contrib-hls.js:15048 Uncaught TypeError: Cannot read property 'segments' of undefined`

![screenshot 2016-10-01 23 19 42](https://cloud.githubusercontent.com/assets/1261046/19018414/9632e04a-882d-11e6-8de5-ac1c1181d6d3.png)
the type is set to "combine"
![screenshot 2016-10-01 23 22 39](https://cloud.githubusercontent.com/assets/1261046/19018426/0110e588-882e-11e6-9991-40c78c23f768.png)

I hard coded the type to "video" but gives problem with other things.

**Comment by Ambroos** [comment]
I am encountering this exact same issue. segment.type is set to combined. If needed I can provide some examples privately.

**Comment by forbesjo** [comment]
I've published version 1.1.1 that reverts the changes between 1.1.0 and 1.0.3, this should fix your issue. The changes in 1.1.0 are now part of 2.0.0

**Comment by ColdHeat** [comment]
Is the new aes-decrypter in v3.6.12 ?

**Comment by forbesjo** [comment]
the aes-decripter built into the videojs-contrib-hls dist file is 1.1.0 so you shouldn't have this problem if you're using that. If you're using browserify it'll automatically pick up 1.1.1 because it's in our semver range.

**Comment by gesinger** [comment]
Closing for now. Please give the latest version of videojs-contrib-hls (as of this comment, v5.3.3) a shot. If it's still a problem, please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.

**Comment by ghaydarov** [comment]
I am getting the same error with latest versions.
> Uncaught TypeError: Cannot read property 'segments' of undefined


Content of m3u8
> #EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:12
#EXT-X-KEY:METHOD=AES-128,URI="http://localhost:3000/my-data-key.key",IV=0x41c086d257f79afc44e91d10bc9c05b5
#EXTINF:11.344667,
Chapter_1_hls1M00000.ts
#EXTINF:11.261233,
Chapter_1_hls1M00001.ts
#EXTINF:7.507489,
Chapter_1_hls1M00002.ts
#EXTINF:11.261244,
Chapter_1_hls1M00003.ts
#EXTINF:5.255233,
Chapter_1_hls1M00004.ts
#EXT-X-ENDLIST

Full error:

> Uncaught TypeError: Cannot read property 'segments' of undefined
    at http://localhost:3000/assets/videojs-contrib-media-sources/dist/videojs-con…85dfba2372d7d02f621728fda9c4517280661bbdf8f92a10b59fd87c.js?body=1:2351:25
    at Array.reduce (native)
    at VirtualSourceBuffer.processPendingSegments_ (http://localhost:3000/assets/videojs-contrib-media-sources/dist/videojs-con…85dfba2372d7d02f621728fda9c4517280661bbdf8f92a10b59fd87c.js?body=1:2346:45)
    at VirtualSourceBuffer.done_ (http://localhost:3000/assets/videojs-contrib-media-sources/dist/videojs-con…85dfba2372d7d02f621728fda9c4517280661bbdf8f92a10b59fd87c.js?body=1:2184:12)
    at Worker.VirtualSourceBuffer.transmuxer_.onmessage (http://localhost:3000/assets/videojs-contrib-media-sources/dist/videojs-con…85dfba2372d7d02f621728fda9c4517280661bbdf8f92a10b59fd87c.js?body=1:2009:22)
