### ISSUE TITLE
[Feature] Count Viewers

### ISSUE THREAD

**Issue by DoM1niC** [videojs/videojs-contrib-hls#823]
Hey :)

HLS work perfect with OBS to Nginx RTMP, but I have a problem to get the viewer of my Livestream.... :(

A simple feature will to track the play js function to a count current views ....

**Comment by dmlap** [comment]
You would need a server somewhere to add up all of those viewer counts, and then some way of querying for the current count of viewers from that server. That's definitely doable but this project is focused on the in-browser aspects of live streaming so we wouldn't take on something like that. Sorry!

**Comment by hoodsy** [comment]
@DoM1niC did you have any luck getting a viewer count? I'm struggling with this as well.
