### ISSUE TITLE
seeking within live streaming

### ISSUE THREAD

**Issue by AlricLou** [videojs/videojs-contrib-hls#826]
how can I seek my hls video while m3u8 file doesn't have #EXT-X-ENDLIST tag?

**Comment by BrandonOCasey** [comment]
#785

**Comment by adgoncal** [comment]
I am currently trying to achieve this. So far, this is what I have:

```javaScript
var lastDuration = Infinity;
player.on('timeupdate', function() {
  var duration = player.duration();
  if(!isFinite(duration)) {
    var start = player.seekable().start(0);
    var end = player.seekable().end(0);
    if(start !== end) {
      // 5 seconds offset to prevent freeze when seeking all the way to left
      duration = end - start - 5;
      if(duration >= 0 && duration !== lastDuration) {
        player.duration(duration);
        lastDuration = duration;
      } else if(isFinite(lastDuration)) {
        player.duration(lastDuration);
      }
    }
  }
});
```

Problems I have found with this:

- When a new segment is loaded, `player.duration()` is set to `Infinity` and there is a flicker on the `controlBar` because the `vjs-live` class is added and immediately afterwards it is removed due to the above code setting `duration` to a finite number.

**Comment by Eriken** [comment]
@adgoncal 
Did you improve on your fix?

**Comment by adgoncal** [comment]
@Eriken 
No, I did not.
I tried using https://github.com/toolbox-tve/videojs-dvrseekbar but ran into some of the same issues. 
In the end I had to write a custom seekbar because the flicker was not acceptable. 

Something like this:

```javaScript
var seekbarTracker = {
  duration: 0,
  time: 0,
  seekPercent: 0,
  hasDVR: false,
};

player.on('timeupdate', throttle(function() {
  var hasDVR = false;
  var duration = Math.floor(getDuration(player) * 1000);
  var time;
  var seekPercent;
  
  if(duration) {
    seekbarTracker.duration = duration;

    // constrain time
    time = Math.floor(Math.max(0, Math.min(duration, player.currentTime() * 1000)));
    seekbarTracker.time = time;
    seekPercent = time / duration;
    if(seekPercent !== seekbarTracker.seekPercent) {
      onSeekPercentChange(player, seekPercent, duration);
    }
    seekbarTracker.seekPercent = seekPercent;

    // duration is not Infinity, so if isLive() returns true, then player should have DVR.
    hasDVR = isLive(player);
  }

  seekbarTracker.hasDVR = hasDVR;
}, 100));

function getDuration(player) {
  var seekable = player.seekable();
  return seekable && seekable.length ? seekable.end(0) - seekable.start(0) : 0;
}

function onSeekPercentChange(player, seekPercent, duration) {
  var seekable = player.seekable();

  if(seekable && seekable.length) {
    // constrain currentTime
    player.currentTime(Math.max(0, Math.min(seekable.end(0), seekable.start(0) + (seekPercent * duration))));
  }
}

function isLive(player) {
  if(!isFinite(player.duration())) {
    return true;
  }

  var acceptableDelay = 30;
  var seekable = player.seekable();
  return seekable && seekable.length && seekable.end(0) - player.currentTime() < acceptableDelay;
}
```

**Comment by Eriken** [comment]
Thank you very much for the quick response!

I have very little experience with JS so sadly I could not get your example to work. Is the timeupdate event handler suppose to call a throttle function with such a big function parameter?

**Comment by adgoncal** [comment]
@Eriken 
Throttling is not required. What throttle does is take a function and limit how often it runs. If you throttle something to 100ms, then it will only run once every 100ms no matter how many times you call that function. The `timeupdate` event happens many times per second, but we don't really need to update the seekbar that often. You can use any throttling method for this. 

Throttle Examples

- https://remysharp.com/2010/07/21/throttling-function-calls
- http://benalman.com/projects/jquery-throttle-debounce-plugin/

The code I posted was not tested. It is not the exact code I am using, but a reduced (untested) version that serves as an example of how you can keep track of the seek position and implement your own seekbar. You can use it as a reference, but you may need to modify it.

**Comment by Eriken** [comment]
Ah, that makes sense. Thanks for your time!

I will post a working solution here when able.

**Comment by gesinger** [comment]
Thanks for the code @adgoncal . I'm going to close this issue though in favor of another that reflects the same issue: https://github.com/videojs/videojs-contrib-hls/issues/354

**Comment by sgromkov** [comment]
> When a new segment is loaded, player.duration() is set to Infinity and **there is a flicker** on the controlBar because the vjs-live class is added and immediately afterwards it is removed due to the above code setting duration to a finite number.

To remove flickering you can add next code to [dvrseekbar.js](https://github.com/toolbox-tve/videojs-dvrseekbar):

```
var Slider = _videoJs2['default'].getComponent('Slider');

Slider.prototype.update = function update() {
  // In VolumeBar init we have a setTimeout for update that pops and update to the end of the
  // execution stack. The player is destroyed before then update will cause an error
  if (!this.el_) {
    return;
  }

  // If scrubbing, we could use a cached value to make the handle keep up with the user's mouse.
  // On HTML5 browsers scrubbing is really smooth, but some flash players are slow, so we might want to utilize this later.
  // var progress =  (this.player_.scrubbing()) ? this.player_.getCache().currentTime / this.player_.duration() : this.player_.currentTime() / this.player_.duration();
  var progress = this.getPercent();
  var bar = this.bar;

  // If there's no bar...
  if (!bar) {
    return;
  }

  // Protect against no duration and other division issues
  if (typeof progress !== 'number' || progress !== progress || progress < 0 || progress === Infinity) {
    progress = 0;
  }

  // Convert to a percentage for setting
  var percentage = (progress * 100).toFixed(2) + '%';

  // Set the new bar width or height
  if(progress != 0) {
    if (this.vertical()) {
      bar.el().style.height = percentage;
    } else {
      bar.el().style.width = percentage;
    }
  }
};
```

Flickering is happened cause `progress` value sometimes `< 0` or `Infinity`. And Slider sets the `bar.el().style.width` to null, and then to real position. 

In my code I check the `progress` value, and if it null do not change the bar width. So, flickering is not happened to me now.

Then you should customize player css, to remove seekbar twitching. But it's much more easy, than the seekbar flickering problem. Something like this:
```
.vjs-dvrseekbar .vjs-dvrseekbar-progress-control {
  display: flex !important;
}
.vjs-dvrseekbar .vjs-live-button {
  width: auto;
  cursor: pointer; }

.vjs-dvrseekbar .vjs-live-button .label,
.vjs-dvrseekbar .vjs-live-button .vjs-live-label {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-align: center;
  -ms-flex-align: center;
  align-items: center;
  font-size: .7em;
  padding-left: 6px;
  padding-right: 6px;
  height: 100%;
}

.vjs-dvrseekbar .vjs-live-control {
  display: none;
}

.vjs-dvrseekbar .vjs-remaining-time {
  display: none;
}
```

**Comment by sgromkov** [comment]
@prashanthag can you show me your work example?

**Comment by sgromkov** [comment]
@prashanthag and could you try to use my branch of dvrseekbar.js: https://github.com/sgromkov/videojs-dvrseekbar/tree/fix-seekbar-flickering

Just take a videojs-dvrseekbar.js from it and try.
