### ISSUE TITLE
Better in-band metadata cues

### ISSUE THREAD

**Issue by imbcmdth** [videojs/videojs-contrib-hls#830]
## Intro
Videojs-contrib-hls currently creates TextTrack VTTCues from ID3 tags within the metadata track contained by the TS segments. Safari also creates Cues from ID3 data when playing back HLS natively. Right now the two cues are not the same.

This idea behind this proposal is to make them *functionally* the same.

ID3 tags are simply points-in-time and as such they do not have any concept of a duration. Cues on the other hand are designed to cover a span of time.

Right now, contrib-hls creates cues that start at the ID3 tag time and have a zero duration. There is an issue with certain browsers and zero-length cues so we want to move away from zero-length cues but do it in a way that is compatible with code already written for Safari's native id3-cues.

## The Draft Spec
The specification for in-band metadata suggests creating "ID3" cues that *start at zero* and end whenever the cue point is supposed to be fired. I know, I read that twice too because it sounds wrong but you can see for yourself in the document [Sourcing In-band Media Resource Tracks from Media Containers into HTML](https://dev.w3.org/html5/html-sourcing-inband-tracks/) section *3.5.a*.

It is important to note that the document above does **not** describe what Safari does. As usual, it marches to it's own tune.
```
Source ID3 Metadata:

      ID3      ID3      ID3
[------|--------|--------|-----]
|                              |
Start of video                 End of video

The Draft's Version of Cues:

      ID3      ID3      ID3
[------]
[---------------]
[------------------------]
```
## Safari
Emulating the entirety of Safari's behavior would be difficult because testing has uncovered that Safari changes the cue's start and end times somewhat dynamically.

In Safari, the cues are created with a `startTime` set to the time of the ID3 tag and an `endTime` that is set to the duration of the stream. When the player first enters the cue - the ID3 tag is triggered - the `endTime` is changed to be equal to the `startTime` of the *next id3 tag cue*.

We don't know why this is done dynamically when playback enters a cue instead of once when the cues are created.

```
Source ID3 Metadata:

      ID3      ID3      ID3
[------|--------|--------|-----]
|                              |
Start of video                 End of video

Apple's Version of Cues:

      ID3      ID3      ID3
       [--------]
                [--------]
                         [-----]
```

## Proposal
What we are thinking about implementing is a system that emulates the important parts of Safari's behavior without having to dynamically change the cues *too much*.

1. On each segment append, generate an array of ID3 tags ordered by time
1. If any cues in the metadata TextTrack contains the earliest ID3 tag in the array, set the end time of those cues to end at the earliest ID3 tag's time
1. Iterate through array of ID3 tags
  1. Create cues that start at the proper time and end at the start of the next ID3 tag in the array
  1. The cue for the last ID3 tag in the array should have an `endTime` that is set to either the `startTime` of next cue  in the metadata TextTrack *OR* `Number.MAX_VALUE` if there are no existing cues that come ofter this one in time
1. When `endOfStream` is called, set the `endTime` of any cues with an `endTime` of `Number.MAX_VALUE` to the video's duration

**Comment by gkatsev** [comment]
Thankfully that spec is an unofficial draft at the moment. I think the reason why Safari does these things so dynamically is because cues from id3 aren't made until basically `cuechange` triggers, so, safari doesn't know when to end the previous cue until that time. But you need to do it right because because otherwise `activeCues` will have multiple cues. This also seems like the flaw in that spec.

**Comment by forbesjo** [comment]
Closing since this is in progress
