### ISSUE TITLE
Authenticated playlists don't play back on Microsoft Edge

### ISSUE THREAD

**Issue by ellyjonez** [videojs/videojs-contrib-hls#831]
Microsoft Edge 13 & 14 doesn't appear to support the crossorigin attribute (see: http://stackoverflow.com/a/34596602/1642428). Because of this, adding crossorigin="use-credentials" to the video tag does not work, and playlists that require authentication won't play in native HLS on the Microsoft Edge browser. 

I realize this is an issue with Edge & the VideoJS HLS plugin uses native HLS when possible. Just wondering if there is any known workaround within VideoJS HLS that might help overcome this in Edge. I see a few other conversations about overriding the plugin's fallback to native HLS, and wonder if anyone has had any luck solving this problem by doing so and if there is any documentation or info on how to achieve this?

Thanks

**Comment by forbesjo** [comment]
We're currently looking into enabling MSE-based HLS over native functionality in certain browsers in order to work around the browser's various quirks to maintain consistent behavior across platforms. We're still in the process of investigation. Please keep an eye out for this change.

**Comment by AdamTyler** [comment]
@forbesjo has there been any progress on this investigation?

If it is still going to be a while, can you point me to a quick and dirty to force the plugin over the native browser hls?

**Comment by forbesjo** [comment]
A quick way to prioritize contrib-hls over native is to remove the `supportsNativeHls` check in https://github.com/videojs/videojs-contrib-hls/blob/master/src/videojs-contrib-hls.js#L681 and modify https://github.com/videojs/videojs-contrib-hls/blob/master/src/videojs-contrib-hls.js#L695 to `videojs.getComponent('Html5').registerSourceHandler(HlsSourceHandler('html5'), 0);` which will put contrib-hls first in the HTML5 sourceHandler list.

Note that you may have to load your video source with `player.src()` and not use a source element.

**Comment by AdamTyler** [comment]
Thanks for the reply. That does get contrib-hls to work over the native implementation (testing in Safari 9). It worked using the source element too.
There are some issues I'm seeing like getting error code 3 when seeking around or trying to replay a video but I guess that is to be expected since the plugin hasn't been developed to be used instead of the native.
