### ISSUE TITLE
Video on IE 11 (Win10) freezes after 10 seconds

### ISSUE THREAD

**Issue by elmehdielkettani** [videojs/videojs-contrib-hls#833]
## Description

On IE11, windows 10, the stream freezes 10 seconds after it starts (first segment).

Reproduced on multiple VMs just by trying the project test page: http://videojs.github.io/videojs-contrib-hls/
## Sources

http://videojs.github.io/videojs-contrib-hls/
## Steps to reproduce
1. Go to the project test page: http://videojs.github.io/videojs-contrib-hls/
2. Start the video
3. Wait until it gets 10s in.
   => The video freezes and does not resume.
### Expected

Video should keep playing
### Actual

Video freezes and can't be resumed
### Error output

No Error output in the console.
### videojs-contrib-hls version

videojs-contrib-hls 3.5.2
### videojs version

video.js 5.10
### Browsers

IE 11 on Win 10. Reproduced in the following versions:
- 11.545.1010586.0
### Platforms

Desktop Windows 10

**Comment by mrmckeb** [comment]
We're experiencing the same issue, not sure how to resolve.

**Comment by BrandonOCasey** [comment]
It is a known issue that IE11 has problems playing HLS video in HTML mode. We suggest forcing Flash mode (which we don't do in the demo page but probably should)
https://github.com/videojs/videojs-contrib-hls#known-issues

**Comment by paulomedia** [comment]
Hi,
In window 8 and window 10 with IE11 we have to forze always to tech flash to reproduce hls live/vod, but in windows 7 IE11 videojs detect that the browser don't support Media Extensions and change the tech to flash, we don't have to forze the change of tech.
versions used in tests:
videojs - 5.12.6
videojs-contrib-hls - 3.6.12

**Comment by daliwell** [comment]
This was the issue I referenced higher up in this issue: https://github.com/videojs/videojs-contrib-hls/issues/833#issuecomment-243481399

**Comment by gesinger** [comment]
Some version of IE11 have known issues playing back content using native HTML SourceBuffers. The workaround for these issues is to force the player to use flash when running on IE11. See https://github.com/videojs/videojs-contrib-hls#known-issues for more details. Thank you for reporting the issue.
