### ISSUE TITLE
Stream fails in middle of live stream

### ISSUE THREAD

**Issue by TylerZubke** [videojs/videojs-contrib-hls#834]
## Description
Briefly describe the issue.

While watching a live video in Chrome (it might happen in FF too, but I haven't tried yet), the stream will randomly stop and a message will pop up saying "A network error caused the media download to fail part-way." Here's a screenshot of the network tab/console:
![screen shot 2016-08-26 at 11 23 01 am](https://cloud.githubusercontent.com/assets/5394768/18010853/50448c88-6b80-11e6-9bcd-87657b105280.png)

Note a .ts file 404s and there is a CORS issue in the console as well as an InvalidStateError.
I'm not sure if this is a Wowza problem or a problem with the plugin, but any insight would help. I can provide more info if I'm missing something.

I tried a test stream on the [plugin demo player](http://videojs.github.io/videojs-contrib-hls/) and saw the error as well. It takes anywhere from 10 minutes to an hour for the error to occur.

This is potentially related to #775 , #550 , and #491

## Sources
Is a certain source or a certain segment affected? I can provide a url if needed, but I can't keep the stream up indefinitely.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Watch live video in Chrome
2. Wait for error to happen (could take anywhere from 10 minutes to an hour

### Expected
It shouldn't throw an error during playback. Even if this is a Wowza issue, can't the plugin continue streaming without bombing out due to one file that can't be retrieved?

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 3.5.2
videojs-contrib-hls 3.1.0 -- it seemed to happen more frequently with this version.

### videojs version
what version of videojs does this occur with?
video.js 5.11

### Browsers
what browsers are affected? please include browser and version for each
* Chrome (any version)

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* Windows 7 and OSX Yosemite (but it probably happens on every operating system)

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* Whatever other plugins the plugin demo player is using

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* Whatever other libraries/framework the plugin demo player is using

**Comment by forbesjo** [comment]
Would you be able to link your stream so we could debug? Thanks

**Comment by JackSimth** [comment]
404=file not found.  It's a return status code from the server.  The 404 would be generated by the WOWZA server (or perhaps a proxy in line), not the javascript itself.  I'd be inclined to start by looking for server side problems - too much load, a disconnected stream, file maintenance deleting a segment while computers are still requesting it, and so on.

**Comment by TylerZubke** [comment]
Sorry I forgot to update this. I've done a lot more digging and this is definitely a server side issue. 

I don't know if it's possible, but it would be nice if the plugin could continue streaming and not error out when one .ts file 404s. If this is something that you guys would consider implementing I can change this to a feature request or something. If not, I'll just close it. 

I know there are other people having similar problems with Wowza so I wanted to briefly document the problem here in case it helps anyone. When a request is made for a chunklist (.m3u8), the .ts files listed in the response for the chunklist MUST go to the same instance. We have our EC2 instances behind a load balancer, and occasionally the load balancer would send the requests for a .ts file to a different instance which caused the 404. Enabling stickiness on the load balancer is the solution.

**Comment by lilyxs** [comment]
I have a similar problem,HTML5 play m3u8 video stream requests a history, drag a TS file, take a long time, no timely request to the corresponding TS document, network error caused the error A media download to fail part-way, then the TS file, call the play method, the error is to stay, not to play video. Excuse me, how to solve??? @TylerZubke 
![qq 20170405174238](https://cloud.githubusercontent.com/assets/16396078/24699643/4d6c9e28-1a27-11e7-9f03-0da5069eb229.png)
