### ISSUE TITLE
Large m4v files encoded to hls doesn't display video.

### ISSUE THREAD

**Issue by sobytes** [videojs/videojs-contrib-hls#835]
## Description

Hi All, I seem to be hitting this issue where when i encode large m4v files (it works fine with files under 400mb) exported from screenium they never seem to play.

Example just paste this url.
https://s3-eu-west-1.amazonaws.com/s3bubble.learning.theme/streamiumthemesetup30frames/encoded-28-08-2016-18-57-16/encoded-28-08-2016-18-57-16.m3u8

Here: http://videojs.github.io/videojs-contrib-hls/

It gives the same error i get, it only seems to do it on files over 400mb that i have encoded, i am exporting from screenium at h.264 at 60 frames a second i have also tried 30 fps.

And using AWS elastic transcoder to encode into the different segments, i have tried running it through handbrake with web optimised checked as i thought it might be a metadata issue but it give the same results.

## Steps to reproduce
Record video with screenium export to desktop encode with AWS elastic transcoder.

### Expected
Start playing video

### Error output
No errors just video starts but with no display.

### videojs-contrib-hls version
@version 3.5.3

### videojs version
Video.js 5.10.8

### Browsers
Tested in all browsers tried flash tech html5 

### Other Plugins
None

### Other JavaScript
jQuery

**Comment by sobytes** [comment]
This issue relates to having different audio encoding settings for individual playlists keep them all the same and they encode and play correctly.

**Comment by dmlap** [comment]
@sobytes thanks for following up with the root cause.
