### ISSUE TITLE
Videojs HLS player can't load file sometimes but file is valid and works in vlc

### ISSUE THREAD

**Issue by omarosman107** [videojs/videojs-contrib-hls#836]
Every time I go to my website cablecentral.tk and load Cbsn from the list it sometimes says can't load file. If I do a refresh it will come back to normal.
What do you think the problem is?

**Comment by BrandonOCasey** [comment]
please answer all of the questions in the [ISSUE_TEMPLATE](https://github.com/videojs/videojs-contrib-hls/blob/master/ISSUE_TEMPLATE.md)

**Comment by omarosman107** [comment]
Description

Every time I go to my website cablecentral.tk and load Cbsn from the list it sometimes says can't load file.
Sources

CBSN

Steps to reproduce

Explain in detail the exact steps necessary to reproduce the issue.

1. 2. 3.

Results

Expected

player to have started and streaming video.

Error output


Additional Information

videojs-contrib-hls version
3.5.3

what version of videojs-contrib-hls does this occur with? videojs-contrib-hls x.y.z

videojs version
5.11.4
what version of videojs does this occur with? video.js x.y.z
5.11.4
Browsers
chrome
what browsers are affected? please include browser and version for each *

Platforms

what platforms are affected? please include operating system and version or device and version for each *
windows
Other Plugins

are any other videojs plugins being used on the page? If so, please list them with version below. *

Other JavaScript

are you using any other javascript libraries or frameworks on the page? if so please list them below. *
