### ISSUE TITLE
Long HLS playlists not playing properly

### ISSUE THREAD

**Issue by SuriGill** [videojs/videojs-contrib-hls#846]
## Description
Whenever I try playing a static playlist longer than 13ish hours with GOP sizes of 1 second, it seems to crash and show up as another playlist with the time after 13ish hours. So for example, a fifteen hour hls playlist would be shortened down to the last two hours. Also for live playlists at these lengths, it seems to just not play and either be stuck with a black screen or with the first frame of the playlist. I've tested out these players using different libraries such as hls.js and they work so it is not an error with .m3u8 file. 

## Steps to reproduce
1. Get a 14 hour long playlist with GOP sizes of 1 second

### Expected
Please describe what you expected to happen that did not happen in the description.

### Error output
There's no console/error output messages when this happens and I'm unable to track where it is in the library to make a change on my own fork. 

### videojs-contrib-hls version
videojs-contrib-hls 3.5.3

### videojs version
video.js 5.11.6

### Browsers
I've tested this on google chrome and firefox

### Platforms
Linux/Windows

**Comment by mjneil** [comment]
Would you be able to provide a link to your playlist that causes this?

**Comment by SuriGill** [comment]
Unfortunately it's created using ffmpeg and it's around 20gb to upload. I will try to creating a smaller different one.

**Comment by dmlap** [comment]
@SuriGill are you retaining all segments in the m3u8 for the duration of your stream? You may just be hitting the limits of available memory on the machine you're playing the stream from. We're open to changes that improve memory efficiency but you'll probably be better off by clearing out old content from that m3u8 as time progresses.

I'm closing this one based on that recommendation but feel free to continue commenting if something more complex is going on.

**Comment by mjneil** [comment]
There is a good chance this is realted to BaseMediaDecodeTime being a 32 bit value rolling over at around 13 hours. There is a [pull request](https://github.com/videojs/mux.js/pull/118) that is still in review to switch to version 1 tftd boxes. @SuriGill can you try using the PR to see if it corrects your issue?
