### ISSUE TITLE
Any chance of getting capleveltostage added?

### ISSUE THREAD

**Issue by triwav** [videojs/videojs-contrib-hls#847]
I've been using Mangui's flashls but am planning to make the switch to videojs-contrib-hls so we no longer need Flash. Was wondering if there was any plans of adding capleveltostage. It basically limits the max video size played back to one the same or smaller than the current size of the video player which can help keep bandwidth requirements lower. It looks like this should be pretty easy to build on my own and just run a timer to see if the size of the video player has changed and enable or disable the video streams accordingly but would prefer a built in option instead. Thanks.

**Comment by dmlap** [comment]
You're in luck! The default adaptive switching algorithm in this project already does that. Technically, we will switch to the rendition that's just bigger than the player's display size if there isn't an exact match, but we wouldn't choose a rendition any bigger than that. More details in [our design doc](https://github.com/videojs/videojs-contrib-hls/blob/master/docs/bitrate-switching.md), if you're interested.
