### ISSUE TITLE
Live 608 captions

### ISSUE THREAD

**Issue by jamsterdam29** [videojs/videojs-contrib-hls#849]
## Description
Have been looking at a live test stream with 608 captions and while the captions are converted into VTTCues, the display does not fully reflect the 608 display.  I know webvtt does not have the idea of "roll-up" captions, but what is the expectation for how live captions should display?  

It might be ok if live captions did not fully reflect 608, but sometimes it makes them hard to read.  Sentences are split in weird places, the centering of all lines makes more difficult to follow, and some lines appear and disappear too fast.  

This may be more of a question of how 608 is interpreted and converted, what the expectation is, and if there is any way to improve. Thanks.

## Steps to reproduce
play a live stream with live programming (sports, news, etc...) and compare to 608 native display (vlc seems to display based on native 608 codes).

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls x.y.z

### videojs version
what version of videojs does this occur with?
video.js 5.11.6
videojs-contrib-hls 3.5.3

### Other Plugins
videojs-contrib-ads 3.3.11
videojs-ima 0.4.0

**Comment by dmlap** [comment]
Our goal for converting CEA-608 would be to follow the [current W3C spec](https://dvcs.w3.org/hg/text-tracks/raw-file/default/608toVTT/608toVTT.html) so if you see particular instances we're not achieving that, please file separate issues for any you find. We are missing support for parsing some of the positioning and formatting commands in CEA-608 as well as paint-on mode today. If you're interested in helping out with that, please check out [mux.js](https://github.com/videojs/mux.js)!
