### ISSUE TITLE
Clarification of Deep Merge

### ISSUE THREAD

**Issue by SuriGill** [videojs/videojs-contrib-hls#851]
## Description
I was curious as to why a deep merge was added to combine playlists and in what use cases this has. I'm currently trying to play playlists that aren't having their previous chunks being replaced and are able to have new chunks appended to the end. With larger size playlists, this takes up a huge amount of CPU power and if it is not necessary, I can submit a PR for this line (https://github.com/videojs/videojs-contrib-hls/blob/master/src/playlist-loader.js#L38) to equal simply original[i]. 

## Sources
https://github.com/videojs/videojs-contrib-hls/blob/master/src/playlist-loader.js#L38

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 3.5.2

### videojs version
what version of videojs does this occur with?
video.js 5.11.6

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by dmlap** [comment]
Most live HLS that I've seen removes content from the beginning of the stream when it adds content to the end. For long-running streams (days/weeks/years), this is important to ensure the m3u8s don't grow to GBs. If our merge is inefficient, PRs to fix that would be totally welcome but we want to retain the capability to correctly play back live content that drops segments over time.
