### ISSUE TITLE
The chrome in Windows OS can not show the whole picture of the video which recorded by mac.

### ISSUE THREAD

**Issue by benvirus** [videojs/videojs-contrib-hls#857]
## Description
Firstly,I recod a video by mac pro.So it's type is mov . Then I transcode it into mp4 type and splite it into .ts file. When I play it with mac, it's no problem.But in windows OS,Some browsers like chrome can not show the whole picture.

## Sources
http://default.prod.dev.qiqiuyun.cn:9071/video-player/examples/demo-sdk-play-rate-display.html
Please browse the above link with mac and Chrome in windows.You will find the problem.

## Steps to reproduce

1.Record a video by Mac
2.Transcode it into mp4
3.Splite the mp4 into .ts files.

**Comment by gkatsev** [comment]
What version of chrome and what version of windows? Do you have a screenshot of how it looks?
Just tried it on windows 10 and chrome 53.0.2785.143 and it seems to be looking just fine. Also, thanks for the test case link.

**Comment by benvirus** [comment]
Thank you very much for your reply.
I tried the link on windows10 and chrome 51.0.2704.106 m.
Please look at the screenshot as follow:
![image](https://cloud.githubusercontent.com/assets/13535932/19374821/52b07642-9201-11e6-954c-4a6b18d4a43a.png)
As you can see: the video can not show the whole picture of the video file.
But on mac OS,test with chrome 53.0.2785.143.Please see the screenshot as follow and focus on the part marked with red line:
![image](https://cloud.githubusercontent.com/assets/13535932/19375019/bda8b12a-9202-11e6-8b01-80bfb1955007.png)
Now The difference appears.
Looking forward for your reply.
Thank you again.

**Comment by forbesjo** [comment]
This appears to be a browser bug that was fixed with Chrome 53, closing since it is out of our control
