### ISSUE TITLE
video.js:11075 Uncaught TypeError: this.tech_.audioTracks is not a function

### ISSUE THREAD

**Issue by jburnett31** [videojs/videojs-contrib-hls#858]
## Description
Attempting to change the `player.src` in my example does not load the next video and continue playing as expected. The goal here was simply to have a list of videos to play and automatically load and play the next when the current video ends. Here is the code:
```
<!DOCTYPE html>
<head>
<link href="http://vjs.zencdn.net/5.9/video-js.css" rel="stylesheet">
<script src="//vjs.zencdn.net/5.9/video.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/3.6.0/videojs-contrib-hls.js"></script>
</head>
<body>
<video id='example-video' width='1280' height='720' class="video-js vjs-default-skin" controls>
</video>
<script>
var videoList = [
	{src: "videos/15_1500k.m3u8", type: 'application/x-mpegURL'},
	{src: "videos/16_1500k.m3u8", type: 'application/x-mpegURL'}
];

function getVideoEnumerator() {
	var idx = 0;
	return function() {
		if (idx < videoList.length) {
			return videoList[idx++];
		}
		else return null;
	}
}

window.onload = function() {
var enumerator = getVideoEnumerator();
videojs('example-video').ready(function() {
	var player = this;
	player.on('canplay', function() {
		player.play();
	});
	player.src(enumerator());
	player.on('ended', function() {
		var next = enumerator();
		if (next != null) {
			player.src(next);
		} else
			return;
	});
});
}
</script>
</body>
</html>
```
## Steps to reproduce
1. Load the page.
2. Skip to the end of the video.
3. The 'ended' callback triggers the exception on the `src` call.

### Expected
As mentioned, I expected the 'ended' callback to change the video source and the video to start playing when 'canplay' is triggered.

### Error output
```
Uncaught TypeError: _videoJs2.default.AudioTrack is not a constructor (videojs-contrib-hls.js:997)
Uncaught TypeError: _this3.tech_.audioTracks is not a function (videojs-contrib-hls.js:15682)
VIDEOJS: TypeError: this.tech_.audioTracks is not a function(…) (video.js:19842)
Uncaught TypeError: this.tech_.audioTracks is not a function (video.js:11075)
```

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 3.6.0

### videojs version
what version of videojs does this occur with?
video.js 5.9

### Browsers
what browsers are affected? please include browser and version for each
* Chrome Version 53.0.2785.143 m

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* Windows 7

**Comment by forbesjo** [comment]
Looks like you're using an older version of video.js that doesn't support the audio track API, please try video.js 5.10.1+. https://github.com/videojs/video.js/blob/master/CHANGELOG.md#5101-2016-05-03
