### ISSUE TITLE
HLS videos on Safari don't loop

### ISSUE THREAD

**Issue by kirkeverett** [videojs/videojs-contrib-hls#860]
## Description
If it set the "loop" attribute on the videojs object to true, I expect the video to loop indefinitely. This works as expected on Chrome. On Safari, the video never loops. It just stays in a "Playing" state (keeps firing timeupdate events where the current time is zero) indefinitely. If i remove the "loop" attribute, it triggers the the "ended" event as expected when the video completes. 

How do we get the auto-loop behavior on Safari that we see on Chrome. I got looping to work by not setting the "loop" flag on the video and explicitly restarting the video when "ended" event is fired. That seems to work ok but I'm curious why it doesn't work the same way on all the platforms. 

### videojs-contrib-hls version
videojs-contrib-hls 3.1.0

### videojs version
video.js 5.10.6 

### Browsers
what browsers are affected? please include browser and version for each
* Safari 9.1.3 and up (didn't try earlier versions)

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* Mac OS

**Comment by forbesjo** [comment]
HLS is supported natively on Safari so in that scenario this plugin is automatically skipped by video.js's source handler selector. It looks like Safari can't handle looping HLS videos (see http://jsbin.com/gabiqedumi/1/edit?html,output)

**Comment by forbesjo** [comment]
Closing since this is a native bug
