### ISSUE TITLE
hls.byteReceived and hls.segmentXhrTime are null

### ISSUE THREAD

**Issue by russitto** [videojs/videojs-contrib-hls#867]
## Description

hls.byteReceived and hls.segmentXhrTime are null
## Sources

Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.
## Steps to reproduce

Explain in detail the exact steps necessary to reproduce the issue.
Open Develope Tools (F12)
1. Open Developer Tools (F12)
2. type: videojs(document.querySelector('video').parentNode).tech({IWillNotUseThisInPlugins: 1}).hls.bytesReceived
3. type: videojs(document.querySelector('video').parentNode).tech({IWillNotUseThisInPlugins: 1}).hls.segmentXhrTime
## Results

null in both case.
### Expected

Numbers
### videojs-contrib-hls version

3.5.3
### videojs version

video.js 5.11.6
### Browsers
- all, i.e: Chrome

**Comment by dmlap** [comment]
@russitto were you testing this in Edge? Edge has native support for HLS. Currently this project delegates to a native implementation of HLS if one is available.

**Comment by russitto** [comment]
Sorry, forget about Safari and Edge. But Firefox? Chrome?

**Comment by ddunkin** [comment]
It looks like this was removed in the audio track refactor by @imbcmdth. https://github.com/videojs/videojs-contrib-hls/commit/2cce0c1859a53fee5c6ed46deb79cfc550cead45#diff-b97e9f0783b7b7b3b21cfaa1457b03eaL1149

**Comment by forbesjo** [comment]
In VHS you'll want https://github.com/videojs/http-streaming#hlsstats
