### ISSUE TITLE
Flash Fallback

### ISSUE THREAD

**Issue by toddaa** [videojs/videojs-contrib-hls#870]
Fresh clones of the video.js and videos-crontrib-hls repos and am struggling to get flash fallback to work correctly in Win7/IE11.  The video-js.swf loads properly.  It downloads the playlist.m3u8 file and then a single chunk but no more.

I am recalling a similar issue months ago and the solution was to use a video-js.swf file from a specific version.  Does anyone recall this as well?  I can seem to find any official documentation about this or a good example including "working" config that provides fallback.

Please advise, and thank you!

**Comment by forbesjo** [comment]
We have a fix for this in the works and will release shortly

**Comment by mjneil** [comment]
Can you provide your source playlist.m3u8?

**Comment by forbesjo** [comment]
This might actually be a different issue than I initially thought, could you provide an example source?

**Comment by mjneil** [comment]
I think the latest version of contrib-hls 3.6.5 fixes this problem, can you try and confirm if you are still experiencing issues?

**Comment by toddaa** [comment]
I just pulled in 3.6.6 this morning and tested.  Works perfect now.  Thanks all for the update!

**Comment by campones** [comment]
could you show me an example of flash fallback using videojs-contrib-hls?

currently I m using hls.js  and the only solution has been to setup 2 sources with 2 different extension ( application/x-Mpeg and video/mp4 )

it seems videojs-contrib-hls has a builtin flash fallback feature so I would love to see a proper setup for this, possibly using the html player setup

**Comment by forbesjo** [comment]
If you take a look at the demo page at http://videojs.github.io/videojs-contrib-hls/ you'll see a code snippet that includes the video.js library and this plugin which enables HLS playback on non-Safari browsers. Basically all you need to do is provide your HLS source either using a source element or calling `player.src(yourSource)`, video.js will automatically select HTML5 or Flash playback depending on the browser's capabilities.

**Comment by campones** [comment]
yes I realized later it was now totally automatic
