### ISSUE TITLE
CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED, when using webpack

### ISSUE THREAD

**Issue by eric7578** [videojs/videojs-contrib-hls#874]
First, thanks for this great plugin for your work! But I encountered some problem when I use **webpack** as the bundler, everything is fine without webpack, but once it involved, I got this error:

`**VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)** The media could not be loaded, either because the server or network failed or because the format is not supported. `

The following are my video.js versions
`
"video.js": "^5.11.8",
"videojs-contrib-hls": "^3.6.4",
`

And provided are my code for import the modules
`import 'expose?videojs!video.js';`
`import 'videojs-contrib-hls';`
`import 'expose?Hls!hls.js';`

**Comment by antondomratchev** [comment]
@eric7578 I am not sure if this will solve your problem. I've encountered similar issue and my solution has been to specify the source type as `type="application/x-mpegURL"` this maybe different for you depending on the media type being consumed.

**Comment by eric7578** [comment]
@antondomratchev thanks for the reply
I just solved my problem by the following workaround.
`import 'videojs-contrib-hls/dist/videojs-contrib-hls';`
