### ISSUE TITLE
Can't find hls in player for Safari only

### ISSUE THREAD

**Issue by zymtx5g79k** [videojs/videojs-contrib-hls#881]
## Description
I need to change bandwidth, but i can't find hls object in Safari browser.

JSBin: http://jsbin.com/debocajecu/1/edit?html,output

## Sources
Nothing special

## Steps to reproduce (in JSBin)
1. Play video. Click on "Play" button.
2. Try to find hls. Click on "Look for Hls" button.

## Results
Exception: Undefined is not an object (evaluating 'hls.bandwidth')

### Expected
Any number in alert.

### Error output
Undefined is not an object (evaluating 'hls.bandwidth')

## Additional Information
videojs-contrib-hls 3.0.2
video.js 5.10.2

### Browsers
Safari: 10.0 (11602.1.50.0.10)

### Platforms
OS X (El Capitan 10.11.6)

### Other Plugins
none

### Other JavaScript
none

**Comment by gkatsev** [comment]
This is because on Safari contrib-hls isn't run. We use the native HLS implementation on Safari.

**Comment by zymtx5g79k** [comment]
Thanks for quick answer!
Is there way to limit bandwidth on Safari? I need change level (quality) in js.

**Comment by gkatsev** [comment]
Unfortunately, there isn't a way of doing it natively. I believe we're working on a way to force contrib-hls to run on any browser which would enable you to use it on Safari. Though, I don't think we have an ETA for that yet.
