### ISSUE TITLE
Uncaught TypeError in segment loader

### ISSUE THREAD

**Issue by mjprude** [videojs/videojs-contrib-hls#885]
## Description

While testing error handling with [Murphy](https://github.com/mrocajr/murphy), for a manifest with a missing (404) ts file, no error is caught. Instead, we get an Uncaught TypeError on `playlist.segments.length` and the player becomes unresponsive (at least from a user's perspective).

Demonstrated here, assuming Murphy is running on port 9191:

``` HTML
<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8 />
  <link href="https://cdnjs.cloudflare.com/ajax/libs/video.js/5.11.9/alt/video-js-cdn.css" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/video.js/5.11.9/video.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/3.6.6/videojs-contrib-hls.js"></script>
</head>
<body>
  <h1>Video.js  Example Embed Pointing to 404-Throwing Stream</h1>

  <video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="268" 
  data-setup='{}'>
    <source src="http://localhost:9191/error/apple/gear4/prog_index.m3u8?tsnotfound=1" type="application/x-mpegURL">
  </video>

</body>
</html>
```
## Sources

https://github.com/videojs/videojs-contrib-hls/blob/master/src/segment-loader.js#L385
## Steps to reproduce
1. Clone down [Murphy](https://github.com/mrocajr/murphy) and run the server
2. Load the src "http://localhost:9191/error/apple/gear4/prog_index.m3u8?tsnotfound=1" into the player.
### Expected

My expectation for any fatal playback error is for it to be raised through the videojs error system. That way, out of the box, the user knows an error occurred, and more customized error solutions will be easier and more reliable to implement.
### Error output

`videojs-contrib-hls.js:4191 Uncaught TypeError: Cannot read property 'length' of undefined`
### videojs-contrib-hls version

videojs-contrib-hls 3.0.5
videojs-contrib-hls 3.6.6
### videojs version

what version of videojs does this occur with?
video.js 5.11.6
video.js 5.11.9
### Browsers

what browsers are affected? please include browser and version for each
- Chrome 53.0.2785.143
- Firefox 45.3.0
### Platforms
- OSX

**Comment by forbesjo** [comment]
We'll investigate and make it error out in the correct way.

**Comment by sgavali** [comment]
I'm also seeing this issue with my stream, but the bipbopall stream is not showing this problem.

**Comment by sgavali** [comment]
Is there anything needs to be done while creating playlist ?

**Comment by sgavali** [comment]
My issue looks to be related to content, got it working with different stream.

**Comment by gesinger** [comment]
Hey @mjprude , sorry this ticket has gone a long time without much attention. We recently updated how we handle errors like this, and now if a playlist errors (including a 404 for a TS file) we will blacklist the playlist. If the playlist is the last one available, we will retry after a delay. I tested the scenario with a 404ing TS file, and the behavior followed that logic (and no longer throws an exception).

Please give the latest version of videojs-contrib-hls a shot (as of this comment, v5.4.0), and let us know if you notice any issues. Thanks for posting the issue and for the debugging information.

**Comment by rparjun** [comment]
@gesinger I had a similar issue, when loading a mpeg2video file using m3u8 playlist, it was crashing with an error 'Cannot read property 'segments' of undefined' at at 'https://unpkg.com/videojs-contrib-hls@5.5.3/dist/videojs-contrib-hls.js:18036:25'.

Type was coming as 'combined' and that key was not present in 'segmentObj'. 

Can we have a friendly error message if this is not supported.

Video.js 5.19.2
videojs-contrib-hls.js: v5.5.3
Google Chrome: 58.0.3029.110

Generating m3u8:
ffmpeg -i inp.ts -f segment -segment_time 10 -segment_list list.m3u8 -segment_format mpegts 'list-file%5d.ts'
