### ISSUE TITLE
Interfacing with `fLoader` via. videojs?

### ISSUE THREAD

**Issue by silverbucket** [videojs/videojs-contrib-hls#886]
I'd like to implement my own segment fetching function, with `hls.js` I can do this using the `fLoader` property of the config object, used during initialization. 

``` javascript
var hls = new Hls({
  fLoader: customMediaRequest
});
```

However I can't figure out how to do this the right way with the `videojs-contrib-hls` module, any pointers? Is it even possible?

**Comment by silverbucket** [comment]
Does anyone have any idea about this? I basically want to be able to pass in Hls config (as described here) https://github.com/dailymotion/hls.js/blob/master/API.md#fine-tuning when using `videojs-contrib-hls`.

I tried passing in a config object when initializing `videojs` like this:

```javascript
var options = {
  html5: {
    hlsjsConfig: {
      fLoader: function () { console.log('test'); }
    },
    hls: {
      hlsjsConfig: {
        fLoader: function () { console.log('test'); }
      }
    }
  }
};

var player = videojs('video', options);
```

Placing the hls-specific config in any of those positions in the options object don't seem to have any effect. Is there a way to pass in options to Hls?

**Comment by silverbucket** [comment]
ping @dmlap and @forbesjo because you seem to be active with this repo. ^^

**Comment by gkatsev** [comment]
Hls.js is an unrelated project to this one.

**Comment by silverbucket** [comment]
@gkatsev ah right, I was confusing Hls with hls.js, thanks for correcting me. So, with that in mind - do you know a way to over-ride the Media fetching function when initializing the library?

**Comment by dmlap** [comment]
@silverbucket depending on what you're trying to do, you can override [hls.xhr](https://github.com/videojs/videojs-contrib-hls/blob/master/README.md#hlsxhr) or (better) provide an implementation of `videojs.Hls.xhr.beforeRequest`.

Closing since I think that covers your question. Feel free to comment if I missed something.

**Comment by silverbucket** [comment]
@dmlap thanks for the reply. I tried overriding `videojs.Hls.xhr` but the function never seems to be called. 

```javascript
videojs.Hls.xhr = function (url, callback) {
  console.log('XHR called ', url, callback);
};

var player = videojs('video');
player.ready(function () {
  player.src({
    src: "https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8",
    type: "application/x-mpegURL"
  });
  player.play();
});
```

This function never ends up being called.

**Comment by silverbucket** [comment]
ping @dmlap ?

**Comment by dmlap** [comment]
I think you're overriding the wrong function. If you'd like to completely overwrite requests, you do it on a per-player basis (not globally for the page). Like this:

```js
var player = videojs('video');
player.ready(function () {
  player.src({
    src: "https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8",
    type: "application/x-mpegURL"
  });

  player.tech({ IWillNotUseThisInPlugins: true }).hls.xhr = function (url, callback) {
    console.log('XHR called ', url, callback);
  };
  player.play();
});
```
