### ISSUE TITLE
Site crashes after throwing this error.

### ISSUE THREAD

**Issue by McQuinTrix** [videojs/videojs-contrib-hls#891]
The page on Chrome says 'Aww Snap!" and shows this error in console:

hls.min.js:1 Setting MediaSource.duration below the highest presentation timestamp of any buffered coded frames is deprecated due to specification change. Support for implicit removal of truncated buffered media will be removed in the future. You should instead perform explicit remove(newDuration, oldDuration) on all sourceBuffers, where newDuration < oldDuration. See https://www.chromestatus.com/features/6107495151960064 for more details.

**Comment by dmlap** [comment]
I've never seen that happen. Can you provide us with a [reduced test case](https://css-tricks.com/reduced-test-cases/),?

**Comment by gesinger** [comment]
Closing for now. If you are still experiencing this issue with the latest version of videojs-contrib-hls (as of this comment, v5.0.0), please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.
