### ISSUE TITLE
Adding Headers into beforeRequest Hls Videojs function

### ISSUE THREAD

**Issue by apatinoyu** [videojs/videojs-contrib-hls#896]
Hello everyone and thanks for you offering help. I tried to send Headers into the videojs.Hls.xhr.beforeRequest function, so I implement:

```
videojs.Hls.xhr.beforeRequest = function(opt){
opt.headers.access-control-allow-origin= nameDomain
opt.headers['X-User-Id'] = userId;
}
```
Debugging the library videojs, it seems like it gets my headers and it adds the headers into xhr but when it is sent suddenly it disappears. So in the request headers result is:
`Access-Control-Request-Headers:access-control-allow-origin,x-user-id` and no values. I am using videojs version 5.12.2 and videojs-contrib-hls as well. Regards.

**Comment by gkatsev** [comment]
Answered here: https://github.com/videojs/video.js/issues/3752
