### ISSUE TITLE
Stream stops no errors in chrome

### ISSUE THREAD

**Issue by samueleastdev** [videojs/videojs-contrib-hls#897]
## Description
Here is a full test case 

http://jsbin.com/tosibacaxa/2/edit?html,output

It seems to work fine in firefox but it will just stop in chrome no errors in the network tab.

## Steps to reproduce
should see this in the codepen click play it will get to the apple logo and stop

### Expected
keep playing or switch segments

### Error output
No errors

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 3.6.7

### videojs version
what version of videojs does this occur with?
video.js 5.11.9

### Browsers
chrome seems to work in firefox and safari

**Comment by samueleastdev** [comment]
Just update in the tests works fine in every other browser and mobile i have tested just seems to be a issue with chrome

**Comment by samueleastdev** [comment]
Any suggestions on what I can check for? 

I have tried the latest version and it still stops on the specific segment should it switch?

Thanks

**Comment by mjneil** [comment]
It looks like a gap is being created on the segment boundary due to a rendition switch. The gap skipping logic should detect and skip past the gap, but seems like a bug is causing it to think there is no gap to skip. We should be able to get a fix for this

**Comment by samueleastdev** [comment]
Ok thanks @mjneil that would be great.

**Comment by samueleastdev** [comment]
Awesome I see it's all working with the new version ;) really appreciate your updates on this legends
