### ISSUE TITLE
BeforeRequest function is not called on Safari

### ISSUE THREAD

**Issue by apatinoyu** [videojs/videojs-contrib-hls#904]
Hello, thanks for the player.
I found an issue or maybe I am doing something wrong. Please help me to understand this.

## Description
I want to set custom HTTP headers on every request made by the player. To do so I would like to use `beforeRequest` callback. So, I am setting these headers in my videojs variable. Then I initialize the player. It is working fine on Chrome & Firefox but fails on Safari.

## Steps to reproduce
On Safari, while debugging it never goes into/through the `beforeRequest` function so the headers are not being set at all.

### Expected
I expect to see the same queue or list of functions that are being called for this process in different kind of browsers.

### Actual
Does not go through the `beforeRequest` function on Safari.

#### videojs
 videojs#^5.12.6
videojs-contrib-hls version 3.6.9
#### browsers
Safari 9.1

**Comment by mjneil** [comment]
Safari supports native HLS, so the player lets Safari take over, so the source handler is never initialized. 

We are currently working on a beta build that changes a lot of our segment fetching logic. [v3.7.0-beta4](https://github.com/videojs/videojs-contrib-hls/tree/v3.7.0-beta4) has a change that allows you to override native HLS to force the source handler to be created. This can be done by setting `videojs.options.hls.overrideNative = true`. This build may be unstable though.

Alternatively, you could try adding the [override changes](https://github.com/videojs/videojs-contrib-hls/commit/dd08a491df8b58864ffcfef16ffbd68914e76631) to your own fork and give it a try.

I don't think theres been much testing on using contrib-hls in Safari in favor of the native implementation yet, so these suggestions may not work, but a good place to start.

**Comment by apatinoyu** [comment]
Hello, thanks for your fast reply.
I added the videojs-contrib-hls.js  from the repository v3.7.0-beta4 .
and now I get the errors: 
`videojs.Hls.xhr.beforeRequest`  while debugging `Hls` is undefined. 
or
`videojs.options.hls.overrideNative = true;`  while debugging `options` does not have hls, so `hls` is undefined.
So far I use the videojs-contrib-hls.js . Do I need something else from the repository  v3.7.0-beta4 ?
Regards.

**Comment by apatinoyu** [comment]
I built the v.3.7.0 Beta and added the contrib-hls.js into my project .
Good news: I properly set and send the headers on Safari.
Bad new: I could not get a response, status still pending. 
I'll go deeper and be coming back in case I may close the issue.
Regards.

**Comment by gesinger** [comment]
Hey @apatinoyu , did you have any luck with getting HTTP responses?  We've made a lot of changes to videojs-contrib-hls in the meantime. Please give v5.0.0 a shot (latest version as of this post), and if you're still experiencing issues, would you be able to put together a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output)? Thanks.

**Comment by gesinger** [comment]
In the latest player, we are seeing a bug where overrideNative does not work for Safari. That is being investigated in https://github.com/videojs/videojs-contrib-hls/issues/1005 . Closing this issue for now. Thank you.
