### ISSUE TITLE
Can't resume live video after pausing for > 45 seconds.

### ISSUE THREAD

**Issue by TylerZubke** [videojs/videojs-contrib-hls#914]
## Description
Briefly describe the issue.
This was kind of fixed in a recent release, but I'm still able to reproduce it (mainly in Chrome, I don't think I've had an issue with Firefox). If I start watching a live video, then pause it, then hit play again after waiting for about a minute or longer, it the loading spinner comes up and the video never starts playing again. It happens roughly 50% of the time whereas before it happened nearly every time. I'm using the demo player (http://videojs.github.io/videojs-contrib-hls/) to make sure it's not something wrong in my player too. There is one other weird issue as well. Sometimes the video will start playing again after pausing for a while, but then about 5-10 seconds later it will stop again and the spinner will come up. When this happens I've found I can click play again and it continues just fine. Again, I'm only seeing these issues in Chrome.

## Sources
Any live stream will work. I can provide a link to one if needed, but I can't leave it running indefinitely. 

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Using Chrome, open livestream in demo player (http://videojs.github.io/videojs-contrib-hls/)
2. Pause video
3. Resume video after waiting a minute or two

## Results
Loading spinner will come up and sometimes video doesn't continue playing. Or, video continues playing briefly, then the spinner comes up again and the video doesn't continue unless you click play again.

### Expected
Video continues playing.

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 3.6.11

### videojs version
what version of videojs does this occur with?
video.js 5.10

### Browsers
what browsers are affected? please include browser and version for each
* Chrome 54, probably other versions as well

### Platforms
what platforms are affected? please include operating system and version or device and version for each
OSX and Windows

**Comment by blendi-93** [comment]
have the same problem streamplaylist: https://streaming-02.mivitec.net/live/smil:test.smil/playlist.m3u8
(only useable from german ips sry)

**Comment by mjneil** [comment]
The most recent release includes a ton of live stream stability enhancements. Can you try your stream with the latest version (4.0.2) and see if this is still an issue for you?

**Comment by blendi-93** [comment]
still an issue.

video-js: 5.14.1
video-js-hls-contirb: 4.0.2

Firefox: 50.1.0
Windows: 10

**Comment by campones** [comment]
same here..

**Comment by AgustinLado** [comment]
Hey! It's still an issue with video.js 5.16.0 and videojs-contrib-hls 4.1.1 (using Chrome 55).

**Comment by gesinger** [comment]
We have a PR that we hope to get in soon that should address playback stopping for live streams when trying to resume after being paused for long periods of time: https://github.com/videojs/videojs-contrib-hls/pull/1006 . 

Thanks for the test stream @blendi-93 . I tested it with the current player and the branch from the PR and confirmed the bug in the current player as well as working behavior when using the branch.

**Comment by gesinger** [comment]
This should be fixed as of the latest release (v5.3.2). Please give it a shot and if you are still experiencing an issue, please re-open or file a new issue. Thank you.
