### ISSUE TITLE
withCredentials not working

### ISSUE THREAD

**Issue by runtheyards** [videojs/videojs-contrib-hls#915]
Just thought I would let you know that on making requests using the .withCredentials does not work, tried a couple of the most recent version and the beta branch and nothing worked. For an alternative use hls.js as that worked for me.

**Comment by mjneil** [comment]
can you provide an example with this happening?

**Comment by bigt11** [comment]
I have credential working.  Here is how i have it in JS.  It passes on my cookies

```
//setup videojs
videojs(VideoIdName, {
  "controls": true,
  "fluid": true,
  "preload": 'none',
  "techOrder": ["html5"],
  "html5": {
    "hls": {
      "withCredentials": true,
    }, 
  },
}, function(){
```

**Comment by gesinger** [comment]
Thanks for the note @bigt11 . @runtheyards are you still experiencing this issue with the latest version of videojs-contrib-hls (as of this comment, v5.4.0)?

**Comment by runtheyards** [comment]
@gesinger I was not using it within the html5 prop. Not working on this project anymore but would guess that was the issue.

**Comment by gesinger** [comment]
Thanks for the update @runtheyards , we appreciate it. Closing this ticket. If anyone is still experiencing this issue, please let us know.
