### ISSUE TITLE
Live stream in player not working on mobile

### ISSUE THREAD

**Issue by arnaudgandibleux** [videojs/videojs-contrib-hls#921]
Hi,

When I want to stream my HLS live stream it will work in Chrome and Firefox. But when I want to live stream my HLS to a mobile browser, it won't work anymore. I get the error: " Format not supported".

If I try to play a .m3u8 file, it will work on mobile as well. just livestream is not working.

Any thoughts?

**Comment by mjneil** [comment]
What mobile device, OS, and browser are you using? Can you provide a code example and stream source that reproduces the error?

**Comment by arnaudgandibleux** [comment]
Android, Ipad, Iphone. None are working. I use Firefox, Chrome, safari.

The stream source I can't provide because a VPN is needed. I'm sorry

Code:
<video id="really-cool-video" width="960" height="540" class="video-js vjs-default-skin vjs-big-play-centered" preload="auto" controls>
		<source src="http://10.3.50.11/live/test/index.m3u8" type="application/x-mpegURL">
	</video>

**Comment by arnaudgandibleux** [comment]
And the stream is a nginx server which set an rtmp stream to hls. Footage is sent by OBS to the server

**Comment by arnaudgandibleux** [comment]
Okay, found problem. The problem was not HLS but the panorama plugin. Sorry for bothering you =D

**Comment by xiaosunJessica** [comment]
I met the similar problem, can you tell me how to solve it , or how the problem caused by the panorama plugin

**Comment by wuyuedefeng** [comment]
how solve?  I has same problem with hls, aes 128,   Desktop chrome safari is ok, but on mobile every safari show browser did not support.
