### ISSUE TITLE
Documentation for event handling outdated?

### ISSUE THREAD

**Issue by arendjr** [videojs/videojs-contrib-hls#923]
## Description

Regarding events, the documentation says:

> Standard HTML video events are handled by video.js automatically and are triggered on the player object. In addition, there are a couple specialized events you can listen to on the HLS object during playback:

It goes on to describe the **loadedplaylist** event, among others. But if I listen to this event on the HLS object, it seems to never get triggered. Digging into the source it appears I have to listen to the event on the `hls.masterPlaylistController_.masterPlaylistLoader_`object. However, it feels wrong that I have to listen to this event on a nested object that is considered private.

Am I missing something or is the documentation for this outdated?

### Expected
The **loadedplaylist** event should be triggered on the HLS object. Alternatively, the documentation should describe what *is* the recommended way of listening to this event.

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
current master branch

### videojs version
what version of videojs does this occur with?
current master branch

**Comment by imbcmdth** [comment]
We decided to remove the `loadedplaylist` function since it seems like the function is very much internal to HLS and only bad things can happen if user rely on that function.

The other events are accessible through other means now

**Comment by gesinger** [comment]
Thanks for reporting @arendjr , we have updated the documentation in https://github.com/videojs/videojs-contrib-hls/pull/992
