### ISSUE TITLE
Update plugin script in gh-pages

### ISSUE THREAD

**Issue by forbesjo** [videojs/videojs-contrib-hls#926]
## Description
The gh-pages page is using contrib-hls 3.x.x, update the npmcdn link to use unpkg instead and w/o a version range. 
https://github.com/videojs/videojs-contrib-hls/blob/gh-pages/index.html#L155

**Comment by rudemateo** [comment]
should the video.js version be updated from 5.10 to the latest 5.12.6 as well? https://github.com/videojs/videojs-contrib-hls/blob/gh-pages/index.html#L154

**Comment by gkatsev** [comment]
What about using a url like: `https://unpkg.com/videojs-contrib-hls@latest/dist/videojs-contrib-hls.js`
Or maybe even have a dropdown for tags that loads in `@{{tagname}}` based on the dropdown.

**Comment by rudemateo** [comment]
fwiw, if you leave the version range off, the "latest" currently resolves to 3.6.13

**Comment by gkatsev** [comment]
```sh
$ npm dist-tag ls videojs-contrib-hls
latest: 3.6.13
next: 4.0.2
```
looks like that's what the tags are. I think we would be great to have a tag/version dropdown similar to how unpkg.com has (see top right corner): https://unpkg.com/videojs-contrib-hls@3.6.13/dist/

**Comment by gesinger** [comment]
Resolved as part of https://github.com/videojs/videojs-contrib-hls/pull/966
