### ISSUE TITLE
How to restart live stream when it stucks for 2 seconds?

### ISSUE THREAD

**Issue by fakirpic** [videojs/videojs-contrib-hls#930]
Hi

when live stream stucks for 2-3 seconds and there is a spinner on the video like this
https://i.imgur.com/bHiqemT.jpg
how can i restart it?

i have such code

```
this.on('ended', function() {
	  player.src({
            src: stream(),
            type: 'application/x-mpegURL'
    });player.play();
    console.log('end res?');
});
this.on('error', function() {
	  player.src({
            src: stream(),
            type: 'application/x-mpegURL'
    });player.play();
    console.log('err res?');
});
```

this works when end or network error.but i want to do same when it just stucks?

**Comment by gesinger** [comment]
Hey @fakirpic , is the stream stuck because it is still loading, because there's a gap in the buffer, or another reason? Do you happen to have an example that you can provide in a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output)? Thanks.

**Comment by gesinger** [comment]
Closing for now. If you are still experiencing this issue with the latest version of videojs-contrib-hls (as of this comment, v5.0.0), please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.
