### ISSUE TITLE
If playing a video in a browser tab and changing to another tab after a while streams stops with error Uncaught TypeError: Cannot read property 'map' of undefined.

### ISSUE THREAD

**Issue by yokrysty** [videojs/videojs-contrib-hls#931]
## Description
If I start playing m3u8 in a browser tab wait for stream to start then if I change browser tab after a while streaming stops. When I change to the player's tab in console I get the following error videojs-contrib-hls.js:5030 Uncaught TypeError: Cannot read property 'map' of undefined. If page is not reloaded, streaming doesn't recover.

## Sources
Source is HLS AES-128.
I don't have the source publicly available, sorry.

## Results
![untitled](https://cloud.githubusercontent.com/assets/9500609/20862370/1adad474-b9b1-11e6-9c03-e3d50d401790.jpg)

### Expected
HLS video playing

### Error output
videojs-contrib-hls.js:5030 Uncaught TypeError: Cannot read property 'map' of undefined.

### videojs-contrib-hls version
videojs-contrib-hls 4.0.2

### videojs version
video.js 5.14.0

### Browsers
Latest Chrome

### Platforms
Windows 10 x64

### Other Plugins
videojs-chromecast-2.0.8

### Other JavaScript
jquery-2.2.4
google cast_sender.js v1

**Comment by mjneil** [comment]
Playing encrypted streams in a background tab has been a problem area. We hope to address and fix issues with background tab playback in the next few months, so stay tuned.

**Comment by mjneil** [comment]
This should be fixed as of v5.0.0.  Closing this issue, if you still experience problems please open a new issue.

**Comment by murmanskiy** [comment]
I need to contact you
skype - murmanskiy.bhf
Telergam - @murmanskiy
