### ISSUE TITLE
how to add event to loadingSpinner?

### ISSUE THREAD

**Issue by fakirpic** [videojs/videojs-contrib-hls#934]
Hi how to add event to loadingSpinner is active and not?
when player sets loadingSpinner to true i want to console.log("video stucks");
and when it false i want to console.log("video stucks");

thanks

**Comment by fakirpic** [comment]
i am still waiting for  response

**Comment by mjneil** [comment]
You can try listening to the `waiting` event on the player for when the spinner is active and listen for `playing` when the spinner deactivates. If this doesn't work, please make an issue in the [video.js project](https://github.com/videojs/video.js) as this is not an hls specific issue.

**Comment by fakirpic** [comment]
for god sake thank you
