### ISSUE TITLE
fmp4 demo

### ISSUE THREAD

**Issue by muhammad-ammar** [videojs/videojs-contrib-hls#935]
Is there any fmp4 demo available? Using http://videojs.github.io/videojs-contrib-hls/ i have tried fmp4 source from https://developer.apple.com/streaming/examples/ but its not working. Only the first source from https://developer.apple.com/streaming/examples/ is playing which is not fmp4.

**Comment by gkatsev** [comment]
Unfortunately, most of the sources from Apple don't include CORS headers, which is required for us to work. See the hosting considerations section in the README.
I think we have a test stream but don't have a link right now.

**Comment by forbesjo** [comment]
Try https://d2zihajmogu5jn.cloudfront.net/advanced-fmp4/master.m3u8

**Comment by muhammad-ammar** [comment]
@gkatsev @forbesjo Thanks for your help.
