### ISSUE TITLE
video.load makes the player stuck in "loading" state

### ISSUE THREAD

**Issue by Kasher** [videojs/videojs-contrib-hls#936]
## Description
Hey,

When I change the source of an existing video, and then call "video.load()" (or the videoJs's equivalent, player.load() ), the player stucks in a "loading" state - the loading-spinner is shown and the player never gets loaded.
Here is an example that will make things much clearer:
http://jsbin.com/ximareqedi/1/edit?html,output

Just try to press on one of the buttons. You'll see that the video is not playable after that.

## Sources
https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8
(It's not relevant for the issue...)

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Play a video with a HLS source.
2. Call either video.load or player.load

### Expected
The call to load should either be ignored (if the video is loaded already), or it should load the video (if it is not loaded). This is the common implementation of the load function.

### Error output
None.

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
videojs-contrib-hls 3.7.0-beta4
It reproduces in older versions as well.

### videojs version
video.js 5.12.5

### Browsers
Chrome

### Platforms
Linux

### Other Plugins
None

### Other JavaScript
None

Thanks in advance!!!

**Comment by gesinger** [comment]
Hey @Kasher , thanks for reporting the issue! The current behavior is definitely an issue (the player getting stuck and never loading), however, for load calls with the HTML tech, the underlying video element is sent a load, which resets the media element ( https://www.w3.org/TR/html5/embedded-content-0.html#dom-media-load ). I think to resolve this and keep close to the spec we'll have to do some of the aborting behavior as well in videojs-contrib-hls.

We will still try to find a way to fix this, but is there a specific use-case you were looking to solve?

Thanks again!

**Comment by gesinger** [comment]
Hey @Kasher , thanks again for reporting, and for providing the information. I just saw https://github.com/videojs/videojs-contrib-hls/issues/806 looks to be the same issue. Going to close this one in favor of the older one.
