### ISSUE TITLE
video crop on chrome 

### ISSUE THREAD

**Issue by zainmansoor** [videojs/videojs-contrib-hls#937]
I just implemented video.js code on my site but in chrome some video are cut. But its work fine on Firefox. Can any one help me?
Video https://www.geo.tv/latest/124229-Abbottabad-Commission-report-should-be-made-public-Justice-r-Iqbal

**Comment by mjneil** [comment]
What do you mean by the video is cut? Can you provide a reduced test case exhibiting the problem behavior? What version of videojs-contrib-hls are you using?

**Comment by zainmansoor** [comment]
The issue is that we uploaded different ratio video that's why some part has been cropped, But when i set my videojs player primary flash then its work fine for me.

**Comment by zainmansoor** [comment]
@mjneil you can use below URL for testing.
https://stream1.jeem.tv/vod/dbb6625bdeecc2b566b047bc5e183ead.mp4/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MTIvMTkvMjAxNiA5OjQ5OjMzIEFNJmhhc2hfdmFsdWU9dzhucXdXb2lZZmE4MXhIdjI4YWRiUT09JnZhbGlkbWludXRlcz02MCZpZD0x

this URL has different ratio now put this on your player and set primary html5 and run on chrome to see the issue

**Comment by mjneil** [comment]
I am not seeing the issue here [http://jsbin.com/kunuquqeri/edit?html,output](http://jsbin.com/kunuquqeri/edit?html,output) can you try updating to the latest version of videojs-contrib-hls and see if that solves your issue?

**Comment by zainmansoor** [comment]
@mjneil watch last 4 seconds than you will understand my issue. But its work fine here https://www.geo.tv/latest/124229-Abbottabad-Commission-report-should-be-made-public-Justice-r-Iqbal
 because we used primary flash tech order on it. You can compare both url to understand.

**Comment by gesinger** [comment]
Hey @zainmansoor and @mjneil , I also watched both videos (in the jsbin and in the geo.tv link) multiple times, with skipping around and without, and though I think I recall seeing a longer ending once in the flash variant, they both now appear the same to me for the last 15 seconds, and I can't seem to validate the other behavior that I recall.

@zainmansoor , are you seeing this with other sources, or just this one? And does it replicate the same behavior in flash vs html every time, or just some/most times?

**Comment by zainmansoor** [comment]
@gesinger see screen shot 
HTML5 PLayer:
![1](https://cloud.githubusercontent.com/assets/24650784/22137412/bc8e7558-defc-11e6-9e94-c1ead0482ae4.png)

Flash Player:
![2](https://cloud.githubusercontent.com/assets/24650784/22137419/cab92146-defc-11e6-8dbb-11a2ee2b3f99.png)

But if you open jsBin link in Firefox its work fine but if you open this in chrome then you will face this issue. And its just happen in some video. Well i used only flash now because its work fine on flash every time. Problem with html5 on chrome.

**Comment by gesinger** [comment]
@zainmansoor , I created a jsbin with the latest Video.js and videojs-contrib-hls ( http://jsbin.com/requfo/1/edit?html,output ), as well as with 5.10.2 and 4.0.2 (the version @mjneil created) ( http://jsbin.com/requfo/4/edit?html,output ) and don't see the issue in either.

<img width="1269" alt="screen shot 2017-01-24 at 5 08 39 pm" src="https://cloud.githubusercontent.com/assets/356726/22269276/bfc2a37a-e258-11e6-8f22-83a89e63cad8.png">
<img width="1251" alt="screen shot 2017-01-24 at 5 14 32 pm" src="https://cloud.githubusercontent.com/assets/356726/22269275/bfc19638-e258-11e6-9496-e82517e5a079.png">

Chrome version: 55.0.2883.95 (64-bit)

What version of Chrome are you using?

**Comment by zainmansoor** [comment]
@gesinger your provided both links behave same as my issue, may be its my chrome version issue my current version is  55.0.2883.87 m (64-bit).

**Comment by gesinger** [comment]
@zainmansoor , have you been able to test with another version of Chrome?

**Comment by zainmansoor** [comment]
@gesinger i updated my version 55.0.2883.87 m (64-bit) TO 56.0.2924.87 (64-bit) but issue is still happening.

**Comment by gesinger** [comment]
Is there anything else in your environment that could be impacting it (maybe a browser extension)?

**Comment by zainmansoor** [comment]
@gesinger i have tested it more than 5 pc's but still facing same problem, so i used primary flash for these videos.
Thank you for helping me. its just browser specific issue we can use primary flash for that.
Now i'm going to close this issue.

Thanks @gesinger

**Comment by gesinger** [comment]
Thanks for testing in different environments @zainmansoor . If we notice this come up locally we'll try to post here with any info we gain (or potential solutions). If you happen to stumble across any reason that it was occurring, we'd be happy for the info too. Thanks again.

**Comment by strashila** [comment]
Hi,

We have the same issue - the right part of the video is cropped in Chrome only, and inside HTML5 based player only. Works fine in Firefox, IE, and on Android an iOS native browsers

Thanks,
Alex

**Comment by Frindecent** [comment]
The issue is still there in video.js on chrome (windows version). The issue occurs on videos with resolution like 1680x1050. t
@gesinger you can reproduce the error when using chrome on windows (any version of chrome). you can use video like screen recordings. it will have the right side cropped. Please let me know if you have any way around that.

**Comment by donlaur** [comment]
I have seen the issue on Windows Chrome, but not on Mac.  Did anyone happen to find the reason or a fix?

**Comment by Frindecent** [comment]
Unfortunately we were not able to solve it with videojs. What I did was while encoding our videos , I maintained the aspect ration between height and width of the videos and the new videos due to their proper height/width ratio didnot had this issue.
