### ISSUE TITLE
Is AES encrypted, single-segment HLS that uses #EXT-X-BYTERANGE supported?

### ISSUE THREAD

**Issue by dtiesling** [videojs/videojs-contrib-hls#938]
## Description
I'm getting the traceback below and I'm trying to determine if I'm packaging the HLS incorrectly or if this is not supported by videojs-contrib-hls.

### Error output
```
Uncaught TypeError: Cannot read property 'byteLength' of undefined
    at VirtualSourceBuffer.processPendingSegments_ (videojs-contrib-hls.js?version=v0.15.1:16967)
    at VirtualSourceBuffer.done_ (videojs-contrib-hls.js?version=v0.15.1:16754)
    at Worker.VirtualSourceBuffer.transmuxer_.onmessage (videojs-contrib-hls.js?version=v0.15.1:16579)
```

### videojs-contrib-hls version
videojs-contrib-hls 4.0.2

### videojs version
video.js 5.11.9

### Browsers
* Chrome  55.0.2883.87

### Platforms
* Windows 7

**Comment by dmlap** [comment]
That is supported, as long as you're using whole-segment AES and not "sample AES". Can you share your m3u8 or (better yet) a link to your stream?

**Comment by dtiesling** [comment]
Here's a sample HLS you can download - https://storage.googleapis.com/jouststudio-public/encrypted_bunny.m3u8

It probably won't play directly from there due to CORS settings on the google buckets.

This is the ffmpeg I am using to generate the files if that helps at all.
`ffmpeg -i input.mp4 -vf scale=-852:480 -b:a 128k -pix_fmt yuv420p -vcodec libx264 -profile:v high  -hls_list_size 1000000 -hls_flags single_file  -hls_key_info_file info.txt output.m3u8`

**Comment by dtiesling** [comment]
I've also tried encrypted the .ts file myself and I get the same result. It throws the error above and the plays the first segment before freezing.

**Comment by dtiesling** [comment]
@dmlap Have you successfully generated an HLS that uses BYTERANGE, a single segment, and AES encryption?

**Comment by dtiesling** [comment]
Looks to be a bug in ffmpeg. I've had success using bento - https://www.bento4.com/developers/hls/
