### ISSUE TITLE
loading ".key" file multiple times

### ISSUE THREAD

**Issue by delgermurun** [videojs/videojs-contrib-hls#942]
## Description
Hello Videojs Team, 

Thank you for great library.

My video player loads `<foo>.key` file before every section of video. Maybe it is related encoding, but I'm not person who encoded video.

Loading key file multiple times is intentional? I think it is kind of waste of bandwith & time.

## Sources

Here is section of play list file.
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:11
#EXT-X-KEY:METHOD=AES-128,URI="desktopc171bf1a5a074a138e4e8d50e0477938.key",IV=0xe6e51b446806de075810a1b776e34de9
#EXTINF:10.880000,
desktopc171bf1a5a074a138e4e8d50e047793800000.ts
#EXTINF:10.800000,
desktopc171bf1a5a074a138e4e8d50e047793800001.ts
#EXTINF:10.800000,
desktopc171bf1a5a074a138e4e8d50e047793800002.ts
#EXTINF:10.800000,
desktopc171bf1a5a074a138e4e8d50e047793800003.ts
#EXTINF:7.200000,
desktopc171bf1a5a074a138e4e8d50e047793800004.ts
#EXTINF:10.800000,
desktopc171bf1a5a074a138e4e8d50e047793800005.ts
#EXTINF:10.800000,
desktopc171bf1a5a074a138e4e8d50e047793800006.ts
#EXTINF:10.800000,
desktopc171bf1a5a074a138e4e8d50e047793800007.ts
#EXTINF:7.200000,
desktopc171bf1a5a074a138e4e8d50e047793800008.ts
#EXTINF:10.800000,
desktopc171bf1a5a074a138e4e8d50e047793800009.ts
#EXTINF:10.800000,
desktopc171bf1a5a074a138e4e8d50e047793800010.ts
#EXTINF:10.800000,
desktopc171bf1a5a074a138e4e8d50e047793800011.ts
#EXTINF:10.800000,
desktopc171bf1a5a074a138e4e8d50e047793800012.ts
#EXTINF:7.200000,
desktopc171bf1a5a074a138e4e8d50e047793800013.ts
#EXTINF:10.800000,
...
```

Here is Network screenshot

![screen shot 2016-12-24 at 12 20 32 pm](https://cloud.githubusercontent.com/assets/492616/21465217/7c775710-c9d4-11e6-893f-fd3144d9401b.png)

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 3.6.13

### videojs version
what version of videojs does this occur with?
video.js 5.12.6

### Browsers
what browsers are affected? please include browser and version for each
* Chrome & Firefox, not test on Safari

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* MacOS

Thanks in advance.

**Comment by andreyhammer** [comment]
HI.
 I think that isn't bug. it is key rotation for each segment.

**Comment by gesinger** [comment]
Thanks for reporting @delgermurun , and thanks for the response @andreyhammer . This behavior is intended, and we rely on the browser cache to handle the caching for keys. While we might be able to do the caching of the key ourselves, we'd have to be aware of potential "HTTP expires" headers to handle mentioned key rotation and make other considerations in the code. As of now it is simpler to rely on the browser cache.
