### ISSUE TITLE
No way to set up URL Signing

### ISSUE THREAD

**Issue by stoicbuddha** [videojs/videojs-contrib-hls#946]
## Description
There is no way to set up URL signing on the manifests, .ts files, or .key files

## Proposed Solution
I think this could work if we could pass certain options to the player for URL signing, then md5 hash everything in the plugin if the option is set.  Maybe something like `url_signing: {'thing1': 'stuff', 'thing2': 'morestuff'}`.

The CDN we use, for example, allows you to sign the URL up to, but before, the filename, allowing you to essentially sign a path, meaning it'd work for any file coming from there regardless of extension.

**Comment by gesinger** [comment]
Hey @stoicbuddha , we do have a beforeRequest function that can be overridden to modify the URLs before they are requested: https://github.com/videojs/videojs-contrib-hls#hlsxhr

Please let us know if that doesn't work for you!
