### ISSUE TITLE
Add option to clear buffer on manual rendition selection

### ISSUE THREAD

**Issue by elhampour** [videojs/videojs-contrib-hls#948]
I create a plugin for change the quality , according to documentation this is the solution , 

 player.tech_.hls.selectPlaylist = function () {
                return player.tech_.hls.playlists.master.playlists.filter(function (playlist) {
                    return playlist.attributes.RESOLUTION.height === src.height;
                })[0];

but when user clicks on a new quality, i took a while to change the quality , because some part of previous quality had been downloaded and this behaviour is not what i want.

i want to change the quality with no waiting.

**Comment by dmlap** [comment]
When are you activating your plugin? If you do it immediately after setting the source, I would think your modified playlist selector would kick in before any buffering.

**Comment by elhampour** [comment]
This is not about the initial moment, lets say my video has two format both of them in hls format. when user plays the video the bad quality ( 240p ) gets activated and the next two part of video immediately gets downloaded, bit if user decides to view th 360 quality, i change the playlist like the solution above , but the default behaviour of contrib plugin is to play the downloaded part ( 240P) first and after them it goes to download the 360 format, but i want to make the plugin to play and download 360 format immediately after user change the quality.

**Comment by elhampour** [comment]
no one ? i need it asap.

**Comment by gesinger** [comment]
We don't have an exposed API to clear out the buffer/cause an immediate switch. However, if you use https://github.com/videojs/videojs-contrib-quality-levels then it should start overlaying content, and should switch within 1 segment duration (possibly sooner, possibly a bit later).

**Comment by gesinger** [comment]
@elhampour , does this satisfy your use case?

**Comment by gesinger** [comment]
Closing for now. If this didn't satisfy your use case, please let us know. Thank you.

**Comment by elhampour** [comment]
@gesinger no it does not satisfy my need, i can change the quality through the plugin that you mention but i have to wait for the downloaded part to play and then my new quality comes into play. but i want to change that imminently

**Comment by klimentLambevski** [comment]
@gesinger Hi i know this is closed but i need to ask if you have any kind of option for clearing out downloaded segments? i want to clear segments after switching to higher resolution because if the user has chosen lower resolution and many segments are preloaded the video continues to buffer after those downloaded segments

**Comment by sachinaaglave** [comment]
@elhampour @gesinger  Any update on this?

**Comment by pureexe** [comment]
I'm also waiting for API to clear buffers.

**Comment by forbesjo** [comment]
Moving this enhancement request to VHS
