### ISSUE TITLE
Overriding native HLS support breaks player on Safari and Edge

### ISSUE THREAD

**Issue by mkorszunsands** [videojs/videojs-contrib-hls#949]
## Description

I want callback `beforeRequest` being executed in all browsers with (Safari, Edge) and without (Chrome, Firefox) native HLS support. To do so I am setting:

`videojs.options.hls.overrideNative = true`

Which was recommended in this [issue](https://github.com/videojs/videojs-contrib-hls/issues/904).

I tried with the latest version (4.2.0) and v3.7.0-beta4 of [videojs-contrib-hls](https://github.com/videojs/videojs-contrib-hls)

Setting above flag makes `beforeRequest` being called in browsers with native HLS support (Safari, Edge) but video itself does not play any more and further errors are thrown.

## Steps to reproduce

1. Play a video on Safari with `videojs.options.hls.overrideNative = true`
2. Play a video on Edge with `videojs.options.hls.overrideNative = true`

### Expected
Safari and Edge should call `beforeRequest` and play video.

### Error output

`TypeError: Attempted to assign to readonly property `
`TypeError: undefined is not an object (evaluating 'this.messageHandlers')`

Which occur in below code snippet:

```return "init" === e.data.action && e.data.options ? void(this.messageHandlers = new f(e.data.options)) : (this.messageHandlers || (this.messageHandlers = new f), void(e.data && e.data.action && "init" !== e.data.action && this.messageHandlers[e.data.action] && this.messageHandlers[e.data.action](e.data)))```

## Additional Information
videojs-contrib-hls versions: 4.2.0 
When I remove the line: `videojs.options.hls.overrideNative = true`; 
The video is playing on Safari and Edge.

Including the line: `videojs.options.hls.overrideNative = true`;
The video is not played on Safari and Edge (although `beforeRequest` is called) and results with above error.

videojs-contrib-hls versions: 3.7.0Beta4
When I remove the line: `videojs.options.hls.overrideNative = true`; 
The video is playing on Safari and Edge.

Including the line `videojs.options.hls.overrideNative = true`; 
The video is not playing on Safari and results with above error.
The video is not playing on Edge and results with below error: 

`XmlHttpReques. Access is denied.`

### videojs-contrib-hls version
* 4.2.0 
* 3.7.0Beta4

### videojs version

* 5.13.2

### Browsers
* Safari
* Edge

### Platforms
* OSX
* Windows 10

**Comment by forbesjo** [comment]
Would you be able to provide a sample source to debug? Also I would recommend disabling the native audio and video track APIs with:
```js
var player = videojs('player', {
  html5: {
    nativeAudioTracks: false,
    nativeVideoTracks: false
  }
});
```
having these options on may cause conflicts.

**Comment by mkorszunsands** [comment]
@forbesjo thank you so much for this hint!!! It solves the problem :) 👍

**Comment by adgoncal** [comment]
@mkorszunsands: I am confused. On the initial post you wrote multiple times that you tested on version 4.2.0, but the latest version I could find is 4.0.3. Have you tried with version 4.0.3? Does it work?

I am having a similar issue and setting `videojs.options.hls.overrideNative = true` together with the code by @forbesjo does not seem to solve it. I am still investigating my issue though.

**Comment by gesinger** [comment]
Looks like the cases were solved. Closing.
