### ISSUE TITLE
Cannot build with browserify `cannot find module browserify-shim` in mux.js

### ISSUE THREAD

**Issue by fozzle** [videojs/videojs-contrib-hls#951]
See: https://github.com/videojs/mux.js/issues/131

Video.js @ 5.15.1 
videojs-contrib-dash @ 2.6.1

**Comment by gesinger** [comment]
Thanks for reporting @fozzle . https://github.com/videojs/mux.js/pull/151 was recently merged in. This is pending a release of mux.js, but should be resolved soon.

**Comment by gesinger** [comment]
A fix for this was merged in via https://github.com/videojs/mux.js/pull/151 , and was released as part of v4.1.3 of mux.js. videojs-contrib-media-sources and videojs-contrib-hls were also updated to point to the new version. Please give the latest version of videojs-contrib-hls (v5.5.0) a shot and let us know if you are still experiencing issues. Thanks for reporting the issue!
