### ISSUE TITLE
can't paly live hls on android

### ISSUE THREAD

**Issue by SentoIsuzu** [videojs/videojs-contrib-hls#953]
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. MediaError {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported."}

It seems to be working fine in only Safari  What am I missing?  

I'm using these versions:
video.js : 5.11.9 
videojs-contrib-hls : /4.0.3

**Comment by mjneil** [comment]
videojs-contrib-hls requires video.js version ^5.15.1. Can you try updating your video.js version and see if that solves your issues?

**Comment by gesinger** [comment]
Closing for now. If you are still experiencing this issue with the latest versions of videojs-contrib-hls  and Video.js (available via the jsbin template below) please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.

**Comment by kiscoman** [comment]
Hello, 
I´m having the same problem. Is easy to reproduce, just using the developer tools of Chrome, select any of the 3 android devices, and go to the template that suggest "gesinger". Error code 4 appear.
But with any other equipment selected, like ipad works.
