### ISSUE TITLE
Some playlists not working with contrib-hls 3.5.3 and above

### ISSUE THREAD

**Issue by mkhazov** [videojs/videojs-contrib-hls#954]
## Description
pen: https://codepen.io/mkhazov/pen/pRgGVy

## Sources
https://embed.life.ru/playlist/e2edb01fb1d61d965328785310e3f617/index.m3u8

### Error output
Player goes though all available playlists, and none of them suits it:
```
VIDEOJS: WARN: Problem encountered with the current HLS playlist. Switching to another playlist.
VIDEOJS: WARN: Problem encountered with the current HLS playlist. Switching to another playlist.
VIDEOJS: WARN: Problem encountered with the current HLS playlist. Switching to another playlist.
```
Playback doesn't begin at all.

### videojs-contrib-hls version
3.5.3 and above (tested with 3.5.3, 3.6.0. 4.0.2)
**the same playlist works fine with videojs-contrib-hls 3.5.2**

### videojs version
5.14.1

### Browsers
Chrome, Firefox

### Platforms
OS X El Captain

Additional info:
`#EXTINF:10.00` does not exactly match the duration (9 s 832 ms) of the first chunk. Can this cause the problem?

**Comment by gesinger** [comment]
Hey @mkhazov , sorry this issue has gone a while without much attention. I tried playing your stream, but it seems that a lack of CORS headers was preventing me from playing it: `XMLHttpRequest cannot load https://embed.life.ru/playlist/e2edb01fb1d61d965328785310e3f617/index.m3u8. No 'Access-Control-Allow-Origin' header is present on the requested resource.` Would you be able to add CORS headers so we can give it another go? Thanks.

**Comment by gesinger** [comment]
Closing for now. If you're still having trouble, please add CORS headers to the stream and re-open the issue. Thank you.
