### ISSUE TITLE
Download the m3u8 after click play button (with preload=none). Is it possible?

### ISSUE THREAD

**Issue by csuarez93** [videojs/videojs-contrib-hls#955]
I have been fighting some days with this problem. Does anyone have a solution?

**Comment by gesinger** [comment]
Hey @csuarez93 , are you trying to prevent the player from downloading any m3u8 file until after the play button is clicked?

**Comment by AndriyOleksyuk** [comment]
@gesinger, yes

**Comment by mkhazov** [comment]
Any update on this?

**Comment by stoicbuddha** [comment]
Is there any solution to this?

**Comment by gesinger** [comment]
@stoicbuddha , there isn't a current solution, however, we are looking at ways to add it via a configuration flag

**Comment by forbesjo** [comment]
Moving this enhancement to VHS
