### ISSUE TITLE
4.0.3 Webpack Build Issues, Code 4 

### ISSUE THREAD

**Issue by zshenker** [videojs/videojs-contrib-hls#956]
## Description
Using v4.0.3 of videojs-contrib-hls when built via a Webpack build pipeline, I get a "(CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media." error when trying to load an HLS source. This issue does not occur when rolling back to 4.0.2.

I am using the workarounds mentioned in #600 to alias webworkify to webworkify-webpack-dropin in the webpack.config.js

## Steps to reproduce
Git repo with an example is at https://github.com/zshenker/webpack-hls-sample
Just run `npm install` and `npm run bundle` after git clone. This will run the Webpack build and output into `dist/` directory.

Hosted example at: http://s3.amazonaws.com/o.apps.ign.com/video-player/__support/webpack-hls-sample/4.0.3/default.html

Working Example with 4.0.2(via Webpack build) at: http://s3.amazonaws.com/o.apps.ign.com/video-player/__support/webpack-hls-sample/4.0.2/default.html

Working version using 4.0.3 pulled from unpkg CDN(not built via webpack) at: http://s3.amazonaws.com/o.apps.ign.com/video-player/__support/webpack-hls-sample/4.0.3/cdn.html

## Results
HLS source does not play and returns code 4 error

### Expected
HLS source loads and plays successfully

### Error output
(CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.

### videojs-contrib-hls version
videojs-contrib-hls 4.0.3

### videojs version
video.js 5.14.1

### Browsers
* Chrome

### Platforms
* All

### Other Plugins
* None

### Other JavaScript
* None

**Comment by zshenker** [comment]
Additional note to this, I just tried updating video.js from 5.14.1 to 5.15.1, and this error is resolved.

On GitHub, 4.0.2 is marked as "Latest" of videojs-contrib-hls, but on npm 4.0.3 is latest. While with video.js 5.14.1 is "Latest"(on GitHub & npm) and 5.15.1 is "Pre-Release/next".

Is it expected that there would be issues using videojs-contrib-hls 4.0.3 with video.js 5.14.1? and should 4.0.3 be latest on npm?

**Comment by gesinger** [comment]
Hey @zshenker , thanks for letting us know it was resolved. I don't imagine there should've been issues with those versions of each project, though it's possible the issue was due to videojs-contrib-hls' listing of video.js ^5.15.1 as a dependency for videojs-contrib-hls 4.0.3. Please let us know if you find any more issues, and thank you.

**Comment by wangxd8** [comment]
I have also encountered such a problem, how can I solve it?
