### ISSUE TITLE
 No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://null.jsbin.com' is therefore not allowed access.

### ISSUE THREAD

**Issue by samueleastdev** [videojs/videojs-contrib-hls#957]
## Description

I get this error when pasting a link into the jsbin example
~~~
XMLHttpRequest cannot load http://iphone-streaming.ustream.tv/uhls/3064708/streams/live/iphone/playlist.m3u8. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://null.jsbin.com' is therefore not allowed access.
~~~

http://jsbin.com/kesokexono/edit?html,output

Everything works fine in Safari it only seems to be a Chrome issue?

### videojs-contrib-hls version
videojs-contrib-hls 4.0.2

### videojs version
video.js 5.15.1

**Comment by gkatsev** [comment]
Because this project uses javascript to request the segments, they're required to have CORS headers from the server as outlines in the [hosting considirations](https://github.com/videojs/videojs-contrib-hls#hosting-considerations) in our [README](https://github.com/videojs/videojs-contrib-hls#hosting-considerations).

Safari runs HLS natively and thus doesn't require CORS headers.

**Comment by samueleastdev** [comment]
Hi @gkatsev,

Thanks for the update.

I have tried adding this to my .htaccess. 
~~~
#Solution using mod_headers and mod_setenvif
<IfModule mod_headers.c>
       SetEnvIf Origin (.*) AccessControlAllowOrigin=$1
       Header add Access-Control-Allow-Origin %{AccessControlAllowOrigin}e env=AccessControlAllowOrigin
       Header set Access-Control-Allow-Credentials true
</IfModule> 
~~~

And tried adding this to my vhosts file
~~~
Header set Access-Control-Allow-Origin "*"
~~~

And tried adding this to my php app
~~~
header('Access-Control-Allow-Origin: *');
~~~

Not sure what else i can try?

**Comment by gkatsev** [comment]
The header needs to be set on the server serving the HLS manifests and segments. Since the url is from ustream.tv, it would need to be there.

**Comment by samueleastdev** [comment]
ah right ok thanks @gkatsev
