### ISSUE TITLE
Delay before playing after seek

### ISSUE THREAD

**Issue by servercimen** [videojs/videojs-contrib-hls#962]
## Description
Video doesn't continue or delayed after seeking.

Checkout this example:
http://jsbin.com/qofebetivo/1/edit?html,output
Try skipping a few minutes, observe how playing is delayed or sometimes stopped. It may take couple tries to see the problem.

You can compare it to here where the problem does not happen. Only difference is videjs-contrib-hls version (4.1.0 vs 3.6.13)
http://jsbin.com/vulohibiri/1/edit?html,output

### videojs-contrib-hls version
videjs-contrib-hls 4.1.0
Same problem does not happen with videjs-contrib-hls 3.6.13

### videojs version
videojs 5.16.0

### Browsers
Chrome 55.0.2883.95 (64-bit)

### Platforms
Mac OSX Sierra Version 10.12.2 (16C67)

**Comment by 418900516** [comment]
we have this problem. when get the segment and push the buffer,the seeked event not trigger ,delay some seconds before play. Are you solution the problem?

**Comment by servercimen** [comment]
No solution yet, I just use videjs-contrib-hls version 3.6.13 which doesn't have the same problem

**Comment by 418900516** [comment]
I try videojs-contrib-hls version 3.6.13,but the case still appear. Are you know the seeked event what time is triggered?

**Comment by gesinger** [comment]
Hey @servercimen , sorry this ticket has gone a while without much attention, and thank you for reporting the issue. We've made a lot of changes and improvements to our segment fetching logic, including around seeking. I gave it a shot with our latest player: http://jsbin.com/vokipos/34/edit?html,output (at the time of this comment, v5.3.3), and the seeking looks much snappier and consistent versus the sample you provided from version 4.1.0. Please give it a shot and let us know if you are still experiencing issues. Thank you.
