### ISSUE TITLE
The Video did not play properly when clicking backwards on the progress bar.

### ISSUE THREAD

**Issue by DonkeyInBeijing** [videojs/videojs-contrib-hls#964]
## Description
Briefly describe the issue.
The video played on a wrong position when we clicked backwards on progress bar.

## Sources
Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Playing a video
2. Click forwards on the progress bar
3. Click backwards until the video was playing properly again from step 2

### Expected
The video was playing regularly on where we clicked the progress bar.

### Error output
The video was playing on a wrong position ahead of where we clicked.

## Additional Information
Chrome version:  55.0.2883.87
We did not find the issue on former Chrome version;
HLS version: we updated the HLS plugin from 3.x to 4.0.2, both of them have problem on the newest Chrome version.

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 4.0.2

### videojs version
what version of videojs does this occur with?
video.js 5.10.4

### Browsers
what browsers are affected? please include browser and version for each
Chrome version:  55.0.2883.87
We did not find the issue on former Chrome version;

### Platforms
what platforms are affected? please include operating system and version or device and version for each
Window 7

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by 418900516** [comment]
I found this issue too.when click backwards ,the video back to the forward position on the progress bar, and play the video continue, but the time on the progress bar stop,later the video stop play.

**Comment by gkatsev** [comment]
I think this is an issue with chrome. We have a workaround in videojs 5.16.
It's been out for a while and we haven't heard bad stuff about it, so, probably will promote it to latest soon.

**Comment by gesinger** [comment]
Video.js 5.16.0 is now latest. Closing for now. If you are still experiencing this issue with the latest versions of Video.js (as of this comment, 5.16.0) and videojs-contrib-hls (as of this comment, v5.1.0), please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.

**Comment by DonkeyInBeijing** [comment]
@gkatsev @gesinger Thanks Gary , Garrett， I did not expericence this issue any more after upgrade to version 5.16.

**Comment by gesinger** [comment]
Glad to hear it @DonkeyInBeijing , thanks for letting us know!
