### ISSUE TITLE
Compatibility with videojs 6.0 RC

### ISSUE THREAD

**Issue by ngoisaosang** [videojs/videojs-contrib-hls#968]
## Description
Can't play m3u8 files in video.js 6.0.0-RC.0 but it still play in video.js 5.15.1
The video played and showed "No compatible source was found for this media."

## Steps to reproduce
1. Import media from d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8 and other m3u8 files
2. Press play but it show "No compatible source was found for this media."

### Error output
* Press play but it show "No compatible source was found for this media."

### videojs-contrib-hls version
* videojs-contrib-hls 4.1.1

### videojs version
* video.js 6.0.0-RC.0

### Browsers
* Google Chrome version 55.0.2883.87 m (64-bit)

### Platforms
* Windows 10 Pro version 1607 64bit

**Comment by gesinger** [comment]
@gkatsev , I assume this is expected since it is for Video.js 6 and videojs-contrib-hls has not yet been updated to support it?

Exception on line: `videojs.getComponent('Html5').isSupported()` where getComponent('Html5') returns undefined.

JSBin: http://jsbin.com/catonuj/2/edit?html,output

**Comment by gkatsev** [comment]
Yup, we need to change `getComponent` to `getTech`. I was planning on making a PR at some point. But anyone can do it as well.
