### ISSUE TITLE
Version 4.1.0 and 4.1.1 minified JS files are identical

### ISSUE THREAD

**Issue by thomaspeeters** [videojs/videojs-contrib-hls#970]
## Description
The minified JS files for the releases 4.1.0 and 4.1.1 are identical, but the non-minified are not. This feels like a possible mistake to me. I'm talking about the pre-built files you can download on the Releases page.

**Comment by forbesjo** [comment]
Looks like uglify has `--screw-ie8` as true which is unquoting reserved keywords in IE8. I'll add `--support-ie8` to our uglify step. Thanks for catching this!

**Comment by thomaspeeters** [comment]
No problem. Thanks for finding the cause so quickly.

**Comment by forbesjo** [comment]
This will be fixed in the next version (#971)
