### ISSUE TITLE
Player not working when source is provided dynamically after player created on IE11 Win10

### ISSUE THREAD

**Issue by m1ch3lp3r3z** [videojs/videojs-contrib-hls#973]
## Description
Player remains blank when the player instance is created sourceless and the source is added later on via `src` method.

## Sources
I don't have a public link at the moment but this has been tested in several PC's with different streams and all throw same result.
I found this sample HLS: http://playertest.longtailvideo.com/adaptive/captions/playlist.m3u8

## Steps to reproduce
Just play it.

### Error output
The only warning I see is "Video is not ready", and it's due to an attempt to set `currentTime` when the player still seems not to be ready and hence throws "InvalidStateError", the step is executed again when the player is ready. Also this warning shows up when the source is fed from the start and in this case the player does work even after showing that warning.

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 4.1.0

### videojs version
what version of videojs does this occur with?
video.js 5.15.1

### Browsers
IE11 but only on Windows 10, works on Windows 7
*

### Platforms
Windows 10
*

### Other Plugins
Just videojs and videojs-contrib-hls.
*

**Comment by gesinger** [comment]
Example jsbin: http://jsbin.com/puqihuc/3/edit?html,output

**Comment by Kasher** [comment]
:+1: 
This is really a critical bug for us.
Is there any estimation about how long will it take to fix it?

Thanks!

**Comment by forbesjo** [comment]
This no longer seems to be an issue, most likely due to IE11 MSE fixes we've made. Closing.
