### ISSUE TITLE
IE11 Flash fallback failing

### ISSUE THREAD

**Issue by scrouchman** [videojs/videojs-contrib-hls#974]
## Description
IE11 on windows 10 not falling back to flash so video fails to start

## Sources
https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Open IE11 on windows 10
2. Navigate to http://videojs.github.io/videojs-contrib-hls/
3. Press play

### Expected
Video should play as normal

## Additional Information
Video plays fine on Edge & Chrome. Confirmed that Flash is setup for IE11 and that it works

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 4.1.1

### videojs version
what version of videojs does this occur with?
video.js 5.15.1

### Browsers
what browsers are affected? please include browser and version for each
* IE11 

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* Windows 10

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* No

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* No

**Comment by scrouchman** [comment]
Closing this as while a few 'issues' suggest this should be automatic its clearly not. Solved by doing some browser detection and changing the techOrder

**Comment by forbesjo** [comment]
Some further information: IE11 on Windows 10 and 8.1 does support MSE so this plugin will by default not fall back to Flash playback.
