### ISSUE TITLE
originalSegment is undefined at first segment end

### ISSUE THREAD

**Issue by StevenMeyer** [videojs/videojs-contrib-hls#98]
When playing a live stream using HLS, the stream plays for around 10 seconds before pausing. The streams are fine in HTML5 players.

My console is filled up with this message:
> TypeError: originalSegment is undefined&nbsp;&nbsp;&nbsp;&nbsp;[videojs.hls.js:136](https://github.com/videojs/videojs-contrib-hls/blob/master/src/videojs-hls.js#L136)

This is Fedora 19, Firefox 30. I'll try to get an example to show, when work permits.

**Comment by dmlap** [comment]
We cleaned up some issues with translating media indices for live playlists that I believe fixed this. Please re-open if you see it on latest.

**Comment by gak2** [comment]
Hi,

I am really struggling with this issue of a live HLS stream from Wowza freezing after 10 seconds in Chrome/Firefox.  I have tried all combinations of videojs 5.2.0 » 5.10.1, and videojs.hls 1.2.0 » 2.2.0, to no avail.  It does stream fine to Android though, so I don't think Wowza setup is the problem.

On both Chrome and Firefox, it looks as though the media blocks run into a loop ...

`media_w1438989202_52.ts	
media_w1438989202_53.ts	
media_w1438989202_54.ts	
media_w1438989202_53.ts	
media_w1438989202_54.ts	
media_w1438989202_53.ts`

... after 10secs this fails and the browser goes into an endless request for the same media_xxxxxx.ts chunklist.  Result is: video stops dead in Chrome, and on Firefox goes into eternal loading-circle.

Bizarrely, it _will_ keep playing in IE, where is seems to alternate loading .m3u8, .ts, .m3u8, .ts, .m3u8 ... it would be great if I could even see a link where someone has this working correctly?

All help greatly appreciated  :)

Thanks  :)
