### ISSUE TITLE
mediachange event on android chrome

### ISSUE THREAD

**Issue by sgavali** [videojs/videojs-contrib-hls#986]
## Description
On PC chrome and using ABR  playlist I could see player switching to different profile using mediachange event. But on android chrome I'm not seeing same alerts. Also player.tech_.hls.bandwidth is also not seen on android chrome.

Is ABR supported in android chrome ?

## Sources
http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8

## Steps to reproduce
Setting width height of player as 1920 x 1080 and adding alert in mediachange event

### videojs-contrib-hls version
5.0.0

### videojs version
5.16.0

### Browsers
Android chrome 55.0

**Comment by gesinger** [comment]
Hey @sgavali , Android supports native HLS playback, so we use their player if available, and you may not have access to all of videojs-contrib-hls' features. You can override that behavior using https://github.com/videojs/videojs-contrib-hls#overridenative if you'd like.

If that doesn't work, please let us know. Thanks.

**Comment by sgavali** [comment]
Thanks Garret, a naive question, using videojs-contrib-hls on Android chrome with native playback supported is as good as not using videojs-contrib-hls plugin's implementation ?

**Comment by gesinger** [comment]
In our testing, playback seemed relatively equitable. Though as always there's the possibility of bugs. If you don't need many advanced features, native can be a good choice for browsers that support it. But if you want the full range of features that videojs-contrib-hls supports with its own playback on top of the basics, then it might be worth giving native override a shot.

**Comment by gesinger** [comment]
As an update, videojs-contrib-hls might not be fully supported for some older versions of Chrome (re: Chrome 46 mentioned in your comment).

**Comment by sgavali** [comment]
Thanks Garrett for information.
