### ISSUE TITLE
HLS for WordPress plugin 

### ISSUE THREAD

**Issue by onigetoc** [videojs/videojs-contrib-hls#987]
I have the videojs Wordpress plugin.
https://wordpress.org/plugins/videojs-html5-player/
The js file are loaded in the footer.
I added the hls javascript in the footer. but it do no work.

I tryed your demo. if we put all the js in the footer the plugin do not work. How can we make it work with all js in the footer to make it work with the Wordpress videojs plugin?

**Comment by gesinger** [comment]
Hey @onigetoc , do you have an example of your page?

**Comment by onigetoc** [comment]
Here on Wordpress
http://codesniff.com/jquery/hls-http-live-streaming-video-for-videojs-plugin-for-wordpress-m3u8?preview_id=766&preview_nonce=cc412f1886&_thumbnail_id=629&preview=true
and here standalone (Click the link under video to load other streaming video, they all working)
http://scriptsmashup.com/scripts/videojs-contrib-hls-master/

**Comment by gesinger** [comment]
Hey @onigetoc , glad to hear you got it working. If anything else comes up, please let us know. Thank you.
