### ISSUE TITLE
Video won't restart after long pause

### ISSUE THREAD

**Issue by onigetoc** [videojs/videojs-contrib-hls#988]
Streaming live Video won't restart after long pause.

It should depent on witch video streaming is, but most of the time, the video won't restart after long pause. 
It may have to reload completly.

**Suggestion:**
Like some Live TV or Youtube LIVE, there's a little Red DOT before Live text.
https://www.youtube.com/watch?v=zaah_hbUHOg&list=PL8fVUTBmJhHJBH1SO88FYKaQsisgItjpn

May be doing some javascript to change the dot color when playing or pause and when is live or playing in buffer.

```
.vjs-live-display:before {
  content: "•";
  font-size: 172%;
  padding-right: 5px;
  vertical-align: sub;
  color: red;
}
```
Demo: http://codesniff.com/jquery/hls-http-live-streaming-video-for-videojs-plugin-for-wordpress-m3u8

Another interesting thing, On Youtube, when you click the live button it reload to Live streaming and not in buffer mode.

**Comment by onigetoc** [comment]
Pure CSS RED GREY light Before LIVE text.
```
.video-js .vjs-live-display:before {
      content: "•";
      font-size: 172%;
      padding-right: 5px;
      vertical-align: sub;
      color: #ccc;
    }
    .video-js.vjs-playing .vjs-live-display:before {
      color: red;
    }
    .video-js .vjs-live-display:before, .video-js.vjs-paused .vjs-live-display:before, .video-js.vjs-waiting .vjs-live-display:before, .video-js.vjs-seeking .vjs-live-display:before {
      color: #ccc;
    }
```

But need a javascript solution to restart the video in real time and not in the buffer

**Comment by onigetoc** [comment]
When you pause a HLS m3u8 video, it won't restart in you click play. 
Like Youtube, I though about a way to click the LIVE text to reload the video to real time streaming, It may be implemented in your js.

```
    // RELOAD VIDEO ON CLICK LIVE BUTTON 
    $(document).on('click', '.vjs-live-display', function () {
      player.src({"type":player.currentType(), "src":player.currentSrc()});
      player.load();
      player.play();
    });
```

**Comment by mjneil** [comment]
Resuming live stream after a long pause is being address in #1006 so keep an eye out for when that gets merged in

**Comment by onigetoc** [comment]
what about the idea to go real time when clicking the LIVE button?
Youtube do it this way: https://www.youtube.com/watch?v=MTBOptDSVhQ

**Comment by gesinger** [comment]
That is definitely something we will consider, or it can be done via a plugin @onigetoc 

As for the behavior we have implemented in the above PR, we try to resume from wherever the viewer paused, but if it has been a long enough time that the paused time fell out of the available window, we seek to the live point and resume from there.

**Comment by gesinger** [comment]
This should be fixed as of the latest release (v5.3.2). If you are still experiencing an issue, please re-open or file a new issue. Thank you.

**Comment by campones** [comment]
working fine now on my end,  that's great!

**Comment by onigetoc** [comment]
It's work, i did find out that if i seek, the video will restart too. It's look faster than reloading the video.
