### ISSUE TITLE
goes wrong when importing them as module.

### ISSUE THREAD

**Issue by seeLuck** [videojs/videojs-contrib-hls#995]
## Description
module goes wrong with webpack

## Steps to reproduce
1.
install these modules.
`
npm install video.js videojs-contrib-hls
`
2.
import them in the project.
```
import videojs from 'video.js'
import 'videojs-contrib-hls'
// import VTTJS_PATH from 'file!videojs-vtt.js/dist/vtt.min.js';
// videojs.options['vtt.js'] = VTTJS_PATH;
let player = videojs(document.getElementById('example-video'));
player.src({
    src: "http://xxxxx.m3u8",
    type: 'application/x-mpegURL',
});
player.play();
```

### Error output
`
VIDEOJS: TypeError: Cannot convert undefined or null to object(…)
`

## Additional Information
It works if loaded them with normal script src as the demo did.

### videojs-contrib-hls version
videojs-contrib-hls 5.1.1

### videojs version
video.js 5.16.0

### Platforms
macOS 10.12.2

It might be some problem in configuration. Is there any 'import' demos of videojs-contrib-hls for reference? thx.

**Comment by mahpah** [comment]
you might want to read #600 comments

**Comment by gesinger** [comment]
Hey @seeLuck , thanks for reporting, but I'm going to close this ticket in favor of https://github.com/videojs/videojs-contrib-hls/issues/600 . Thanks @mahpah for referencing it.
