### ISSUE TITLE
Uncaught TypeError: Cannot read property 'handleDecrypted_' of undefined

### ISSUE THREAD

**Issue by kitce** [videojs/videojs-contrib-hls#997]
I just installed this library via `bower` and build the distributable files without errors.

When I tried to play my M3U8 url (http://127.0.0.1:3000/stream/index.m3u8) in my localhost website (http://127.0.0.1:8000) , the following error occurred.

```
Uncaught TypeError: Cannot read property 'handleDecrypted_' of undefined
    at Worker.MasterPlaylistController.decrypter_.onmessage (videojs-contrib-hls.js:598)
MasterPlaylistController.decrypter_.onmessage @ videojs-contrib-hls.js:598
```

Googled the error for some time but no luck, any idea?

I can play this stream in MPC-HC without any problem.

**Comment by kitce** [comment]
I found the bug.

In `MasterPlaylistController` -> `this.decrypter_.onmessage`:

`audiosegmentLoader_` should be `audioSegmentLoader_`

**Comment by gesinger** [comment]
Thanks for the catch @kitce ! Created a PR to fix it at https://github.com/videojs/videojs-contrib-hls/pull/1001
